### ISSUE TITLE
dangling comma

### ISSUE THREAD

**Issue by rjpalermo1** [SimulatedGREG/electron-vue#10]
Fresh install:

         ERROR in ./app/src/App.vue

           ✘  http://eslint.org/docs/rules/comma-dangle  Unexpected trailing comma
           /Users/Tektango/projects/stack/dev-studio/app/src/App.vue:39:6
             },
                 ^

         ✘ 1 problem (1 error, 0 warnings)

Removed comma in my build and all well....

**Comment by SimulatedGREG** [comment]
Thanks for posting. What plugins did you select during the project scaffolding?

**Comment by Kun8018** [comment]
This is a elinter error.you can check your code and just delete a extra comma,then every thing goes well
