### ISSUE TITLE
Mac App Store rejecting Electron apps due to private API use

### ISSUE THREAD

**Issue by mobileguru121** [SimulatedGREG/electron-vue#1007]
#### **Mac App Store Rejection**
The automated review process is rejecting the apps on the Mac App Store because of their use of private API calls.

The detected private API symbols include:

CAContext CALayerHost NSAccessibilityRemoteUIElement NSNextStepFrame NSThemeFrame NSURLFileTypeMappings

How to exclude those private api from electron framework (version 2.0.4) and approve to Apple?

Thanks in advance.

**Comment by mmswide** [comment]
By upgrading the new electron version I can solve the problem.
