### ISSUE TITLE
 Cannot find module 'vue'

### ISSUE THREAD

**Issue by RezaHaidari** [SimulatedGREG/electron-vue#101]
##### Describe the issue / bug.

previous version (webpack 1) its works fine, but in current version (webpack2) i got this error " Cannot find module 'vue' "

##### How can I reproduce this problem?

install new version from vue-cli on window10 , npm i and finally  run with "npm run dev" command.

##### If visual, provide a screenshot.

![2017-01-23_212202](https://cloud.githubusercontent.com/assets/12013210/22215902/38eb6716-e1b2-11e6-8a00-9fe7b4e282aa.jpg)

##### Tell me about your development environment.
  * Node version: 6.9.1
  * NPM version: 3.10.10
  * vue-cli version: 2.10
  * Operating System: windows10

**Comment by SimulatedGREG** [comment]
From #102 
> Node version: 7.4
NPM version: 4.1.2
vue-cli version: (if necessary) 2.8
Operating System: Windows 10 x64

**Comment by SimulatedGREG** [comment]
@RezaHaidari 

Can you confirm `node_modules` were installed inside the `app` directory?

**Comment by MatthewOverall** [comment]
Yes, they installed under /app/node_modules/

-vue
-vue-electron
-vue-router
-vuex

**Comment by SimulatedGREG** [comment]
@MatthewOverall 

Are you also on Windows?

**Comment by MatthewOverall** [comment]
Yes

**Comment by MatthewOverall** [comment]
What can I do to help? I just pulled this down for the first time and can't see immediately where the issue is coming from. If you can't replicate the issue in your environment I would be glad to set up a remote session.

**Comment by SimulatedGREG** [comment]
@MatthewOverall 

Currently trying to investigate within a virtual box. But I think it might be an issue trying to add `app/node_modules` to globalPath in `app/index.ejs`.

**Comment by MatthewOverall** [comment]
Yes, you are correct, the path seperator is acting as an escape char. 
`require('module').globalPaths.push('D:\Source\cube-utils-ui\app\node_modules')`
vs
`require('module').globalPaths.push('D:\\Source\\cube-utils-ui\\app\\node_modules')`

**Comment by SimulatedGREG** [comment]
Just caught myself, lol. This is pretty unfortunate, going to apply a fix shortly.

![image](https://cloud.githubusercontent.com/assets/8327811/22217300/0fab7c3c-e168-11e6-87cc-65933cf5b71f.png)

**Comment by MatthewOverall** [comment]
In the meantime @RezaHaidari, until he releases the fix.

replace 
`require('module').globalPaths.push('<%= htmlWebpackPlugin.options.appModules %>')`
with
`require('module').globalPaths.push('<%= htmlWebpackPlugin.options.appModules.replace(/\\/g,'\\') %>')`

inside the index.ejs file.

**Comment by charlesdelorme** [comment]
Your fix dosen't work for me @MatthewOverall.
The new fixed path is incorrect, my path doesn't have any "/" by default. 
(With htmlWebpackPlugin.options.appModules)

Path with the new fix:
![path](http://i.imgur.com/RJ2veqC.png)

**Comment by RezaHaidari** [comment]
@charlesdelorme

copy new update, work for me. 

require('module').globalPaths.push('<%= htmlWebpackPlugin.options.appModules.replace(/\\/g,'\\\\') %>')

thanks @MatthewOverall

**Comment by MatthewOverall** [comment]
@charlesdelorme You must have coppied it just before my edit. 
`require('module').globalPaths.push('<%= htmlWebpackPlugin.options.appModules.replace(/\\/g,'\\\\') %>')`

**Comment by SimulatedGREG** [comment]
Thanks for the help @MatthewOverall ! My virtual box is very sluggish to get things done quickly.

**Comment by MatthewOverall** [comment]
@SimulatedGREG 

Glad to help. Thanks for creating this boiler plate project. Really well done.
