### ISSUE TITLE
vue-devtools + devtron not appearing in the devtools window

### ISSUE THREAD

**Issue by lurein** [SimulatedGREG/electron-vue#1018]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
I haven't made any changes whatsoever to index.dev.js, and I'm not getting console errors re: this, but I can't find vue-devtools or devtron in the devtools window when it pops up! Is there something I have to do independently to enable it?
##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by davidchalifoux** [comment]
From https://simulatedgreg.gitbooks.io/electron-vue/content/en/faqs.html

> Make sure to close and reopen the developer tools panel on first launch if they are missing. Also check your terminal check for any error messages that may occur during installation.
