### ISSUE TITLE
Blank app with run dev

### ISSUE THREAD

**Issue by charlesdelorme** [SimulatedGREG/electron-vue#102]
##### Describe the issue / bug.
\#
The module vue is not found and the module vue is installed in app/node_modules.
[Log with npm run dev](https://gist.github.com/anonymous/1e39dd62161c5817553bfc344b89ba5a)
The app works fine when I make npm run build.

##### How can I reproduce this problem?
\#
Normal installation and npm run dev

##### If visual, provide a screenshot.
\#
![Electron screenshot](https://i.imgur.com/5ZkmNpU.png)

##### Tell me about your development environment.
  * Node version: 7.4
  * NPM version: 4.1.2
  * vue-cli version: (if necessary) 2.8
  * Operating System: Windows 10 x64

**Comment by charlesdelorme** [comment]
Same issues as #101 
We just publish our issues at the same time.

**Comment by SimulatedGREG** [comment]
Was just noticing that. Going to continue on #101.

**Comment by govi2010** [comment]
i'm getting this errors in both mac and windows

**Comment by charlesdelorme** [comment]
Take a look at #101, if you have the error again post an issue. 😄
