### ISSUE TITLE
"Getting started" broken, webpack can't resolve modules 

### ISSUE THREAD

**Issue by Simon-L** [SimulatedGREG/electron-vue#103]
### "Getting started" basic setup is broken as of now on my setup
webpack can't resolve:
'strip-ansi', 'sockjs-client', 'core-js/library/fn/object/assign' and 'core-js/library/fn/object/define-property'

##### Describe the issue / bug.
It worked on January 22-23,
when running `npm run dev`, right after `npm install`, it fails at the end and displays the following in red:
 ```
       ERROR in (webpack)-dev-server/client?http://localhost:9080
         Module not found: Error: Can't resolve 'strip-ansi' in '[project path]node_modules/webpack-dev-server/client'
          @ (webpack)-dev-server/client?http://localhost:9080 3:16-37
          @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js
         
         ERROR in (webpack)-dev-server/client/socket.js
         Module not found: Error: Can't resolve 'sockjs-client' in '[project path]node_modules/webpack-dev-server/client'
          @ (webpack)-dev-server/client/socket.js 1:13-37
          @ (webpack)-dev-server/client?http://localhost:9080
          @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js
         
         ERROR in ./~/babel-runtime/core-js/object/assign.js
         Module not found: Error: Can't resolve 'core-js/library/fn/object/assign' in '[project path]node_modules/babel-runtime/core-js/object'
          @ ./~/babel-runtime/core-js/object/assign.js 1:30-73
          @ ./~/babel-runtime/helpers/extends.js
          @ ./app/src/renderer/main.js
          @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js
         
         ERROR in ./~/babel-runtime/core-js/object/define-property.js
         Module not found: Error: Can't resolve 'core-js/library/fn/object/define-property' in '[project path]node_modules/babel-runtime/core-js/object'
          @ ./~/babel-runtime/core-js/object/define-property.js 1:30-82
          @ ./~/babel-runtime/helpers/defineProperty.js
          @ ./app/src/renderer/vuex/modules/counters.js
          @ ./app/src/renderer/vuex/modules nonrecursive \.js$
          @ ./app/src/renderer/vuex/modules/index.js
          @ ./app/src/renderer/vuex/store.js
          @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./app/src/renderer/App.vue
          @ ./app/src/renderer/App.vue
          @ ./app/src/renderer/main.js
          @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js
```

The scaffold setup is the following:
```
? Select which Vue plugins to install vue-electron, vue-resource, vue-router, vuex
? Use linting with ESLint? No
? Setup unit testing with Karma + Mocha? No
? Setup end-to-end testing with Spectron + Mocha? No
? What build tool would you like to use? packager
```

I received a warning about node version, I'm on 4.7.2, `npm install` recommended node >= 6.0.0 and the docs recommend >= 6.5.0.

Could it be caused only by versions?

*I initially wanted to post an issue about adding jQuery + Foundation JS to this boilerplate as i'm unable to find a way to do that but this is yet another issue that arised while trying to get to that!*

##### How can I reproduce this problem?
Following the `Getting started` guide found at: https://simulatedgreg.gitbooks.io/electron-vue/content/docs/getting_started.html.

##### Tell me about your development environment.
  * Node version: 4.7.0
  * NPM version: 2.15.11
  * vue-cli version: `$ vue --version
2.8.0`
  * Operating System: Ubuntu (Linux Mint) Linux 64 bit

**Comment by Simon-L** [comment]
After diving in a long list of errors and adding modules that were reported to miss, I ended up installing these npm packages with `--save-dev` in the root folder of the electron-vue project:
```
strip-ansi
inherits
ansi-regex
debug
url-parse
sockjs
sockjs-client
websocket-driver
websocket-extensions
requires-port
querystringify
original
json3
ms
faye-websocket
eventsource
core-js
```

**Comment by citycide** [comment]
> NPM version: 2.15.11

It's probably because of this honestly. NPM >= 3.0 uses a flat(ter) hierarchy. Try upgrading that and this might be solved.

**Comment by SimulatedGREG** [comment]
@Simon-L 

Were you able to try out @citycide's suggestions? If not, I would recommend trying it out with [`npm-windows-upgrade`](https://github.com/felixrieseberg/npm-windows-upgrade).

**Comment by SimulatedGREG** [comment]
Going to go ahead and close this for now. Feel free to comment back if you are still having issues.
