### ISSUE TITLE
ESLint errors break WebPack builds

### ISSUE THREAD

**Issue by Luminess** [SimulatedGREG/electron-vue#105]
A bit irritating when I run my app, and it comes up with the electron file browser instead of my app just because ESLint was complaining about unused variables.

**Comment by SimulatedGREG** [comment]
@Luminess 

If you don't like the way ESLint is setup, then you can always customize it. Within `.eslintrc.js` you can adjust how [`no-unused-vars`](http://eslint.org/docs/rules/no-unused-vars) is handled. This issue has nothing to do with electron-vue.
