### ISSUE TITLE
Can't find module in electron.js when pack all the things.

### ISSUE THREAD

**Issue by SidKwok** [SimulatedGREG/electron-vue#106]
##### Describe the issue / bug.
It is FINE when it is on dev mode, but when I do `npm run build:mas`, it will tells me that can't find the module.

##### If visual, provide a screenshot.
In `electron.js`:
```javascript
const axios = require('axios');
console.log(axios);
```
When I build the package:
<img width="299" alt="0171a662b848a0c2378de296a4c02282" src="https://cloud.githubusercontent.com/assets/13268747/22281876/3a801014-e314-11e6-8615-3b3841643b60.png">

##### Tell me about your development environment.
  * Node version: v6.2.0
  * NPM version: 3.8.9
  * vue-cli version: (if necessary)
  * Operating System: macOS 10.12.2 (16C67)

If you need more information, just comment, Thanks~

**Comment by SimulatedGREG** [comment]
@SidKwok 

The version of electron-vue you used to scaffold you app previously did not support bundling the main process, in other words you can't use any npm packages in `electron.js`. But good news! A recent update of electron-vue has migrated to using webpack 2 and supports many new features like using npm packages in the main process.

I would recommend scaffolding a new app and transferring over your source files. You can take a look at the milestone [here](https://github.com/SimulatedGREG/electron-vue/milestone/1?closed=1).

**Comment by SidKwok** [comment]
Thanks for your feedback. I can import the npm packages now, but there's something wrong with `Promise`.
When I pack:
<img width="512" alt="c89999e3f4b4a4fc55fbd7549ff79c63" src="https://cloud.githubusercontent.com/assets/13268747/22284297/9b4bb3a0-e321-11e6-86a0-d679d7fd72eb.png">

**Comment by Abramwow** [comment]
I got the same issue on windows, can't resolve any babel-runtime helper module. Babel-runtime add these helper module import on the top of compiled file. 

![image](https://cloud.githubusercontent.com/assets/2335683/22405437/8815c71c-e67d-11e6-861f-867cc0cfed2b.png)

When i install babel-runtime in app dir, i can pack app with no error, maybe webpack search these helper module in app dir. But the packaged app still can't find any third-party modules.

![image](https://cloud.githubusercontent.com/assets/2335683/22406032/1c43a230-e686-11e6-814a-f7e998a10565.png)

**Comment by SimulatedGREG** [comment]
Could you guys try updating `.babelrc` by moving the `transform-runtime` plugin so only the renderer environment has it enabled. This might solve the issues but may not be a solid solution. I'll will be investigating some different settings, that are more specific to the electron environment.

**Comment by SimulatedGREG** [comment]
Going to close this for now, since nobody has reported anything back. This may have been related to the official Webpack 2 release as certain dependencies may have needed to update. Did look into modifying babel to target `node@^6`, but will be holding off on that for now.
