### ISSUE TITLE
Unable to install `vue-devtools` on m1 macbook pro running electron vue

### ISSUE THREAD

**Issue by jyooi** [SimulatedGREG/electron-vue#1071]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
Unable to install `vue-devtools`:
 Error: Exited with code 9
\#

##### How can I reproduce this problem?
when running the project.
\#

##### If visual, provide a screenshot.
<img width="656" alt="Screenshot 2021-03-02 at 10 55 50 PM" src="https://user-images.githubusercontent.com/42993221/109666740-7145f900-7baa-11eb-8a0b-d7c85e47744b.png">
\#

##### Tell me about your development environment.
  * Node version: 14.15.4
  * NPM version: 7.5.4
  * vue-cli version: (if necessary)
  * Operating System: ARM M1 macos

**Comment by mehboobsamnani** [comment]
Hey @jyooi did your issue got solved , care to explain the solution please ?

**Comment by jyooi** [comment]
Hi @mehboobsamnani, yeah i have solve this issue by simple update the electron-devtools-installer version to latest version , I hope it help

**Comment by mehboobsamnani** [comment]
> Hi @mehboobsamnani, yeah i have solve this issue by simply update the electron-devtools-installer to latest version , I hope it help

thanks mate it did help.
