### ISSUE TITLE
Build issue: SyntaxError: Identifier 'tasks' has already been declared

### ISSUE THREAD

**Issue by RoshanMali** [SimulatedGREG/electron-vue#1076]
##### Describe the issue / bug.

Thank you for creating this package.

I'm facing this issue while building:

```
const tasks = new Listr(
        ^

SyntaxError: Identifier 'tasks' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```
on .electron-vue\build.js:45

##### How can I reproduce this problem?

1. Create new project using this command: `vue init simulatedgreg/electron-vue my-project`
2. run: npm run build

##### If visual, provide a screenshot.

![image](https://user-images.githubusercontent.com/30631249/115723328-7f8be680-a39d-11eb-85a7-ba3112495145.png)

##### Tell me about your development environment.
  * Node version: v12.19.0
  * NPM version: 6.14.8
  * vue-cli version: 4.5.8
  * Operating System: Windows

**Comment by itenl** [comment]
Same issues, but u can comment [the code](https://github.com/SimulatedGREG/electron-vue/blob/8d4ed607d65300381a8f47d97923eb07832b1a9a/template/.electron-vue/build.js#L41) to working, btw, it is recommended that u use `electron-builder`.

**Comment by huaeval** [comment]
rename tasks

**Comment by oldsweet** [comment]
Same issues,can someone can help me? QwQ

**Comment by doc-han** [comment]
This is an actual error in the code. Tasks has been defined multiple times.

**Comment by phelogges** [comment]
i got this issue solved by commenting [tasks](https://github.com/SimulatedGREG/electron-vue/blob/8d4ed607d65300381a8f47d97923eb07832b1a9a/template/.electron-vue/build.js#L41) and [Multispinner](https://github.com/SimulatedGREG/electron-vue/blob/8d4ed607d65300381a8f47d97923eb07832b1a9a/template/.electron-vue/build.js#L42) instance, then upgrading `electron-builder` to the latest version.

**Comment by eliooses** [comment]
Thanks for the workaround @phelogges !, works like a charm.

**Comment by RoshanMali** [comment]
@phelogges solution worked, Thanks.

**Comment by 583** [comment]
I solved this issue by rename the follow code.
line 45    =>     "  const tasks"    to   "  const _tasks" 
line 77    =>     "  await tasks "   to    " await _tasks"
