### ISSUE TITLE
Module not found cannot resolve component-normalizer

### ISSUE THREAD

**Issue by jrenton** [SimulatedGREG/electron-vue#108]
I just tried to do a fresh install of electron-vue via the `vue-cli` per the steps in this projects' README with all options checked, along with using `electron-builder` and I get the following error when attempting to run `npm run dev` on windows:

`Module not found: Error: Can't resolve 'ode_modulesue-loaderlibcomponent-normalizer'` (yes it is formatted all weird like that for some reason).

  * Node version: 6.6.0
  * NPM version: 3.10.8
  * vue-cli version: 2.8.0
  * Operating System: Windows 10

Full error (for an individual file, but is the same for all .vue files):
```
ERROR in ./app/src/renderer/components/LandingPageView/CurrentPage.vue
         Module not found: Error: Can't resolve 'c:Codeapi-response-comparer-v2
         ode_modulesue-loaderlibcomponent-normalizer' in 'c:\Code\api-response-comparer-v2\app\src\renderer\components\LandingPageView'
          @ ./app/src/renderer/components/LandingPageView/CurrentPage.vue 5:16-108
          @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/eslint-loader?{}!./app/src/renderer/components/LandingPageView.vue
          @ ./app/src/renderer/components/LandingPageView.vue
          @ ./app/src/renderer/routes.js
          @ ./app/src/renderer/main.js
          @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js
```

**Comment by jrenton** [comment]
I also tried upgrading everything and that still doesn't work. New versions:

- Node version: 6.9.4
- NPM version 3.10.8
- vue-cli version: 2.8.0

**Comment by SimulatedGREG** [comment]
It seems, for whatever reason, paths are being treated improperly as literal strings. This is a problem for Windows as `\` is used to escape things, therefore breaking the paths. I don't have access to a windows machine other than a VM, but I (and others) didn't previously run into this problem.

**Comment by jrenton** [comment]
I tried again today and it worked! There must have been a bug with vue router or something.

**Comment by SimulatedGREG** [comment]
Oh that's good to hear! There may be a few bugs here and there since most people are updating their packages to support webpack 2.

**Comment by kunKun-tx** [comment]
it's a [vue-loader](https://github.com/vuejs/vue-loader/issues/601) issue and got fixed pretty quickly. I was affected and had no clue for the whole afternoon...
