### ISSUE TITLE
Suggest to support LiveScript

### ISSUE THREAD

**Issue by wuxianliang** [SimulatedGREG/electron-vue#11]
Dear @SimulatedGREG 
  Thank you very much! This project help me a lot! But I partially failed when I add LiveScript. It is easy to use LiveScript inside Vue's component, but outside. I have tried for a long time but never found a similar solution. Could not understand why adding this snippet in webpack.config.js does not work. @roosephu would you like to share more knowledge on this issue? Thanks.
```javascript
{
      test: /\.ls$/,
      loader: 'livescript-loader'
},
```

**Comment by roosephu** [comment]
You are having troubles using LiveScript outside Vue? I did encounter a problem with LS but it's inside Vue. I'm using `vue-livescript-loader` instead of `livescript-loader`, and actually I hacked it. I changed https://github.com/borestad/vue-livescript-loader/blob/master/index.js#L14 to 
```js
source = source.replace(/[\/]{2}/g, '#');
```
It seems that `source` uses `\n` to separate lines. 

And could you please post your error messages?

**Comment by SimulatedGREG** [comment]
@wuxianliang 

I'm having no issues when using LiveScript outside of a Vue component file. Were you sure to install the [`livescript-loader`](https://www.npmjs.com/package/livescript-loader) in the correct `package.json`? ([more info](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/project_structure.html#packagejson-is-for-all-your-development-needs))

Steps I took to get this working:
1. Use `vue-cli` to scaffold a new project
2. Installed [`livescript-loader`](https://www.npmjs.com/package/livescript-loader) in root directory of application (not inside the `app` directory).
3. Added the loader to `webpack.config.js` (at line 43, just after `vue-loader`)
```js
{
  test: /\.ls$/,
  loader: 'livescript-loader'
}
```
Then made a `test.ls` file inside `./app/src` with...
```ls
console.log 'hello world'
```
And imported `test.ls` in `main.js`
```js
import './test.ls'
```
Lastly, I started the app with `npm run dev` and saw that `'hello world'` was in console.

**Comment by SimulatedGREG** [comment]
@roosephu 
As for your situation, this would be a problem with [`vue-loader`](https://github.com/vuejs/vue-loader). Please check out this [issue](https://github.com/vuejs/vue-loader/issues/135). There's already a [pull request](https://github.com/vuejs/vue-loader/pull/289) to fix, so hopefully that happens soon 😁. And if you are wanting to use both LiveScript and JavaScript WITH eslint then make sure to check this [issue](https://github.com/vuejs/vue-loader/issues/162#issuecomment-201980468) out as well.

**Comment by roosephu** [comment]
@SimulatedGREG Thanks! When I take a closer look at `vue-livescript-loader`'s source file this time, I notice that it mentioned this issue. It's a shame that I ignored the comments. Anyway, thanks for the suggestions 😄 .

**Comment by wuxianliang** [comment]
Thank you very much! @SimulatedGREG @roosephu 
I have understood the problem. I missed this fact that Js and Ls would import .js file first.
When we have store.js file and store.ls file at the same time, with import/require! store Js and Ls will import store.js only even if it is empty. If we want to import .ls file, we need to import store.ls
```javascript
import abc from 'store.ls'
```
When we have store.ls only, we do not need to indicate .ls. Just
```javascript
import/require! store 
```
Less projects are using LiveScript and JavaScript at the same. Never see 
```javascript
import abc from 'store.ls'
```
Now I got it. Thank you very much!

**Comment by SimulatedGREG** [comment]
Glad to hear everything is working for you now. If you don't want to keep adding `.ls` to your imports you could try adding the extension to the [`webpack.config.js`](https://github.com/SimulatedGREG/electron-vue/blob/master/template/webpack.config.js#L79).
