### ISSUE TITLE
Caching issues, possibly Vuex related

### ISSUE THREAD

**Issue by 6r1d** [SimulatedGREG/electron-vue#1105]
While trying `electron-vue`, I saw that old `store` modules remain, even if I removed the file manually, and even if I restarted `npm run dev`.

**How do I clear the dev cache** to make things less messy, at least?

#### Reproducing the issue

Add this code to App.vue to see old store modules:

```javascript
async created () {
  console.log(this.$store.state)
},
```

Remove the Counter from `/renderer/store/modules/`.

See if Counter is displayed in the list on the **next launch** of `npm run dev`.
That is what I see in an app I'm debugging after 3 restarts:

![](https://i.imgur.com/MYKG4Ru.png)

`store/modules` only contains standard `index.js` and `Common.js` file.

#### Development environment

  * Node version: v16.1.0
  * NPM version: 7.16.0
  * Operating System: Ubuntu 18.04.5 LTS

#### Deps:

```javascript
{
  "dependencies": {
    "core-js": "^3.16.0",
    "uuid": "^8.3.2",
    "vue": "^2.5.16",
    "vue-electron": "^1.0.6",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-electron": "^1.0.0"
  },
  "devDependencies": {
    "ajv": "^6.5.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-minify-webpack-plugin": "^0.3.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.26.0",
    "cfonts": "^2.1.2",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.1.6",
    "css-loader": "^0.28.11",
    "del": "^3.0.0",
    "devtron": "^1.4.0",
    "electron": "^2.0.4",
    "electron-builder": "^20.19.2",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "listr": "^0.14.3",
    "mini-css-extract-plugin": "0.4.0",
    "node-loader": "^0.6.0",
    "node-sass": "^6.0.1",
    "sass-loader": "^7.0.3",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "vue-devtools": "^5.1.4",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.15.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3"
  }
}
```

**Comment by LXWLXW** [comment]
Have you solved this problem?
By deleting this line, cache problem has been dealed 
![image](https://user-images.githubusercontent.com/17760738/130176056-ed93ee0a-49dc-4247-bab9-9e02e7c2ce02.png)

**Comment by 6r1d** [comment]
> By deleting this line, cache problem has been dealed

Thanks, this helped.
I'm surprised this part exists, but seems like it has its uses.

> Have you solved this problem?

Only now, really.
