### ISSUE TITLE
Unable to @extend from classes in other files (happens only while building)

### ISSUE THREAD

**Issue by manuelro** [SimulatedGREG/electron-vue#111]
### Found an issue or bug? Tell me all about!
I'm having problems trying to get sass-loader to recognize previously computed classes and `@extend` them. For instance, I have two files (file A and B), in file A I create classes dynamically using `@each`, in file B I want to `@extend` from one of the classes dynamically created on file A

##### Describe the issue / bug.
\#
I get an error that basically says that the class I want to @extend does not exist, which tells me that the way Sass files are being loaded has something to do here. Although I made sure to load the Sass files that contains the class which I'm going to @extend first, and then the Sass file that @extends from a class in that file. 

##### How can I reproduce this problem?
\#
Install any NPM package that has Saas in it, @import one Sass file that @extends from classes created by the other file.

##### If visual, provide a screenshot.
\#
```
ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-22358182!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/renderer/App.vue
Module build failed:
  @extend .o-color--black;
         ^
      "mark" failed to @extend ".o-color--black".
The selector ".o-color--black" was not found.
Use "@extend .o-color--black !optional" if the extend should be able to fail.
      in D:\Documents\Projects\box\box-desktop-vue\v1\boxscreen-desktop\app\node_modules\composite-css\stylesheets\vendor\_normalize.scss (line 175, column 11)
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-22358182!./~/sass-loader!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/renderer/App.vue 4:14-272
 @ ./app/src/renderer/App.vue
 @ ./app/src/renderer/main.js
```

On the Vue side, I have something like this:
```
<style lang="scss">
  @import "~some-package/stylesheets/A.scss";
  @import "~some-package/stylesheets/B.scss";
</style>

...
```

##### Tell me about your development environment.
  * Node version: v6.9.2
  * NPM version: 3.10.9
  * vue-cli version: (if necessary) 2.8.0
  * Operating System: Windows 10

**Comment by SimulatedGREG** [comment]
@manuelro 

> Use "@extend .o-color--black !optional" if the extend should be able to fail.

Did you try the suggestion action from `sass-loader`?

**Comment by SimulatedGREG** [comment]
Closing this for now. Feel free to comment back.
