### ISSUE TITLE
Cannot find module 

### ISSUE THREAD

**Issue by p-le** [SimulatedGREG/electron-vue#116]
I'm currently having  problem when using node-analyzer module in main process. in dev, it works fine,
but when i run packaged file, it says cannot find module.

im using latest electron-vue version

use node-analyzer in main process
![image](https://cloud.githubusercontent.com/assets/20235327/22775191/db6a3254-eeed-11e6-9ca4-069cd487b653.png)

when i run packaged app
![image](https://cloud.githubusercontent.com/assets/20235327/22774896/8de57a12-eeec-11e6-9068-557f6d5b456d.png)

  * Node version: 7.2.0
  * NPM version: 3.10.9
  * vue-cli version: (if necessary)
  * Operating System: Windows 7 64 bit

**Comment by SimulatedGREG** [comment]
@p-le 

Where you sure to install `node-analyzer` in the `app/package.json`?

**Comment by p-le** [comment]
I have installed **node-analyzer** in **app/package.json**
![image](https://cloud.githubusercontent.com/assets/20235327/22809590/d71266ca-ef76-11e6-9890-9ab7b34a7fa6.png)

**Comment by p-le** [comment]
ok, after one day of searching, when i try to extract **app.asar** in **win-unpacked/resources,**, it works but i see something is wrong with asar archive 
`
asar extract app.asar app
`

**Comment by p-le** [comment]
finally i found the reason, it was caused by **index.js** of **node-analyzer** module 
`
module.exports = require('./lib/segmenter');
`
![image](https://cloud.githubusercontent.com/assets/20235327/22818167/02dc4608-efaf-11e6-8453-2bae4f814739.png)

in **node-analyer** folder, it is Segmenter.js not segmenter.
the problem is lowercase and uppercase........
