### ISSUE TITLE
npm run dev fails

### ISSUE THREAD

**Issue by rr326** [SimulatedGREG/electron-vue#119]
##### Describe the issue / bug.
`npm run dev` fails on fresh install. webpack-dev-server args aren't working.

(Note - I also tried forcing webpack-dev-server == 2.2.0 and also tried removing the --hot option, but then the next arg failed.) 

##### How can I reproduce this problem?
fresh install
`vue init simulatedgreg/electron-vue electronvue`

##### If visual, provide a screenshot.
Output with `export npm_config_loglevel=verbose`
```
.-(~/dev/tmp/electronvue)-------------------------------------------------------------------------------------------------------------------------------------(rrosen@RossMacbook)-
`--> npm run dev                                                                                                                                                             [py3]
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
npm info using npm@4.0.5
npm info using node@v6.9.2
npm verb run-script [ 'predev', 'dev', 'postdev' ]
npm info lifecycle electronvue@0.0.0~predev: electronvue@0.0.0
npm info lifecycle electronvue@0.0.0~dev: electronvue@0.0.0

> electronvue@0.0.0 dev /Users/rrosen/dev/tmp/electronvue
> node tasks/runner.js

Starting webpack-dev-server...

webpack  fallbackLoader option has been deprecated - replace with "fallback"

webpack  loader option has been deprecated - replace with "use"

webpack  Project is running at http://localhost:9080/

webpack  webpack output is served from /
         Content not from webpack is served from /Users/rrosen/dev/tmp/electronvue/app/dist

webpack

webpack  error: unknown option `--hot'

npm verb lifecycle electronvue@0.0.0~dev: unsafe-perm in lifecycle true
npm verb lifecycle electronvue@0.0.0~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/rrosen/dev/tmp/electronvue/node_modules/.bin:/Users/rrosen/.rvm/gems/ruby-2.1.5/bin:/Users/rrosen/.rvm/gems/ruby-2.1.5@global/bin:/Users/rrosen/.rvm/rubies/ruby-2.1.5/bin:/usr/local/Cellar/pyenv-virtualenv/1.0.0/shims:/Users/rrosen/.pyenv/shims:/Users/rrosen/.pyenv/bin:/Users/rrosen/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Users/rrosen/.rvm/bin
npm verb lifecycle electronvue@0.0.0~dev: CWD: /Users/rrosen/dev/tmp/electronvue
npm info lifecycle electronvue@0.0.0~postdev: electronvue@0.0.0
npm verb exit [ 0, true ]
npm info ok
```

##### Tell me about your development environment.
  * Node version: 6.9.2
  * NPM version: 4.0.5
  * vue-cli version: (if necessary) 2.8.1
  * Operating System: OSX 10.12.3

**Comment by SimulatedGREG** [comment]
@rr326 

Sorry for the trouble you are having, but I unfortunately can't reproduce this issue. I've tried multiple node versions and npm versions, including the specifics you provided, and have had no issues. I'm wondering if `webpack-dev-server` made a release recently that broke with the `--hot` flag, but has since removed that release. This might be worth investigating on [`webpack-dev-server`](https://github.com/webpack/webpack-dev-server)'s side as this isn't a direct issue with `electron-vue`.


Currently working with...
* node@6.9.2
* npm@4.0.5
* macOS 10.12.3
```bash
npm ls webpack-dev-server webpack

webpack-hot-test@0.0.0 ~
├── webpack@2.2.1 
└── webpack-dev-server@2.3.0
```

**Comment by gimyboya** [comment]
Same here when i do a fresh installation the command `npm run dev` fails and i get the following error

`Starting webpack-dev-server...

webpack  fallbackLoader option has been deprecated - replace with "fallback"

webpack  loader option has been deprecated - replace with "use"

webpack  Project is running at http://localhost:9080/
         webpack output is served from /

webpack  Content not from webpack is served from /home/itachi/Desktop/dev/git/nour/app/dist

webpack  Hash: c66bb46691883ed94c06
         Version: webpack 2.2.1
         Time: 15109ms
                 Asset       Size  Chunks                    Chunk Names
         imgs/logo.png    61.9 kB          [emitted]         
           renderer.js    1.15 MB       0  [emitted]  [big]  renderer
            index.html  493 bytes          [emitted]         
         chunk    {0} renderer.js (renderer) 384 kB [entry] [rendered]
            [65] (webpack)/hot/emitter.js 77 bytes {0} [built]
            [73] ./app/src/renderer/main.js 503 bytes {0} [built]
            [74] (webpack)-dev-server/client?http://localhost:9080 4.9 kB {0} [built]
            [75] (webpack)/hot/dev-server.js 1.57 kB {0} [built]
            [79] ./app/src/renderer/routes.js 143 bytes {0} [built]
            [84] ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./app/src/renderer/App.vue 77 bytes {0} [built]
            [91] ./~/babel-runtime/helpers/extends.js 544 bytes {0} [built]
           [132] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
           [158] ./~/strip-ansi/index.js 161 bytes {0} [built]
           [161] ./app/src/renderer/App.vue 1.53 kB {0} [built]
           [171] ./~/vue-loader/~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?id=data-v-017a3761!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/renderer/App.vue 1.46 kB {0} [built]
           [176] (webpack)-dev-server/client/overlay.js 3.59 kB {0} [built]
           [177] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
           [180] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
           [202] multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js 52 bytes {0} [built]
              + 188 hidden modules
         Child html-webpack-plugin for "index.html":
             chunk    {0} index.html 541 kB [entry] [rendered]
                 [0] ./~/lodash/lodash.js 540 kB {0} [built]
                 [1] (webpack)/buildin/module.js 517 bytes {0} [built]
                 [2] ./~/html-webpack-plugin/lib/loader.js!./app/index.ejs 1.02 kB {0} [built]

webpack  webpack: Compiled successfully.

Starting electron...

electron  /home/itachi/Desktop/dev/git/nour/node_modules/electron/index.js:9
            throw new Error('Electron failed to install correctly, please delete node_modules/' + path.basename(__dirname) + ' and try installing again')
            ^
          
          Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
              at Object.<anonymous> (/home/itachi/Desktop/dev/git/nour/node_modules/electron/index.js:9:9)
              at Module._compile (module.js:571:32)
              at Object.Module._extensions..js (module.js:580:10)
              at Module.load (module.js:488:32)
              at tryModuleLoad (module.js:447:12)
              at Function.Module._load (module.js:439:3)
              at Module.require (module.js:498:17)
              at require (internal/module.js:20:19)
              at Object.<anonymous> (/home/itachi/Desktop/dev/git/nour/node_modules/electron/cli.js:3:16)
              at Module._compile (module.js:571:32)
` 

I fixed this issue by reinstalling manually...

node: 7.4.0
npm: 4.0.5
vue: 2.8.1

Ubuntu 16.10 64bit

**Comment by SimulatedGREG** [comment]
@gimyboya 

Your issue is specific to `electron` trying to run its postinstall to download. As the logs suggests...
```bash
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
```
 have you tried doing so?

**Comment by gimyboya** [comment]
As i mentioned i have fixed this error by reinstalling electron again manually i didn't delete anything i just reinstalled electron alone inside my project folder

**Comment by rr326** [comment]
I tried reinstalling electron and it didn't work. Any ideas what to try next?

```
rm -rf node_modules/electron
npm install electron
npm run dev
...
webpack  error: unknown option `--hot'
```

@gimyboya 
How did you get the logging? That might help me debug on my end.

**Comment by AkiraLaine** [comment]
@rr326 I don't think that will help you, as your issue is a completely different one from @gimyboya.

It's a weird issue though.

**Comment by gimyboya** [comment]
@rr326 in my case i didn't remove electron i just override it with a new installation... you may try again by initializing a new project and overriding electron if you get the same problem

**Comment by rr326** [comment]
@AkiraLaine 
Correct - that did not change anything

@SimulatedGREG 
Another clue:
If I add a truly bogus argument to the webpack-dev-server run statement in `runner.js` I get a different outcome:

runner.js (end)
```
let command_line = `webpack-dev-server --bogus --hot --colors --config webpack.renderer.config.js --port ${config.port} --content-base app/dist`
console.log('Command: ', command_line)
run(command_line, YELLOW, 'webpack')

Usage: https://webpack.js.org/configuration/dev-server/

         Config options:
... (Big usage help screen)
webpack  Unknown argument: bogus
```

Then if I start removing args, they all fail (not just --hot). 
It's almost like some subsidiary command is getting the command line and expects the previous args to have been popped out. 

```
Command:  webpack-dev-server --hot --colors --config webpack.renderer.config.js --port 9080 --content-base app/dist
webpack  error: unknown option `--hot'

Command:  webpack-dev-server  --colors --config webpack.renderer.config.js --port 9080 --content-base app/dist
webpack  error: unknown option `--colors'

Command:  webpack-dev-server  --content-base app/dist --config webpack.renderer.config.js --port 9080
webpack  error: unknown option `--content-base'
```

Any ideas how I can debug? I've acked through the entire directory looking for "unknown option" and modified every error / console call with a line number(so I could then trace from there), but I can't find it.  Maybe that is coming from a globally install module or node itself.

**Comment by rr326** [comment]
@SimulatedGREG 
Here's another clue.  I decided to try to build the project. 

I get another "unknown option" error.  (This is in a fresh install, and latest Node, npm, webpack)

```
.-(~/dev/tmp/ev2)---------------------------------------------------------------------------------------------------------------------------------------------(rrosen@RossMacbook)-
`--> node --version                                                                                                                                                          [py3]
v6.9.5
.-(~/dev/tmp/ev2)---------------------------------------------------------------------------------------------------------------------------------------------(rrosen@RossMacbook)-
`--> npm --version                                                                                                                                                           [py3]
4.2.0
.-(~/dev/tmp/ev2)---------------------------------------------------------------------------------------------------------------------------------------------(rrosen@RossMacbook)-
`--> npm ls webpack webpack-dev-server                                                                                                                                       [py3]
ev2@0.0.0 /Users/rrosen/dev/tmp/ev2
├── webpack@2.2.1
└── webpack-dev-server@2.3.0

-(~/dev/tmp/ev2)---------------------------------------------------------------------------------------------------------------------------------------------(rrosen@RossMacbook)-
`--> npm run build                                                                                                                                                           [py3]

> ev2@0.0.0 build /Users/rrosen/dev/tmp/ev2
> npm run pack && build


> ev2@0.0.0 pack /Users/rrosen/dev/tmp/ev2
> npm run pack:main && npm run pack:renderer


> ev2@0.0.0 pack:main /Users/rrosen/dev/tmp/ev2
> cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.main.config.js

Hash: f887bb40c90e6f3d9373
Version: webpack 2.2.1
Time: 927ms
  Asset       Size  Chunks             Chunk Names
main.js  931 bytes       0  [emitted]  main
   [1] ./app/src/main/index.js 745 bytes {0} [built]
    + 1 hidden modules

> ev2@0.0.0 pack:renderer /Users/rrosen/dev/tmp/ev2
> cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js

fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
 10% building modules 6/8 modules 2 active .../dev/tmp/ev2/app/src/renderer/App.vue
  error: unknown option `-p'


npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "pack:renderer"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ev2@0.0.0 pack:renderer: `cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ev2@0.0.0 pack:renderer script 'cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ev2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.renderer.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ev2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ev2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rrosen/.npm/_logs/2017-02-13T13_58_34_595Z-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "pack"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ev2@0.0.0 pack: `npm run pack:main && npm run pack:renderer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ev2@0.0.0 pack script 'npm run pack:main && npm run pack:renderer'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ev2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run pack:main && npm run pack:renderer
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ev2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ev2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rrosen/.npm/_logs/2017-02-13T13_58_34_684Z-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ev2@0.0.0 build: `npm run pack && build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ev2@0.0.0 build script 'npm run pack && build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ev2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run pack && build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ev2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ev2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rrosen/.npm/_logs/2017-02-13T13_58_34_740Z-debug.log
```

**Comment by rr326** [comment]
My bad.

After spending a truly ridiculous amount of time tracing through node code, I finally tracked it back to my environment. I had NODE_PATH set in my .zshrc - probably from several years ago when I just started out. I removed that and it all worked.

**Comment by SimulatedGREG** [comment]
That sure sounds like a horrible experience. Glad you got everything sorted out!

**Comment by rr326** [comment]
BTW - I've been using the template. Really great. Thanks so much.
