### ISSUE TITLE
app.asar larger after updating electron-vue (node_modules related)

### ISSUE THREAD

**Issue by zxc23** [SimulatedGREG/electron-vue#122]
Now, this isn't an extremely serious issue, but after updating my project to the most recent electron-vue template (including webpack 2) and using electron-packager (as I've always done), I've noticed that resources/app.asar is 30mb larger than it used to be, which is making my final zipped size 65mb instead of 50mb.

I extracted app.asar to have a look, and it has a node_modules folder which is full of packages. I checked my older builds and saw that the node_modules folder inside app.asar was empty. If I am understanding this correctly, the previous build was bundling modules into build.js. Is there a way to achieve the previous behaviour?

I've modified a few things in the configs, but don't think they were relevant to this. I can provide more info if necessary.

**Comment by SimulatedGREG** [comment]
@zxc23 

Yes, you would be correct. The newer `electron-vue` treats all packages as webpack `externals` and no longer bundles everything into one `build.js` file. The main reasoning for this was to support the main process and eliminate issues related to native node modules. All that to say, `node_modules` is now included within production builds. 

Now there a few things you can try to minimize any extra overhead in file size.

##### Option 1
Use `yarn clean` within the `app` directory. This will go through all `node_modules` and remove extraneous files to limit overall package size ([More Info](https://yarnpkg.com/en/docs/cli/clean)). That why markdown files, test files, etc. will be removed before packaging.

##### Option 2
Configure `webpack` to no longer treat dependencies as externals by removing [`webpack.renderer.config.js`@L18](https://github.com/SimulatedGREG/electron-vue/blob/master/template/webpack.renderer.config.js#L18) and re-adding `node_modules` to the build setting's `ignore` option at [`config.js`@L30](https://github.com/SimulatedGREG/electron-vue/blob/master/template/config.js#L30) (Line numbers vary). This will set things back to bundling all assets into one file.

**Comment by zxc23** [comment]
Thanks for the response.  I already had the externals line (almost) cleared, but the ignore option I had not updated. I ended up breaking things and then fixing everything... pretty sure it's all OK now. Easy to break things I have to say! But I've learnt a lot about electron, vue, and webpack from electron-vue, so I must give my thanks! 👍

**Comment by SimulatedGREG** [comment]
No problem. And for anybody else that reads this later, feel free to comment any further questions. I'll be detailing some of this info in the documentation.

**Comment by emmanuelgeoffray** [comment]
hi @SimulatedGREG 
indeed it would be nice to mention how to use `yarn clean` in the docs, as the docs mention it but does not explain how to use it. I found this issue by looking for explanations.

Best,
Emmanuel

**Comment by SimulatedGREG** [comment]
@emmanuelgeoffray 

Just as posted above, the [`yarn` documentation](https://yarnpkg.com/en/docs/cli/clean) does a fairly good job at describing what `yarn clean` accomplishes. When using the current version of electron-vue, after installing dependecies with `yarn`, you can follow that with `yarn clean`.

Just as noted in the `yarn` documentation, this feature is typically meant for more *advanced* users, and there probably isn't a guarantee that your application dependencies will fully function afterwords (but I'm sure `yarn` knows what to do for the most part). In the end, this may not make too much of a significant difference to build size.

**Comment by emmanuelgeoffray** [comment]
Thanks @SimulatedGREG for the clarification!
