### ISSUE TITLE
Vuex docs recommend avoiding strict mode in production

### ISSUE THREAD

**Issue by zxc23** [SimulatedGREG/electron-vue#123]
I was puttering around in the Vuex 2 docs and noticed that it recommends not using strict mode in production: https://vuex.vuejs.org/en/strict.html

I checked the electron-vue template and saw that it has strict: true hard-coded: https://github.com/SimulatedGREG/electron-vue/blob/master/template/app/src/renderer/vuex/store.js#L14

**Comment by SimulatedGREG** [comment]
@zxc23 

Nice catch. I've know this before, but didn't realize I had this hard coded. Whoops. Will fix in next update.
