### ISSUE TITLE
module is not defined(using electron-packager)

### ISSUE THREAD

**Issue by lyg1949** [SimulatedGREG/electron-vue#126]
### Found an issue or bug? Tell me all about!

I run the following commands:
```
# Install vue-cli and scaffold boilerplate
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project

# Install dependencies and run your app
cd my-project
npm install
npm run dev
```
It worked ok!,but when after running `npm run pack`,open `index.html` file, I got an error:`module is not defined`

##### How can I reproduce this problem?

Just repeat the above steps.

##### If visual, provide a screenshot.
![error](https://cloud.githubusercontent.com/assets/6082887/22955899/c064a014-f359-11e6-93cb-b6c96b0b0f67.PNG)

##### Tell me about your development environment.
  * Node version: 6.9.1
  * NPM version: 4.0.1
  * vue-cli version: (if necessary) 2.7.0
  * Operating System: win 10

**Comment by SimulatedGREG** [comment]
@lyg1949 

Are you trying to open `index.html` in a normal web browser? If so, then that won't work as expected.

**Comment by lyg1949** [comment]
@SimulatedGREG 

I forgot to say that I open the `index.html` file in `chrome` web browser(v57)

**Comment by SimulatedGREG** [comment]
Yes that is expected behavior. `electron-vue` does not build for web; only for electron.

**Comment by lyg1949** [comment]
@SimulatedGREG 
Thank you!

**Comment by sarada123** [comment]
i am new to electron with angular js.Please help me to overcome the issue
"HashMap is undifined"

**Comment by zivoradmilekic** [comment]
Hi @SimulatedGREG! I am building app that serves static files over local network via express.js.
I managed to duplicate renderer functionality and adapt it to my needs. But I have problem with webpack's build, as you mentioned and 'require' not working in browser.

Is there some quick fix for my problem and what would it be? Thanks...
