### ISSUE TITLE
Feature request: default webpack config for web dev. use case (i.e. "webpack.web.config")

### ISSUE THREAD

**Issue by utkukaratas** [SimulatedGREG/electron-vue#128]
I'm guilty of abusing this awesome tool for web development purposes (before I go on.. thank you for this!). 

I don't use electron-vue for Electron and its native desktop targets. But for developing a Vue based single page webapp it's been a life saver. It comes with the tooling builtin, sane webpack and npm configurations, with all the live loading hotness and what not. 

The only nuisance I had to deal with was configuring a seperate webpack config and a main.js for a web output. That's because the current default configs are a little bit too involved with Electron runtime and webpack.renderer.config.js is not something I'd like to poke. That's why I went with a completely seperate webpack config.

IMHO it would be great if the default template handled this use case (either with seperate config files or with some simple boolean switches in root config.js).

**Comment by SimulatedGREG** [comment]
This doesn't sound like too bad of an idea. I wouldn't plan to provide extensive support to building for `web`, but making an extra `webpack.web.config.js` doesn't seem like a problem.

**Comment by tirjok** [comment]
@utkukaratas i am also interested to run same app for web and desktop.

**Comment by utkukaratas** [comment]
@tirjok I'll send a pull request once I'm sure everything is right.

**Comment by utkukaratas** [comment]
@tirjok sent a PR just now.

**Comment by mmorainville** [comment]
+1 I'm also interested, it's a great idea and it could save some time when developing an Electron app that could end up being a simple webapp too.

**Comment by SimulatedGREG** [comment]
Alright guys, this has made it the `dev` branch as it part of the next Milestone (#171). Closing.

**Comment by wesleymostien** [comment]
so, how to run this please ? It's not clear...

**Comment by SimulatedGREG** [comment]
@wesleymostien 

There is a small bit about the configuration in the docs, https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html. This configuration is provided as a strong base. You can modify for your needs. Running `npm run build:web` will create a `web` output in `dist/web`.
