### ISSUE TITLE
Error building with electron-builder: "Error: Exit code: ENOENT. spawn icns2png ENOENT"

### ISSUE THREAD

**Issue by nicklaw5** [SimulatedGREG/electron-vue#130]
Getting this error when running `npm run build`:

```
Packaging for linux x64 using electron 1.6.0 to dist/linux-unpacked
Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT
```
##### Describe the issue / bug.
Unable to build with `electron-builder`. [Here is the console output](http://pastebin.com/fA7Sqks5)

This [issue](https://github.com/electron-userland/electron-builder/issues/1158) seems to indicate a problem with `icns2png` not being able to convert the macOS icns file to a png. But I'm not entirely sure. Perhaps we can specifically set a 32x32.png for the build?

##### How can I reproduce this problem?
Stock standard install:
```bash
vue init simulatedgreg/electron-vue my-project # select electron-builder for build tool
cd my-project
npm install
npm run build
```

##### Tell me about your development environment.
  * Node version: v7.5.0
  * NPM version:  v4.1.2
  * vue-cli version: v2.8.1
  * Operating System: Ubuntu 16.04.1

**Comment by SimulatedGREG** [comment]
@nicklaw5 

I think you would be right about there being issues trying to convert the `icns` to a `png`. Luckily,  it seems that `electron-builder` now supports an option for a `linux` specific image icon now. I'll be pushing out an update to support this soon. Hopefully this new feature solves your problem.
https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions

**Comment by nicklaw5** [comment]
@SimulatedGREG Any progress on getting the Linux image option added? I'm hoping to start work on a new project over the weekend.

**Comment by arthurvasconcelos** [comment]
@nicklaw5 i "solve" this problem using electron-builder docker image.

```sh
docker run --rm --name electron -ti -d -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules electronuserland/electron-builder:wine
docker exec electron npm install && npm prune
docker exec electron npm run build:linux
docker exec electron npm run build:windows
```

If you don't need build to Windows you can use `electron-builder:latest` instead.

`build:linux` >> `npm run pack && build --linux --x64`
`build:windows` >> `npm run pack && build --windows --x64`

**Comment by SimulatedGREG** [comment]
This has been fixed in the `dev` branch and will be released in the next milestone; #171 for more info. Closing.

**Comment by NPellet** [comment]
With electron-builder and Ubuntu 17, I solved it by running:
sudo apt install icnsutils
and
sudo apt install graphicsmagick

**Comment by xuzc** [comment]
@NPellet it has been solved in my Ubuntu 16 with latest electron-builder

**Comment by justUmen** [comment]
For Arch : https://aur.archlinux.org/packages/libicns/
