### ISSUE TITLE
Some bindings.js issue

### ISSUE THREAD

**Issue by Pioruniasty** [SimulatedGREG/electron-vue#132]
##### Describe the issue / bug.
After I cloned my electron-vue project from private repository, installed all node modules (via npm install) and ran dev server i took 2 warnings which doesn't allows me to test my app (even build). All those warnings are on screenshot below.

##### If visual, provide a screenshot.
http://oi68.tinypic.com/2qi02fp.jpg

##### Tell me about your development environment.
  * Node version: 7.3.0
  * NPM version: 4.1.1
  * vue-cli version: 2.7.0 
  * Operating System: Windows 10 (updated)

**Comment by SimulatedGREG** [comment]
@Pioruniasty 

I'm assuming since you are getting compiler warnings your electron app isn't opening anymore. Take a look at this recent change to get that back and running. 

https://github.com/SimulatedGREG/electron-vue/commit/fb47110e5b643755bd4fc51036b1a42b4817a89c

**Comment by SimulatedGREG** [comment]
Going to assume this did the trick. Feel free to comment back any other questions. Closing this for now.
