### ISSUE TITLE
BrowserWindow icon

### ISSUE THREAD

**Issue by carbontwelve** [SimulatedGREG/electron-vue#136]
Electron didn't seem to be using the icon defined within `app/icons/icon.ico` for the application icon; adding the icon path to the `BrowserWindow` options fixed this for me; e.g:

```
index.js 14:1
mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    icon: `${__dirname}/../../icons/icon.ico`
})
```

**Comment by SimulatedGREG** [comment]
@carbontwelve 

Are you using linux?

**Comment by carbontwelve** [comment]
@SimulatedGREG sorry, should have listed my development environment:

* Windows 7
* Node v5.10.1
* NPM v3.8.3

I created the `icon.ico` from a 256x256 png and then used [this online tool](http://icoconvert.com/image_to_icon_converter/) to create the `icon.icns` file.

I am going to try and reproduce the problem on another project and provide additional details - it could be I am just doing it wrong.

**Comment by carbontwelve** [comment]
Ok, looks like when I try to reproduce on another project I do not get the same error. I must have had a issue with the tools I was using to generate the icon (originally it only contained the size 64x64 until a colleague pointed me to the aforementioned online tools,) or got confused with which icon file I was using with my build (likely forgot to copy the new icon file or some such human error.)

I am going to conclude that this was a problem with my build and as I am unable to reproduce on another project using a clean version of elecron-vue I am closing this issue.

**Comment by SimulatedGREG** [comment]
Yeah, creating the icon files can be finicky sometimes. It's always good to follow the OS's guidelines to know what sizes are needed.

**Comment by carbontwelve** [comment]
It might be a good idea to have a second in the electron-vue documentation about icons and the most common pit falls - maybe with some suggested tooling that is known to work? I'd offer to help but my knowledge of such things is pitifully incomplete.
