### ISSUE TITLE
How to install ESLint on an existing project?

### ISSUE THREAD

**Issue by cawa-93** [SimulatedGREG/electron-vue#137]
I used your assembly and created the project without ESLint. After a few weeks of development I have realized how much I was wrong. What steps I take to install ESLint and configure environment way as if it was set from the very beginning?

**Comment by utkukaratas** [comment]
Just create a new temporary project with eslint on and diff with your current project. It should be a few additional blocks of configuration here and there.

**Comment by SimulatedGREG** [comment]
Sorry for late reply. But yes, @utkukaratas comment would probably be the easiest route to accomplish this.
