### ISSUE TITLE
Vue-resource CORS error

### ISSUE THREAD

**Issue by Edodums** [SimulatedGREG/electron-vue#140]
I'm trying to use vue-resource for the web request ( GET ) . 
I have as a application server GlassFish ( because the prevoius version of the app I'm recreating was based on JAVA EE ) , anyway when I try to make this request it returns on the console this :

> XMLHttpRequest cannot load http://localhost:8080/Alimos/api/user/all. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9080' is therefore not allowed access

`export default {
  data () {
    return {
      dati: ['']
    }
  },
  methods: {
    getAllProjects: function () {
      // GET /someUrl
      this.$http.get('http://localhost:8080/Alimos/api/user/all').then(response => {
        // get body data
        this.dati = response.body
      }, response => {
        // error callback
      })
    }
  }
}
`
  * Node version: latest
  * NPM version: latest
  * vue-cli version: (if necessary)
  * Operating System: win x64

**Comment by SimulatedGREG** [comment]
@Edodums 

This is not a direct issue with `electron-vue` or `vue-resource`, so I will be closing this. But to help you out, please take a look at what `Access-Control-Allow-Origin` actually does and how to adjust this setting with your backend server. In short, this HTTP Header defines what hosts are allowed to consume your API. In this case, the host `localhost:8080` is not *whitelisted* to use it.

**Comment by Edodums** [comment]
Thank you , sincererely , anyway I used axios ( and I fixed the application server problem )
You're great!
