### ISSUE TITLE
Feature request: supply travis ci and appveyor support

### ISSUE THREAD

**Issue by gengjiawen** [SimulatedGREG/electron-vue#141]
With this feature, not only we can have ci support, but also we have auto deploy binary release.
see this project [https://github.com/develar/onshape-desktop-shell](https://github.com/develar/onshape-desktop-shell) and related docs [https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts](https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts).

**Comment by gengjiawen** [comment]
There are also an article http://hoverbaum.gitlab.io/2016/08/03/Building-Electron-based-applications-using-CIs .

**Comment by gengjiawen** [comment]
This is one of my project [android-studio-helper](https://github.com/gengjiawen/android-studio-helper) using this template and CI integration.

**Comment by SimulatedGREG** [comment]
@gengjiawen 

Sorry for the late reply; work has been super busy lately.

I've have considered this in the past but felt implementing something like this might be more of the developer's job. It is worth considering for `electron-builder` users though.

**Comment by gengjiawen** [comment]
I think for electron-builder user, this will be useful for opensource project. It's very handy.
```

```

**Comment by SimulatedGREG** [comment]
Build configs have been added! Will be released in next milestone, #171 for more info. Closing.
