### ISSUE TITLE
Plugins can't be accessed in components

### ISSUE THREAD

**Issue by Shotman** [SimulatedGREG/electron-vue#145]
##### Describe the issue / bug.
\# Can't access vue plugins inside components.
I wanted to install several vue plugins on a fresh install, like : vue-ls, vue-events etc
I installed them with ```npm install --save vue-ls``` (in both the root and app folder)
Then put : ```import VueLocalStorage from 'vue-ls'``` as well as ```Vue.use(VueLocalStorage)``` in my app/main.js file
The plugin can be accessed in the app/main.js file but as soon as I go in a component, App.vue or even LandingPageView.vue calling ```this.$ls``` as the doc states I get a undefined.

The problem is the same with the "stock" plugins like ```vue-electron```, calling ```this.$electron``` in a component doesn't work even on the fresh install, still is undefined in the components

##### How can I reproduce this problem?
\# I did nothing more than what's described so should be easy to reproduce

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: v7.4.0
  * NPM version: v4.3.0
  * Electron version : v1.6.1 
  * vue-cli version: (if necessary) v2.8.1
  * Operating System: Antergos

**Comment by SimulatedGREG** [comment]
@Shotman 

I cannot seem to reproduce this issue. The only item that seems could be an issue is your OS. I also tried using `vue-ls` as well, without problem. Are you able to use the regular `webpack` template without issue?

**Comment by SimulatedGREG** [comment]
Going to close this for now. Feel free to comment back.
