### ISSUE TITLE
Build: babel/webpack issue

### ISSUE THREAD

**Issue by cooltrooper** [SimulatedGREG/electron-vue#146]
`Module not found: Error: Can't resolve 'babel-runtime/helpers/typeof'`

When using es6 types in the main process when trying to compile the app the above error is generated. This doesn't occur when running in development.

Issue is present on fresh copy when running build, error on command pack:main

Following code in index.js

`var object = "hello";
console.log(typeof object);`

  * Node version: 7.7.2
  * NPM version: 4.1.2
  * Operating System: OSX

**Comment by cooltrooper** [comment]
Installing babel-runtime to the app folder as well as the project folder solves the issue. However babel is a development requirement rather than a app dependency so shouldn't really be installed there if I understand the documentation correctly.

**Comment by cooltrooper** [comment]
addning

`path.join(__dirname, 'node_modules')`

to the main process web pack config also solves this problem

**Comment by SimulatedGREG** [comment]
There was a time when `babel-runtime` was needed, but looking at the official webpack template some things have changed. I feel it would be better to follow their approach to ensure electron-vue follow the community "standards".

**Comment by cooltrooper** [comment]
Looking at the vuejs template it appears they still use babel-plugin-transform-runtime, though babel-runtime isn't explicitly required it is a dependency of babel-plugin-transform-runtime

**Comment by SimulatedGREG** [comment]
Go ahead and install `babel-runtime` in `app` directory for now. Will be fixed in next Milestone. Sorry for the last reply everyone.
