### ISSUE TITLE
vuex:module command not working.

### ISSUE THREAD

**Issue by mrgodhani** [SimulatedGREG/electron-vue#147]
### Found an issue or bug? Tell me all about!

Not able to run npm run vuex:module <name_of_module>

##### Describe the issue / bug.
\#

When trying to create new vuex module command executed gives an error as show below.

##### How can I reproduce this problem?
\#

Just install fresh project and try to run npm / yarn run vuex:module <modulename>

##### If visual, provide a screenshot.
\#
```
yarn run v0.17.10
$ node tasks/vuex/module.js Feeds
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/mgodhani/Desktop/Projects/rss-reader/app/src/vuex/modules/Feeds.js'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.writeFileSync (fs.js:1222:33)
    at Object.<anonymous> (/Users/mgodhani/Desktop/Projects/rss-reader/tasks/vuex/module.js:12:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

##### Tell me about your development environment.
  * Node version: v7.2.0
  * NPM version: 4.4.1
  * vue-cli version: (if necessary)
  * Operating System: MacOS

**Comment by SimulatedGREG** [comment]
@mrgodhani 

Sorry for the inconvenience, but these commands have been removed for quite [some time now](https://github.com/SimulatedGREG/electron-vue/commit/f25177bd7f8e958f406aade4d1024624ee6a83e2) and are no longer supported. Doing a "fresh install" no longer includes these scripts.
