### ISSUE TITLE
debugging main process command

### ISSUE THREAD

**Issue by alexey2baranov** [SimulatedGREG/electron-vue#149]
Hello! I am very new with electron-vue. I have `npm run dev` very simular with vue-cli boilerplate. But I can't find any command to start main process debugging in package.json

So my question is it a lack or I miss something?

**Comment by SimulatedGREG** [comment]
There currently isn't any preset way to debug the main process in electron-vue. This is worth considering, but will be put on the back burner for the moment.

**Comment by alexey2baranov** [comment]
Maybe repacking `npm pack:main` and debugging app from dist folder as in electron "debugging main process" manual help us first time?

**Comment by SimulatedGREG** [comment]
`electron@^1.7.2` will be adding support for Node's Inspector Agent, making this process super simple with Chrome. There will be documentation about this usage; closing.

https://github.com/electron/electron/issues/6634

**Comment by wbern** [comment]
https://stackoverflow.com/questions/48091899/electron-main-and-renderer-process-debug-configuration/50787937#50787937
