### ISSUE TITLE
should add axios as an option

### ISSUE THREAD

**Issue by chovy** [SimulatedGREG/electron-vue#152]
vue-resource isn't officially a recommendation anymore by vue project. They recommend axios.

**Comment by SimulatedGREG** [comment]
Yeah, you bring a fair point. The only reason I've been somewhat avoiding this transition is partly because `axios` doesn't support JSONP. I'll be adding this on my to-do list, but have been pretty busy with work so expect maybe this weekend.

**Comment by SimulatedGREG** [comment]
Merged into `dev` branch. Check #171 for details.
