### ISSUE TITLE
Failed to `npm install`

### ISSUE THREAD

**Issue by Phantr4x** [SimulatedGREG/electron-vue#153]
##### Describe

Failed to `npm install`

```bash
electron@1.6.2 postinstall: `node install.js`
Exit status 1
```

Failed at the electron@1.6.2 postinstall script 'node install.js'.

##### Reproduce

```bash
vue init SimulatedGREG/electron-vue my-project
```
select `vue-electron` module only,

and then cancel all the options for test,

finally run `npm install`.

##### Screenshot
![image](https://cloud.githubusercontent.com/assets/5728981/23865713/7bf22e8a-0851-11e7-8b47-44f142412578.png)

##### Environment
  * Node version: `v7.6.0`
  * NPM version: `v4.1.2`
  * vue-cli version: `v2.8.1`
  * Operating System: `macOS Sierra`

**Comment by SimulatedGREG** [comment]
@Phantr4x 

Are you able to setup [electron-quick-start](https://github.com/electron/electron-quick-start) without issue? The error you ran into is specific to `electron` and not related to how `electron-vue` is configured or setup.

**Comment by Phantr4x** [comment]
Sorry for bothering you. 😭 

I found that the network led to the error, because of the GFW in China. That's too bad.

And I ran `cnpm install`. It works!

**Comment by Phantr4x** [comment]
Thx for your answer

**Comment by EternCoder** [comment]
@Phantr4x  I had the same issue.
Thanks to you, I fix it now!

**Comment by qky1412** [comment]
I always got stuck at the 'postinstall', and it always ends with connection timeout, whatever the VPN i use, is it really only  related to GFW? @Phantr4x @EternCoder

**Comment by EternCoder** [comment]
@qky1412 I am not sure. As on my issue in which I always get time out. I am using shadowsocks with chrome on windows, and after setting http_proxy to https://127.0.0.1:8080, it worked.

**Comment by EternCoder** [comment]
@qky1412 I am not sure. As on my issue in which I always get time out. I am using shadowsocks with chrome on windows, and after setting http_proxy to https://127.0.0.1:8080 on cmd, it worked.

**Comment by Phantr4x** [comment]
@qky1412 

You can try [SpechtLite](https://github.com/zhuhaow/SpechtLite) & its shell export command.

And using `proxychains4` is another solution.

**Comment by qky1412** [comment]
thx, it IS my network problem @Phantr4x @EternCoder
