### ISSUE TITLE
Translate Docs

### ISSUE THREAD

**Issue by Jonham** [SimulatedGREG/electron-vue#155]
I love Electron and I love Vue.js. I share this boilerplate to my Chinese friends,     
but they prefer a Chinese version documents.     
    
So I decide to translate this boilerplate. May I ?

**Comment by Jonham** [comment]
If I can, I just create a new folder on the root, or create a sub-folder to `docs/` ?

**Comment by SimulatedGREG** [comment]
@Jonham I would love if you could make this possible. I'm not entirely sure how to setup GitBook to support multiple languages, but I do know it is possible. If you wanting to move forward with this, go ahead a make a PR with the sub-folder in `docs/` like you mentioned.

**Comment by Jonham** [comment]
👌 OK！ I will check out.

**Comment by shuaibird** [comment]
Have you already set it up? Here is the [gitbook doc for multi-lingual](https://toolchain.gitbook.com/languages.html)
BTW, I could help to translate.

**Comment by re-fort** [comment]
I sent a pull request instead of @Jonham

**Comment by SimulatedGREG** [comment]
@re-fort @Jonham @shuaibird 

Thank you guys so much for your interest in wanting to help translate the documentation. Sorry for the late reply, but I just merged @re-fort's PR and multi-lingual support is now here! Feel free to fork the project and get started. Everything related to this will be inside `docs/`.

**Comment by SimulatedGREG** [comment]
Alright everyone. The latest Milestone release has made it to the `master` branch. If any of you are still interested in helping translate the documentation please feel free to get started by forking this repo and working in the `docs/` directory.

**Comment by re-fort** [comment]
Thank you for your hard work😊 
I'll work on it!

**Comment by fluency03** [comment]
@SimulatedGREG I would really help with translating the doc to Chinese!!!

**Comment by SimulatedGREG** [comment]
@fluency03 

That's great to hear! You can always get started by forking this repo and working in the `docs/` directory. You will essentially duplicate the `en` folder and make a `cn` directory for the Chinese translation.

**Comment by SimulatedGREG** [comment]
Shout outs to @re-fort for getting electron-vue a Japanese translation! 🎉 

https://simulatedgreg.gitbooks.io/electron-vue/content/ja/

**Comment by fluency03** [comment]
@SimulatedGREG I am working on the Chinese translation.

**Comment by fluency03** [comment]
I just started working on it recently, and I am busy at my work this month.   So please do not expect this to be delivered very soon :).....  

I am actually also wondering is there other people working on the Chinese.    I would like to make sure that we are not doing duplicate works.    Otherwise, I will just continue my translation based on my pace.

**Comment by SimulatedGREG** [comment]
Absolutely no rush. You are never obligated to do this translation, but the community is very grateful if you do so! Thank you so much.

**Comment by fluency03** [comment]
Should I submit pull request based on what I have translated, or, you prefer I submit them after all completed?

**Comment by SimulatedGREG** [comment]
I would say work in your own fork, and post it here. That way any other contributors that are willing to help can create PRs at your fork.

**Comment by fluency03** [comment]
Thanks @SimulatedGREG . 

Please find my fork at: https://github.com/fluency03/electron-vue. I am working on the Chinese translation at directory: `docs/cn`. :) :) :)

**Comment by GiovanniSM20** [comment]
@SimulatedGREG 

Please find my fork at: https://github.com/GiovanniSM20/electron-vue. I'm working on the Portuguese translation at directory: docs/pt-br. :octocat:

**Comment by fluency03** [comment]
I have submitted pull request.  Please have a look. @SimulatedGREG

**Comment by SimulatedGREG** [comment]
Thanks to the efforts from @fluency03 & @LuckyLin electron-vue documentation now has a Chinese translation! :tada:

**Comment by Amimaro** [comment]
Are you still working on the Portuguese translation? @GiovanniSM20

**Comment by XanderLuciano** [comment]
Closing due to lack of response.
