### ISSUE TITLE
Error on using element-ui with vue-js-devtools

### ISSUE THREAD

**Issue by Phantr4x** [SimulatedGREG/electron-vue#158]
##### Describe

When I use `element-ui` with `vue-js-devtools` in console, it will throw an error like this once I click the component in the component tree view:

![image](https://cloud.githubusercontent.com/assets/5728981/24144866/d3934430-0e69-11e7-9f41-c0e921a36f7c.png)

Consequently I could not check the information of my element-ui-component. What's wrong with it?

##### Environment
  * Node version: v7.6.0
  * NPM version: v4.4.1
  * vue-cli version: v2.8.1
  * Operating System: macOS Sierra

**Comment by Phantr4x** [comment]
Yeah I found that it was caused by `vue-devtools`.

That's a bug of `vue-devtools`, some one found it on version `3.1.0`, and the latest version is `3.1.2` now.

**Comment by SimulatedGREG** [comment]
I had a feeling that might have been the issue at hand. I've only ever seen something like one other time and is probably related to the recent changes of the `vue-template-compiler`. To update the `vue-devtools` in electron your have to open up your `userData` directory mentioned in [`electron-devtools-installer`](https://github.com/MarshallOfSound/electron-devtools-installer#how-does-it-work), remove the `vue-devtools` folder and re-run your app in development.

**Comment by Phantr4x** [comment]
You're right, I found your answer on an issue in [vuejs/vue-devtools/issues/68](https://github.com/vuejs/vue-devtools/issues/68).

Thanks a lot : D

I've solved it by:

```js
BrowserWindow.removeDevToolsExtension('Vue.js devtools');
BrowserWindow.addDevToolsExtension('/path/to/vue-devtools/shells/chrome');
```

**Comment by SimulatedGREG** [comment]
That is a much easier solution. Forgot that method existed, haha. Glad you got this sorted out.
