### ISSUE TITLE
How to Load Certain Route on App Activate Event?

### ISSUE THREAD

**Issue by iamazik** [SimulatedGREG/electron-vue#159]
I'm having a really hard time to figure out how to load a particular route when the `activate` event is fired. I've these following routes:
```javascript
export default [
  {
    path: '/',
    name: 'login-page',
    component: require('components/LoginPageView')
  },
  {
    path: '/tracker',
    name: 'tracker-page',
    component: require('components/TrackerPageView')
  },
  {
    path: '*',
    redirect: '/'
  }
]
```

Now, I'd like to load the `/tracker` route once the `app.on('activate')` is fired on the following:
```javascript
app.on('activate', () => {
  if (mainWindow === null) {
    createWindow()
  }
})
```

**Comment by abishekrsrikaanth** [comment]
@iamazik Not sure what exactly you are trying to achieve, but why not try checking `vue-router`'s Navigation Guards https://router.vuejs.org/en/advanced/navigation-guards.html

**Comment by SimulatedGREG** [comment]
@iamazik 

It would have to do with setting the browserWindow's loaded URL. When using the `file` protocol in production you can take advantage of `vue-router`'s hash method to point to another route. This would of course require some more logic on your end, but below you can find that adding `#<route-path>` can be used to open a specific route.

```js
`file://${__dirname}/index.html#other-route`
```

**Comment by iamazik** [comment]
Thanks @abishekrsrikaanth and @SimulatedGREG , I was finally able to achieve this by using the [Per-Route Guard](https://router.vuejs.org/en/advanced/navigation-guards.html#per-route-guard) `beforeEnter` method. Here's my draft:

```javascript
let auth = true

export default [
  {
    path: '/',
    name: 'login-page',
    component: require('components/LoginPageView'),
    meta: {
      auth: false
    },
    beforeEnter: (to, from, next) => {
      if (auth) {
        next('/tracker')
      } else {
        next()
      }
    }
  },
  {
    path: '/tracker',
    name: 'tracker-page',
    component: require('components/TrackerPageView'),
    meta: {
      auth: true
    }
  },
  {
    path: '*',
    redirect: '/'
  }
]
```
Any feedbacks are most welcome to improve this even better :)

**Comment by SimulatedGREG** [comment]
For the most part what you posted is a decent solution. Glad you got it sorted out.
