### ISSUE TITLE
Create a Splash Screen

### ISSUE THREAD

**Issue by abishekrsrikaanth** [SimulatedGREG/electron-vue#160]
I am working on an app using the `vue-electron` package and am not quite sure how to implement a splash screen, would you be able to advice/suggest a good way to do it?

**Comment by jackel27** [comment]
Why not do a component and a route redirection timeout?

**Comment by abishekrsrikaanth** [comment]
@jackel27, could you clarify a bit more on what you mean by redirection timeout?

**Comment by SimulatedGREG** [comment]
If you are looking for a traditional splash screen in a separate window, you could spin up a browser window, load a route specifically meant for the splash screen and use a timeout. Once that timeout is done, close your splash screen and load up the main browser window of your full app. There's plenty of ways to go about this but looking through electron's docs will surely help you get a better idea. I'll be closing this as it isn't a direct issue with electron-vue.
