### ISSUE TITLE
Error in install and can build my Os distributions only and can't build another distributions 

### ISSUE THREAD

**Issue by EmadAdly** [SimulatedGREG/electron-vue#161]
##### First Error when Package installation 

1)
```bash
npm WARN prefer global node-gyp@3.6.0 should be installed with -g
```
2) 
```bash
npm WARN my-project@0.0.0 No repository field.
npm WARN my-project@0.0.0 No license field.
```
3) 
``` bash
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN my-project@0.0.0 No repository field.
```

##### Second Error when Build Package 
```bash
Building AppImage for arch x64
Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /media/emad/DevExe/electron/my-project/node_modules/electron-builder-util/src/util.ts:75:16
    at exithandler (child_process.js:218:5)
    at ChildProcess.errorhandler (child_process.js:230:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at exec (/media/emad/DevExe/electron/my-project/node_modules/electron-builder-util/src/util.ts:53:3)
    at /media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:136:28
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:186:11)
    at /media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:28:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:58:11)
    at new LinuxTargetHelper (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:16:23)
    at getHelper (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/linuxPackager.ts:32:18)
    at outDir (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/linuxPackager.ts:61:122)
    at mapper (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/targets/targetFactory.ts:15:16)
    at LinuxPackager.createTargets (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/linuxPackager.ts:61:7)
    at createTargets (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/targets/targetFactory.ts:22:12)
    at /media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/packager.ts:175:41
From previous event:
    at Packager.doBuild (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/out/packager.js:299:11)
    at /media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Packager.build (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/out/packager.js:251:11)
    at /media/emad/DevExe/electron/my-project/node_modules/electron-builder/src/builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/media/emad/DevExe/electron/my-project/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.2
npm ERR! code ELIFECYCLE
npm ERR! my-project@0.0.0 build: `npm run pack && build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the my-project@0.0.0 build script 'npm run pack && build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run pack && build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/emad/DevExe/electron/my-project/npm-debug.log

```
and stop building, when open dist folder i found only linux-unpacked 

##### Tell me about your development environment.
  * Node version: 7.2.0
  * NPM version: 4.0.2
  * vue-cli version: (if necessary)
  * Operating System: Ubuntu 16.10 for 46-bit
In package (You are using electron v1.6.2 with node v7.4.0 on the linux platform.)

Thanks in advance

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#linux

```
sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
```

**Comment by EmadAdly** [comment]
Thanks so much my dear

Still Installation errors

```bash
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^2.0.2 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.0.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN my@0.0.0 No repository field.
```
#### windows build
When build by `npm run build --win` not have build dist for win but build dist for Linux, that is done without any errors.

how can build to windows ? and what about installation errors ?

**Comment by SimulatedGREG** [comment]
@EmadAdly 

If you are using `electron-builder` and developing on a linux machine, you cannot build for Windows. `electron-builder` was made to only build for the OS it is running on and is recommended to use services like [circleci](https://circleci.com/) and [AppVeyor](https://circleci.com/) to build for other OSs.

The errors you have posted are not errors and are warnings that detail binaries meant for `mac` and `win` are being skipped as they won't function on linux.

**Comment by EmadAdly** [comment]
Thanks @SimulatedGREG 

Solved problem and now i can build to `windows` and  `mac`  from ` linux` by using `electron-builder` through install prebuild as globally
```bash
$ npm install -g prebuild
```
and also add `build-all` to package.json

```js
"scripts": {
    ...
    "build-all": "npm run pack &&build -mwl",
    ...
}
```

**Comment by SimulatedGREG** [comment]
Never seen `prebuild` before; looks pretty interesting. Glad you got this sorted out.

**Comment by ndabAP** [comment]
Followed your instructions, @EmadAdly, got this:

> Error: spawn hdiutil ENOENT
>     at exports._errnoException (util.js:1050:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:367:16)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> From previous event:
>     at spawn (/home/jclaus/Entwicklung/itl/node_modules/electron-builder-util/src/util.ts:118:3)
>     at /home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/targets/dmg.ts:49:11
>     at Generator.next (<anonymous>)
>     at /home/jclaus/Entwicklung/itl/node_modules/graceful-fs/graceful-fs.js:99:16
>     at /home/jclaus/Entwicklung/itl/node_modules/graceful-fs/graceful-fs.js:43:10
>     at FSReqWrap.oncomplete (fs.js:114:15)
> From previous event:
>     at DmgTarget.build (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/targets/dmg.js:233:11)
>     at taskManager.addTask.default.map.it (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/platformPackager.ts:106:85)
> From previous event:
>     at MacPackager.packageInDistributableFormat (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/platformPackager.ts:106:41)
>     at /home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/macPackager.ts:94:26
> From previous event:
>     at /home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/macPackager.ts:94:10
>     at Generator.next (<anonymous>)
> From previous event:
>     at MacPackager.pack (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/macPackager.js:190:11)
>     at /home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/packager.ts:253:24
> From previous event:
>     at Packager.doBuild (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/packager.js:340:11)
>     at /home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/packager.ts:184:52
>     at Generator.next (<anonymous>)
> From previous event:
>     at Packager.build (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/packager.js:259:11)
>     at /home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/builder.ts:266:40
>     at Generator.next (<anonymous>)
>     at build (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/builder.js:69:21)
>     at loadEnv.then (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/src/cli/cli.ts:49:4)
> From previous event:
>     at build (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/builder.js:69:21)
>     at loadEnv.then (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/cli/cli.js:155:79)
>     at runCallback (timers.js:672:20)
>     at tryOnImmediate (timers.js:645:5)
>     at processImmediate [as _immediateCallback] (timers.js:617:5)
> From previous event:
>     at Object.args [as handler] (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/cli/cli.js:155:68)
>     at Object.self.runCommand (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/node_modules/yargs/lib/command.js:233:22)
>     at Object.Yargs.self._parseArgs (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/node_modules/yargs/yargs.js:1018:24)
>     at Object.get [as argv] (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/node_modules/yargs/yargs.js:927:19)
>     at Object.<anonymous> (/home/jclaus/Entwicklung/itl/node_modules/electron-builder/out/cli/cli.js:151:465)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:427:7)
>     at startup (bootstrap_node.js:151:9)
>     at bootstrap_node.js:542:3
