### ISSUE TITLE
Environment Configuration

### ISSUE THREAD

**Issue by PunchRockgroin** [SimulatedGREG/electron-vue#162]
Not an issue, but a question: 

What would be the best way to store and use environment configuration variables? 

For example, I'd rather not store production DB, oAuth and other sensitive data in an easy to find way, and have the information be available after packaging. I know there are several tools out there I'm just curious as to anyone else's practices for this.

**Comment by anthonyettinger** [comment]
I put keys and passwords in `.bashrc` and then reference them in my app with `const secret = process.env.MYAPP_SECRET` for example.

**Comment by SimulatedGREG** [comment]
One general technique used is to import a JSON file into your app with your credentials and then make sure to add that JSON file to your repo's `.gitignore` to ensure that those credentials never get uploaded to GitHub (or whatever you are using). Going to close this as this is not realated to electron-vue.

**Comment by bbeng89** [comment]
Sorry to comment on such an old issue, but I actually had this same question, and was thinking I could work with [vue's modes and .env files ](https://cli.vuejs.org/guide/mode-and-env.html#modes) but couldn't seem to get it to work. Is the JSON file approach still the recommended way to do this, or is there now a way to make `.env.[mode]` files work?
