### ISSUE TITLE
Less loader issues

### ISSUE THREAD

**Issue by rdpascua** [SimulatedGREG/electron-vue#163]
I don' know if this is an issue or what, I've installed a fresh installation of electron-vue and I've added `less-loader` and `less` to the main `package.json`

```
renderer
   template/
     main.less
```

inside renderer main.js

```
import './template/less/main.less'
```

I've got this issue, I've been using electron-vue since 1.0 but this is the first time I've encountered this issue. I can't seem to fix this.

```
  Module parse failed: /foo/app/src/renderer/template/less/main.less Unexpected character '@' (9:0)
         You may need an appropriate loader to handle this file type.
```

**Comment by eberkund** [comment]
Don't you also need to modify the webpack config to accommodate LESS?

**Comment by rdpascua** [comment]
Let me check if it works, the last time I used this works gracefully.

**Comment by SimulatedGREG** [comment]
@rdpascua 

Installing `less` and `less-loader` will only allow you to use `<style lang="less">` in your Vue component files. If you are wanting to also manually `import` Less files in your JS, then you must also add the loader to the `webpack` configuration. You can bypass this using `@import` in your `App.vue`'s `<style>` tag.

**Comment by rdpascua** [comment]
I can close this @SimulatedGREG thankyou for your support.
