### ISSUE TITLE
Vue packages version mismatch Vue2.2.5

### ISSUE THREAD

**Issue by lilien1010** [SimulatedGREG/electron-vue#164]
``` 
         Vue packages version mismatch:
         
         - vue@2.1.8
         - vue-template-compiler@2.2.5
```

but after I run npm install,it shows this

![image](https://cloud.githubusercontent.com/assets/3814966/24322530/22c9eaba-11a1-11e7-8f8f-52a6aa2e02a6.png)

and here is my package.json  about vue-template-compiler

![image](https://cloud.githubusercontent.com/assets/3814966/24322537/32d03d06-11a1-11e7-80ec-7e167379925b.png)

**Comment by bahit** [comment]
At the time of writing this,  I had the same error but updated version:

```
Vue packages version mismatch:
         
         - vue@2.2.2
         - vue-template-compiler@2.2.6
```

To fixed it I ran using yarn:
`yarn add vue@^2.2.6 vue-template-compiler@^2.2.6`

Basically just had to make sure vue and vue-template-compiler to have the same version.

**Comment by SimulatedGREG** [comment]
@lilien1010 

Yeah, the recent changes with `vue` and `vue-template-compiler` have caused many plugins to rebuild their templates. Updating those modules, including the template compiler, should solve the issues, just as @bahit mentioned.

**Comment by SimulatedGREG** [comment]
I'm going to close this for now, feel free to comment back any questions.

**Comment by rr326** [comment]
I'm running into the same problem: It says:
```
Vue packages version mismatch:

- vue@2.2.4
- vue-template-compiler@2.2.6
```
But Vue is actually at 2.2.6 (I reinstalled just to be safe).
I've reinstalled vue-template-compliler also. (it is 2.2.6)

I'm using NPM. (Do I need to switch to yarn?) 
Any suggestions?

**Comment by SimulatedGREG** [comment]
@rr326 

I would definitely give `yarn` a try here. To be safe, delete `node_modules` entirely and then install with `yarn`.

**Comment by bahit** [comment]
@rr326 

For NPM:
`npm install vue@^2.2.6 --save`

Anyway, I just tried starting a new project and this `Vue packages version mismatch:` problem didn't occur the last time I started a new project. Perhaps, it's fixed now?

**Comment by SimulatedGREG** [comment]
@bahit 

Most likely due to the `vue` and `vue-template-compiler` changes. There was most likely a package mismatch from a peer dependencies or something.

**Comment by rr326** [comment]
Thanks for the help. I've worked around it but if this becomes a bigger issue (more posts), I'll volunteer to dig in on it. Otherwise I'll let it sit and hope it resolves itself. (And @bahit - I had tried that and it actually IS vue@2.2.6 installed but somewhere it thinks it is 2.2.4)
