### ISSUE TITLE
Where should the static file to be placed?

### ISSUE THREAD

**Issue by erguotou520** [SimulatedGREG/electron-vue#17]
There's no `static` folder in the project. So where to put them (like images, fonts, etc.)? `/app/dist`?

**Comment by AkiraLaine** [comment]
Yes. That's where you should put them :smile:

**Comment by erguotou520** [comment]
That folder is ignored due to `app/dist/` in `.gitignore`. I try to change the file to
```
.DS_Store
Thumbs.db
node_modules/
app/dist/
dist/
!app/dist/static/
releases/
npm-debug.log*
selenium-debug.log
test/unit/coverage
test/e2e/reports
```
but `/app/dist/static` folder is still ignored. Please help.

**Comment by AkiraLaine** [comment]
You need to remove all tracked files and then re-add them. 

```bash
git rm -r —cached .
```

Then just `git add -A` and commit as you normally would.

**Comment by erguotou520** [comment]
Are sure? [My repo is here](https://github.com/erguotou520/FirebaseStatic)
After
```shell
git rm -r —cached .
git add -A
```
my src goes empty while `/app/dist/static` is still ignored.

**Comment by SimulatedGREG** [comment]
Looking at your repo I can tell that you originally started with a different boilerplate. And from looking at the commits you also tried to manually switch to using electron-vue. Although possible, I am unable to fully know what changes you made. I would recommend starting fresh with electron-vue and moving over necessary Vue components files to ensure things like `.gitignore` and project structure are best optimized for electron-vue. I previously closed this issue as there's no internal problem with electron-vue itself, but more of problems related to migrating to electron-vue.

**Comment by erguotou520** [comment]
Yes, it based on [electron-boilerplate-vue](https://github.com/bradstewart/electron-boilerplate-vue) firstly. But I really start fresh with `electron-vue`, just copy files from previous project. I'll try it again.
