### ISSUE TITLE
Feature request: hot-reload for main process

### ISSUE THREAD

**Issue by gengjiawen** [SimulatedGREG/electron-vue#172]
Anything we can do to achieve this?

**Comment by SimulatedGREG** [comment]
Not really, unfortunately since the main `electron` process has to run off actual files on disk. The only reason this is possible in the browser is because they can use `http` and Web Sockets to communicate new data. There was some webpack support in the past to get this working for purely node applications, but I don't believe anything ever became stable and the idea has been dropped.

**Comment by gengjiawen** [comment]
What if we watch main process file folder, if we observe something change, we restart the process. We can use some watch library like [nodemon](https://github.com/remy/nodemon)

**Comment by SimulatedGREG** [comment]
Somewhat possible but the only concern there is that electron will have to close all browser windows and recreated them on every file change. Might be counterintuitive

**Comment by gengjiawen** [comment]
Maybe we can add one more script to support both render and main process hot reload. Without this feature, edit main process related file is really painful.

**Comment by gengjiawen** [comment]
I implement this feature with nodemon, it's very easy to implement. Just put another script in `package.json`
```
 "both-dev": "nodemon --delay 5 -w app/src/main tasks/runner.js",
```

**Comment by chris-schmitz** [comment]
@gengjiawen something you may want to consider would be the electron-reload package: https://github.com/yan-foto/electron-reload.

I've used this on a couple of projects and it works nicely.

It would be worth doing a PR to offer integrating electron-reload directly with this project. I'm considering creating that PR, but I just found this repo so I want to explore it a bit before I start getting opinionated on what it needs or doesn't need. 

Regardless, electron-reload will give you that nodemon-esq auto reload of the renderer and main process.

**Comment by gengjiawen** [comment]
With this project, I don't think you will need extra tool to achieve reload.

**Comment by SimulatedGREG** [comment]
@chris-schmitz 

Thanks the suggestion. I'll definitely be looking into this.

**Comment by chris-schmitz** [comment]
Awesome :) Glad I could help (even if it doesn't get incorporated).
