### ISSUE TITLE
peerjs(webrtc) / vuejs

### ISSUE THREAD

**Issue by Mistes974** [SimulatedGREG/electron-vue#173]
### Found an issue or bug? Tell me all about!
Hello,
I currently have a problem when I try to add a library (peerjs) it's not a bug, it's for sure a lack of experience of my part.
I wanna declare globaly my peerjs , and call it from anywhere , and i really don't know how to do it :/

##### How can I reproduce this problem?
npm install peerjs --save
in main.js i added : import Peer from 'peerjs' and below Vue.use(Peer)
in my custom component i tryed with this.$Peer('id', {key:'valueofmykey'}) and many other combinations but have that error : Uncaught ReferenceError: Peer is not defined

Someone can help ?
Thx

**Comment by re-fort** [comment]
`peerjs` is not Vue plugin.
To load a library automatically, you could add `ProvidePlugin` in your `webpack.config`
See https://webpack.js.org/plugins/provide-plugin/

**Comment by SimulatedGREG** [comment]
@Mistes974 

Just as @re-fort stated, `peerjs` alone is not a Vue plugin and cannot be `install`ed directly. To use `peerjs` in your JS files, simply import it and use it directly. For example...

**main.js**
```js
// import
import Peer from 'peerjs'

// and use directly
const peer = new Peer('pick-an-id', { key: 'myapikey' });

/* You can then attach this instance to Vue by... */
Vue.prototype.$peer = peer
```
By doing the above, you can now access it in all component files through `this.$peer`.

Going to close this as it isn't a direct issue with electron-vue. Feel free to comment back any questions.
