### ISSUE TITLE
failed to compile when using async/await or es6 Promise

### ISSUE THREAD

**Issue by Rocket1184** [SimulatedGREG/electron-vue#175]
### Describe the issue / bug.
failed to compile when using async/await or es6 Promise, but it runs well in **dev** mode

### How can I reproduce this problem?
init a new project with config below
```sh
$ vue init simulatedgreg/electron-vue pure

? Application Name pure
? Project description An electron-vue project
? Select which Vue plugins to install vue-electron, vue-router, vuex
? Use linting with ESLint? No
? Setup unit testing with Karma + Mocha? No
? Setup end-to-end testing with Spectron + Mocha? No
? What build tool would you like to use? packager
? author rocka <i@rocka.me>

```

and just **add** this to the **bottm** of `app/src/main/index.js`

```js
/**
 *  original file app/src/main/index.js above
 */

function getSthPromise() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(Math.random());
    }, 1000);
  })
}

async function getSthAsync() {
  let num = await getSthPromise();
  console.log(num);
}
```

and pack or build the project
```sh
$ npm run pack:main
```

then error:
```sh
> pure@0.0.0 pack:main /tmp/pure
> cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.main.config.js

Hash: fa6a071040ab40c0c82f
Version: webpack 2.3.3
Time: 556ms
   [1] ./app/src/main/index.js 2.03 kB {0} [built]
    + 1 hidden modules

ERROR in ./app/src/main/index.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in '/tmp/pure/app/src/main'
 @ ./app/src/main/index.js 3:19-55

ERROR in ./app/src/main/index.js
Module not found: Error: Can't resolve 'babel-runtime/helpers/asyncToGenerator' in '/tmp/pure/app/src/main'
 @ ./app/src/main/index.js 7:25-74
ERROR in ./app/src/main/index.js
Module not found: Error: Can't resolve 'babel-runtime/core-js/promise' in '/tmp/pure/app/src/main'
 @ ./app/src/main/index.js 11:15-55
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pure@0.0.0 pack:main: `cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.main.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pure@0.0.0 pack:main script 'cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.ma
in.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pure package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack -p --progress --colors --config webpack.main.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pure
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pure
npm ERR! There is likely additional logging output above.
```

### If visual, provide a screenshot.
![screenshot_20170404_220233](https://cloud.githubusercontent.com/assets/13914967/24660596/85c3be86-1915-11e7-8fd2-4fae10f20ffb.png)

### Tell me about your development environment.
  * Node version: v7.7.3
  * NPM version: 4.4.4
  * vue-cli version: 2.8.1
  * Operating System: GNU/Linux 4.10.6-1-ARCH x86_64

i love async/await and hate callbacks.
what can i do....

or for suggestions to modify the webpack config file?

**Comment by SimulatedGREG** [comment]
Go ahead and install `babel-runtime` inside the app directory. There have been some recent changes within the babel community that may have caused this. This should fix the issues you are running into.

**Comment by Rocket1184** [comment]
i'd rather write my own webpack config files than using babel-runtime
why using polyfill when node/chrome already support those features?

Also, it takes a long time to complie Promise/async/await codes into ES5

**Comment by SimulatedGREG** [comment]
This fix is only meant to be temporary. I thought I mentioned this but it must have been on a different issue. The next milestone will be doing a rework of this area and will include using Babili in order to target es2015 available features in node 7. I would have done this sooner but it wasn't until ~recently that babili came out of beta.

**Comment by SimulatedGREG** [comment]
A better fix that uses built in features has now been implemented into the `dev` branch and will release with the next milestone. Check #171 for more info.

**Comment by Rocket1184** [comment]
thanks for your effort 😃
