### ISSUE TITLE
Can not find npm module in packaged application

### ISSUE THREAD

**Issue by altjz** [SimulatedGREG/electron-vue#176]
### Found an issue or bug? Tell me all about!
I want to use websocket in main Process. Everything is working fine under development environment, But can't nod find the websocket module in package application

##### Describe the issue / bug.
\#
`npm run dev` - working perfect
`npm run build:darwin` - not working

##### How can I reproduce this problem?
\#
install websocket module
```shell
cd app
npm i ws --save
```
require in app/src/main/index.js
```javascript
'use strict'
let Websocket = require('ws')
import { app, BrowserWindow } from 'electron'
```
config.js
```javascript
'use strict'

const path = require('path')

let config = {
  // Name of electron app
  // Will be used in production builds
  name: 'my-project',

  // Use ESLint (extends `standard`)
  // Further changes can be made in `.eslintrc.js`
  eslint: true,

  // webpack-dev-server port
  port: 9080,

  // electron-packager options
  // Docs: https://simulatedgreg.gitbooks.io/electron-vue/content/docs/building_your_app.html
  building: {
    arch: 'x64',
    asar: true,
    dir: path.join(__dirname, 'app'),
    icon: path.join(__dirname, 'app/icons/icon'),
    ignore: /\b(src|index\.ejs|icons)\b/,
    out: path.join(__dirname, 'builds'),
    overwrite: true,
    platform: process.env.PLATFORM_TARGET || 'all'
  }
}

config.building.name = config.name

module.exports = config
```
##### If visual, provide a screenshot.
\#
![bug](https://cloud.githubusercontent.com/assets/10369139/24789647/899aba26-1ba6-11e7-852d-b28f9efa59fa.png)
##### Tell me about your development environment.
  * Node version: `v7.4.0`
  * NPM version: `4.0.5`
  * vue-cli version: (if necessary) `vue version 2.8.1`
  * Operating System: `macOS Sierra 10.12.4`

**Comment by SimulatedGREG** [comment]
This looks like it may be an `npm` issue related to #154 (minus the part about using jQuery). Could you give [`yarn`](https://yarnpkg.org) a try?

**Comment by altjz** [comment]
hi @SimulatedGREG , I never use yarn before, but I tried electron-builder, it works like a charm.

**Comment by SimulatedGREG** [comment]
I totally forgot `ws` was a native node module. So yes, `electron-builder` would definitely be your solution. Glad you got this sorted out.

**Comment by altjz** [comment]
Hi @SimulatedGREG, [ws](https://www.npmjs.com/package/ws) is not native module. Here is the electron-builder output
```
No native production dependencies
Packaging for darwin x64 using electron 1.6.2 to dist/mac
```
And I tried other module with electron-packager, such as [sweetalert2](https://limonte.github.io/sweetalert2/), Same problem.
![bug2](https://cloud.githubusercontent.com/assets/10369139/24986782/d54f68c2-202e-11e7-9e40-9a20a7b5dbe8.png)

I think it relates with electron-packager asar option, if I set asar to false in config.js, Problem solved.
But anyway, electron-builder is a better option.

**Comment by zivoradmilekic** [comment]
Hi guys, I had same issue and I finally fix it. I made mistake. I installed node modules for main in package.json in root of my project instead of app/package.json. When I copied from one dependencies object to another it finally compile! Please try it. I hope this is of some help.
