### ISSUE TITLE
Created and mounted methods are triggered more than once.

### ISSUE THREAD

**Issue by inssitu** [SimulatedGREG/electron-vue#177]
Every time I enter to a route the methods created and mounted are triggered. Why is this happen?
In the official vue-cli for web doesn't happen this, only are triggered once.

  * Node version: 6.9.4
  * NPM version: 4.3.0
  * Operating System: Mac Sierra

**Comment by SimulatedGREG** [comment]
@inssitu 

Do you have a project of this I can take a look at?

**Comment by inssitu** [comment]
@SimulatedGREG I just created a new project [https://github.com/inssitu/demo](https://github.com/inssitu/demo)

<img width="424" alt="captura de pantalla 2017-04-09 a las 23 35 23" src="https://cloud.githubusercontent.com/assets/8522674/24841152/4c96d5d2-1d7d-11e7-977c-7286d9b29732.png">

**Comment by SimulatedGREG** [comment]
@inssitu 

Other than the fact you have a duplicate route entry that should be...
```js
{
  path: '*',
  redirect: '/view-one'
}
```
...I don't understand what that issue is. Both `mounted` & `created` hooks will run when the route is loaded, this is expected behavior of `vue-router`.

**Comment by SimulatedGREG** [comment]
I'm assuming this can be closed now...
