### ISSUE TITLE
Karma coverage always 100%

### ISSUE THREAD

**Issue by arthurvasconcelos** [SimulatedGREG/electron-vue#181]
##### Describe the issue / bug.
When I run unit tests, the Karma's coverage summary always return 100%. I ran this on my ongoing project, on a new master installation and  a new dev installation, the results are always the same... It's like Karma isn't reading my code at all...

##### How can I reproduce this problem?
npm run unit

##### If visual, provide a screenshot.
![screenshot from 2017-04-11 19-00-00](https://cloud.githubusercontent.com/assets/1286768/24932855/caee56f4-1ee9-11e7-96a3-ef1245f0b474.png)

##### Tell me about your development environment.
  * Node version: v6.10.0
  * NPM version: 3.10.10
  * vue-cli version: 2.8.1
  * Operating System: Ubuntu 16.04

**Comment by SimulatedGREG** [comment]
Thanks for the fix @Lawrr 

@arthurvasconcelos Take a look at #186 for the simple fix.

**Comment by arthurvasconcelos** [comment]
It worked like a charm! Thanks @Lawrr!

@SimulatedGREG already applied to my project and everything is working just fine now! Thanks! =D
