### ISSUE TITLE
Builded App is blank

### ISSUE THREAD

**Issue by Antoniobk** [SimulatedGREG/electron-vue#182]
##### Describe the issue / bug.
When I compile the apps using npm run build the app just display a blank page. This is the file structure I use: 
![structure1](https://cloud.githubusercontent.com/assets/4043311/25062701/abfac476-2196-11e7-9c46-d56c16730231.jpg)

in vue-router the mode is "hash(default)" and in webpack.render.config.js  add 'pages' on resolve
```
resolve: {
    alias: {
      'styles': path.resolve(__dirname, 'app/src/renderer/scss'),
      'components': path.join(__dirname, 'app/src/renderer/components'),
      'pages': path.join(__dirname, 'app/src/renderer/pages'),
      'renderer': path.join(__dirname, 'app/src/renderer')
    },
}
```
##### Tell me about your development environment.
  * Node version: v6.3.0
  * NPM version: v3.10.9
  * Operating System: Win 10

**Comment by SimulatedGREG** [comment]
@Antoniobk 

Do you get any errors when running `npm run pack`?

**Comment by Antoniobk** [comment]
This was the result, apparently with no errors,
![ewqewq](https://cloud.githubusercontent.com/assets/4043311/25074255/9d24a206-22bc-11e7-87da-2549b33f6ead.jpg)

**Comment by SimulatedGREG** [comment]
Do you have a project repo I could take a look at?

**Comment by Antoniobk** [comment]
Ready, add you as collaborator

**Comment by SimulatedGREG** [comment]
@Antoniobk 

Alright, found the problem. It has to do with the default `electron-packager`'s `ignore` setting. In this specific case the  sub-dependency `ecdsa-sig-formatter` has main files in a `src` folder, so they were being ignored and not making it to a final build.

Updating your `ignore` setting to `/^\/(src|index\.ejs|icons)/` in **config.js** will fix the problem.

**Comment by shenliuming** [comment]
emmm, Can you show you config

**Comment by ManojAmarasekara** [comment]
Hello, I'm using this boilerplate to make a desktop Mac app. When I run `npm run build` it successfully creates the dmg file. When I open it I get a blank screen. There aren't any renders which I've done already. 

Can you help me with this?
What am I doing wrong here?

ps - If you want to look into the repo I will share it with you as well.
