### ISSUE TITLE
Where should I save the files that the app generated while working?

### ISSUE THREAD

**Issue by Phantr4x** [SimulatedGREG/electron-vue#183]
I found that file-system operations (e.g. `fs.writeFile()` and `fs.readFile()`) not working in `.asar`.

So where is the right path to save the files that my app generated?

**Comment by SimulatedGREG** [comment]
This is more of an `electron` specific question. In the desktop application world, usually locally stored files are saved in the user's application data. You can get references to that path with electron's `app` module. https://electron.atom.io/docs/api/app/#appgetpathname

**Comment by Phantr4x** [comment]
Uh, that helps me a lot, thank you.
