### ISSUE TITLE
Editing docs page via simulatedgreg.gitbooks.io/electron-vue reached 404 error

### ISSUE THREAD

**Issue by bahit** [SimulatedGREG/electron-vue#184]
### Found an issue or bug? Tell me all about!
Bug
##### Describe the issue / bug.
When trying to click the link "EDIT THIS PAGE" when browsing Electron-Vue docs via simulatedgreg.gitbooks.io/electron-vue would result in 404 error page.
##### How can I reproduce this problem?
1. Go to any docs page at https://simulatedgreg.gitbooks.io/electron-vue/en/ 
2. Browse at the top of the page and click "EDIT THIS PAGE".
3. The page will load to a 404 Github page error.
##### If visual, provide a screenshot.
![screen shot 2017-04-19 at 9 50 54 am](https://cloud.githubusercontent.com/assets/508511/25159970/c320dddc-24e5-11e7-96fc-57bfb7f95bba.png)

I think the reason here is the URL is directing to incorrect page:
`https://github.com/SimulatedGREG/electron-vue/tree/master/en/entry_indexhtml.md` where the correct URL would be `https://github.com/SimulatedGREG/electron-vue/tree/master/docs/en/docs/entry_indexhtml.md`

**Comment by SimulatedGREG** [comment]
@bahit 

Good catch! Just pushed a fixed.
