### ISSUE TITLE
Assets not found on build

### ISSUE THREAD

**Issue by thanoseleftherakos** [SimulatedGREG/electron-vue#185]
##### Describe the issue / bug.
Im trying to import assets with the following way:
`import spoon from '../assets/img/tools/spoon.png';`
When I run `npm run dev` everything works as expected, but when I build the project I am getting 
the following error in the console GET file:///imgs/spoon.png net::ERR_FILE_NOT_FOUND`
Same thing happens if when i build for win32 and for darwin

##### Tell me about your development environment.
  * Node version: v6.9.1
  * NPM version: 3.10.8
  * vue-cli version: (if necessary)
  * Operating System: macos sierra

**Comment by tylerjheslop** [comment]
Same issue here with the same config. 
Menu isn't rendering and assets are missing.

**Comment by NadhirBoukhenifra** [comment]
can you try this please,

`import spoon from './../assets/img/tools/spoon.png';`

by adding the` ./ `befor the path !!

**Comment by SimulatedGREG** [comment]
@thanoseleftherakos 

Do you have a project repo that I could take a look at?

**Comment by SimulatedGREG** [comment]
Sorry for the trouble everyone. This is also related to #198. 

A fix as been made in the `dev` branch. You can take a look at the changes here (https://github.com/SimulatedGREG/electron-vue/commit/131b8416990e5a38980e95a682e67f284f6614ce), specifically with the `copy-webpack-plugin`. This will be released in the next milestone, see #171 for more info.
