### ISSUE TITLE
App Ubuntu Launcher Question mark icon ?

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [SimulatedGREG/electron-vue#189]
##### Describe the issue / bug.
\#
Amm,

i have installed electron-vue and everything goes Fine, But when run this:

`npm run dev
`
or 
`npm run build
`

 the Window Appear but in the launcher i get Question Mark icon?

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: v7.9.0
  * NPM version: v4.2.0
  * vue-cli version: (if necessary) 2.8.1
  * Vue v2.2.6
  * Vue-electron v1.0.6
  * Operating System: Ubuntu 16.04 LTS x64

**Comment by SimulatedGREG** [comment]
@NadhirBoukhenifra 

Assuming you  are using `electron-packager` make sure to read this, https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon. It states that the `linux` platform needs to set the `icon` within the `BrowserWindow` options. This is also stated in the electron-vue docs, https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-electron-packager.html#default-building-configurations.

**Comment by NadhirBoukhenifra** [comment]
I'm using **electron-builder**
I have tried with BrowserWindow, But Nothing ??
and the path is correct because after build terminates I see this:

![screenshot from 2017-04-22 21-25-01](https://cloud.githubusercontent.com/assets/13006236/25307947/551ffede-27a2-11e7-9b2d-6735cbee0b65.png)

and I have changed the icons in the `app/icons` folder to the icon in the picture, to make sure that the icons loaded correctly in the path:

```
  mainWindow = new BrowserWindow({
    height: 728,
    minHeight: 728,
    minWidth: 1024,
    width: 1024,
    icon: path.join(__dirname, 'app/icons/icon.png')
  })
```
and i have in `app/icons`

- icon.icns
- icon.ico
- icon.png  (1024px x 1024px)

Any other ideas ... !!, and thanks for the comment ,

**Comment by NadhirBoukhenifra** [comment]
I think I found the problem
I have changed to `electron-packager` then `npm run build` but nothing changed,
in folder build/app-linux-x64/resources
I use  `asar e app.asar dist` to extract the `dist` folder , and i do not found the icons at all !!!

![screenshot from 2017-04-24 12-06-03](https://cloud.githubusercontent.com/assets/13006236/25335544/6426a8fc-28eb-11e7-88c7-334cc4cbb750.png)

i changed in `config.js` the
`ignore: /^\/(src|index\.ejs|icons)/,`
to
` ignore: /^\/(src|index\.ejs)/,`
and the `icons` folder appear after extract , i think that path not working with `app.asar` file ??

can you change the paths to load icons from `app root` directly not from **sub-folders** ??

**Comment by SimulatedGREG** [comment]
The new upcoming project structure will be solving this, check #171 for more info. Going to close.
