### ISSUE TITLE
[Help] Importing css errors, alias not working.

### ISSUE THREAD

**Issue by Ampix0** [SimulatedGREG/electron-vue#190]
### Found an issue or bug? Tell me all about!

Sorry, this may not be a bug and is probably more likely an issue on my end, please forgive me if so.
I am trying to make use of SCSS, the vue-loader seems to already be included in the config, and I have installed the needed modules. However I am unable to import the SCSS sheet containing my variables and mixins.

##### Describe the issue / bug.
Reddit post: https://www.reddit.com/r/vuejs/comments/66x5rm/having_trouble_importing_scss_undefined/

Error: http://imgur.com/a/ZUcLm

No matter what I have tried I can not get the correct path to the file or there is some other issue with the configuration. The var.scss file needs to be loaded into the app.vue file. 

The alias doesn't appear to work as well which makes me think maybe the path isn't the issue.
I have tried many different path variations but no luck.

- ./var
- ./var.scss
- var
- var.scss
- ~/var.scss
- ~/var
- ~var

\#

##### How can I reproduce this problem?

Attempt to import css

\#

##### If visual, provide a screenshot.

http://imgur.com/a/ZUcLm

\#

##### Tell me about your development environment.
  * Node version: 6.9.3
  * NPM version: 3.10.10
  * vue-cli version: (if necessary)
  * Operating System: Windows 10 build 1703

**Comment by NadhirBoukhenifra** [comment]
Hi,
try this: (it should work :))

` @import './../var.scss'`

if you want to put your `scss` files in `src/assets/scss`
the import should be like this:

`@import './../assets/scss/var.scss'`

other notice:
the path is from `App.vue` if you work with another component inside `components` folder then you must add another **level** to the path (i mean **/../**)

`@import'.**/../**../assets/scss/var.scss'`

look at the picture my folder named `css`

**Comment by SimulatedGREG** [comment]
@Ampix0 

You're initial try with `@import "renderer/var.scss";` was just missing the `~`. Change it to `@import "~renderer/var.scss";`.

One extra thing to note, if you are wanting to use a variables file you would have to import this file in every component that needs it. But luckily, you can actually import a variables files directly into the loader so all components have access to it without having to manually import it every time.

This can be done by updated the `vue-loader` configuration in `webpack.renderer.config.js` at line 54.
```
scss: 'vue-style-loader!css-loader!sass-loader?data=@import "~renderer/vars.scss";'
```

**Comment by Ampix0** [comment]
@SimulatedGREG unfortunately that is not working as well, that's currently how i have it written. I'm going to try @NadhirBoukhenifra suggestions now as well and report back.

error:

```

         ERROR in ./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-09a923c1!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/renderer/App.vue
         Module build failed:
         undefined
         ^
               File to import not found or unreadable: ~renderer/var.scss.
         Parent style sheet: stdin
               in C:\Users\Ampix0\Documents\GitHub\electron-vue\tickr-for-robinhood\app\src\renderer\App.vue (line 15, column 1)
          @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-09a923c1!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./app/src/renderer/App.vue 4:14-269 13:2
-17:4 14:20-275
          @ ./app/src/renderer/App.vue
          @ ./app/src/renderer/main.js
          @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js
```

**Comment by Ampix0** [comment]
@NadhirBoukhenifra your direct relative path did work. So somehow my issue is resolving the alias. Thank you for getting me this far.

**Comment by SimulatedGREG** [comment]
@NadhirBoukhenifra  

Do you have a project repo I could look at?

**Comment by Ampix0** [comment]
@SimulatedGREG almost untouched. 
https://github.com/Ampix0/ticker-for-robinhood

**Comment by SimulatedGREG** [comment]
@Ampix0 

![image](https://cloud.githubusercontent.com/assets/8327811/25318439/8a3567b4-2854-11e7-8292-0bc67bfa1295.png)

Your `vars.scss` isn't in your `app/src/renderer` folder like your original screenshot implied. Moving that file to the renderer folder and using the method of injecting into the loader itself should do the trick.

**Comment by Ampix0** [comment]
@SimulatedGREG Well that's embarrassing... Not sure if the file was somehow moved or if the indenting in my IDE tricked me. Eitherway I apologize for wasting everyone's time!

**Comment by SimulatedGREG** [comment]
No problem, I know that struggle as well. Glad we got this sorted out.

**Comment by ChucKN0risK** [comment]
Hello everyone,

I has an issue for importing my styles. I followed the instructions from the "Using Pre-Processors" page in the doc.

Here is my folder architecture:
<img width="297" alt="capture d ecran 2017-06-03 a 14 55 40" src="https://cloud.githubusercontent.com/assets/3913276/26753746/cdbedb80-486d-11e7-876d-92eae7292ce4.png">

And here is what I wrote in consequence in my webpack.renderer.config.js:
```
{
    test: /\.vue$/,
        use: {
            loader: 'vue-loader',
            options: {
                loaders: {
                    sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1&data=@import "./src/renderer/scss/style"',
                    scss: 'vue-style-loader!css-loader!sass-loader?data=@import "./src/renderer/scss/style";'
            }
        }
    }
},
```

Unfortunatley this failed to compile and I got the following error message:
<img width="877" alt="capture d ecran 2017-06-03 a 15 02 47" src="https://cloud.githubusercontent.com/assets/3913276/26753743/c5afd4d0-486d-11e7-97b2-f1717013af17.png">

I managed to fix this by changing the source in my webpack.renderer.config.js like so:
```
loaders: {
    sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1&data=@import "renderer/scss/style"',
    scss: 'vue-style-loader!css-loader!sass-loader?data=@import "renderer/scss/style";'
}
```
