### ISSUE TITLE
build:clean fails in dev branch

### ISSUE THREAD

**Issue by Oriol-GG** [SimulatedGREG/electron-vue#193]
##### Describe the issue / bug.
\# On the simple structure (`dev` branch), the directory for builds is named `build`. However, in the script for `build:clean` it is referenced as `builds` and hence, not cleaned.
I changed `builds` to `build` and works fine, but then the `icons` are also deleted. So I had to add the `!build/icons` pattern to the `del` patterns to make it work as expected.

I tried forking the repo and the directory is named `builds` in it, and I can't find how you generate the directory when using `vue-cli` so I don't understand why in a generated project is named `build` instead. I would add a PR myself, but I don't know where may other conflicts be between the naming convention of `build`/`builds` or which one do you prefer. 

Thank you so much Greg for this awesome project! I'm loving the simpler-structure and I will soon move a big project to it (once it's finished before the end of the year I will be sure to let you know to wear the `built with electron-vue` badge with pride).

Will fill more issues if I find any bug. Again, thank you so much! 😄 

##### How can I reproduce this problem?
\# I just cloned the repo, checked out the `dev` branch, and `yarn` to install dependencies. Clean install.

##### Tell me about your development environment.
  * Node version: v6.9.5
  * NPM version: v3.10.10
  * Yarn version: v0.23.2
  * Operating System: macOS Sierra 10.12.3

**Comment by Oriol-GG** [comment]
Also, I don't know if this is intentional or not, but in #112 your images shows `dist` to be inside `built`, but it was generated as a separate directory:

<img width="257" alt="screen shot 2017-04-24 at 18 01 30" src="https://cloud.githubusercontent.com/assets/17446354/25329753/1881384a-2918-11e7-9a09-b6f888e35055.png">

**Comment by SimulatedGREG** [comment]
@Oriol-GG 

Thanks for the catch, will note that. And for the `build` vs `dist` structure, this will probably make it to the final build. I am wanting to separate this some for the future support of a `web` targeted output.

**Comment by SimulatedGREG** [comment]
This has been fixed and pushed to the `dev` branch. Check #171 for more info.
