### ISSUE TITLE
Vue-cli installation doesn't install vue-*

### ISSUE THREAD

**Issue by rdpascua** [SimulatedGREG/electron-vue#20]
During vue-cli scaffolding selecting `vue-router`, `vuex` and `vue-resource` doesn't install them actually.

**Comment by LostKobrakai** [comment]
The test libraries are also not installed.

**Comment by SimulatedGREG** [comment]
@rdpascua What steps can I take to reproduce this?

**Comment by rdpascua** [comment]
I just used the vue cli init nothing else.

**Comment by SimulatedGREG** [comment]
I understand what you're saying, but I'm not getting the same issues. You are aware this boilerplate uses a 2 package.json setup right? Vue and all plugins will be installed at `app/package.json`. What version of node and os are you using ?

**Comment by rdpascua** [comment]
```
Node: v6.4.0
OS: Ubuntu 16.04 (x64)
```

Yes I'm aware, what I'm talking about is nothing is appended in the `package.json` let me check on how I can contribute for a fix on this issue.

**Comment by SimulatedGREG** [comment]
What about your `vue-cli` version?
 I just used `nvm` to install node `v6.4.0` and still had no trouble.

**Comment by rdpascua** [comment]
@SimulatedGREG I'm using the latest, let me check so I can help you what's happening.

**Comment by SimulatedGREG** [comment]
Going to try do this in my virtual box.

**Comment by rdpascua** [comment]
```
? Select which Vue plugins to install (Press <space> to select)
❯◉ vue-electron
 ◉ vue-resource
 ◉ vue-router
 ◉ vuex
```
It turns out an issue with the character encoding, the radio now appears fine that's why I'm not noticing anything.

**Comment by SimulatedGREG** [comment]
Ahh, I probably wouldn't have noticed that either. Maybe you should suggest an issue with `vue-cli`. Out of curiosity, are you using the default Terminal app that comes with Ubuntu?

**Comment by rdpascua** [comment]
I'm using the default but different shell (zsh)
