### ISSUE TITLE
Packager ignoring module source code (module not found in production)

### ISSUE THREAD

**Issue by rickhall** [SimulatedGREG/electron-vue#204]
I'm no expert on this stuff, so I'm just happy I was able to get to the bottom of this issue...

My app has a dependency on emailjs-imap-client. It works fine with "npm run dev" but failed like this when running the app created from "npm run build":

```
Uncaught Error: Cannot find module 'emailjs-imap-client'
    at Module._resolveFilename (module.js:470:15)
```
After digging around, I noticed that the module directory being packaged into the app (I turned off asar to inspect the contents) didn't have any source code in it. After some more digging around, I saw that config.js has this:

`    ignore: /\b(src|index\.ejs|icons)\b/,`

Since in dev mode emailjs-imap-client has its source in src/, I removed the "src" from the ignore and rebuilt. After that, the production app started without issue.

Again, I'm no expert, but is it a general requirement that modules shouldn't use the "src" directory to distribute their source and should put it someplace else (e.g., lib/ or something) or is the default configuration in config.js being a little over zealous in what it ignores?

Thanks in advance.

**Comment by SimulatedGREG** [comment]
I would personally say modules shouldn't distribute code from the `src` directory, but that just isn't the case. This issue came up a few weeks ago and the `ignore` value has been updated to...
```js
ignore: /^\/(src|index\.ejs|icons)/,
```
Feel free to comment back if you need any more help. Closing.

**Comment by rickhall** [comment]
Yes, that appears to work for me too. Thanks!
