### ISSUE TITLE
Geolocation in Electron

### ISSUE THREAD

**Issue by Antoniobk** [SimulatedGREG/electron-vue#205]
Is there any way to get geolocation from vue-electron?
In the following code I am sent to error
```
geoLocation() {
  if (!navigator.geolocation) {
    console.log( 'Geolocation is not supported by your browser')
    return
  }
  let success = (position) => {
    console.log('success',position)
  }
  let error = () => {
    console.log('error')
  }
  navigator.geolocation.getCurrentPosition(success, error)
},
```

**Comment by SimulatedGREG** [comment]
@Antoniobk 

This is an `electron` specific issue but here is the reason to the problem and a simple solution (https://electron.atom.io/docs/api/environment-variables/#google_api_key). Hope this helps.
