### ISSUE TITLE
Reading local file from disk

### ISSUE THREAD

**Issue by vlad-saling** [SimulatedGREG/electron-vue#206]
Hey,

first of all, thank you for electron-vue. It's a really nice combo to work with. 👍 
I recently decided to create a little side-project of mine and while working on features I ran into one issue. I am trying to read a file from disk (I am writing an app, that should save/load user data from and to disk). My code looks like this:
```
const fs = require('fs') 
...
methods: {
  fetchLocalData () {
    fs.readFile('./cl-data.json', 'utf8', function (err, data) {
      if (err) {
        return err
      } else {
        this.healthCheck = 'boo'
      }
    })
  },
...
data () {
  return {
    healthCheck: ''

```

When I try to run it, I get this error:
```
Uncaught TypeError: Cannot set property 'healthCheck' of undefined
    at eval (eval at <anonymous> (renderer.js:1288), <anonymous>:22:28)
    at tryToString (fs.js:426)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413)
```

It seems to me (however improbable it sounds) like the inner scope of readFile doesn't have access to Vue object's variables. At this point I am not sure what am I doing wrong. Or am I trying to do something, that isn't even possible?

Notes:
Bug can be reproduced by attempting to read local file and assign it's content (or assign any global variable) from within `readFile` method.

  * Node version: v7.7.3
  * NPM version: 4.2.1
  * Operating System: Win10 64bit

**Comment by SimulatedGREG** [comment]
@vlad-saling 

The context of `this` isn't inherited in the code you posted. Using an arrow function will solve this issue, as it provides lexical binding so the context of `this` is shared.
```js
fs.readFile('./cl-data.json', 'utf8', (err, data) => {
  if (err) {
    return err
  } else {
    this.healthCheck = 'boo'
  }
})
```

**Comment by vlad-saling** [comment]
Oh my, indeed... You rock! Thank you :) You can close this issue.

**Comment by SimulatedGREG** [comment]
No problem sir. Glad you got this sorted out.
