### ISSUE TITLE
Router not working with two BrowserWindows

### ISSUE THREAD

**Issue by melquic** [SimulatedGREG/electron-vue#207]
Hi,
I’m trying to create an app with two BrowserWindows using the same Vue App with vue-router, but the router aren’t working. I’m always receiving error ‘Cannot GET /’ for the second route.

**main\index.js**
```
var mainURL = `http://localhost:9080/`
var secondURL = `http://localhost:9080/page2`

function createWindow () {
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800
  })
  mainWindow.loadURL(mainURL)
  mainWindow.on('closed', () => {
    mainWindow = null
  })

  secondWindow = new BrowserWindow({
    height: 600,
    width: 800
  })
  secondWindow.loadURL(secondURL)
  secondWindow.on('closed', () => {
    secondWindow = null
  })
}

app.on('ready', createWindow)
```
**routes.js**
```
export default [
  {
    path: '/',
    name: 'landing-page',
    component: require('components/LandingPageView')
  },
  {
    path: '/page2',
    name: 'landing-page2',
    component: require('components/LandingPageView2')
  },
  {
    path: '*',
    redirect: '/'
  }
]
```

Testing code: https://github.com/melquic/vue-two-windows.git

Error print screen:
<img width="1412" alt="vue-two-windows-error" src="https://cloud.githubusercontent.com/assets/1239634/25764689/8a6c61be-31bf-11e7-9bb3-a5e9d56228dc.png">

Thank you for help!
Best.

**Comment by SimulatedGREG** [comment]
@melquic 

I would highly avoid using the `history` mode as it won't work in a final production app. By using the default `hash` mode and changing the url in the second window to `http://localhost:9080/#/page2` things should work fine.

**Comment by melquic** [comment]
@SimulatedGREG Thank you a lot! It's working now... 
By the way, how should I call the second route when I build production? `file://${__dirname}/index.html#page2` ?

**Comment by SimulatedGREG** [comment]
That should do the trick.

**Comment by melquic** [comment]
@SimulatedGREG Thank you!

**Comment by cnikolov** [comment]
Just to let you know I also tried in single window more than one router and it doesnt work. I am getting some weird errors..

router code:

import Vue from 'vue'
import Router from 'vue-router'
import datastore from '../datastore'
Vue.use(Router)
const HomePage = require('@/components/HomePage');
const LoginPage = require('@/components/LoginPage');
const TestPage = require('@/components/TestPage');

export default new Router({
  mode: 'hash',
  routes: [
    {
      path: '/home',
      name: 'HomePage',
      component: HomePage.default,

    },
    {
      path: '/',
      name: 'LoginPage',
      component: LoginPage,

    },
    {
      path: '*',
      redirect: '/'
    }
  ]
})

vue.esm.js?a026:628 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <MyApp> at src/renderer/App.vue
         <Root>
