### ISSUE TITLE
[Question] Unit test only one spec

### ISSUE THREAD

**Issue by melquic** [SimulatedGREG/electron-vue#208]
Guys, when we execute npm run unit, it runs all test specs at once. Is it possible to ask karma to run only a specific test spec?
Thank you.

**Comment by SimulatedGREG** [comment]
@melquic 

There isn't a easy way to set this up as Karma is given the entire list of specs when running. This file (https://github.com/SimulatedGREG/electron-vue/blob/master/template/test/unit/index.js) determines what is feed into Karma, so you would need to adjust what specs are being required.

This is nearly the same setup as the official `vuejs-templates/webpack` setup and there are no plans to add this sort of capability.

**Comment by SimulatedGREG** [comment]
Going to close this. Feel free to comment back any other questions.

**Comment by melquic** [comment]
Ok. Thanks!
