### ISSUE TITLE
How to access electron "app" from vue?

### ISSUE THREAD

**Issue by alexcroox** [SimulatedGREG/electron-vue#212]
I'd like to display the app version in my ui. The version should come from package.json. However I can't seem to access `app` from within my renderer components.

I've tried 

```
<script>
  import app from 'electron'

  export default {

    data () {
      return {
        appVersion: app.getVersion()
      }
    },
```

I was considering importing `package.json` to read it directly from there but I'm not sure if this will work both in dev and build since package.json doesn't get packaged (I'm using electron-builder)?

**Comment by SimulatedGREG** [comment]
@alexcroox 

You almost had it, but you need to destructure the app from `electron`.
```js
import { app } from 'electron'
```

**Comment by alexcroox** [comment]
`app` is undefined if I log it after the import

**Comment by SimulatedGREG** [comment]
My mistake, I for some reason thought `app` was a shared module. You'll need to access it from `remote`. In development you'll probably get the version of `electron` being used, but in prod you should get the version from `package.json`.

```js
import { remote } from 'electron'

console.log(remote.app.getVersion())
```

**Comment by alexcroox** [comment]
Definitely getting somewhere but I think that is the version of electron itself since it doesn't match either of my package.json (it shows 1.6.6 when package.json has 0.1.1). When I run `npm run build` that random version number reveals itself:

```
No native production dependencies
Packaging for darwin x64 using electron 1.6.6 to dist/mac
```

**Comment by SimulatedGREG** [comment]
Just as I just previously mentioned, you will get the `electron` version in development, but in a production build you will get the `package.json` version. This behavior is described in electron's documentation (https://electron.atom.io/docs/api/app/#appgetversion).

**Comment by alexcroox** [comment]
Can confirm, when built it is correct. Thank you so much!

**Comment by n82** [comment]
Hi @SimulatedGREG and @alexcroox

I had a similar problem with `app.getPath('userData')` returning `Electron` in development and `My-App` in production.

In `.electron-vue/dev-runner.js` i replaced 

```
`electronProcess = spawn(electron, ['--inspect=5858', path.join(__dirname, '../dist/electron/main.js')])`
```

with 

```
electronProcess = spawn(electron, ['--inspect=5858', '.'])
```

This way Electron will read `package.json` and load the `main` script.

**Comment by marceloavf** [comment]
Is that safe to use this approach of @n82, @SimulatedGREG ?
