### ISSUE TITLE
Configuring product name on build file?

### ISSUE THREAD

**Issue by rdpascua** [SimulatedGREG/electron-vue#215]
![capture](https://cloud.githubusercontent.com/assets/2498246/26022445/4fa38d2c-37d8-11e7-88d1-0b464e05dcaf.PNG)

I've tried updating `package.json`  but it doesn't work, is this specific on the `npm run build:win32` ?

**Comment by SimulatedGREG** [comment]
Within `config.js`, the name option in the build settings defines your application name. 

https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#name

**Comment by rdpascua** [comment]
Sorry I skimmed the docs.

for reference I found everything right here
https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#options
