### ISSUE TITLE
can't access static folder at build app

### ISSUE THREAD

**Issue by kawamataryo** [SimulatedGREG/electron-vue#216]
Hi. thanks for this great component. 

I would like to ask you the question.

I can't access static folder at build app.(use dev branch)
I referred　 #198 .

My code is this.

src/renderer/components/disease.vue
```disease.vue
var Database = require("nedb");
var diseaseDB = new Database({
    filename: 'static/disease.json',
    autoload: true
});
```

My tree is this
```
├── src
│   ├── index.ejs
│   ├── main
│   │   ├── index.dev.js
│   │   └── index.js
│   └── renderer
│       ├── App.vue
│       ├── assets
│       │   └── logo.png
│       ├── components
│       │   ├── Db.vue
│       │   ├── Disease.vue
│       │   ├── Index.vue
│       │   ├── Write.vue
│       │   ├── assets
│       │   │   └── disease.json
│       │   ├── caseDB.json
│       │   └── forms
│       │       ├── ippan.vue
│       │       ├── kotsu.vue
│       │       ├── kyubyou.vue
│       │       └── tensou.vue
│       ├── main.js
│       ├── main.scss
│       ├── myfunc.js
│       ├── router
│       │   └── index.js
│       └── store
│           ├── index.js
│           └── modules
│               ├── Counter.js
│               └── index.js
├── static
│   └── disease.json
```

static/disease.json can be accessed in development mode,
 but can not be accessed in build app.

<img width="850" alt="2017-05-15 22 22 19" src="https://cloud.githubusercontent.com/assets/11070996/26059516/0106a47e-39bd-11e7-8f90-c309848bfafc.png">

Please tel me how to use static folder at build  app.
thank you.

**Comment by SimulatedGREG** [comment]
For your use case, you wouldn't want to use the `static` folder for you `*.db`. The native desktop approach to saving local files is to use the user's documents space or the system's application data directories. You can use Electron's [`app.getPath`](https://electron.atom.io/docs/api/app/#appgetpathname) API to get a path to one of those directories. This way you can have a reliable space for your `*.db`s and other possible files/configurations. I would consider manipulating files inside your application would be an anti-pattern to avoid.

**Comment by kawamataryo** [comment]
Thank you so much!  I will try your advice.

**Comment by benlipp** [comment]
@SimulatedGREG How do we use `app.getPath` in development mode? It seems that the dev server does not host the files, and instead just appends the local path to the server. This results in `http://localhost:9080/home/phatlipp/.config/Electron/files/1.mp4` which is not found.
