### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by lianshengxing** [SimulatedGREG/electron-vue#217]
##### Describe the issue / bug.
\#

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by SimulatedGREG** [comment]
Going to close since the template is left empty and there is no information to describe this issue.
