### ISSUE TITLE
Electron builder version

### ISSUE THREAD

**Issue by patleeman** [SimulatedGREG/electron-vue#220]
### Found an issue or bug? Tell me all about!

Electron builder in the template is currently at version 11.4.4

`"electron-builder": "^11.4.4",`

Latest is 17.10.0 

I'm not sure if this will screw up any of the build scripts, but I'm currently using 17.8.0 and it seems to be working fine. I'm currently working off the dev branch.

**Comment by SimulatedGREG** [comment]
@patleeman

Planning to update all dependencies before release of next milestone.

**Comment by patleeman** [comment]
Excellent!

I've had a pretty good experience upgrading my app from v.1 to the single package.json and minimized version of the boilerplate. Thanks for all your hard work.
