### ISSUE TITLE
Debug on main process

### ISSUE THREAD

**Issue by Jun90925** [SimulatedGREG/electron-vue#221]
# How to debug main process with vscode?

**Comment by SimulatedGREG** [comment]
Debugging the `main` process in electron will be going through major changes with the next release of `electron@1.7.2` as Node will be moving to the `v8` Inspector Agent. In the current moment, electron-vue doesn't provide a simple way to debug with vscode other than debugging production code. The future 1.7.2 release will enable debugging with `chrom://inspect` to make this entire process much easier. Make sure to check out https://github.com/SimulatedGREG/electron-vue/issues/180 for more information.

**Comment by SimulatedGREG** [comment]
Related: https://github.com/electron/electron/pull/9436

**Comment by SimulatedGREG** [comment]
With the new release of `electron@1.7.2` you can now open `chrome://inspect` from Google Chrome and then connect to the remote electron process will running your application in development mode. I know this isn't the answer to debugging with VSCode, but at the current moment this recent major change with Node needs to be mitigated on VSCode's side now. There really isn't much I can do here.

related: https://github.com/Microsoft/vscode/issues/24611
