### ISSUE TITLE
CRUD example

### ISSUE THREAD

**Issue by Zyles** [SimulatedGREG/electron-vue#222]
Thanks for the boilerplate.

Would be nice if you could make a CRUD example, either in this package or the documentation towards a rest API for example, or a local database.

**Comment by SimulatedGREG** [comment]
@Zyles 

As far as speaking with a rest API, `vue-resource`/`axios` is all you need. How that is done is not related to this boilerplate at all, so there is no reason to provide of an example of it. Just look at the plugin's docs for an example.

A local database would be specific to `electron` and there will be new documentation about that in the next milestone release (see #171 for more info). The `dev` branch docs are nearly complete and here is a reference on how to use `nedb` with the upcoming new setup (https://simulatedgreg.gitbooks.io/electron-vue/content/v/49bff43af869662d7a5314b99147c05419329544/en/savingreading-local-files.html).
