### ISSUE TITLE
how can i use the path of image in the main process when i want to creat a Tray

### ISSUE THREAD

**Issue by lianshengxing** [SimulatedGREG/electron-vue#225]
`ipcMain.on('create-tray',() => {
  mainWindow.hide();
  if(trayOn == false) {
      const contextMenu = Menu.buildFromTemplate([{
          label: '退出',
          click: function () {
              tray.destroy()
              app.quit()
          }
      }])
      const iconPath =  path.join(__dirname, '/logo/logo.png')
      tray = new Tray(iconPath)
      // tray = new Tray('app/src/renderer/components/assets/icon/logo.png')
      tray.setToolTip('个人工作平台')
      tray.setContextMenu(contextMenu)
      trayOn = true
  }else {
      return
  }
})`

it works will in the development progress, but it dose not work after i package the project and throw an err

**Comment by SimulatedGREG** [comment]
#224 #226
