### ISSUE TITLE
how i can open office in the main process

### ISSUE THREAD

**Issue by lianshengxing** [SimulatedGREG/electron-vue#226]
`ipcMain.on('create-word',() => {
  shell.openItem(path.join(__dirname, '../renderer/components/HomeViews/new.docx'));
})

ipcMain.on('create-xls',() => {
  shell.openItem(path.join(__dirname, '../renderer/components/HomeViews/new.xls'));
})

ipcMain.on('create-ppt',() => {
  shell.openItem(path.join(__dirname, '../renderer/components/HomeViews/new.ppt'));
})`

it works well in the development progress, but it dose not work after i package the project

**Comment by SimulatedGREG** [comment]
This is the same situation as the #224. Please refer to the docs I posted there on how to handle Static Assets and how `__dirname` is handled.

**Comment by SimulatedGREG** [comment]
@lianshengxing 

Coming in the next milestone release will be a `__static` variable that will provide a reliable way to access your `static/` assets. More info at #171. Here is a link to the upcoming documentation, https://simulatedgreg.gitbooks.io/electron-vue/content/v/9772e38a3e73c5610ba845b2d07103d1b2a7a29d/en/using-static-assets.html#use-case-within-js-with-fspath-and-static.
