### ISSUE TITLE
I want to know something about autoUpdater

### ISSUE THREAD

**Issue by lianshengxing** [SimulatedGREG/electron-vue#228]
how should i config it in the main process

**Comment by SimulatedGREG** [comment]
Auto update support would require the usage of `electron-builder` and `electron-updater`. One "gotcha" to auto updating is that you must have a valid Code Signing certificate to sign you application. Operating Systems will not auto update your application without one. Greater support for auto updating and building with a CI server is currently in the `dev` branch and will be released in the next milestone release.

References in `dev` branch:
https://simulatedgreg.gitbooks.io/electron-vue/content/v/9772e38a3e73c5610ba845b2d07103d1b2a7a29d/en/using-electron-builder.html#automated-deployments-using-ci
https://github.com/SimulatedGREG/electron-vue/blob/dev/template/src/main/index.js#L49-L66
https://github.com/SimulatedGREG/electron-vue/blob/dev/template/.travis.yml
https://github.com/SimulatedGREG/electron-vue/blob/dev/template/appveyor.yml

PS: This issue tracker is meant for issues with electron-vue. If you are having general questions about Vue or Electron, then please reach out their respective communities to ask these sort of questions.
