### ISSUE TITLE
Page is blank

### ISSUE THREAD

**Issue by Zyles** [SimulatedGREG/electron-vue#229]
Some newbie issues here. I tried to copy the landing page template and link to a custom view but it just ends up blank and I can't see any errors in console and the "dev tools disconnected" in the app.

What am I missing?

##### Describe the issue / bug.
Tried to make a new view, but it is blank when I click the link.

##### How can I reproduce this problem?

routes.js
````
export default [
  {
    path: '/',
    name: 'landing-page',
    component: require('components/LandingPageView')
  },
  {
    path: '/current-system',
    name: 'current-system',
    component: require('components/CurrentSystemView')
  },
  {
    path: '*',
    redirect: '/'
  }
]
````

renderer/components/CurrentSystemView/CurrentSystem.vue

`````
<template>
<div>
  <p>Current system: <code>`{{ $route.path }}`</code></p>
</div>
</template>

<script>
  export default {
    created () {
      // Set $route values that are not preset during unit testing
      if (process.env.NODE_ENV === 'testing') {
        this.$route = {
          name: 'current-system',
          path: '/current-system'
        }
      }
    }
  }
</script>

<style scoped>
  code {
    background-color: rgba(40, 56, 76, .5);
    border-radius: 3px;
    color: #fff;
    font-weight: bold;
    padding: 3px 6px;
    margin: 0 3px;
    vertical-align: bottom;
  }

  p { line-height: 24px; }
</style>
`````

renderer/components/CurrentSystemView.vue

````
<template>
  <div>
    <h1>Current System</h1>
    <current-system></current-system>
  </div>
</template>

<script>
  import CurrentSystem from './CurrentSystemView/CurrentSystem'
  export default {
    components: {
      CurrentSystem
    },
    name: 'current-system'
  }
</script>

<style scoped>

</style>
````

And in the LandingPageView.vue I added:

````
<router-link to="current-system">Current system</router-link>
````

##### Tell me about your development environment.
All latest on Windows 10.

**Comment by Zyles** [comment]
I changed the path to "/current-system-page" and it works?? Conflict with naming scheme?

**Comment by SimulatedGREG** [comment]
This would be a naming conflict within Vue's internal component tree. It is possible to have different components with the same file name but they all must have different `name`s.
