### ISSUE TITLE
Getting/setting mainWindow in index.js

### ISSUE THREAD

**Issue by Zyles** [SimulatedGREG/electron-vue#230]
##### Describe the issue / bug.

How do you access the window properties in src/main/index.js

```
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    frame: false,
    resizable: true,
    alwaysOnTop: true
  })
```

I want to be able to toggle "alwaysOnTop" to true/false using a <button>

I may also want to resize the window with a function, if that is possible.

**Comment by SimulatedGREG** [comment]
**https://electron.atom.io/docs/api/browser-window/#winsetalwaysontopflag-level-relativelevel**
```js
mainWindow.setContentSize(width, height[, animate])
```

**https://electron.atom.io/docs/api/browser-window/#winsetcontentsizewidth-height-animate**
```js
mainWindow.setAlwaysOnTop(flag[, level][, relativeLevel])
```

**Comment by Zyles** [comment]
Sorry but I can't access mainWindow from a component since it is "not defined".

How do you access it from the render process? Or specifically from a component.

**Comment by SimulatedGREG** [comment]
@Zyles 

So sorry! I read your comment wrong; it was the middle of the night so I must have been super tired 😴 .

If you need to get access to your BrowserWindow from the `renderer` process, then you can do something like...

**SomeComponent.vue** 
```js
const mainWindow = this.$electron.remote.BrowserWindow.getFocusedWindow()
```
And of course from here you can then use the API methods I post before.

**Comment by Zyles** [comment]
Thank you that works.

**Comment by Dsaint109** [comment]
Hi this fix doesn't work anymore... is there anything I can do
I get an error like this
> Uncaught TypeError: Cannot read property 'remote' of undefined
