### ISSUE TITLE
MacOS Sierra dev env Electron is not running

### ISSUE THREAD

**Issue by Pioruniasty** [SimulatedGREG/electron-vue#231]
##### Describe the issue / bug.
\# I can't start electron dev on macos sierra. After starting webpack dev server electron is not running (I don't know but I think it's because of 36 line in runner.js). But if I will try to build for production everything works fine. I found this problem only on my Macbook Pro (2015) cause on Windows everything builds fine.

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: 7.10
  * NPM version: 4.2
  * vue-cli version: (if necessary)
  * Operating System: MacOS Sierra

**Comment by Pioruniasty** [comment]
Ok I think i know how to repair. Actually now it's working for me fine. Meybe someone has better suggestion.

In line 36 I changed "VALID" to "successfully" and it's working good. **data** in last usage of "run" function is "webpack: Compiled successfully" and ofc. test with "VALID" didn't worked well.

**Comment by SimulatedGREG** [comment]
@Pioruniasty 

This issue has actually been fixed for quite sometime. Did you just recently scaffold a new project or is this an existing project?

Related: #114

**Comment by Pioruniasty** [comment]
An existing. Ok I will create new project and I will transport all source files there. Thanks for qck replay! <3

**Comment by SimulatedGREG** [comment]
@Pioruniasty 

As an FYI, there is going to be a major release this week. So you may want to wait on transferring everything over, 😉 . See #171 for more info.

**Comment by Pioruniasty** [comment]
Oh, ok then, I will wait. Thanks for info! 💗
