### ISSUE TITLE
Cannot run unit tests on macOS

### ISSUE THREAD

**Issue by popod** [SimulatedGREG/electron-vue#234]
when I run `npm run unit` with an empty electron-vue project with all default params, this doesn't works !

I have the following and nothing more append (an empty electron window appear)..

```
01 06 2017 02:18:24.153:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
01 06 2017 02:18:24.156:INFO [launcher]: Launching browser visibleElectron with unlimited concurrency
01 06 2017 02:18:24.196:INFO [launcher]: Starting browser Electron

```

**Comment by SimulatedGREG** [comment]
@popod 

I can't seem to reproduce this issue. Could you provide more information about your development environment, as specified in the issue template. Also do you have a personal proxy running locally that could tamper with webpack or the test runner?

**Comment by popod** [comment]
Hi, thanks for reply ! I don't have any personal proxy (others command like `npm run e2e` or `npm run build` works well).

Here are the informations :
  * Node version: 7.4.0
  * NPM version: 4.0.5
  * Operating System: macOS Sierra (10.12.5)

package.json :

```
"devDependencies": {
    "babel-core": "^6.8.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-istanbul": "^3.1.2",
    "babel-plugin-transform-runtime": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.18.0",
    "babel-runtime": "^6.6.1",
    "chai": "^3.5.0",
    "cross-env": "^3.1.4",
    "css-loader": "^0.26.1",
    "del": "^2.2.1",
    "devtron": "^1.1.0",
    "electron": "^1.3.1",
    "electron-builder": "^11.4.4",
    "electron-debug": "^1.1.0",
    "electron-devtools-installer": "^2.0.1",
    "electron-rebuild": "^1.1.3",
    "eslint": "^3.13.1",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^2.0.5",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "extract-text-webpack-plugin": "^2.0.0-beta.4",
    "file-loader": "^0.9.0",
    "html-webpack-plugin": "^2.16.1",
    "inject-loader": "^2.0.1",
    "json-loader": "^0.5.4",
    "karma": "^1.7.0",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^1.1.1",
    "karma-electron": "^5.2.1",
    "karma-mocha": "^1.2.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.26",
    "karma-webpack": "^2.0.1",
    "mocha": "^3.0.2",
    "require-dir": "^0.3.0",
    "spectron": "^3.4.0",
    "style-loader": "^0.13.1",
    "tree-kill": "^1.1.0",
    "url-loader": "^0.5.7",
    "vue-hot-reload-api": "^2.0.7",
    "vue-html-loader": "^1.2.2",
    "vue-loader": "^10.0.2",
    "vue-style-loader": "^1.0.0",
    "vue-template-compiler": "^2.1.10",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0",
    "webpack-merge": "^2.4.0"
  }
```

Hope this helps !

**Comment by popod** [comment]
And this is the console logs :

```
npm run unit

> test@0.1.0 unit /Users/test/Documents/Documents/Projets/test/electron-vue
> karma start test/unit/karma.conf.js

(node:95679) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
02 06 2017 11:33:55.942:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/
02 06 2017 11:33:55.944:INFO [launcher]: Launching browser visibleElectron with unlimited concurrency
02 06 2017 11:33:55.981:INFO [launcher]: Starting browser Electron
```

**Comment by SimulatedGREG** [comment]
I'm still unable to reproduce this issue :/. Could you try a fresh scaffold with the new project structure (https://github.com/SimulatedGREG/electron-vue/issues/171#issuecomment-305960282)?

**Comment by popod** [comment]
Same problem with latest electron-vue.. All works fine except unit tests :(

**Comment by SimulatedGREG** [comment]
I'm not able to reproduce; have tried on multiple `node` versions for both macOS and Windows. I know that this operation works as CI servers are able to run tests without issue. Have you tried scaffolding a new application on a different system?

**Comment by popod** [comment]
No I've not try that.. but what about my system ? what could cause this issue and what could I do to debug this ?

Just for information: I use electron-builder in vue-electron initialisation and defaults params for all others configs. Have you test with this config too ?

I've try with a new scaffolding app and this doesn't works.. But now this is my current package.json (I've done some update to use latest electron version):

```
"devDependencies": {
    "babel-core": "^6.8.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^7.0.0",
    "babel-plugin-istanbul": "^4.1.4",
    "babel-plugin-transform-runtime": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.18.0",
    "babel-runtime": "^6.6.1",
    "chai": "^4.0.2",
    "cross-env": "^5.0.0",
    "css-loader": "^0.28.4",
    "del": "^2.2.1",
    "devtron": "^1.1.0",
    "electron": "^1.6.10",
    "electron-builder": "^18.5.1",
    "electron-debug": "^1.1.0",
    "electron-devtools-installer": "^2.0.1",
    "electron-rebuild": "^1.1.3",
    "eslint": "^3.13.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-html": "^2.0.0",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-node": "^5.0.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "extract-text-webpack-plugin": "^2.0.0-beta.4",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.16.1",
    "inject-loader": "^3.0.0",
    "json-loader": "^0.5.4",
    "karma": "^1.7.0",
    "karma-chai": "^0.1.0",
    "karma-coverage": "^1.1.1",
    "karma-electron": "^5.2.1",
    "karma-mocha": "^1.2.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "0.0.31",
    "karma-webpack": "^2.0.1",
    "mocha": "^3.0.2",
    "require-dir": "^0.3.0",
    "spectron": "^3.6.4",
    "style-loader": "^0.18.2",
    "tree-kill": "^1.1.0",
    "url-loader": "^0.5.7",
    "vue-hot-reload-api": "^2.0.7",
    "vue-html-loader": "^1.2.2",
    "vue-loader": "^12.2.1",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.1.10",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0",
    "webpack-merge": "^4.1.0"
  }
```
Could you try if `npm run unit` still work on your side with this dev-dependencies versions ? Perhaps I've a newer version of some dev-dependency module installed locally..

Thanks for your time and answers ;)

**Comment by SimulatedGREG** [comment]
The `devDependencies` you posted are related to the previous version of electron-vue with the old 2 `package.json` setup. The new version has modules like `webpack-hot-middleware` and `babili-webpack-plugin`, and the list you posted above doesn't have those.

And yes, I've tested the options you mentioned, and so does the CI server every night. It tests just about every combination of scaffold options possible. I asked if you could try this on another system because, although quite rare, there have been cases where *something* on the system can prevent expected actions/results. If you have a project repo you'd like me to take a look at, please fell free to post that.

Here's what I just did to get this working.
 * Node version: 7.2.0
 * yarn version: 0.24.5
 * vue-cli version: 2.8.2
 * Operating System: macOS Sierra (10.12.5)

```bash
vue init simulatedgreg/electron-vue 234
cd 234
yarn
yarn run unit
```
![kapture 2017-06-07 at 23 41 01](https://user-images.githubusercontent.com/8327811/26912607-3c50b9f4-4bdb-11e7-96e4-9f4601674c14.gif)

**Comment by popod** [comment]
For the package.json, this is the one for my current project which use not the newer electron-vue.. But I've the same problem when I test with the new version..

I have perhaps found the difference between our two environments.. I've using node v7.4.0 for my first tests and now I'm on v8.0.0. But as you tell me, you are on v7.4.0. Is it possible that this is the newer node versions who cause the problem ?

**Comment by popod** [comment]
I found the problem.. I don't know why, but it seems that 0.0.0.0 is not handled correctly on my laptop. By adding `ListenAddress: '127.0.0.1' in karma.conf all works now !

**Comment by SimulatedGREG** [comment]
@popod 

Glad you got this sorted out. It sounds like your `hosts` file on your system was modified.
