### ISSUE TITLE
how to pack the preload resource

### ISSUE THREAD

**Issue by ljyf5593** [SimulatedGREG/electron-vue#236]
when use the electron browserWindow Object to create a window with preload option
if use npm run dev is right  but if use npm run build  there will have a error "unable to load preload script"

i think the reason is the preload not pack to the app.asar, but how can i do it ?

**Comment by SimulatedGREG** [comment]
@ljyf5593 There isn't a super easy solution for this, but here's some direction on how to accomplish this.

You would need to treat your preload script as a Static Asset and provide a path to it with the `preload` option. The current setup of electron-vue doesn't provide much help for getting an absolute path to the static assets folder, but in the next upcoming release this will be much easier to accomplish with a new [`__static`](https://simulatedgreg.gitbooks.io/electron-vue/content/v/32b46b943254d38f35ce06d886d906f69ad6d90c/en/using-static-assets.html#use-case-within-js-with-fspath-and-static) variable. This setup is currently available using the `dev` branch (#171 for more info).

Reffering to https://simulatedgreg.gitbooks.io/electron-vue/content/en/main-process.html#on-the-subject-of-using-dirname--filename , you can place your preload script in `app/dist` and use `path.join(__dirname, '/preloadScript.js')` in production. This path would need to be adjusted to something like `path.join(__dirname, '../../dist/preloadScript.js')` in development.

**Comment by SimulatedGREG** [comment]
Related: #239

**Comment by SimulatedGREG** [comment]
Closing in favor of #239
