### ISSUE TITLE
How can i translate Docs into Multinational language  and How can i use scss?

### ISSUE THREAD

**Issue by hlipeter** [SimulatedGREG/electron-vue#237]
### use .scss and translate
Hi !
I just did this :
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project
cd my-project
npm install
npm run dev

Only this and nothing more,No problems arise!
but,I can't translate and use *.scss !
yes , I have seen most of the issue and did more , None of them can succeed
incloud what you said in [issue#125](https://github.com/SimulatedGREG/electron-vue/issues/125)
I build your own github to show [electron-vue](https://github.com/shdgit/electron-vue)

It's important to me ！

Thank you !

##### Describe the issue / bug.
\#
import 'assets/style/main.scss'  in app.vue

 ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./app/src/renderer/App.vue
         Module not found: Error: Can't resolve 'assets/style/main.scss' in '/Users/gokuai/Documents/workspace/electron-vue/app/src/renderer'
          @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./app/src/renderer/App.vue 3:0-32
          @ ./app/src/renderer/App.vue
          @ ./app/src/renderer/main.js
          @ multi (webpack)-dev-server/client?http://localhost:9080 webpack/hot/dev-server ./app/src/renderer/main.js
#\

**Comment by SimulatedGREG** [comment]
@shdgit 

https://github.com/shdgit/electron-vue/pull/1/files

**Comment by SimulatedGREG** [comment]
If you are interested in translating the documentation to another language, please see #155.

**Comment by hlipeter** [comment]
OK , As import *.scss  file ，I Got it ! You're right, Thanks a lot!
