### ISSUE TITLE
v-link directive not found

### ISSUE THREAD

**Issue by PDeveloper** [SimulatedGREG/electron-vue#24]
Using electron-vue (this has been amazing so far btw : ) ), I can't seem to use `v-link` in my Components, the devtools error with `[Vue warn]: Failed to resolve directive: link (found in component <login>)`

Use the `v-link` directive in a `Component.vue`. Everything else has been untouched from setup.

  * Node version: 4.5.0
  * NPM version: 2.15.9
  * Operating System: Windows 10

**Comment by SimulatedGREG** [comment]
Are you using vue@next (2.0)?

**Comment by PDeveloper** [comment]
Yes!

**Comment by SimulatedGREG** [comment]
Ah ha! Make sure to check out the changes for vue-router@next. The `v-link` directive has been replaced with a `<router-link>`. https://github.com/vuejs/vue-router/releases/tag/v2.0.0-beta.1

**Comment by PDeveloper** [comment]
Thanks for the pointer! I had to dig a bit deeper to find that releases page, I now got it to work!

Keep this thing rockin', super fast feedback : )
