### ISSUE TITLE
Minimize milestone - duplicate webpack configs?

### ISSUE THREAD

**Issue by alexcroox** [SimulatedGREG/electron-vue#240]
I'm just in the process of migrating my old electron-vue project to the latest milestone release. However I'm a little confused, there is 4 webpack configs in total, 2 in `./electron-vue/` and 2 in root. According to the updated documentation I should be using the electron-vue/ ones, but what purpose do the 2 in root serve other than confusion?

**Comment by alexcroox** [comment]
They aren't in the master /template folder so I'm guessing `vue init` incorrectly adds them to the root. I've deleted them for now with no issues.

**Comment by SimulatedGREG** [comment]
Make sure `vue-cli`is updated. There was a recent issue that somehow mixed a cached and current version of a template. Not sure how this is possible, but I also into this during development.

**Comment by alexcroox** [comment]
Oh, so is it best I start the entire migration process again in case there are other inconsistencies? :(

**Comment by SimulatedGREG** [comment]
All updated files should be in order, so you shouldn't have any issues. You may just have extra files from the older version, another would be the `config.js` which has been removed.

**Comment by alexcroox** [comment]
OK thank you very much! Loving the new refactor, <3 single package.json for one!
