### ISSUE TITLE
Travis Build Tests Repeatedly Fail - `asar-integrity`

### ISSUE THREAD

**Issue by harryparkdotio** [SimulatedGREG/electron-vue#244]
##### Describe the issue / bug.
Every build test run, both the linux and macOS build jobs fail. This is the error which is shown, build tests timeout after 10 minutes.

##### How can I reproduce this problem?
Run travis build tests

<img width="1069" alt="screen shot 2017-06-05 at 11 15 05 am" src="https://cloud.githubusercontent.com/assets/11331772/26767141/5e250d5c-49e0-11e7-8403-b3fcae4455c1.png">

##### Development Environment.
  * Node version: v8.0.0
  * NPM version: v5.0.2
  * Operating System: macOS Sierra 10.12.5

**Comment by SimulatedGREG** [comment]
@harryparkdotio 

Are you code signing? Can you post a link to the build logs? There apparently is a major code signing related change happen in `electron-builder` and `electron`, both involving the new `asar-integrity` check.

Related: https://github.com/electron/electron/pull/9648, https://github.com/electron-userland/electron-builder/releases/tag/v18.4.0

**Comment by harryparkdotio** [comment]
Yes, I ended up running `yarn` locally, which resulted in the same errors. I didn't pick this up locally because I use `npm`, not `yarn`.

So far, I erased my `node_modules/` folder and reinstalled them with `yarn`. I did find that `asar-integrity` was required by `electron-builder`. It seems to be that `asar-integrity` `v0.1.1` isn't availible, or at least only works with `v0.1.0`.

Here is a link to my builds [Mixtape - Travis CI](https://travis-ci.org/harryparkdotio/mixtape). It's failed for the past few. I tried erasing the cache, but no luck.

No, I'm not currently code signing.

**Comment by SimulatedGREG** [comment]
Yeah I just discovered the same issue. The current `electron-builder@18.4.0` is requiring `asar-integrity@0.1.1` which doesn't actually exist on npm, only version `0.1.0` is available. When running `yarn`, apparently this isn't handled properly when you are asked for a version. Looks like 2 separate issues have been exposed.

A quick fix should be locking your `electron-builder` version to `18.3.5`. Did you happen to update that `18.4.0` in any way?

**Comment by develar** [comment]
Fixed, sorry (thanks for early testing (18.4.0 it is next, not stable version yet)).

**Comment by harryparkdotio** [comment]
I believe that `electron-builder` `18.4.0` is a prerelease, but no I didn't update to it, must've been done automatically. I am using the latest release (maximum 2 days old) of `electron-vue`, maybe it's because of that?

**Comment by SimulatedGREG** [comment]
![image](https://cloud.githubusercontent.com/assets/8327811/26773707/14f2a17e-4992-11e7-8ef0-36224d8ff4b1.png)

**Comment by harryparkdotio** [comment]
Let's try running a build test shall we? I'll let you know the results.

**Comment by SimulatedGREG** [comment]
Thank you so much @develar !

@harryparkdotio I'm not sure how the pre-release got installed. Maybe an `npm@5` issue?

**Comment by SimulatedGREG** [comment]
Looks like the builds are moving along fine this time around. What's interesting is that https://www.npmjs.com/package/electron-builder shows `18.3.5` as current release, but running `npm view electron-builder`, version `18.4.0` is available.

![image](https://cloud.githubusercontent.com/assets/8327811/26773872/e2fe7548-4992-11e7-89ef-6a528589ebd7.png)

**Comment by harryparkdotio** [comment]
Maybe, but it don't think that its because of `npm@5`.

<img width="569" alt="screen shot 2017-06-05 at 5 02 56 pm" src="https://cloud.githubusercontent.com/assets/11331772/26773928/db93d810-4a10-11e7-9674-bafb39c5f2ee.png">

Build passed, thanks @SimulatedGREG and @develar!

**Comment by SimulatedGREG** [comment]
Well after all that, time to go checkout out this mixtape application of yours. Glad we got this sorted out. 😀
