### ISSUE TITLE
 Can't resolve 'winreg' when i executed 'npm run build'

### ISSUE THREAD

**Issue by lianshengxing** [SimulatedGREG/electron-vue#245]
excuse me, i ues the 'winreg' module to access the registry, but when i executed the command  'npm run build:win32',it threw an err that 'ERROR in ./app/src/main/index.js
Module not found: Error: Can't resolve 'winreg' in 'E:\wzh-projects\grgzpt\app\src\main'
 @ ./app/src/main/index.js 8:15-32'

i use 'const Registry = require('winreg')' 

could you help me ?

**Comment by SimulatedGREG** [comment]
Were you sure to install `winreg` in the `app/package.json`?

**Comment by lianshengxing** [comment]
i have resolved this problem,but i don not understand that why it can not be used in the 'main/index.js',when i ues it in the renderer process ,it worked well

**Comment by SimulatedGREG** [comment]
Closing since you have stated in another issue that your project has been migrated over to the latest milestone release.
