### ISSUE TITLE
web build requires eslint packages even if eslint wasn't configured

### ISSUE THREAD

**Issue by nest-aka-swan** [SimulatedGREG/electron-vue#247]
There are errors in web build script: Cannot find module
eslint-loader
eslint
etc
I suppose it happens because loader for js/vue files is set to eslint-loader in webpack.web.config.js

To reproduce don't install eslint support during vue init

  * Node version: 6.10.3
  * NPM version: 5.0.2
  * vue-cli version: 2.8.1
  * Operating System: win10

**Comment by SimulatedGREG** [comment]
@nest-aka-swan 

Nice catch. Will push fix later today. Quick fix for now would be to remove the `eslint-loader` from the `webpack.web.config.js` (https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.web.config.js#L20-L30).

**Comment by SimulatedGREG** [comment]
Fixed in https://github.com/SimulatedGREG/electron-vue/commit/df8783b1f1078c411bea388e8ab413803c3f4f4e
