### ISSUE TITLE
can not use '__static' 

### ISSUE THREAD

**Issue by lianshengxing** [SimulatedGREG/electron-vue#248]
when i use 'let fileContents = fs.readFileSync(path.join(__static, '/Grgzpt.exe'), 'utf8')',it threw an error that '__static is not defined'

**Comment by SimulatedGREG** [comment]
@lianshengxing 

The `__static` variable is a very new feature from the last milestone release from just a few days ago. If your project still has a two `package.json` structure with the `app` folder, then your scaffold isn't update to date with the current version.

**Comment by lianshengxing** [comment]
@SimulatedGREG 
so what should i do to updata to the current veision

**Comment by SimulatedGREG** [comment]
https://simulatedgreg.gitbooks.io/electron-vue/content/en/migration-guide.html

This is a good start, but isn't a full proof method. Depending on what you *may* have changed in your project, there could be other items to migrate manually.

**Comment by lianshengxing** [comment]
@SimulatedGREG 
excuse me,i i found two 'src' folders in the project, which one should i change

**Comment by SimulatedGREG** [comment]
This happened because of a `vue-cli` issue where a cached version of the template merges with an updated version.  Make sure your `vue-cli` version is update to date with `npm i -g vue-cli@latest`. 

**Related:** https://github.com/vuejs/vue-cli/pull/450, https://github.com/SimulatedGREG/electron-vue/issues/240

Items such as `app`, `tasks`, and `config.js` no longer exist. Make sure to reference the current template to check for the differences. https://github.com/SimulatedGREG/electron-vue/tree/master/template

**Comment by lianshengxing** [comment]
i use the latest 'electron-vue' project, and when i use 'let fileContents = fs.readFileSync(path.join(__static, '/Grgzpt.exe'), 'utf8')' in the 'main/index.js',it threw an error that 'no such file or directory, open 'C:\Users\wzh-lian\Desktop\my-project\Userswzh-lianDesktopmy-projectstatic\Grgzpt.exe''

**Comment by SimulatedGREG** [comment]
> open 'C:\Users\wzh-lian\Desktop\my-project\Userswzh-lianDesktopmy-projectstatic\Grgzpt.exe''

Not sure what you changed, but this path that was created surely doesn't look right.

**Comment by lianshengxing** [comment]
in the 'main/index.js' ,you give the code that 'if (process.env.NODE_ENV !== 'development') {
  global.__static = path.join(__dirname, '/static')
}',and then i use 'console.log(__static)',when i executed the command that 'npm run dev',the output is 'Userswzh-lianDesktopmy-projectstatic', but when i use 'console.log()__dirname)', the output is 'src/main', could you explain about that

**Comment by SimulatedGREG** [comment]
Related: #101 
Fixed in: https://github.com/SimulatedGREG/electron-vue/commit/37075c80674927888f869710adfcb66ad15bfbe0

In short, `win32` uses `\` backslashes for file paths, but in JS Strings, these will be interpreted as escape delimiters.

**Comment by lianshengxing** [comment]
@SimulatedGREG 
thanks a lot for that,i have changed the project and it worked well.  and then i want to use the 'shell.openItem' to open the 'Grgzpt.exe' in the static folder,how should i write the path

**Comment by SimulatedGREG** [comment]
Assuming `Grgzpt.ext` is in `static/`...

```js
import { shell } from 'electron'
import path from 'path'

shell.openItem(path.join(__static, '/Grgzpt.exe'))
```

**Comment by lianshengxing** [comment]
yes,it worked.but in the latest project,when i executed the command 'npm run build:win32',it threw an err that 'Error: EPERM: operation not permitted, symlink 'C:\Users\wzh-lian\Desktop\my-project\node_modules\._7zip@0.0.6@7zip\' -> 'C:\Users\wzh-lian\AppData\Local\Temp\
electron-packager\win32-x64\test-win32-x64\resources\app\node_modules\7zip''

**Comment by SimulatedGREG** [comment]
> Error: EPERM: operation not permitted, symlink

Looking at the error you posted, it seem you are running into a permission error. Is your terminal running in Administrator mode?

**Comment by lianshengxing** [comment]
You mean that I should run the cmd as Administrator?

**Comment by SimulatedGREG** [comment]
Exactly that.

**Comment by lianshengxing** [comment]
i just can not understand about that,and how to build the project

**Comment by SimulatedGREG** [comment]
Are you able to build a blank project from a fresh and untouched `vue init simulatedgreg/electron-vue my-project`?

**Comment by lianshengxing** [comment]
I uesd 'vue init simulatedgreg/electron-vue my-project' to create a new project ,and then I executed the command 'npm run build:win32',it threw the same error

**Comment by lianshengxing** [comment]
Is this error related to the '7zip'?

**Comment by SimulatedGREG** [comment]
@lianshengxing 

It looks like `7zip` might not have the proper permissions to complete the build step.

Unless your cmd isn't being ran as administrator, (which it should be running as administrator), I don't really know what to tell you about `Error: EPERM: operation not permitted, symlink`. Your system is throwing a permission error and restricting the build process from completing. I know for fact that the build process works on Windows, including ~300 users and AppVeyor CI servers. Another thing to make sure of is that your system has the proper build tools installed (https://simulatedgreg.gitbooks.io/electron-vue/content/en/getting_started.html#a-note-for-windows-users).

Other than fixing the `__static` bug that was discovered earlier in this thread, the rest of this thread does not pertain to an electron-vue issue. Please do not post error outputs without attempting to find solutions online, as **not every** issue or error log directly pertains to electron-vue.
