### ISSUE TITLE
How to use IPC?

### ISSUE THREAD

**Issue by Zyles** [SimulatedGREG/electron-vue#249]
I have spent a few hours but can't get this to work.

Can you give some pointers on how to use IPC with this package?

Basic example:

Running a background process in index.js and want to send the data to a render processes and update the VueJS data in a view.

An example scenario is reading a log file with "tail" or polling on file system, and displaying the log file changes in a window.

Thanks.

**Comment by SimulatedGREG** [comment]
Using the default boilerplate with the initial landing page components, here's an example...

**LandingPage.vue** in a `mounted` hook
```js
mounted () {
  setInterval(() => {
    this.$electron.ipcRenderer.send('ping')
  }, 1000)

  this.$electron.ipcRenderer.on('pong', (event, data) => {
    console.log(data)
  })
}
```

**main/index.js**
```js
ipcMain.on('ping', (event, data) => {
  event.sender.send('pong', Math.random())
})
```

This example will `console.log` the result of `Math.random()` from the `main` process every second in the `renderer` process dev tools.

**Comment by Zyles** [comment]
Thank you, this is really hard stuff.

One step closer.

**Comment by tregismoreira** [comment]
@SimulatedGREG I tried this, but I'm getting the following error:

```
Uncaught TypeError: Cannot read property 'ipcRenderer' of undefined
```

Do you have any idea why?

**Comment by tregismoreira** [comment]
My fault, I left a line out of mounted hook. Sorry :P

**Comment by rafaelpimpa** [comment]
Putting it in the ``beforeCreate()`` hook is better if you're emitting events that are too 'quick', e.g. electron-builder ``autoUpdater`` events.

**Comment by shiva2991** [comment]
Hi when i used this approach with vue router to navigate between two components to and fro renderer listeners are exceeded. Is there any way to listen only once?

**Comment by nickfan** [comment]
> renderer listeners are exceeded

i have the same issue, @shiva2991 have you resolved the problem?

**Comment by chiragshahklc** [comment]
You can either use `mounted` or `beforeCreate` hook. I personally prefer `mounted` hook.
```js
  mounted() {
   this.$electron.ipcRenderer.on("ping", (event, msg) => {
      console.log(msg);
      event.reply("pong", "ping-pong");
    });
  },
  destroyed() {
    this.$electron.ipcRenderer.removeAllListeners();
  }
```

When switching between components using vue-router, `destroyed` hook helps with removing listeners. This will make sure that listeners will not be register multiple times as they have been already de-register before.

**Comment by nickfan** [comment]
@chiragshahklc thx.

**Comment by shiva2991** [comment]
@nickfan sorry for the late reply, I solved that issue by removing all listeners in beforeDestroy() hook method.

**Comment by tvortsa** [comment]
HOW HOW HOW HOW !?!?!?!?!

I can update vue list by ipcRender.on() in vue - single file cimponent !?

**Comment by abhimatta999** [comment]
Is there any way, To listen to messages sent from Main to renderer in Vuex

**Comment by abhimatta** [comment]
> You can either use `mounted` or `beforeCreate` hook. I personally prefer `mounted` hook.
> 
> ```js
>   mounted() {
>    this.$electron.ipcRenderer.on("ping", (event, msg) => {
>       console.log(msg);
>       event.reply("pong", "ping-pong");
>     });
>   },
>   destroyed() {
>     this.$electron.ipcRenderer.removeAllListeners();
>   }
> ```
> 
> When switching between components using vue-router, `destroyed` hook helps with removing listeners. This will make sure that listeners will not be register multiple times as they have been already de-register before.
> 
> For reference
> https://electronjs.org/docs/api/ipc-main
> https://electronjs.org/docs/api/ipc-renderer

Removing removeAllListener() doesn't work for me. I am switching routes and when I'm coming on the component second time, the event is firing multiple times

**Comment by rafalimaz** [comment]
The only solution that worked to me was to use a preload.js file that allows use window.ipcRenderer.send(channel, args...) on vue files.
https://stackoverflow.com/questions/63615355/how-to-import-ipcrenderer-in-vue-js-dirname-is-not-defined
