### ISSUE TITLE
vue-cli · Missing helper: "isEnabled"

### ISSUE THREAD

**Issue by lanbin** [SimulatedGREG/electron-vue#25]
After init, console shows this message

```shell
# lanbin @ lanbindeMBP in ~ [20:47:52] 
$ vue init simulatedgreg/electron-vue teleconverter

? name teleconverter
? author lanbin <mail.com>
   vue-cli · Missing helper: "isEnabled"
```

  * Node version: v6.0.0
  * NPM version: 3.8.6
  * Operating System: MacOS 10.11.6

**Comment by SimulatedGREG** [comment]
@lanbin 

What `vue-cli` version are you currently using? This is a very strange error as the handlebar helper `isEnabled` *should* be available if `vue-cli` was able to successfully download the boilerplate. It would seem you were only asked 2 questions which would mean that the boilerplate never got downloaded properly. Did you have potential network problems at the time?

**Comment by lanbin** [comment]
Hi @SimulatedGREG 

this problem maybe caused by my network situation. 
it's solved when i close my Charles...
