### ISSUE TITLE
How to use printToPDF in electron-vue

### ISSUE THREAD

**Issue by filipeluiz** [SimulatedGREG/electron-vue#254]
Hello,

Can you tell me how to do printToPDF inside a button with components in electron-vue?

**Comment by AkiraLaine** [comment]
Hey @filipeluiz 
Here's the docs related printToPDF (https://electron.atom.io/docs/api/web-contents/#contentsprinttopdfoptions-callback)

**Comment by SimulatedGREG** [comment]
To add onto that, you can get ahold of the current BrowserWindow `webContents` using something like...

```js
import { webContents } from 'electron'

const contents = webContents.getFocusedWebContents()
contents.printToPDF(options, callback)
// Use docs link from @AkiraLaine for more info
```

**Comment by SimulatedGREG** [comment]
Closing for now. Feel free to comment back any further questions.
