### ISSUE TITLE
Lifecycle hooks not executed

### ISSUE THREAD

**Issue by Zyles** [SimulatedGREG/electron-vue#257]
##### Describe the issue / bug.

I have this code in the component:

````
      ready () {
        console.log('Ready done')
      },
      beforeMounted () {
        console.log('Before mounted')
      },

      beforeCreated () {
        console.log('Before created')
      },
      mounted () {
        console.log('Updated')
      },

      activated () {
        console.log('Activated')
      },

      updated () {
        console.log('Updated')
      },

      created () {
        console.log('Created')
      }
````

And none of it gets executed! How can this be?

Neither the CLI or the browser console outputs anything.

##### Tell me about your development environment.
  * Node version: 7.9.0
  * Operating System: Win 10

**Comment by Zyles** [comment]
Never mind figured it out.

**Comment by SimulatedGREG** [comment]
@Zyles 

Looks like you were trying to use lifecycle hooks from both `vue@1` and `vue@2`. Either way, glad you got this sorted out.

**Comment by ShaneParker** [comment]
Please describe what the solution was that worked for you as we are sitting with a similar problem (no vue@1 hooks used).

**Comment by Zyles** [comment]
@ShaneParker I think I put the hooks inside "methods" property, but they need to be outside it.

**Comment by devondahon** [comment]
I have exactly the same problem, none of the lifecycle hooks are executed.

How to fix it ?
