### ISSUE TITLE
Get Base Path

### ISSUE THREAD

**Issue by dannysmc95** [SimulatedGREG/electron-vue#258]
##### Describe the issue / bug.
So my issue is, I want to be able to read/write some config files with Vuex, but I am unable to save files correctly, because in dev they work fine, but once compiled and built into an application it can never find the file?

##### How can I reproduce this problem?
Just use fs.writeFile() to write to a file, and then attempt to read from it once you compile the application?

So my question is in the render process, where can I store data to file? or store sqlite files? I can't seem to import electron in the render process?

##### Tell me about your development environment.
  * Node version: 7.10.0
  * NPM version: 4.2.0
  * Operating System: Mac OS X El Capitan

**Comment by SimulatedGREG** [comment]
@dannysmc95 

A good practice within `electron` application is to save your configuration files to a application data directory. This directory is reserved specifically for this purpose and used only for your application. Make sure to take a look at the [`app.getPath` electron API](https://electron.atom.io/docs/api/app/#appgetpathname). I would personally recommend the `userData` option. Using this API is a reliable way to store configuration files across all platforms.

Related: https://simulatedgreg.gitbooks.io/electron-vue/content/en/savingreading-local-files.html

**Comment by SimulatedGREG** [comment]
In short, avoid saving configurations files to the local application, and use `app.getPath` when possible. This also let's you update your application much easier since the `userData` directory will not be affected.

Closing. Please feel free to comment back any further questions.
