### ISSUE TITLE
jQuery is not defined - Foundation

### ISSUE THREAD

**Issue by marceloavf** [SimulatedGREG/electron-vue#259]
Hi

First of all thank you for this awesome project.

I'm trying to implement foundation scss and js into my project, but i came with some problems,

```
Uncaught ReferenceError: jQuery is not defined
    at Object.<anonymous> (D:\xampp\htdocs\electron-vue\node_modules\foundation-sites\dist\js\foundation.js:386)
    at Object.<anonymous> (D:\xampp\htdocs\electron-vue\node_modules\foundation-sites\dist\js\foundation.js:10208)
    at Module._compile (VM129 module.js:571)
    at Object.Module._extensions..js (VM129 module.js:580)
    at Module.load (VM129 module.js:488)
    at tryModuleLoad (VM129 module.js:447)
    at Function.Module._load (VM129 module.js:439)
    at Module.require (VM129 module.js:498)
    at require (VM130 module.js:20)
    at eval (eval at <anonymous> (renderer.js:981), <anonymous>:1:18)

```

I installed Foundation and jQuery via npm and implement jQuery inside **webpack.renderer.config.js**

```
new webpack.ProvidePlugin({ 
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
   })
```
After that i called Foundation inside **main.js** importint it like that

```
import Vue from 'vue'
import axios from 'axios'

import App from './App'
import router from './router'
import store from './store'

import 'foundation-sites'
```

I've done some tests inside LandingPage.vue with jQuery and it worked propertly, but i get this error with foundation trying to call jQuery.

What can I do?
Thanks!

**Comment by leknoppix** [comment]
To include jquery in a project vuejs, you have to do:
`
import jquery form 'jquery'
`

**Comment by marceloavf** [comment]
`import jquery from 'jquery' `

Doesn't work too with it,
I'm thinking about giving up about jQuery, but most of thinks on the web need it,

I saw that with the config in **webpack.renderer.config.js** my jquery start working inside components, but not with foundation implementation.

**Comment by SimulatedGREG** [comment]
I haven't had enough time at the moment to take a look at this, but there's a Medium article that seems to have a lot to say. https://medium.com/@tommaso.marcelli/setting-up-vue-2-and-foundation-6-3f858b4ad20

**Comment by marceloavf** [comment]
I figure out a way to implement, just call Jquery that way on main.js, not inside webpack.

**Main.js**
```
import jQuery from 'jquery'

window.jQuery = jQuery
window.$ = jQuery
```

then implemented **Foundation 6.4** script direct inside **components**, like:

```
import Foundation from 'foundation-sites'

export default {
  name: 'landing-page',
  components: { SystemInformation },
  methods: {
    open (link) {
      this.$electron.shell.openExternal(link)
    }
  },
  mounted () {
    this.accordion = new Foundation.Accordion($('#accordion'), {
      // These options can be declarative using the data attributes
      slideSpeed: 500,
      multiExpand: true
    })
  },
  destroyed () {
    this.accordion.destroy()
  }
}
```

I don't know if it is correct but it works!

If someone knows another way, with webpack or anything so, because **Foundation 6.4 now have webpack**, but can't make it work.

Thanks!

**Comment by re-fort** [comment]
Does the same error occur even if writing to `webpack.main.config.js` instead of `webpack.render.config.js`?

**Comment by marceloavf** [comment]
@re-fort the error stopped with the changes I made, but now I'm getting some test erros with @import inside scss of Foundation

**Comment by SimulatedGREG** [comment]
Going to close this since it is more/less an issue with `webpack` and `jquery`. Feel free to continue discussions here if needed.
