### ISSUE TITLE
question about vue-router within electron-vue

### ISSUE THREAD

**Issue by Nateyo** [SimulatedGREG/electron-vue#262]
I'm using vuetify as my front-end framework and I have a question about its use with vue router.  In [this](http://jsfiddle.net/yyx990803/xgrjzsup/) example it _appears_ that the content is being is being loaded only within `<router-view></router-view>`.  However, what I think is actually happening is that the route changes, the whole page refreshes, and because of this code at the bottom:

```
const app = new Vue({
  router
}).$mount('#app')
```
it appears that just the content changes.

So my question is, should I define a side-bar component, toolbar component, footer component, etc.  Then with every page I have to include those in the template?  I know this is not an issue with electron-vue, I wish there was a questions tag but I just want to make sure I have the concept down before I get too far along and need to re-write a lot of code.  I assumed a vue-router link would load the template inside of the  router-view tag but it just takes me to a separate page.

Also, thanks for all the work you've done, this is a really great package.

**Comment by Nateyo** [comment]
Apologies, I completely missed router-view was already defined in App.vue.  I should be able to figure it out now.

**Comment by SimulatedGREG** [comment]
Hey @Nateyo 

A good practice with any component library is to treat your routes as just the content for that page. Any other components like a sidebar or navigation can then be added along side your `<router-view/>`. This way you avoid manually importing navigational type components for every page. Take this for example...

**App.vue**
```html
<template>
  <div>
    <sidebar></sidebar>
    <router-view></router-view>
  </div>
</template>
```

Just remember that the `<router-view/>` is just another component, and can be placed where ever you need it to be.
