### ISSUE TITLE
Input stuck on vue init

### ISSUE THREAD

**Issue by Hammster** [SimulatedGREG/electron-vue#265]
`vue init simulatedgreg/electron-vue my-project` does not allow me to enter a description it is simply stuck at the input sequence. The error is reproducable on windows 10 and OSX and did not occure with a diffrent template.

Screenshot:
![unbenannt](https://user-images.githubusercontent.com/1093709/27034759-38d59c66-4f7f-11e7-90f0-e6be59e8ffe7.png)

#### Env
  * Node: 8.1.0
  * NPM: 5.0.3
  * vue-cli: 2.8.2
  * OS: Window 10 and OSX
  * CLI: cmder, terminal, cygwin, mintty

**Comment by Hammster** [comment]
It is a issue with vue-cli after clearing the cache the other template did not load either.

**Comment by eberkund** [comment]
I have the same issue

**Comment by Hammster** [comment]
Hey there @eberkund try it with a newer node version then 8.1.0

**Comment by eberkund** [comment]
Updating to 8.1.2 fixed it for me!
