### ISSUE TITLE
Vuex and vue-router not installed during scaffolding

### ISSUE THREAD

**Issue by swan488** [SimulatedGREG/electron-vue#273]
##### Describe the issue / bug.
\#
I chose Vuex and vue-router when scaffolding, but can't find src/renderer/store or src/renderer/router/, or vuex and vue-router in node_modules after npm install.

##### How can I reproduce this problem?
\#
• vue init simulatedgreg/electron-vue my-project
• select Vuex and vue-router when asked
• npm install after vue init

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: v8.0.0
  * NPM version: 5.0.0
  * vue-cli version: (if necessary) 2.8.2
  * Operating System: OSX 10.11.6

**Comment by SimulatedGREG** [comment]
>  select Vuex and vue-router when asked

You stated that you selected `vuex` and `vue-router` during scaffolding. So my question is, did you actually toggle the option, because all four options are already pre-selected by default. If you were to toggle any of the plugins once, then you would disable that during scaffolding.

**Comment by swan488** [comment]
Hi Greg,

Thanks so much! You are right, I did toggle these options because I thought they were off by default.

Happy to close the issue now! 

Cheers!

Amy

**Comment by swan488** [comment]
Will also upgrade my node version too! Thanks for your information!
