### ISSUE TITLE
Webpack config problem for Windows

### ISSUE THREAD

**Issue by jojobyte** [SimulatedGREG/electron-vue#277]
##### Describe the issue / bug.
The code below causes `__static` to become `C:develectron-vuestatic` when it should be `C:\dev\electron-vue\static`
```js
// File: .electron-vue/webpack.main.config.js
// Line: 66
'__static': `"${path.join(__dirname, '../static')}"`
```

##### How can I reproduce this problem?
Specifically this is being noticed when trying to set a Tray icon to an image in a `static/icons` folder. It's happening in the ready event for the app.
```js
app.on('ready', () => {
  const appIcon = new Tray(path.join(__static, 'icons', 'icon.png'))
})
```

##### Possible Solution (My current solution)
```js
// File: .electron-vue/webpack.main.config.js
if (process.env.NODE_ENV !== 'production') {
  mainConfig.plugins.push(
    new webpack.DefinePlugin({
      // This works exactly as expected
      '__static': JSON.stringify(path.join(__dirname, '../static'))
      // Not tested on OSX / Linux
    })
  )
}
```

##### If visual, provide a screenshot.
![electron_2017-06-18_05-32-01](https://user-images.githubusercontent.com/184880/27260371-a3ba0f46-53e7-11e7-8713-01f6301fb19d.png)

This second error only appears when the first one happens. Most likely not actually related to __static, just running into issues because of the broken __static code

![electron_2017-06-18_05-32-08](https://user-images.githubusercontent.com/184880/27260372-a8c8a786-53e7-11e7-8fa0-316f2b9d8a5f.png)

##### Tell me about your development environment.
  * Node version: v8.1.2
  * NPM version: 5.0.3
  * Operating System: Windows 10

**Comment by SimulatedGREG** [comment]
@jeremycook 

This has actually already been fixed. Just used a simple replace to make sure the slashes are properly escaped. 

Check this commit, https://github.com/SimulatedGREG/electron-vue/commit/37075c80674927888f869710adfcb66ad15bfbe0, for the necessary fixes.
