### ISSUE TITLE
The '__static' dose not work when build a 'app.asar'

### ISSUE THREAD

**Issue by lianshengxing** [SimulatedGREG/electron-vue#279]
Sorry about that,but it really made me wonder. I tried using the '__static' to open a 'grgzpt.exe' in my project.
In the 'build.config.js',if I set 'asar:true',there is a 'app.asar' in the resourse folder after I built the project with 'npm run build:win32', and then i run the application, the 'grgzpt.exe' can not be opened. But if I set 'asar:false',it worked well.
What can I do?
Thanks!

**Comment by SimulatedGREG** [comment]
@lianshengxing 

This is expected behavior in `electron` and is also touched in electron-vue documentation. The native OS cannot read files within an `asar` archive, therefore `grgzpt.exe` cannot be started. In conclusion, it is safe to set `asar: false`, but you will lose small optimizations because of that. Aside from that, there isn't really another workaround.

> Please note that in production all files are packed with `asar` by default as it is highly recommended. Because of this, assets within the `static/` folder can only be accessed within electron since it is aware of this behavior. So if you are planning to distribute files to your users, that can for example open in a external program, you would first need to copy those assets from your application into the user's document space or desktop. From there you could use the `shell.openItem()` electron API to open those assets.

https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-static-assets.html

**Comment by lianshengxing** [comment]
Thanks a lot for that.
When I use the 'electron-builder',which config should i change to build an application for 'win32-ia32' on the '×64' platform

**Comment by lianshengxing** [comment]
Another error when I use the 'electron-builder'

'Error: C:\Users\69063\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe exited with code 1
Output:
Command line defined: "APP_ID=org.simulatedgreg.electron-vue"
Command line defined: "APP_GUID=62e3eecb-e013-549b-8222-3caf500ba8f3"
Command line defined: "PRODUCT_NAME=personal-platform"
Command line defined: "PRODUCT_FILENAME=personal-platform"
Command line defined: "APP_FILENAME=personal-platform"
Command line defined: "APP_DESCRIPTION=An electron-vue project"
Command line defined: "VERSION=0.0.0"
Command line defined: "PROJECT_DIR=D:\lian\�����й���Ŀ\grgzpt-s"
Command line defined: "BUILD_RESOURCES_DIR=D:\lian\�����й���Ŀ\grgzpt-s\build"
Command line defined: "COMPANY_NAME=lshx"
Command line defined: "MUI_ICON=D:\lian\�����й���Ŀ\grgzpt-s\build\icons\icon.ico"
Command line defined: "MUI_UNICON=D:\lian\�����й���Ŀ\grgzpt-s\build\icons\icon.ico"
Command line defined: "APP_64=D:\lian\�����й���Ŀ\grgzpt-s\build\personal-platform-0.0.0-x64.nsis.7z"
Command line defined: "APP_64_NAME=personal-platform-0.0.0-x64.nsis.7z"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "MULTI_LANGUAGE_INSTALLER"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=C:\Users\69063\AppData\Local\Temp\electron-builder-YPJBp7\0-1-uninstaller.exe"
Processing config: C:\Users\69063\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\nsisconf.nsh
Processing script file: "<stdin>" (ACP)

Error output:
!include: could not find: "UAC.nsh"
!include: error in script: "multiUser.nsh" on line 2
Error in script "<stdin>" on line 10 -- aborting creation process'
