### ISSUE TITLE
V 2.0 (next) not working or am I just lacking behind?

### ISSUE THREAD

**Issue by blomdahldaniel** [SimulatedGREG/electron-vue#28]
### First of all, this boilerplate is wonderful! I am so thankful!

But I cannot get the 2.0 (next) version to work. Might be because I am doing some vue 2.0 wrong but I just have to ask.

What I could not get to work was simply the way of setting upp a vuex getter so that I can retreive the stores values. I did an experiment on fresh install on 1.0 and fresh install on (vext).

I changhed the `LandingPageView` in the same way:

```diff
<template>
...
-    <h1>Welcome.</h1>
+    <h1>Welcome. {{ mainCounter }}</h1>
+    <button @click="decrementMain">-</button>
+    <button @click="incrementMain">+</button>
...
</template>
```

```diff
<script>
...
+  import { mainCounter } from '../vuex/getters'
+  import { incrementMain, decrementMain } from '../vuex/actions'

  export default {
    components: {
      CurrentPage,
      Links,
      Versions
    },
+    vuex: {
+      getters: {
+        mainCounter
+      },
+      actions: {
+        incrementMain,
+        decrementMain
+      }
+    },
    name: 'landing-page'
  }
</script>
```

And all i get is:
```
vue.common.js?4eb4:2532[Vue warn]: Property or method "mainCounter" is not defined
on the instance but referenced during render. Make sure to declare reactive 
data properties in the data option. (found in component <landing-page>)
```

Same for incrementMain and decrementMain.

What am I missing?

**Comment by blomdahldaniel** [comment]
Sorry, as I wrote this I understood that there must be a vuex-version-thing.

Looked up [2.0.0-rc.1 release note](https://github.com/vuejs/vuex/releases/tag/v2.0.0-rc.1), [2.0 design discussion thread](https://github.com/vuejs/vuex/issues/236) and [examples on next branch](https://github.com/vuejs/vuex/tree/next/examples).

Sorry!

**Comment by SimulatedGREG** [comment]
@blomdahldaniel 

Was just about to link you, haha! Thanks for the kind words 😊.
