### ISSUE TITLE
Question: building for all OS without picture

### ISSUE THREAD

**Issue by leknoppix** [SimulatedGREG/electron-vue#282]
Hello

First of all forgive me for my bad English.
Then, thank you for this project very powerful and simple to use.

I have two questions.
When I compile with the "npm run build" instruction, I get a windows executable. However the icons and pictures that I have included in the "static" folder do not load. On the other hand, during the test phase, the pictures and icons load. I do not understand.

The second question is whether it is possible to compile the final project to all OS, especially window (32 and 64 bits) and linux. Indeed, when I use the "npm run build" statement, I get only the executable corresponding to my work environment.

Thanks again for this project.

**Comment by lianshengxing** [comment]
@leknoppix 
Excuse me. I am using the 'electron-builder' of 'electron-vue'. I have the same question as yours that I want to build an application for 'ia32' on the 'x64' platform,but I do not know how to change the config.
Lately，I also met errors when I executed 'npm run build',the err as

'Error: C:\Users\69063\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\Bin\makensis.exe exited with code 1
Output:
Command line defined: "APP_ID=org.simulatedgreg.electron-vue"
Command line defined: "APP_GUID=62e3eecb-e013-549b-8222-3caf500ba8f3"
Command line defined: "PRODUCT_NAME=personal-platform"
Command line defined: "PRODUCT_FILENAME=personal-platform"
Command line defined: "APP_FILENAME=personal-platform"
Command line defined: "APP_DESCRIPTION=An electron-vue project"
Command line defined: "VERSION=0.0.0"
Command line defined: "PROJECT_DIR=D:\lian\�����й���Ŀ\grgzpt-s"
Command line defined: "BUILD_RESOURCES_DIR=D:\lian\�����й���Ŀ\grgzpt-s\build"
Command line defined: "COMPANY_NAME=lshx"
Command line defined: "MUI_ICON=D:\lian\�����й���Ŀ\grgzpt-s\build\icons\icon.ico"
Command line defined: "MUI_UNICON=D:\lian\�����й���Ŀ\grgzpt-s\build\icons\icon.ico"
Command line defined: "APP_64=D:\lian\�����й���Ŀ\grgzpt-s\build\personal-platform-0.0.0-x64.nsis.7z"
Command line defined: "APP_64_NAME=personal-platform-0.0.0-x64.nsis.7z"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "MULTI_LANGUAGE_INSTALLER"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=C:\Users\69063\AppData\Local\Temp\electron-builder-YPJBp7\0-1-uninstaller.exe"
Processing config: C:\Users\69063\AppData\Local\electron-builder\cache\nsis\nsis-3.0.1.13\nsisconf.nsh
Processing script file: "" (ACP)

Error output:
!include: could not find: "UAC.nsh"
!include: error in script: "multiUser.nsh" on line 2
Error in script "" on line 10 -- aborting creation process' 
But I have never met that before.

Have any suggestion for me？
Thanks a lot

**Comment by SimulatedGREG** [comment]
@leknoppix 

> When I compile with the "npm run build" instruction, I get a windows executable. However the icons and pictures that I have included in the "static" folder do not load. On the other hand, during the test phase, the pictures and icons load. I do not understand.

I would need to see some more specifics of the project to determine the issue here. If you have a project repo that you could link me to, that would be great. 


> The second question is whether it is possible to compile the final project to all OS, especially window (32 and 64 bits) and linux. Indeed, when I use the "npm run build" statement, I get only the executable corresponding to my work environment.

Based on what you stated, I'm assuming you are using `electron-builder`. So to update what builds are created, you would need to update your build settings found in `package.json`.

**Comment by lianshengxing** [comment]
@SimulatedGREG 
Related to the 'https://github.com/electron-userland/electron-builder/wiki/Options',I found that we can use   macros in the file patterns to update what builds are created. But I am not sure whether it is right.And how to config in the package.json

**Comment by leknoppix** [comment]
Thanks for your response. My project is here: https://framagit.org/leknoppix/MonPlayerRadio

**Comment by SimulatedGREG** [comment]
@leknoppix 

**src/main/index.js**
```js
import path from 'path'

// Line 55
  icon: path.join(__static, '/img/icon.png'),

// Line 104
  const tray = new Tray(path.join(__static, '/img/icons.png'))
```

Other notes...

Like I stated previously to you before, make sure your tray icon is a smaller size if you want to support macOS. The large icon right now overflows.

![image](https://user-images.githubusercontent.com/8327811/27511970-fab60fd0-58e6-11e7-8872-9c4ffa3690cd.png)

As for building for multiple platforms and system architectures, that is better suited to ask in the `electron-builder` documentation or community. That is outside the scope and concern of this boilerplate.

**Comment by leknoppix** [comment]
Hi

Thanks for your return.
Adding "path.join(__static," work for icons of index.js but not for my icons or picture in my css files.
