### ISSUE TITLE
Babili causing issues with certain files in production

### ISSUE THREAD

**Issue by zxc23** [SimulatedGREG/electron-vue#285]
I've been grappling with a problem for several days now, which manifested when I incorporated a number of Electron-Vue updates at once. An exception would be thrown when I ran my app in production, but in dev it was fine.

I finally tracked it down to Babili. The thing is, I use a third-party library which is error-ridden but can't be fixed, however it generally works fine. The old uglifyJS was working fine with it, and if I simply remove the Babili plugin, it works. I can't exclude that particular directory for Babili because it seems like Babili is acting on it only after it's all packed into renderer.js.

Is there a way to keep using Babili but for it to exclude a particular directory? Or should I remove Babili altogether and go back to using uglifyJS like older Electron-Vue?

**Comment by simoebenhida** [comment]
sorry for not answering to your question but i have a question where can i find the index.html file ?

**Comment by zxc23** [comment]
The template for index.html is in src/index.ejs and the production index.html after packing is located in dist/electron/index.html

**Comment by SimulatedGREG** [comment]
@zxc23 

From what I understand, the `babili-webpack-plugin` will run on all production code and can't *ignore* specific files or directories. If you aren't too worried about source code protection, then you can safely keep that plugin removed. If you want to fallback to UglifyJS you will need to add that option into the webpack optimize plugin and also reconfigure `.babelrc` to transpile completely to ES5.

**Comment by zxc23** [comment]
I'll take any source code protection I can get really. So, Uglify looks like the only option to get things working again, and ES5 is fine. Anything else lost by going back to Uglify?

**Comment by SimulatedGREG** [comment]
There really isn't much else lost other than some performance speeds during development that are mainly related to `babel-loader` needing to transpile completely to ES5 as opposed to ES6 features found in `node@7`.

**Comment by zxc23** [comment]
Alrighty, thanks for your help.
