### ISSUE TITLE
[Question] How to import/use Jquery or Materialize js into index.html

### ISSUE THREAD

**Issue by tindecken** [SimulatedGREG/electron-vue#288]
I'm trying to use Materialize script in project, It look webpack will generate file index.html, so how to config for include Jquery

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script><br>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>

Many thanks

**Comment by zxc23** [comment]
Instead of including those CDN script tags, install them both with NPM and import them into your project.

**Comment by tindecken** [comment]
where can i import them? I'm a newbie with Vue and Electron

[https://i.imgur.com/qpa0itF.png](url)

**Comment by zxc23** [comment]
For jquery, after npm installing 'jquery', then in the files where you want to use it, import it like:

```
import $ from 'jquery'
```

You need to leave out the ./ so that it knows to look in node_modules for it.

For materialize, after npm installing it, then in your renderer main.js, have something like:

```
import 'vue-material/dist/vue-material.css'
```

The above is not for materialize, but it's something else that I'm using myself. You'll need to adjust it to match the materialize folder structure. After npm installing it, look inside node_modules and the materialize folder and find the main css file.

**Comment by tindecken** [comment]
Hi, 
The main materialize css file is already included in .vue file
[https://i.imgur.com/mMmtfME.png](https://i.imgur.com/mMmtfME.png)

What i want is including materialize js file into project

Thank you.

**Comment by zxc23** [comment]
I think you can just do `import 'materialize-css'` or `require('materialize-css')` in main.js

**Comment by tindecken** [comment]
After require('materialize-css'), still meet the issue on Develop Tool, no error while running `npm run build`

[https://i.imgur.com/pVh7RCr.png](https://i.imgur.com/pVh7RCr.png)

**Comment by zxc23** [comment]
That error is to do with jquery, not materialize.

You shouldn't be importing jquery in main.js. You need to import it in all of the specific files where you're using it. For example, LandingView.vue, actions.js, or whatever it may be.

**Comment by SimulatedGREG** [comment]
@tindecken 

In short, @zxc23 is recommending to use a UI component library over `materialize` + `jquery`. I would also personally recommend this as importing `jquery` into your project causes a lot of anti-patterns where `vue` and `jquery` fight over how the DOM is handled (#192).

Some great and popular Material Design libraries include [`vue-material`](https://vuematerial.github.io/#/) and [`vuetify`](https://vuetifyjs.com/). And as an extra note, some UI libraries need to be whitelisted in `.electron-vue/webpack.renderer.config.js`, which is [super easy](https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js#L14-L21) to add. I believe `vue-material` might fall into that category.

Going to close this as it isn't a direct issue with electron-vue. The original `jquery` issue is more involved with `webpack`. Feel free to comment back any further questions.
