### ISSUE TITLE
Cannot get transparent window.

### ISSUE THREAD

**Issue by azurinko** [SimulatedGREG/electron-vue#290]
App.vue 

<style>
body {
  background: rgba(0,0,0,0);
}
</style>

in index.js I have set transparent and frameless window.

I still get no transparency? It's my mistake or how is that working?

Help is awesome.

**Comment by SimulatedGREG** [comment]
@azurinko 

Setting `frame: false` and `transparent: true` should be all you need. One thing to know is that if your dev tools are attached to the window transparency will be disabled. Detaching the dev tools to a separate window will fix that.

**Comment by azurinko** [comment]
![screenshot_2](https://user-images.githubusercontent.com/29457341/27593517-a957b288-5b57-11e7-96a9-a218e9fd1592.png)
I wish I could solve it into transperent... also main app.vue wich contains router is body totally transparent...

Offtopic: I wanna make some totally working thing about window frame(so I can have my github nonempty and commit something useful.), I already solved that title bar's title is automatically changed on document.title change, but I cannot find anything on events like minimalization maximalization normalization etc... of a window... I can perform those actions to them, but it's not sufficient, if I call event on a button it doesn't get called if it's maximalized other way.

**Comment by SimulatedGREG** [comment]
The `BrowserWindow` API provides all the events you could possibly need, including those for minimizing and maximizing. https://electron.atom.io/docs/api/browser-window/

Once you get ahold of the current browser window, you can listen to any event since the api extends an `EventEmitter`.

**Get access to current window and listen for `maximize` (renderer process)**
```js
import electron from 'electron'

// https://electron.atom.io/docs/api/browser-window/#browserwindowgetfocusedwindow
const mainWindow = electron.remote.BrowserWindow.getFocusedWindow()

// https://electron.atom.io/docs/api/browser-window/#event-maximize
mainWindow.on('maximize', e => {
  // do something
})
```

Going to close since this is not a direct issue with electron-vue.

**Comment by cat998** [comment]
I have same problem,I tried
'mainWindow.webContents.closeDevTools();' and 'mainWindow.webContents.openDevTools({mode:"detach"});',
set css => 'html, body{ background:  rgba(0,0,0,0)}'，still no transparent.
when i set css => 'html, body{ background:  rgba(0,0,0,0.1)}' , got transparent,but this is not totally transparent, i don't know why...

**Comment by cat998** [comment]
I solved this problem. I use iview and it set body #fff .....

**Comment by lurein** [comment]
After declaring transparency in the BrowserWindow API, add the following code to your vue component to remove the background:

`<style>
html, body{
  background-color: transparent!important;
  border-color: transparent!important;
}
</style>`
