### ISSUE TITLE
Module not found: Error: Can't resolve 'sass-loader'

### ISSUE THREAD

**Issue by tregismoreira** [SimulatedGREG/electron-vue#293]
I've followed the guide for [pre-processors](https://simulatedgreg.gitbooks.io/electron-vue/en/using_pre-processors.html), installed the node modules as requested:

 ```
npm install --save-dev sass-loader node-sass
```

And tried to use it in `/src/renderer/App.vue`:

```
<style lang="sass">

</style>
```

But I got the following error:

```
Alerts
ERROR in ./src/renderer/App.vue
Module not found: Error: Can't resolve 'sass-loader' in '/src/renderer'
 @ ./src/renderer/App.vue 4:2-284
 @ ./src/renderer/main.js
 @ multi ./.electron-vue/dev-client ./src/renderer/main.js
```

Did I miss something?

**Comment by SimulatedGREG** [comment]
@tregismoreira 

If you installed `sass-loader` while `npm run dev` was running, you would need to restart the dev script for `webpack` to see the changes. Other than that, there isn't anything else missing. When installing `node-sass` there is a chance it didn't install properly, so make sure there wasn't any error logs.

**Comment by tregismoreira** [comment]
Great, I tried once again and it worked. Thanks @SimulatedGREG, you are awesome! :)

**Comment by SimulatedGREG** [comment]
No problem.
