### ISSUE TITLE
Update to `webpack@^3`

### ISSUE THREAD

**Issue by SimulatedGREG** [SimulatedGREG/electron-vue#296]
Initial testing shows better performance and faster compile time. Going to wait a little bit more just in case any unknown bugs are resolved.

Also waiting on https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/543

**Comment by develar** [comment]
Done in #310

**Comment by SimulatedGREG** [comment]
Added in https://github.com/SimulatedGREG/electron-vue/commit/0ee26cbc561bce8184e0b9e46524c025328337d0
