### ISSUE TITLE
How to compile other JS files into dist/electron/main.js

### ISSUE THREAD

**Issue by tregismoreira** [SimulatedGREG/electron-vue#297]
I have a few custom js modules/services and I would like them to be compiled into `dist/electron/main.js` but I couldn't find how. I tried to add a new path in the rule `/\.js$/` in `webpack.web.config.js` but didn't work. Can you help me?

**Comment by tregismoreira** [comment]
I managed to do it by importing the service in my code:

`import Debug from 'services/debug'`

Now it's compiled/builded all together.

**Comment by SimulatedGREG** [comment]
Glad you got this sorted out. `import`ing or `require`-ing files like this is how dependencies are used in the nodejs environment.
