### ISSUE TITLE
Quasar?

### ISSUE THREAD

**Issue by Zyles** [SimulatedGREG/electron-vue#298]
Is it possible to get this package to work with [Quasar](https://github.com/quasarframework/)?

It is a material design framework with components for Vue JS.

They have an electron wrapper, but did not like it very much (double node_modules directories and not as fancy console as this boilerplate).

I tried to integrate it unsuccessfully. It seems to require a lot of custom configuration.

Maybe it would be better to make a new repo for this. It would be nice if you had the time to make the same magic on a quasar/electron repo as you did here with the single node_modules directory and colored console, and running one "npm run dev" instead of two "quasar dev" as in their repo.

**Comment by SimulatedGREG** [comment]
@Zyles 

I personally agree that the Quasar Framework doesn't do that great of a job with its `electron` wrapper. Here's what you can do to get it working with electron-vue...

**Scaffold electron-vue**
```bash
vue init simulatedgreg/electron-vue my-project
# select desired options
cd my-project
yarn

# add quasar dependencies
yarn add quasar-framework moment fastclick material-design-icons roboto-fontface
```
**src/renderer/main.js**
```js
import Vue from 'vue'
import axios from 'axios'

import App from './App'
import router from './router'
import store from './store'

import Quasar from 'quasar-framework'
import 'quasar-framework/dist/quasar.mat.css'
Vue.use(Quasar)

if (!process.env.IS_WEB) Vue.use(require('vue-electron'))
Vue.http = Vue.prototype.$http = axios
Vue.config.productionTip = false

Quasar.start(() => {
  /* eslint-disable no-new */
  new Vue({
    components: { App },
    router,
    store,
    template: '<App/>'
  }).$mount('#app')
})
```

From here you can start using `quasar-framework` components in your templates. Hope this helps. Closing since this isn't a direct issue with electron-vue, feel free to comment back any other questions.

**Comment by Zyles** [comment]
Hey again.

Everything seems to be working fine using ````npm install quasar-framework```` but I can't do ````npm install quasar-framework --save```` for some reason. When I save it to the package.json all hell breaks loose and I can't launch the app.

The error in the Chrome console:

````
Uncaught SyntaxError: Unexpected token
C:\...\node_modules\quasar-framework\dist\quasar.esm.js:12860 
export
    at createScript (vm.js:74)
    at Object.runInThisContext (vm.js:116)
    at Module._compile (module.js:533)
    at Object.Module._extensions..js (module.js:580)
    at Module.load (module.js:503)
    at tryModuleLoad (module.js:466)
    at Function.Module._load (module.js:458)
    at Module.require (module.js:513)
    at require (internal/module.js:11)
    at eval (external "quasar-framework"?f874:1)
````

I don't understand what is going on.

Thank you.

**Comment by KevinHolbrookML** [comment]
The above instructions no longer seem to work with Quasar 0.14.
It returns the "Unexpected token" error from webpack trying to load the quasar framework.
Searching, no one seems to have found the solution to integrate these two projects, which is a shame.

**Comment by adelamarre** [comment]
Same error here...

**Comment by lunaeidolon** [comment]
Same error 
Uncaught SyntaxError: Unexpected token import

**Comment by QQchu** [comment]
> Same error
> Uncaught SyntaxError: Unexpected token import

hi,you had Solve the problem?I meeting Same error

**Comment by lunaeidolon** [comment]
> > Same error
> > Uncaught SyntaxError: Unexpected token import
> 
> hi,you had Solve the problem?I meeting Same error

我记得好像是不要用 import 引入，用 require 之类的

**Comment by QQchu** [comment]
> > > Same error
> > > Uncaught SyntaxError: Unexpected token import
> > 
> > 
> > hi,you had Solve the problem?I meeting Same error
> 
> 我记得好像是不要用 import 引入，用 require 之类的

是怎么引用，求指导下，我是electron-vue创建后，vue add quasar  以vue插件的形式安装quasar，安装的时候报 Unexpected token import 运行的时候感觉quasar 的组件已经引入，但是没有产生效果

**Comment by QQchu** [comment]
> require

> > > > Same error
> > > > Uncaught SyntaxError: Unexpected token import
> > > 
> > > 
> > > hi,you had Solve the problem?I meeting Same error
> > 
> > 
> > 我记得好像是不要用 import 引入，用 require 之类的
> 
> 是怎么引用，求指导下，我是electron-vue创建后，vue add quasar 以vue插件的形式安装quasar，安装的时候报 Unexpected token import 运行的时候感觉quasar 的组件已经引入，但是没有产生效果
不对，报错是vue add quasar 默认会去找src目录下的main.js 但是electron-vue目录结构下main.js是在renderer下。。。不知道怎么改变插件的默认关联main.js的位置
