### ISSUE TITLE
why is the app folder still in the least template

### ISSUE THREAD

**Issue by hanfengcan** [SimulatedGREG/electron-vue#299]
Hi ! today I use the least template to create a project, I found the app folder still in my project.

Is it usefull now?

**Comment by SimulatedGREG** [comment]
The `app` folder is no longer used in the latest version of electron-vue. There was a previous `vue-cli` issue that would cache templates and then accidentally merge with a newer version. If you go into your home directory and delete `.vue-templates` that will clear things out. Make sure to update `vue-cli` as well.

**Comment by hanfengcan** [comment]
OK
