### ISSUE TITLE
Webpack configuration

### ISSUE THREAD

**Issue by UnitedPOS** [SimulatedGREG/electron-vue#305]
##### Describe the issue / bug.
Does the latest version of electron-vue  have different webpack bundle package configuration?  My code is running differently in DEV and PRODUCTION environment .

**Comment by SimulatedGREG** [comment]
The `webpack` configs that come with electron-vue have always had different settings based on development and production. Other than using HMR and linting during development, the setup is nearly the same in production. The `webpack` config files are located in the `.electron-vue` directory.

Related: https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html

**Comment by UnitedPOS** [comment]
Thx for the reply.  For Example , the following code 

  let a = new Date();
  let time = +a;
  let d = new Date(a.setHours(a.getHours() - 4));
  let date = d.getFullYear() + "-" + ("0" + (d.getMonth() + 1)).slice(-2) + "-" + ("0" + d.getDate()).slice(-2);

The variable time is correct in DEV  but it is 4 hours before  in PRODUCTION (AFTER BUILD).

I'm trying to figure it out what cause the difference, so i can avoid such mistake.

**Comment by SimulatedGREG** [comment]
@UnitedPOS 

Not entirely sure what is causing the issue for the `time` variable, but I'm fairly confident it doesn't have to do with the provided configurations of `webpack`. There aren't any loaders or plugins that would specifically manipulate source code to produce such an effect. One thing your could try is to comment out the `babili-webpack-plugin` to disable code minification and see if that resolves your issue (https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js#L155-L158).

If disabling Babili fixes your issue, then you would probably want to create an issue over there. Closing as this isn't a direct issue with electron-vue.
