### ISSUE TITLE
 How can I check the error after build

### ISSUE THREAD

**Issue by wenpengfei** [SimulatedGREG/electron-vue#306]
My app is all right in develop mode(npm run dev), But the window is blank in bundle mode(npm run build:win32)

**Comment by wenpengfei** [comment]
I open dist/electron/index.html the console shows errors: 

Uncaught ReferenceError: module is not defined
Uncaught ReferenceError: process is not defined

It seems like it can not get electron context?

**Comment by griest024** [comment]
@wenpengfei how did you fix this?

**Comment by xuange306** [comment]
@wenpengfei 你这个问题是怎么解决的?
