### ISSUE TITLE
I would like to use heatmap in vue electron. How to do it

### ISSUE THREAD

**Issue by zsxgb** [SimulatedGREG/electron-vue#308]
I use import heatmap from 'heatmap.js' and use it in the template
https://github.com/pa7/heatmap.js

Var heatmap = heatmap.h337.create,
This is not the way it is.

Because it will be given
Uncaught TypeError: Can not read property 'create' of undefined

**Comment by SimulatedGREG** [comment]
@zsxgb 

This is not a direct issue with electron-vue, so I will be closing. The documentation is a little misleading, but what you `require`/`import` is `h337`.

**Quick Example Use**
```html
<template>
  <div id="myHeatmap"></div>
</template>

<script>
  import h337 from 'heatmap.js'

  export default {
    name: 'landing-page',
    mounted () {
      let heatmap = h337.create({
        container: document.getElementById('myHeatmap')
      })

      heatmap.setData({
        max: 1,
        data: [{ x: 10, y: 15, value: 5 }]
      })
    }
  }
</script>

<style>
  #myHeatmap {
    height: 200px;
  }
</style>
```
