### ISSUE TITLE
env option for main in .babelrc is ignored on npm run dev

### ISSUE THREAD

**Issue by ibeucaly** [SimulatedGREG/electron-vue#309]
##### Describe the issue / bug.
I want to use an babel plugin for only main process code.
I thought it could be done with env option in .babelrc.

But when run `npm run dev`,
the bundled file for main process seems to be applied babel plugins specified in
not env option for main but that for renderer in .babelrc.

I avoid this problem by writing babel settings in webpack.*.config.js as babel-loader options.

##### How can I reproduce this problem?
This problem can be reproduced by specifying an unknown plugin in env option in .babelrc.
No error occurs on `npm run dev` when an unknown plugin is specified at env.main.plugins as below:
```
"env": {
  "main": {
      "presets": ...,
      "plugins": ["unknown-plugin-name"]
  },
  "renderer": ...
}
```

but errors occur for both main and renderer when it is specified at env.renderer.plugins.

##### If visual, provide a screenshot.
\#
![2017-07-11 0 20 55](https://user-images.githubusercontent.com/8400098/28025920-9d285ed6-65cf-11e7-8ed8-6db76ee9a7b2.png)

##### Tell me about your development environment.
  * Node version: 7.10.0
  * NPM version: 4.2.0
  * Operating System: Mac OSX

**Comment by SimulatedGREG** [comment]
@ibeucaly sorry for late reply.

This seems to be a `babel` issue and the `env` options will be deprecated in the next major release in favor of a JS implementation. At the current moment, you could continue with the manual `webpack` configuration approach or you can manually add the plugins you need to each environment.

Related: #339
