### ISSUE TITLE
SQLite3 doesn't work before refresh in dev mode

### ISSUE THREAD

**Issue by maxkorolev** [SimulatedGREG/electron-vue#315]
Hello, we are trying to make app using electron and mapbox/node-sqlite3. 
* Electron version: 1.7.4
* npm version: 5.0.3
* node version: 8.1.4
* node-sqlite3 version: 3.1.8
* Operating system: Windows 10 x64

We use this [advice](https://discuss.atom.io/t/electron-app-database-file-structure-code-structure/16491/2) and we run all queries in render process
So the problem is that no one sql query works in dev mode, until we refresh page using F5 or ctrl-R  
If you refresh page - everything is fine, but in first loading, right after "npm run dev" has done - sql queries just start executing but then nothing happens.
It happens only on Windows - everything's fine on Mac

```
# Install vue-cli and scaffold boilerplate
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project

# Install dependencies and run your app
cd my-project
npm install
npm run dev
npm install sqlite3 --save
npm run build:dir
npm run dev
```

In render/main.js use this code
```
var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');

db.serialize(function() {
  db.run("CREATE TABLE lorem (info TEXT)");

  var stmt = db.prepare("INSERT INTO lorem VALUES (?)");
  for (var i = 0; i < 10; i++) {
      stmt.run("Ipsum " + i);
  }
  stmt.finalize();

  db.each("SELECT rowid AS id, info FROM lorem", function(err, row) {
      console.log(row.id + ": " + row.info);
  });
});

db.close();

```

**Comment by maxkorolev** [comment]
By the way, everything is fine in production(npm run build) and If you run sqlite query in the main process, it will work too.

**Comment by SimulatedGREG** [comment]
@maxkorolev 

Going to close as this isn't a direct issue with electron-vue. I honestly can't think of any reasons to why this is happening on Windows. I work on macOS, so I won't be able to test this myself. Does this have the same affect if you persist to disk, as opposed to `:memory:`?

**Comment by maxkorolev** [comment]
Thank you for response. Yes it has the same affect with persisting to disk.
At first I wanted to create issue in node-sqlite3 repo, but I tried to reproduce bug with [electron-quick-start](https://github.com/electron/electron-quick-start) and I didn't success - everything works fine.
Btw there is no problem in prod mode
So I guess it's direct issue with electron-vue
I work on macOS too and tested it with VirtualBox. I am not sure but maybe it's because of some features for hot reloading page, unfortunately I don't have time now to debug it.
Well windows developers decided just live with that))
