### ISSUE TITLE
[Feature Request] add Flow support

### ISSUE THREAD

**Issue by chenzhekl** [SimulatedGREG/electron-vue#316]
Adding static type checking to js would be beneficial for large app development.

**Comment by SimulatedGREG** [comment]
@chenzhekl 

To be honest with you, there probably won't be any official Flow support in electron-vue unless `vue` brings greater support in `vue-cli@3` that was mentioned at VUECONF 2017's keynote. I haven't seen any official announcement of that, but I do know `vue` is leading more towards TypeScript. Going to close this for now, but will keep in mind for the future.

Have you tried manually adding this into your project? This article should provide enough direction if you are interested. https://alligator.io/vuejs/components-flow/
