### ISSUE TITLE
require in second electron window doesn't work anymore

### ISSUE THREAD

**Issue by SteveJay7** [SimulatedGREG/electron-vue#318]
Beside the electron window where the Vue projects runs, I tried to open another (hidden) electron window in my project which is based on the electron-vue boilerplate, where I want to run express to respond to some http requests.

I simply added my server.html and server.js in the webpack config using the CopyWebpackPlugin and basically the html and js-script gets loaded in the second electron process/window.

The only problem is, that require statements like ...
var express = require('express')
... result in a "Cannot find module 'express'" error and I don't know why.

I would really appreciate your help regarding a quick fix (maybe I just need to modify the require statements a bit) or a more generic solution where I can add my server.html and server.js also as a kind of second entry point to the whole webpack process of electron-vue (instead of using just CopyWebpackPlugin), so I can simply use import statements like in main.js 

Thanks for your help in advance!

**Comment by SimulatedGREG** [comment]
@SteveJay7 

Based on what you told me, I think I might know the issue. If you are loading the `server.html` files over the `webpack-dev-server`, then this is expected `electron` behavior. When a `BrowserWindow` is loaded with `https?`the `node_modules` path needed for `require` to function normally are not injected and need to been set manually. If you take a look at [`src/index.ejs`](https://github.com/SimulatedGREG/electron-vue/blob/master/template/src/index.ejs#L9), you'll see where this is done. In this case I'm passing a file path from `html-webpack-plugin` ([here](https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js#L115)) to my `node_modules`.

**Comment by SteveJay7** [comment]
thanks a lot!

I turned my server.html into a server.ejs, used also the html-webpack-plugin with the node-modules path instead of the copy-webpack-plugin and copied the mentioned lines from index.ejs.

now the modules are found... but renderer.js is also injected now into my server.html (server.ejs).
I thought that maybe the vue-html-loader does that and excluded server.html from the processing of .html files, but still the renderer.js is injected.

Do you know how I can prevent this injection?

**Comment by SimulatedGREG** [comment]
@SteveJay7 

As per `html-webpack-plugin`'s documentation, you can configure which `webpack` chunks to include (or exclude).

https://github.com/jantimon/html-webpack-plugin#filtering-chunks

**Comment by SteveJay7** [comment]
thanks! that did it :-)
