### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Steviey** [SimulatedGREG/electron-vue#32]
Module not found: Error: Cannot resolve module 'vue'
[...]
Multiple loading errors on Win 7/Electron 1.3.5 makes it pretty much useless. Sorry.

**Comment by SimulatedGREG** [comment]
It sounds like `npm install` didn't run properly inside the `app` directory. I can only assume so much based on the little information you provided. Could you please provide the info that was asked in the issue template?
