### ISSUE TITLE
electron-vue Report errors

### ISSUE THREAD

**Issue by okwangyu** [SimulatedGREG/electron-vue#320]
cnpm Can't find
Error: GET https://npm.taobao.org/mirrors/electron/1.7.5/SHASUMS256.txt returned 404
F:\vue\xiaopeng\node_modules\_electron@1.7.5@electron\install.js:48

npm cannot connect
Can you change it to 1.7.4?

**Comment by SimulatedGREG** [comment]
@okwangyu 

You can manually set the `electron` version within the `package.json` or using `cnpm i --save-dev electron@1.7.4`.
