### ISSUE TITLE
problem with using assets path in data binding

### ISSUE THREAD

**Issue by SteveJay7** [SimulatedGREG/electron-vue#321]
If I use the computed assets path in static src attributes of image tags, it works well:
<img src="~@/assets/img/logo.png">

but if I use it in vue data bindings, it can't resolve the path:
<img :src="'~@/assets/img/icon_' + module + '.png'">

putting them into the static folder would work...
<img :src="'static/img/icon_' + module + '.png'">

... but to keep copies of all images in assets and static folder is not a nice option.
then I thought of using the static folder only, but I haven't figured out how to use the static folder in css rules in the style block of a vue component file.

Does anyone know a solution?
Would appreciate it very much!

**Comment by SimulatedGREG** [comment]
@SteveJay7 

This is more/less a limitation with `vue-loader`, as it will only process images from either inlined `<img src>`or from a CSS `url()`. Anything else, like `<img :src="myPathVar">`, that is computed at run-time will not be handled by `webpack`. So the only option left at this point is to use the `static/` folder.
