### ISSUE TITLE
Crash with vue-loader@13

### ISSUE THREAD

**Issue by cawa-93** [SimulatedGREG/electron-vue#323]
After compile with `vue-loader@13.0.2` get error `Failed to mount component: template or render function not defined`

**Comment by develar** [comment]
@cawa-93 As in my patch, use dynamic import and not `require` in your router code to include components. Because new version of vue-loader expect ES2015 imports.

**Comment by develar** [comment]
See https://github.com/vuejs/vue-loader/releases/tag/v13.0.0 "Breaking Changes" for details.
