### ISSUE TITLE
How can I create a custom Vue filter?

### ISSUE THREAD

**Issue by tregismoreira** [SimulatedGREG/electron-vue#326]
I'm trying to figure out how to create a custom Vue filter in this boilerplate, but I couldn't do it. Can anybody help me?

Thanks in advance.

**Comment by mackmm145** [comment]
i don't think it's any different than without this boilerplate. for a global filter, create it before instancing.
```javascript
Vue.filter('wrapIt', function(val, before, after) { return before + val + after})

/* eslint-disable no-new */
new Vue({
  components: {
    App
  },
  router,
  store,
  template: '<App/>'
}).$mount('#app')
```

&nbsp;&nbsp;

**Comment by tregismoreira** [comment]
Nice, thanks for the detailed reply! :)
