### ISSUE TITLE
Update to vue 2.4.2

### ISSUE THREAD

**Issue by EmadAdly** [SimulatedGREG/electron-vue#327]
@SimulatedGREG

why not update to latest vue version and electron: 1.6.*

Thanks

**Comment by SimulatedGREG** [comment]
@EmadAdly 

It is not necessary to keep all dependencies up-to-date when they are still on the same *major* version. In short, `vue@^2.3.3` will install `vue` at the latest update of 2.0, which currently is 2.4.2. Learn more about caret ranges here https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004.

**Comment by EmadAdly** [comment]
@SimulatedGREG 

I have some problems with other dependencies on our apps when working on the version `vue@^2.3.3` but it solved those with the `vue@^2.4.2`

It is not reasonable to ignore both `minor` , `patch` when the `major` not enough 

Finally If you have time, please consider it
