### ISSUE TITLE
getting some errors when install

### ISSUE THREAD

**Issue by brody182** [SimulatedGREG/electron-vue#33]
##### Describe the issue / bug.
\#

getting err message when running install

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/brodyr/Documents/Sites/smart-lock/node_modules/nslog
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

##### How can I reproduce this problem?

# Install vue-cli and scaffold boilerplate
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project

# Install dependencies and run your app
cd my-project
npm install
npm run dev

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:  4.5.0
  * NPM version: 3.10.8
  * vue-cli version: (if necessary)
  * Operating System: macos

**Comment by SimulatedGREG** [comment]
@brody182 

You need to update your node version to 5 or higher (I'd recommend going to 6 for performance), as some dependencies and scripts rely on specific ES2015 features. If you need to have multiple version on node on hand I'd recommend using [`nvm`](http://nvm.sh).
