### ISSUE TITLE
Window Not Closing Correctly

### ISSUE THREAD

**Issue by iamazik** [SimulatedGREG/electron-vue#331]
##### Describe the issue / bug.
Whenever wanting to close the window, the window get closed but a blank window appears after.

##### How can I reproduce this problem?
I am able to reproduce the issue on a fresh Electron-Vue project without modifying anything on my MacBook Pro. Here's my machine configuration:

- OS: macOS Sierra v10.12.6 (16G29)
- Mode: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
- Processor: 2.9 GHz Intel Core i5

##### If visual, provide a screenshot.
I've attached a quick screen record to describe the issue better.
[window-not-closing.zip](https://github.com/SimulatedGREG/electron-vue/files/1184198/window-not-closing.zip)

##### Tell me about your development environment.
  * Node version: v8.2.1
  * NPM version: v5.3.0
  * vue-cli version: v2.8.2
  * Operating System: macOS Sierra

**Comment by SimulatedGREG** [comment]
@iamazik 

I'm not entirely sure what is causing this to happen, and I'm unable to reproduce. Aside from what electron-vue provides in this boilerplate, this seems more related to `electron` itself as the simple action of closing a window has nothing to do with `webpack` or any related setup.

**Comment by iamazik** [comment]
Yeah, I'm not sure either. This issue only occurs on my MacBook Pro but doesn't occur on my Mac Mini 2014 late model. So, considering this issue to be closed.
