### ISSUE TITLE
read version from package.json

### ISSUE THREAD

**Issue by webrtcn** [SimulatedGREG/electron-vue#332]
I want to get version from package.json

I use  

> 
const version = require(**path**).version; 

Who know this path?

**Comment by develar** [comment]
https://github.com/electron/electron/issues/7085

**Comment by webrtcn** [comment]
@develar thank you for you replay.
I find way like this
`
import {version} from '../../../package.json';

export default class loadingService extends ILoading {
    
    constructor() {
        super();
    }

    async getVersion() { 
        return version;
    }
}
`

**Comment by develar** [comment]
I recommend you to use `app.getVersion()` if you only need to get app version.
