### ISSUE TITLE
How do I create a new form and jump to the appropriate page?

### ISSUE THREAD

**Issue by okwangyu** [SimulatedGREG/electron-vue#333]
How to create a new form and jump to the corresponding page by routing, because I found that HTML5 history mode cannot be used when using vue-router. So when you create a new window, you need the index.html page and ask for a solution

**Comment by SimulatedGREG** [comment]
@okwangyu 

This is a question better suited for the Vue.js community and documentation. But what you are probably looking for is [**Programmatic Navigation**](https://router.vuejs.org/en/essentials/navigation.html). If you use Discord, then make sure to check out the official Vue.js Discord server. It has a tone of channels and many people are always around to help answer any questions you may have. (https://discordapp.com/invite/HBherRA)
