### ISSUE TITLE
yarn run build in Builder and Packager get the different, and Packager get nothing

### ISSUE THREAD

**Issue by yangjianhua** [SimulatedGREG/electron-vue#338]
##### Describe the issue / bug.
\#
I have this two project using the same code,  just one use electron-builder and the other use electron-packager to build a Mac executable file.

In Packager: yarn(npm) run build:darwin
In Builder:  yarn(npm) run build

All get the result, but the first runs and get empty (totally nothing), and the second get the correct result(in my case is the Login page)

##### How can I reproduce this problem?
\#
1. npm run build: darwin   in Packager;
2. npm run build in Builder

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:8.2.1
  * NPM version:5.3
  * vue-cli version: (if necessary)
  * Operating System:Mac Sierra

**Comment by SimulatedGREG** [comment]
@yangjianhua 

This is more than likely an internal dependency management issue happening within `electron-packager`'s build step. I would strongly recommend moving forward with `electron-builder` and using a [CI server](https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-electron-builder.html#automated-deployments-using-ci) to build for all your targeted platforms. 

Related: #348

**Comment by SimulatedGREG** [comment]
@yangjianhua 

After further investigation, this is a `npm` related issue with the `--prune` flag. 

https://github.com/npm/npm/issues/17781
