### ISSUE TITLE
vue class component & decorators

### ISSUE THREAD

**Issue by kwoosh** [SimulatedGREG/electron-vue#339]
I tryed to change my way of development by using [vue-class-component](https://github.com/vuejs/vue-class-component), but electron-vue bothers me... 
I installed **vue-class-component**, and tryed it

```vue 
<script>
import Vue from 'vue'
import Component from 'vue-class-component'

@Component({
  props: {
   
  }
})
export default class App extends Vue {
  // some data
  msg = 'Hello'
}
</script>
````
and i got this error

![eve](https://user-images.githubusercontent.com/30318777/28924808-99fc2428-786b-11e7-9e7a-926419ad68cc.png)

Folowing the error instruction i installed [babel-plugin-transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) 
like this - ``` yarn add babel-plugin-transform-decorators-legacy -D  ```
and added a ```"transform-decorators-legacy"``` to ```"plugins"``` in my _.babelrc_ file

![babel](https://user-images.githubusercontent.com/30318777/28924920-fcb9c3d6-786b-11e7-928f-1a2039b45b12.png)

And after, my app stopped working, or i get same error, or i just see my directory instead(((
Past 3 hours i tryed to slove it, but w/out results... May be you can show my mistake, or way to fix it) And it would be greate if u make backward compatibility.

**Comment by SimulatedGREG** [comment]
@kwoosh sorry for the late reply.

It seems that there is a potential bug with `.babelrc` files applying *global* plugins to defined environments. A quick fix would be to add the plugin within the `renderer` environment. Luckily in the next major release of `babel` there will be the ability to define your configurations in JS.

```json
    "renderer": {
      "presets": [
        ["env", {
          "modules": false
        }],
        "stage-0"
      ],
      "plugins": ["transform-decorators-legacy"]
    },
```
