### ISSUE TITLE
Questions about building

### ISSUE THREAD

**Issue by bryantchan** [SimulatedGREG/electron-vue#34]
##### Describe the issue / bug.
- The final build file is too large. I try to make a build from a blank boilerplate and the size turns out to be like over 100mb. 
- I made a build for my app, it's ok to work with me on my own computer but reported errors while on others. Is there anything I missed during the building process?

##### Tell me about your development environment.
  * Node version: v5.3.0
  * NPM version: 3.3.12
  * vue-cli version: 2.1.0
  * Operating System: 10.12.1 Beta

Thank you!

**Comment by SimulatedGREG** [comment]
@bryantchan 

> The final build file is too large. I try to make a build from a blank boilerplate and the size turns out to be like over 100mb.

Unfortunately, yes it is. But this is more related to `electron` itself, as a blank app is roughly around ~109mb (Just downloading a [ZIP'd release](https://github.com/electron/electron/releases/tag/v1.3.7) is around ~40mb). This file size is somewhat large as `electron` does a lot more than you might think. It not only carries the Chromium V8 JavaScript engine, it has native APIs for each OS, and supports a portable version of Node.js. In my opinion ~109mb is rather small when you think about everything it has ready for you. 

electron-vue does its best to minimize final production builds by taking advantage of webpack and ignoring `node_modules`. If you compare your final `app/dist` directory size (after building), you can see just how big your actual app is. Thanks to webpack, some of my biggest apps made have never been over 28mb, and that's **with** all assets like images & fonts. 

> I made a build for my app, it's ok to work with me on my own computer but reported errors while on others. Is there anything I missed during the building process?

You probably didn't miss anything "during the building process", but this just falls into the category of having to test your app. There's nothing extra in the `electron-packager` configuration that would produce better results.  A good word to follow by is to "never assume a user has something already installed". One common item I see people assume is having specific fonts available to them. I'm not saying that's your case, but it's just an example.

Hope this helps. 😊

**Comment by bryantchan** [comment]
@SimulatedGREG thank you!
