### ISSUE TITLE
insp is not a function

### ISSUE THREAD

**Issue by yangwao** [SimulatedGREG/electron-vue#342]
![image](https://user-images.githubusercontent.com/5887929/29004935-aaf7b762-7ad0-11e7-8839-41a9bbc57997.png)

##### How can I reproduce this problem?
⫸  vue init simulatedgreg/electron-vue my-electron

? Application Name my-electron
? Project description An electron-vue project
? Select which Vue plugins to install axios, vue-electron, vue-router, vuex
? Use linting with ESLint? No
? Setup unit testing with Karma + Mocha? No
? Setup end-to-end testing with Spectron + Mocha? No
? What build tool would you like to use? builder
? author Matej Nemcek <ybdaba@gmail.com>

   vue-cli · Generated "my-electron".

  $ cd my-electron
  $ yarn (or `npm install`)
  $ yarn run dev (or `npm run dev`)

cd my-electron/
npm i
npm run dev

close inspector and try reopen it

##### Tell me about your development environment.
  * Node version: 
v7.10.1
  * NPM version:
4.2.0
  * vue-cli version: 
2.8.2
  * Operating System:
16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by yangwao** [comment]
it was electron-debug, with electron@1.3.0 it works

**Comment by Ttou** [comment]
same problem

**Comment by alonsoavotz** [comment]
same problem here..
 but in my package.json i have "electron-debug": "^1.1.0". My Operating System: Windows 10

**Comment by parro-it** [comment]
Hi, [electron-localshortcut](https://github.com/parro-it/electron-localshortcut) author here. We trace down the problem to my package, so I removed my dependency on `insp` as a workaround.

Could you retry and check if it solve your issue?  You should have [electron-localshortcut](https://github.com/parro-it/electron-localshortcut) version 3.0.2 installed as you retry...

**Comment by ScorpioX** [comment]
@parro-it The issue is gone after installing electron-shortcut, a million thanks! :)

**Comment by parro-it** [comment]
@ScorpioX you're welcome, thank you to check it instantly!

**Comment by SlightG** [comment]
@parro-it I've tried to use electron-localshortcut 3.0.2. But this time it says 

>TypeError: equals is not a function
    at WebContents.<anonymous> (/home/me/my-project/dist/electron/main.js:3928:7)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

The same issue occurred in both Windows 10 and Ubuntu 16.04.

**Comment by parro-it** [comment]
Please follow further progress [here](https://github.com/parro-it/electron-localshortcut/issues/38)

**Comment by parro-it** [comment]
Should be solved now, could you please remove node_modules folder and retry?

**Comment by SlightG** [comment]
Thanks, it works.

**Comment by alonsoavotz** [comment]
Yes,  it works.

**Comment by yangwao** [comment]
Works. Thanks! 🤗
```
⫸  npm ls --depth 0
my-electron@0.0.0 /Users/wao/Lab/my-electron
├── axios@0.16.2
├── babel-core@6.25.0
├── babel-loader@7.1.1
├── babel-plugin-transform-runtime@6.23.0
├── babel-preset-env@1.6.0
├── babel-preset-stage-0@6.24.1
├── babel-register@6.24.1
├── babili-webpack-plugin@0.1.2
├── cfonts@1.1.3
├── chalk@1.1.3
├── copy-webpack-plugin@4.0.1
├── cross-env@5.0.4
├── css-loader@0.28.4
├── del@2.2.2
├── devtron@1.4.0
├── electron@1.7.5
├── electron-builder@19.19.1
├── electron-debug@1.4.0
├── electron-devtools-installer@2.2.0
├── extract-text-webpack-plugin@2.1.2
├── file-loader@0.11.2
├── html-webpack-plugin@2.30.1
├── json-loader@0.5.7
├── multispinner@0.2.1
├── style-loader@0.18.2
├── url-loader@0.5.9
├── vue@2.4.2
├── vue-electron@1.0.6
├── vue-html-loader@1.2.4
├── vue-loader@12.2.2
├── vue-router@2.7.0
├── vue-style-loader@3.0.1
├── vue-template-compiler@2.4.2
├── vuex@2.3.1
├── webpack@2.7.0
├── webpack-dev-server@2.6.1
└── webpack-hot-middleware@2.18.2
```

**Comment by parro-it** [comment]
🍾
