### ISSUE TITLE
Material Design icons are not included in the build

### ISSUE THREAD

**Issue by jmeinke** [SimulatedGREG/electron-vue#343]
We use [Vue Material](http://vuematerial.io/#/) in combination with the [Material Design Icons](https://www.npmjs.com/package/material-design-icons) node package. However, after building the electron-vue project using `npm run build` only placeholder texts are shown instead of icon images.

![notworking](https://user-images.githubusercontent.com/941555/29021184-f4e0805e-7b64-11e7-91b0-6165ae7ecc21.png)

The icons are shown correctly as long as  `npm dev run` is used.

![working](https://user-images.githubusercontent.com/941555/29021197-fa91fff0-7b64-11e7-81a9-e91fcc9f7eef.png)

  * Node v8.1.2
  * NPM v5.0.3

How can we include the icons from the Material Design node module into the build?

**Comment by SimulatedGREG** [comment]
@jmeinke 

I would highly discourage using the `material-design-icons` package directly. It contains not only the font files needed for the icons, but also includes just about everything else that you don't need (like source files for iOS, Android, etc). This package was never intended to be used directly. When installing `material-design-icons` into your application you are bloating your final build size with an additional ~52 MB, which will also slow down your build time tremendously.

The *recommended* way of adding the icons to your application is to use the Google Font API by adding the following in your `src/index.ejs`.
```html
<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
```

To answer your question, it may depend on how you are importing the icons. In my testing, the below seems to work fine in both development and production.

```html
<style>
  @import "~material-design-icons/iconfont/material-icons.css";
</style>
```

---

#### Final Build Size Comparison (macOS, uncompressed)
`284.8 MB` - using `material-design-icons`
`232.5 MB` - using the Google Font API

**Comment by jmeinke** [comment]
Thanks a lot for your comprehensive response! 

We have used the solution you suggested (by adding a link to `src/index.ejs`) and now all the icons are shown. I've also removed 'roboto-fontface' from our node modules and readded it as a link like the icons.

This can be closed :+1:
