### ISSUE TITLE
【HELP】Please help me use node-ffi in electron-vue

### ISSUE THREAD

**Issue by webees** [SimulatedGREG/electron-vue#344]
# In the main process

  Error: Could not locate the bindings file. Tried:
   → X:\git\electron_vue\build\binding.node
   → X:\git\electron_vue\build\Debug\binding.node
   → X:\git\electron_vue\build\Release\binding.node
   → X:\git\electron_vue\out\Debug\binding.node
   → X:\git\electron_vue\Debug\binding.node
   → X:\git\electron_vue\Debug\binding.node
   → X:\git\electron_vue\out\Release\binding.node
   → X:\git\electron_vue\Release\binding.node
   → X:\git\electron_vue\build\default\binding.node
   → X:\git\electron_vue\compiled\7.9.0\win32\ia32\binding.node
      at bindings (X:\git\electron_vue\dist\electron\main.js:5743:9)
      at Object.<anonymous> (X:\git\electron_vue\dist\electron\main.js:106:51)
      at __webpack_require__ (X:\git\electron_vue\dist\electron\main.js:21:30)
      at Object.<anonymous> (X:\git\electron_vue\dist\electron\main.js:7263:11)
      at __webpack_require__ (X:\git\electron_vue\dist\electron\main.js:21:30)
      at Object.module.exports.module.exports (X:\git\electron_vue\dist\electron\main.js:5399:11)
      at __webpack_require__ (X:\git\electron_vue\dist\electron\main.js:21:30)
      at Object.<anonymous> (X:\git\electron_vue\dist\electron\main.js:2956:70)
      at Object.module.exports.webpackEmptyContext.keys (X:\git\electron_vue\dist\electron\main.js:3081:30)
      at __webpack_require__ (X:\git\electron_vue\dist\electron\main.js:21:30)

# reproduce this problem

> npm install --global --production windows-build-tools
> npm install -g node-gyp
> npm install ffi --save-dev
> cd node_modules\ffi && node-gyp rebuild (Omit configuration)
> cd node_modules\ref&& node-gyp rebuild (Omit configuration)

**src/main/index.js** Added:

`const ffi = require('ffi')`

# development environment.
  * Node version: v6.11.1
  * NPM version: v5.3.0
  * Operating System: windows10 x64

# *If I do that, then it can work*

**src/renderer/main.js** Added:

```
    /* eslint-disable */
    const ffi = global.require('ffi')
    import Path from 'path'
    let lib = ffi.Library(Path.join(__static, '/dll/Test_x86.dll'), {
        'Add': ['int', ['int', 'int']]
    })
    console.log(lib.Add(5, 5))
    /* eslint-enable */
```

> npm run dev

How do I add **node-ffi** to the main process? This question bothers me for three days. please help me.

**Comment by SimulatedGREG** [comment]
@webees 

The `ffi` is a native node module and needs to built properly against `electron`. We can do that easily with `electron-rebuild`.

```bash
yarn add ffi
yarn add -D electron-rebuild
.\node_modules\.bin\electron-rebuild.cmd
yarn dev
```

**Comment by webees** [comment]
@SimulatedGREG 

Thanks! but, I promise I've tried it. Is there anything else? look that:

src/main/index.js **Just** added:

`const ffi = require('ffi')`

![_20170812003448](https://user-images.githubusercontent.com/5155291/29222735-578c6ef4-7ef6-11e7-924d-f20b509567a4.png)

**Comment by webees** [comment]
solved! Need to add ffi to dependencies in package.json file!

**Comment by Venryx** [comment]
[Just a note for others coming across this thread]

If you're using Webpack, you also have to add ffi/ref as "externals", as I found out here: https://github.com/electron/electron/issues/17745#issuecomment-511115877
