### ISSUE TITLE
static assets in child router not support.

### ISSUE THREAD

**Issue by webrtcn** [SimulatedGREG/electron-vue#345]
I use
`<template>
    <div class="logo">
        <img src="./assets/logo.png">
    </div>
</template>
`

But I got a error 

> logo.png:1 GET http://localhost:9080/src/renderer/router/AccountPages/imgs/logo.png 404 (Not Found)

The render is 
` <div class="logo"><img src="imgs/logo.png"></div>`

**Comment by webrtcn** [comment]
`<template>
    <div class="logo">
        <img :src="logoImage">
    </div>
</template> 
<script>
    import logoScr from './assets/logo.png';
    export default {
        data () {
            return {
                logoImage: `/${logoScr}`
            }
        },
        created() {  
        
        }
    }
</script>

<style>
    .logo {
        width: 100%;
        height: 280px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>`

**Comment by SimulatedGREG** [comment]
@webrtcn 

Please refer to the following links to better understand how `vue-loader` handles these assets.

* `vue-loader` docs: https://vue-loader.vuejs.org/en/configurations/asset-url.html
* example usage with `~@` prefix: https://github.com/SimulatedGREG/electron-vue/blob/master/template/src/renderer/components/LandingPage.vue#L3

**Comment by webrtcn** [comment]
@SimulatedGREG 

Thanks a lot
