### ISSUE TITLE
Uncaught Exception: TypeError: equals is not a function at WebContents.

### ISSUE THREAD

**Issue by timenengwerda** [SimulatedGREG/electron-vue#346]
##### Describe the issue / bug.
Every time I start my dev environment(`npm run dev`) and the Electron app launches I get an alert whenever I touch a random button:
`Uncaught Exception:
TypeError: equals is not a function
    at WebContents.<anonymous> (/Users/xxx/Sites/xxx/dist/electron/main.js:4063:7)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)`
And I can't, for the life of me, find out how the alert snuck in. I've tried cleaning up my main/index.js to make it as barebone as possible but I still get this alert.

Here's line 4054 to 4070:
```
const _onBeforeInput = shortcutsOfWindow => (e, input) => {
	if (input.type === 'keyUp') {
		return;
	}

	const event = _normalizeEvent(input);

	debug(`before-input-event: ${input} is translated to: ${event}`);
	for (const {eventStamp, callback} of shortcutsOfWindow) {
		if (equals(eventStamp, event)) { // this is line 4063
			debug(`eventStamp: ${eventStamp} match`);
			callback();
			return;
		}
		debug(`eventStamp: ${eventStamp} no match`);
	}
};
```

##### How can I reproduce this problem?
I'm actually not sure. I did add some dependencies to my Package.json; but even w/o using said packages in my index.js I still get this error.
The dependencies I have are:
```
    "axios": "^0.16.1",
    "electron-json-storage": "^3.0.7",
    "electron-log": "^2.2.7",
    "electron-updater": "^2.8.2",
    "vue": "^2.3.3",
    "vue-electron": "^1.0.6",
    "vue-router": "^2.5.3",
    "vuex": "^2.3.1"
```

##### Tell me about your development environment.
  * Node version: 6.9.2
  * NPM version: 3.10.9
  * Operating System: MacOS Sierra 10.12.6

**Comment by timenengwerda** [comment]
Managed to 'fix' it by not using devtron's devtools. Not really a fix, so it's most likely my way out of date node. But for now I'm happy to leave Devtron behind

**Comment by develar** [comment]
Please see #342

Please `yarn upgrade`. Or, if you still use npm, remove node_modules and instal again.
