### ISSUE TITLE
Cannot fond module "is-buffer"

### ISSUE THREAD

**Issue by walid1992** [SimulatedGREG/electron-vue#350]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\# Failed to run after packaging, prompt for the Cannot fond module "is-buffer"

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\# 
<img width="997" alt="default" src="https://user-images.githubusercontent.com/16499191/29102703-92f647d6-7ced-11e7-9b06-1505404c6c8a.png">

##### Tell me about your development environment.
  * Node version: v8.2.1
  * NPM version:5.3.0
  * vue-cli version: (if necessary)
  * Operating System: mac

**Comment by SimulatedGREG** [comment]
@walid1992 

There is a current bug within `npm@5.3.0` during the build step, specifically with the `--prune` option for handling dependencies. See #348 for more information.

**Comment by leer168** [comment]
How to fix it? Thank you!
