### ISSUE TITLE
Why "node-loader" is not in dev-dependancies

### ISSUE THREAD

**Issue by popod** [SimulatedGREG/electron-vue#351]
Why "node-loader" is not in dev-dependancies ? In my project, when I run karma unit, I got this error:

```
ERROR in ./app/node_modules/keytar-prebuild/lib/keytar.js
Module not found: Error: Can't resolve 'node-loader' in '/rootPath'
 @ ./app/node_modules/keytar-prebuild/lib/keytar.js 1:13-52
 @ ./app/src/renderer/routes.js
 @ ./app/src/renderer ^\.\/(?!main(\.js)?$)
 @ ./test/unit/index.js
```

In fact, this was because node-loader was not installed... Why ? It seems that it is used by default by webpack..

**Comment by develar** [comment]
Hmmm.... Indeed, strange. The same bug in the electron-webpack.

**Comment by SimulatedGREG** [comment]
@popod 

I'm not entirely sure where this got lost. `node-loader` was once in this boilerplate, but seems to have been removed by mistake. Will re-add back in an upcoming update.

**Comment by SimulatedGREG** [comment]
Fixed in https://github.com/SimulatedGREG/electron-vue/commit/0ee26cbc561bce8184e0b9e46524c025328337d0
