### ISSUE TITLE
SCSS loader in testing environment

### ISSUE THREAD

**Issue by pmccarren** [SimulatedGREG/electron-vue#352]
#### Found an issue or bug with electron-vue? Tell me all about it!
I've been using electron-vue for the past few months, and for someone who spends most of their time on the backend in go + php, it is really quite nice!

I'm struggling to get the testing setup to play nicely with scss files. I have some shared styles (e.g. mixins and variable definitions) that I currently have in a scss file that imports the other necessary scss files (e.g. bootstrap [yes.. bootstrap in electron 😖 haha]).

I'd greatly appreciate any help getting testing working again!
Also, I'd love to know if perhaps there is there a better way to accomplish the same thing? (global scss)

##### Describe the issue / bug.
Unit testing breaks with node-sass + sass-loader + a .scss file.

##### How can I reproduce this problem?
To reproduce:
1. clone ventepos/electron-vue-test#master
2. yarn
3. yarn run unit

The only changes in the test repo are:
- installation of node-sass and sass-loader (ventepos/electron-vue-test@0d7ac0e1398edabd6bdb5fb8cedb8c707c78b588)
- move the css from LandingPage.vue to a .scss file (ventepos/electron-vue-test@9b62410c62e1f5828b04ff33504922cb573878f9)

##### If visual, provide a screenshot.
[Screenshot](http://bit.ly/2uukftU) 

##### Tell me about your development environment.
  * Node version: 8.2.1
  * NPM version: 5.3.0 (yarn 0.27.5)
  * vue-cli version: 2.8.2
  * Operating System: macOS 10.11.6 (15G1611)

**Comment by SimulatedGREG** [comment]
@pmccarren sorry for the late reply.

After doing some research, it seems this is actually an internal `vue-loader` issue. There is a current workaround, https://github.com/vuejs/vue-loader/issues/724, but I unfortunately can't seem to get it working properly. An alternative you could try is to add in the `sass-loader` into the `webpack` config and import it from `src/renderer/main.js`.

**Comment by pmccarren** [comment]
@SimulatedGREG no worries at all. Thanks for looking into it! I'll follow the vue-loader issue and update here as it progresses.

**Comment by chiaramdelucia** [comment]
For anyone who runs into this issue, I fixed it by changing to css test in webpack.renderer.config to the below, just as @SimulatedGREG had recommended. 

```
{
        test: /\.(s*)css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
},
```

**Comment by houssemFat-DDF** [comment]
Thank you @chiaramdelucia !! after searching in this repository, all related webpack and vue plugin finally i can work with scss in may vue file.
Please update the doc so we can start a project without struggling with configuration.
