### ISSUE TITLE
How to change installation appearance 

### ISSUE THREAD

**Issue by marceloavf** [SimulatedGREG/electron-vue#356]
I'm trying to do something like Discord installation, that show a beauty installer at first time it runs.

How can I change the basic installation when generated the build?
Or I need to make it silent and run something?

Thanks!

**Comment by develar** [comment]
If you mean application installer for Windows, please use electron-builder and set `"oneClick": false`

**Comment by marceloavf** [comment]
Doing that it'll be possible to add some loader or different visual installer with HTML or something?

**Comment by develar** [comment]
Yes, using custom macro https://github.com/electron-userland/electron-builder/wiki/NSIS.

I will check discord on Windows.

**Comment by marceloavf** [comment]
I think discord is installed with nsis in silent mode, then it runs a first browser window that check for update, after that it closes and open the actual program.

Is that also possible to create a window whitout the topbar ?

Thanks!
