### ISSUE TITLE
Error: Exit code: ENOENT. spawn fpm ENOENT

### ISSUE THREAD

**Issue by sviat9440** [SimulatedGREG/electron-vue#359]
Hi all, pls help :-)

> PS D:\Lotus\LotusApp> electron-builder -wl
> electron-builder 19.16.0
> No native production dependencies
> ⚠️  Packaging using asar archive is disabled — it is strongly not recommended.
> Please enable asar and use asarUnpack to unpack files that must be externally available.
> Packaging for linux x64 using electron 1.6.11 to dist\linux-unpacked
> Building rpm
> No native production dependencies
> ⚠️  Packaging using asar archive is disabled — it is strongly not recommended.
> Please enable asar and use asarUnpack to unpack files that must be externally available.
> Packaging for win32 x64 using electron 1.6.11 to dist\win-unpacked
> Building NSIS installer
> Error: Exit code: ENOENT. spawn fpm ENOENT

Config: 

```
"build": {
    "appId": "ru.logos.lotus",
    "productName": "Lotus",
    "electronVersion": "1.6.11",
    "buildVersion": "1.0.0.0",
    "asar": false,
    "mac": {
      "category": "logos.lotus.app.ru",
      "icon": "../icon/mac/app.icns"
    },
    "win": {
      "target": ["portable"],
      "icon": "../icon/win/app.ico"
    },
    "linux": {
      "target": ["rpm"],
      "icon": "../icon/png/"
    }
  }
```

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build#windows

To build rpm on windows, please use our Docker image — https://github.com/electron-userland/electron-builder/wiki/Docker

**Comment by SimulatedGREG** [comment]
Closing since this is not a direct issue with electron-vue.
