### ISSUE TITLE
jQuery - '$' is not defined 

### ISSUE THREAD

**Issue by vedtam** [SimulatedGREG/electron-vue#36]
Hi,

I need jQuery to have Bootstrap working. Following the docs I did:

1. npm install bootstrap --save
2. npm install jquery --save
2. imported both into main.js:

```
import 'bootstrap/dist/css/bootstrap.min.css'
import 'jquery/dist/jquery.min.js'
import 'bootstrap/dist/js/bootstrap.min.js'
```

And finally added this to webpacj.config.js:

```
  new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        })
```

Now, bootstrap works. But if I try to test jQuery using:

```
  $(document).ready(function () {
    alert()
  })
```

I get this error in terminal:

>  ✘  http://eslint.org/docs/rules/no-undef  '$' is not defined  
>            /App Projects/Electron/vue/app/src/components/LandingPageView.vue:42:3
>            $(document).ready(function () {
>               ^

I use the latest electron-vie build.

By the way, what does the "..." notation mean here:

```
new Vue({
  router,
  ...App
}).$mount('#app')
```

**Comment by SimulatedGREG** [comment]
@vedtam 

It looks like you got everything setup properly. The error you are receiving is from ESLint's `no-undef` rule. Since jQuery uses the global variable `$` or `jQuery`, ESLint needs to be configured to know about it. Within your `.eslintrc.js` file, add them to `globals`.


`.eslintrc.js` ([docs](http://eslint.org/docs/user-guide/configuring#specifying-globals))
```js
{
  // Other configs...
  "globals": {
    "$": true,
    "jQuery": true
  }
}
```

---

The `...` is an ES7 Object Rest Spread in this case. Here is the [spec](http://sebmarkbage.github.io/ecmascript-rest-spread/), but in short it is a way to join objects together, similar to the use of [`Object.assign()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).

```js
let spreader = {
  var1: true,
  var2: false
}

let obj = {
  otherVar: true,
  ...spreader
}

console.log(obj)
/*
  {
    otherVar: true,
    var1: true,
    var2: false
  }
*/

**Comment by vedtam** [comment]
@SimulatedGREG  thank you so much for the nicely elaborated answer! It works like a charm, and now I get the idea behind the "..." 👍 

One more little thing. I have created a template and a component (TopMenu), now I need to handle the click event of the menu buttons, but no matter how I try, I get:

> [Vue warn]: Property or method "say" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. (found in component ) [Vue warn]: Handler for event "click" is undefined.

./LandingPageView/TopMenu.vue:

```
<template>
  <div>
    <button type="button" name="button" v-on:click="say">BUTTON</button>
  </div>
</template>

```

main.js:

```
import Vue from 'vue'
import Electron from 'vue-electron'
import Resource from 'vue-resource'
import Router from 'vue-router'

import App from './App'
import routes from './routes'

import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.min.js'

Vue.use(Electron)
Vue.use(Resource)
Vue.use(Router)
Vue.config.debug = true

const router = new Router({
  scrollBehavior: () => ({ y: 0 }),
  routes
})

/* eslint-disable no-new */
new Vue({
  methods: {
    say: function () {
      alert()
    }
  },
  router,
  ...App
}).$mount('#app')
```

Thanks!

**Comment by SimulatedGREG** [comment]
The `say` method should be defined within the same `TopView.vue` component file within a `<script>` tag below your `<template>`. There shouldn't really be any cases where the root Vue vm in `main.js` should be modified. Make sure to take a look at using Vue components in the official [Vue docs](http://vuejs.org/guide/single-file-components.html).

```html
<script>
  export default {
    methods: {
      say () {
        // your code here...
      }
    }
  }
</script>
```

**Comment by vedtam** [comment]
@SimulatedGREG man, you are my saviour! I have turned the docs in and out, but haven't found this "Single File Components" section. 

Thanks again, and have a nice day! 👍

**Comment by disarticulate** [comment]
you can also define perfile globas
```
<script>
/* global jQuery */
...
</script>

**Comment by TejaswiChava** [comment]
<script>
     import $ from 'jquery'
</script>

**Comment by alessandroprudencio** [comment]
THANK YOU SOLE SOLUTION SIMPLE AND THAT WORKS

**Comment by RailRunner166** [comment]
doesnt really work in my case. tried it and it had some import error

**Comment by talley** [comment]
@alessandroprudencio  code worked

**Comment by ednsinf** [comment]
> @vedtam
> 
> It looks like you got everything setup properly. The error you are receiving is from ESLint's `no-undef` rule. Since jQuery uses the global variable `$` or `jQuery`, ESLint needs to be configured to know about it. Within your `.eslintrc.js` file, add them to `globals`.
> 
> `.eslintrc.js` ([docs](http://eslint.org/docs/user-guide/configuring#specifying-globals))
> 
> ```js
> {
>   // Other configs...
>   "globals": {
>     "$": true,
>     "jQuery": true
>   }
> }
> ```
> 
> The `...` is an ES7 Object Rest Spread in this case. Here is the [spec](http://sebmarkbage.github.io/ecmascript-rest-spread/), but in short it is a way to join objects together, similar to the use of [`Object.assign()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).
> 
> ```js
> let spreader = {
>   var1: true,
>   var2: false
> }
> 
> let obj = {
>   otherVar: true,
>   ...spreader
> }
> 
> console.log(obj)
> /*
>   {
>     otherVar: true,
>     var1: true,
>     var2: false
>   }
> */
> ```

thanks for help!!!!
