### ISSUE TITLE
Use element-ui in electron-vue template have strange problems

### ISSUE THREAD

**Issue by imRainChen** [SimulatedGREG/electron-vue#361]
#### Found an issue or bug with electron-vue? Tell me all about it!
My project use element-ui have strange problems when i update laster electron-vue template. I don't known why in dev mode have not run, but i found web mode can running good.

##### Describe the issue / bug.
use element-ui component in LandingPage.vue
```javascript
        <el-tooltip class="item" effect="dark" content="Top Left 提示文字" placement="top-start">
          <el-button>you can click this is not work</el-button>
        </el-tooltip>
```
command: npm run dev
result not have show tooltip

command: npm run build:web
will good performance

##### How can I reproduce this problem?
npm install element-ui

**in main.js**
```javascript
import Vue from 'vue'
import axios from 'axios'

import App from './App'
import router from './router'
import store from './store'

import ElementUI from 'element-ui'
import 'element-ui/lib/theme-default/index.css'

Vue.use(ElementUI)

if (!process.env.IS_WEB) Vue.use(require('vue-electron'))
Vue.http = Vue.prototype.$http = axios
Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  template: '<App/>',
  components: { App },
  router,
  store
}).$mount('#app')
```

**in renderer/components/LandingPage.vue**
```javascript
<template>
  <div id="wrapper">
    <img id="logo" src="~@/assets/logo.png" alt="electron-vue">
    <main>
      <div class="left-side">
        <span class="title">
          Welcome to your new project!
        </span>
        <system-information></system-information>
      </div>

      <div class="right-side">
        <div class="doc">
          <div class="title">Getting Started</div>
          <p>
            electron-vue comes packed with detailed documentation that covers everything from
            internal configurations, using the project structure, building your application,
            and so much more.
          </p>
          <button @click="open('https://simulatedgreg.gitbooks.io/electron-vue/content/')">Read the Docs</button><br><br>
        </div>
        <div>
        <el-tooltip class="item" effect="dark" content="Top Left 提示文字" placement="top-start">
          <el-button>you can click this is not work</el-button>
        </el-tooltip>
        </div>
        <div class="doc">
          <div class="title alt">Other Documentation</div>
          <button class="alt" @click="open('https://electron.atom.io/docs/')">Electron</button>
          <button class="alt" @click="open('https://vuejs.org/v2/guide/')">Vue.js</button>
        </div>
      </div>
    </main>
  </div>
</template>
```

Two Result:
command: npm run dev
command: npm run build:web

you can test it.

##### Tell me about your development environment.
  * Node version: 7.9.0
  * NPM version: 5.3.0
  * vue-cli version: (if necessary)
  * Operating System: darwin

**Comment by develar** [comment]
Is there error in the devtools console?

**Comment by imRainChen** [comment]
no error, so bad.

**Comment by develar** [comment]
Try to wrap your code into `div`.

```html
<div>
  <el-tooltip class="item" effect="dark" content="Top Left 提示文字" placement="top-start">
    <el-button>上左</el-button>
  </el-tooltip>
</div>
```

**Comment by imRainChen** [comment]
I try but not this problem

**Comment by imRainChen** [comment]
I use older electron-vue template can running good！

**Comment by SimulatedGREG** [comment]
@imRainChen sorry for late reply.

I can't seem to reproduce this issue. I've done the steps your provided, and built for both `electron` and `web`. Each have the same expected result, and are both working as intended.

**electron**
![image](https://user-images.githubusercontent.com/8327811/29905927-14012de2-8dd7-11e7-83ae-6041395b0ed5.png)

**web**
![image](https://user-images.githubusercontent.com/8327811/29905952-2d58f748-8dd7-11e7-8e95-33802fda6e83.png)

---

I know from past experience when working with `element-ui`, it always helps to use the latest versions of both `vue` and `element-ui`, especially when updating. The `element-ui` team is pretty great at always taking advantage of new `vue` changes, but not necessarily always paying attention to backwards compatibility.

**Comment by imRainChen** [comment]
sorry，not this component. Is <el-tooltip></el-tooltip>

**Comment by SimulatedGREG** [comment]
@imRainChen 

Okay, I am able to reproduce this issue now. It seems `element-ui` falls into that category of modules that need to be [white-listed](https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals). If you go into [`.electron-vue/webpack.renderer.config.js`](https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.renderer.config.js#L21), around line 21, you can add `element-ui` to the `whiteListedModules` list. After making that change, tooltips work now.

**Comment by imRainChen** [comment]
@SimulatedGREG Thank you for your help

**Comment by kinoli** [comment]
@SimulatedGREG this fixed it for me as well. white-list is the answer.

**Comment by zpzxgcr** [comment]
@SimulatedGREG  hey, I trid to add the white list, but it didn't work, look forward to your reply.

**Comment by microkof** [comment]
> @SimulatedGREG hey, I trid to add the white list, but it didn't work, look forward to your reply.

Because you didn't rerun 'yarn run dev'.

**Comment by RexYu512** [comment]
@SimulatedGREG  Thank you，Dude！
Your precise words easily destory my problem.

**Comment by Dinookys** [comment]
@SimulatedGREG Thanks a lot!!!!

**Comment by activeliang** [comment]
@imRainChen 
I also have this problem in my project "rails webpacker vue + element ui".
But I don't understand your method. Besides modifying the externals of webpack, do you have other changes? Can you talk about the steps?

**Comment by hututu007** [comment]
Is this a bug or a design like this?

**Comment by todoyel** [comment]
@SimulatedGREG I am facing the same problem. The template UI is working on the web perfectly but when I try to integrate with electron it's breaking the UI. I have added two images.

![image](https://user-images.githubusercontent.com/55307875/71318828-654bab00-24c0-11ea-94d1-306d0a91710c.png)
![image](https://user-images.githubusercontent.com/55307875/71318834-709ed680-24c0-11ea-8ee6-816856668028.png)
