### ISSUE TITLE
Package for windows shows a blank screen

### ISSUE THREAD

**Issue by cuiyueshuai** [SimulatedGREG/electron-vue#368]
I run "node .electron-vue/build.js && electron-builder --win --x64" in the macOS, and I want package for windows,
build and package is success, but when  I install and open in the windows, this is a blank screen, I don't known how to resolve it. by the way, when I run"npm run build" in the macOS,  package for macOS, it's no problem

mac OS:
<img width="1196" alt="screen shot 2017-08-24 at 10 15 29 am" src="https://user-images.githubusercontent.com/13741688/29646311-446fcc6c-88b5-11e7-9800-d891f8db868f.png">

windows: 
![wechatimg10](https://user-images.githubusercontent.com/13741688/29646403-e2d748b2-88b5-11e7-9c5d-8f36c5f8bb4b.jpeg)

##### Tell me about your development environment.
  * Node version: 8.3.0
  * NPM version: 5.3.0
  * vue-cli version: (if necessary)
  * Operating System: macOsSierra 10.12.3

so, Please forgive my poor English

**Comment by SimulatedGREG** [comment]
@cuiyueshuai 

Seeing that your application works on macOS shows that there something not being handled properly for Windows. I would recommend enabling the dev tools in production to debug things on Windows (https://github.com/SimulatedGREG/electron-vue/blob/master/docs/en/debugging-production.md#production-builds) to determine what is happening. Not sure when you created your project, but make sure to check out https://github.com/SimulatedGREG/electron-vue/commit/29133032ba34e8ec6f11d7911d6eee9b5828780e to ensure you will see any error console logs. This is not a direct issue with electron-vue.

**Comment by cuiyueshuai** [comment]
@SimulatedGREG, yeah, you are right, I have build the my project in the windows,it's work and success release, thank you, I should not be lazy.

**Comment by SimulatedGREG** [comment]
No worries @cuiyueshuai. Glad you got this sorted out.
