### ISSUE TITLE
electron-devtools-installer Failed to fetch extension

### ISSUE THREAD

**Issue by zicjin** [SimulatedGREG/electron-vue#37]

**Comment by SimulatedGREG** [comment]
@zicjin 

Sorry for the language gap. Are you able to translate that to english?

As for the title of the issue, it sounds like this is an issue with [`electron-devtools-installer`](https://github.com/MarshallOfSound/electron-devtools-installer), possibly dealing with connecting to the Chrome Store for downloading the extension. Maybe you are behind a proxy of some sort?

**Comment by zicjin** [comment]
sorry, I thought you would be Chinese
I have used the proxy tool to ensure that the chrome browser install Vue.js devtools extension fine. But there is still request timeout for the  Vue.js devtools installation

```
let installExtension = require('electron-devtools-installer')

installExtension.default(installExtension.VUEJS_DEVTOOLS)
    .then((name) => mainWindow.webContents.openDevTools())
    .catch((err) => console.log('An error occurred: ', err))
```

result:
```
...
Failed to fetch extension, trying 0 more times
electron  An error occurred:  { Error: ETIMEDOUT
              at Timeout._onTimeout (/Users/zicjin/Work/pidan/node_modules/request/request.js:759:15)
              at tryOnTimeout (timers.js:232:11)
              at Timer.listOnTimeout (timers.js:202:5) code: 'ETIMEDOUT', connect: false }
```

**Comment by SimulatedGREG** [comment]
@zicjin This is definitely an issue with [`electron-devtools-installer`](https://github.com/MarshallOfSound/electron-devtools-installer) and should be posted there, closing.

**Comment by kuie** [comment]
这个问题源于不能访问https://clients2.google.com这个网址（需要shadowsocks）
electron-devtools-installer的工作方式是检测是否存在这个扩展，如果没有就开始从google网站下载
所以，我们可以先下载扩展文件之后手动安装到chrome之后再将扩展文件直接复制到相应项目的扩展目录
以win10 系统为例
我们构建的electron应用会在
C:\Users\{username}\AppData\Roaming\{appName}\extensions\
目录下存放扩展文件
里面会有一个IDMap.json文件，如果没有请新建
IDMap.json里面存放了key 为 扩展ID，value 为扩展名称的对象
如：{"nhdogjmejiglipccpnnnanhbledajbpd":"Vue.js devtools"}
之后还会有一个以extensionID命名的文件夹
里面是安装好的扩展文件
还有一个使用crx 扩展名的文件 文件名与之前的文件夹相同
这个crx文件是可以通过chrome扩展商店下载的
如果找不到相应的扩展文件 可以网上搜索相应的扩展ID 再通过http://yurl.sinaapp.com/crx.php下载扩展包
之后安装在chrome 中后找到扩展包实际存放位置
复制已经解压好的扩展文件直接复制到 我们自己的项目缓存扩展文件的文件夹下（上文有提到）
之后重启应用就可以了

**Comment by kuie** [comment]
This problem stems from the inability to access the https://clients2.google.com URL (requires shadowsocks)
The way electron-devtools-installer works is to detect the existence of this extension, if not, start downloading from the google website.
So, we can download the extension file and manually install it to chrome before copying the extension file directly to the extension directory of the corresponding project.
Take the win10 system as an example
The electron application we built will be
C:\Users\{username}\AppData\Roaming\{appName}\extensions\
Store extension files under the directory
There will be an IDMap.json file inside, if not, please create a new one.
IDMap.json stores the object whose key is the extension ID and whose value is the extension name.
as follows
{"nhdogjmejiglipccpnnnanhbledajbpd":"Vue.js devtools"}
There will also be a folder named extensionID.
Inside is the installed extension file
There is also a file with a crx extension with the same file name as the previous folder.
This crx file can be downloaded from the chrome extension store.
If the corresponding extension file is not found, you can search for the corresponding extension ID online and download the extension package via http://yurl.sinaapp.com/crx.php.
After installing in chrome, find the actual storage location of the expansion package.
Copy the unzipped extension file directly to the folder of our own project cache extension file (mentioned above)
Then restart the application.

**Comment by kuie** [comment]
Translation By google 

This problem stems from the inability to access the https://clients2.google.com URL (requires shadowsocks)
The way electron-devtools-installer works is to detect the existence of this extension, if not, start downloading from the google website.
So, we can download the extension file and manually install it to chrome before copying the extension file directly to the extension directory of the corresponding project.
Take the win10 system as an example
The electron application we built will be
C:\Users\{username}\AppData\Roaming\{appName}\extensions\
Store extension files under the directory
There will be an IDMap.json file inside, if not, please create a new one.
IDMap.json stores the object whose key is the extension ID and whose value is the extension name.
as follows
{"nhdogjmejiglipccpnnnanhbledajbpd":"Vue.js devtools"}
There will also be a folder named extensionID.
Inside is the installed extension file
There is also a file with a crx extension with the same file name as the previous folder.
This crx file can be downloaded from the chrome extension store.
If the corresponding extension file is not found, you can search for the corresponding extension ID online and download the extension package via http://yurl.sinaapp.com/crx.php.
After installing in chrome, find the actual storage location of the expansion package.
Copy the unzipped extension file directly to the folder of our own project cache extension file (mentioned above)
Then restart the application.

**Comment by symant233** [comment]
> 这个问题源于不能访问[https://clients2.google.com这个网址
> electron-devtools-installer的工作方式是检测是否存在这个扩展，如果没有就开始从google网站下载

感谢!
开启全局代理, 启动应用后等待一会儿, 再重启下应用就好了.
