### ISSUE TITLE
How I can update components data on ipcRenderer events? 

### ISSUE THREAD

**Issue by rafaelleru** [SimulatedGREG/electron-vue#370]

**Comment by SimulatedGREG** [comment]
@rafaelleru 

This isn't a direct issue with electron-vue, so I will be closing. In short, the presence of `vue` does not change how `electron` APIs are used; everything is still JavaScript. You can easily import `ipcRenderer` in any component you need it in. If you chose to install `vue-electron`, you can access it a little faster. See #249 for more information.
