### ISSUE TITLE
Project with multiple webpack entries crashes in production

### ISSUE THREAD

**Issue by BonusPlay** [SimulatedGREG/electron-vue#377]
##### Describe the issue / bug.
When webpack is provided with multiple entry points ([link1](https://github.com/BonusPlay/test/blob/master/.electron-vue/webpack.renderer.config.js#L27) & [link2](https://github.com/BonusPlay/test/blob/master/.electron-vue/webpack.renderer.config.js#L122-L135)) the project starts and works just fine when running in development, builds perfectly fine, however it crashes on startup after install.
[Repo with source code to reproduce the error](https://github.com/BonusPlay/test).

##### How can I reproduce this problem?
Run `yarn run dev` and application starts without any problems, run `yarn run build` followed up by app install & run and it crashes.

##### If visual, provide a screenshot.
(please ignore the fact that screenshot is from another app)
![image](https://user-images.githubusercontent.com/8405359/29933420-d52a9d5a-8e77-11e7-8d01-9a59c501f238.png)

##### Tell me about your development environment.
  * Node version: 8.4.0
  * NPM version: 5.3.0
  * yarn version: 0.27.5
  * vue-cli version: 2.8.2
  * Operating System: Windows 7 Ultimate x64

**Comment by SimulatedGREG** [comment]
@BonusPlay 

When you added the addition `loader` entry point, you also renamed the `renderer` to `main`, which is also the name of the *main* process entry point. So during the `webpack` build, the actual *main* process script is getting overwritten with the `main` you defined in the renderer setup.

Changing [L26](https://github.com/BonusPlay/test/blob/master/.electron-vue/webpack.renderer.config.js#L26) & [L119](https://github.com/BonusPlay/test/blob/master/.electron-vue/webpack.renderer.config.js#L119) back to the name of *renderer* will fix the issue.
