### ISSUE TITLE
Feature request: Boilerplate for pwa vue project template

### ISSUE THREAD

**Issue by cpxPratik** [SimulatedGREG/electron-vue#378]
I need to create PWA vue app( bootstrapped with vue-cli pwa template), and build it also for electron, so cant use this boilerplate. It would be great if electron-vue has vue-cli template for pwa vue app too.

**Comment by SimulatedGREG** [comment]
Hey @cpxPratik 

There are currently no plans to support any sort of PWA output or official template. The main focus of this boilerplate is to target building for the `electron` environment, with the exception of providing a minimal `web` output. The official `vuejs-templates/pwa` is probably the best option for anybody wanting to get started, and it could theoretically be modified to use the electron-vue project structure, but that is outside the scope of this project.
