### ISSUE TITLE
Wrong getting started guide

### ISSUE THREAD

**Issue by christianmalek** [SimulatedGREG/electron-vue#38]
Hi,

I just followed your "Getting started" guide. But it didn't work (missing references) until I cd'ed into the app directory and executed `npm install`.

**Comment by SimulatedGREG** [comment]
Could you leave you development environment information? There's rare occasions where the post install fails.

**Comment by christianmalek** [comment]
I used yarn instead of npm. Maybe this is it. I'll try it tomorrow and will let you know.

**Comment by SimulatedGREG** [comment]
As per [yarn #853](https://github.com/yarnpkg/yarn/issues/853), the `postinstall` script is unable to run.

**Comment by christianmalek** [comment]
Sorry, I should have checked this before writing an issue. Thanks for clarification.

**Comment by SimulatedGREG** [comment]
@christianmalek 

No problem 😊. Yarn looks a little interesting, but with no install hook support, I'm not sure how long it'll last in today's NPM environment. Many packages really rely on those hooks, even electron does.
