### ISSUE TITLE
Protential feature request: Weex

### ISSUE THREAD

**Issue by swan488** [SimulatedGREG/electron-vue#380]
Hi Greg,

I recently came across Weex, which is supposed to support VueJS for writing native mobile apps.  https://weex.incubator.apache.org/ 

I tried it out but couldn't get npm/yarn run dev to work. It looks promising though, it would be amazing if we could have it integrated in electron-vue project, so it can cross all platforms.

It still seems to need a bit more time to mature, but I thought i'd mention it to you as it may worth watching. :)

Cheers,

Amy

**Comment by swan488** [comment]
An update, i had to use yarn install --ignore-engines to get it to install, and then run yarn/npm start. Some guys were saying npm install with npm3.10.10 works, but npm install doesn't work for me with npm 5.3.0.

With --ignore-engines, the app shows in the local web preview all good, but I got network errors when I tried to view it on my mobile through Weex Playground Android. Possibly because of ignore-engines.

**Comment by SimulatedGREG** [comment]
@swan488 

Thanks for the suggestion, but the idea of mixing together a browser application with a native application just isn't feasible. It might be possible if the mobile output was made with `cordova`, but to provide a truly native UI like `weex` just won't work. There are too many differences between both environments to *magically* build for both. 

> It still seems to need a bit more time to mature

This is can heavily agree on. It's fantastic to see that it was taken in by Apache Incubator, but there still hasn't really been any major documentation updates to help explain everything more thoroughly. In my opinion, [`nativescript-vue`](https://github.com/rigor789/nativescript-vue) is going to win the native *race*.

**Comment by swan488** [comment]
Thanks Greg, that makes sense! I haven't come across nativescript-vue yet, will check it out!
