### ISSUE TITLE
How to use electron-vue to create a modal form?

### ISSUE THREAD

**Issue by okwangyu** [SimulatedGREG/electron-vue#381]
How to use electron-vue to create a modal form, to solve the data inside vuex can be shared in the parent form and the modal form second, this form can be dragged to the parent outside, ask the writer to give a solution.

**Comment by SimulatedGREG** [comment]
@okwangyu 

This is not a direct issue with electron-vue, and I will be closing. Please know that the presensce of `electron` doesn't change how Vue.js is used. This is a question better suited for official documentation or respective communities.

**`electron`**
* https://electron.atom.io/docs/

**`vue`**
* https://vuejs.org/v2/guide/
* https://forum.vuejs.org/
* https://chat.vuejs.org/

**Comment by AlexVFornazieri** [comment]
@okwangyu 
If you opt to use vue.js the buefy is something i likely recommend to you:
>> https://buefy.github.io/
About modal and component's modal (like a form):
>> https://buefy.github.io/#/documentation/modal
