### ISSUE TITLE
how can i use sqlite3 in this project

### ISSUE THREAD

**Issue by alwaysloseall** [SimulatedGREG/electron-vue#383]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\# how can i use sqlite3 in this project

##### How can I reproduce this problem?
\# normal

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: v7.11.0
  * NPM version: v4.1.2
  * vue-cli version: (if necessary) 2.8,2
  * Operating System: win10x64

**Comment by SimulatedGREG** [comment]
@alwaysloseall 

This is not a direct issue with electron-vue, and I will be closing. Please know that the presence of `electron` doesn't change how Vue.js is used. This is a question better suited for official documentation or respective communities.

When creating your db instance with `new sqlite3.Database(filename, [mode], [callback])`, simply point to a filename using `app.getPath()`. See https://simulatedgreg.gitbooks.io/electron-vue/content/en/savingreading-local-files.html for an example.
