### ISSUE TITLE
Release is not pushed to my github repo

### ISSUE THREAD

**Issue by p418** [SimulatedGREG/electron-vue#384]
Hi, 

I followed instructions about building my app:

https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-electron-builder.html

I'm using default appveyor building configuration and all seem to work fine.

![screenshot - 06_09_2017 15_24_57](https://user-images.githubusercontent.com/10288475/30114234-863a261c-9317-11e7-918d-f510af4d2966.png)

But I can't see any draft release note (`GH_TOKEN` is specified) nor any artifacts on build job's artifact listing

![screenshot - 06_09_2017 15_28_06](https://user-images.githubusercontent.com/10288475/30114364-f3379402-9317-11e7-8c2c-f50f24576020.png)

![screenshot - 06_09_2017 15_26_02](https://user-images.githubusercontent.com/10288475/30114280-aaef38b2-9317-11e7-86f3-4c1d0a809934.png)

Is there anything I'm missing ?

**Comment by p418** [comment]
Well, now I can see my app released.

**Comment by Xiongzhenyu** [comment]
@p418  Hi, who to set GH_TOKEN ☺︎

**Comment by p418** [comment]
@Xiongzhenyu If your question is  "where to define `GH_TOKEN` ", its simply an `Environment Variable`.
There's many way to do that.

When building your app like so: 

```sh
GH_TOKEN=xxxxxxxxxxx yarn build
```
Or, like I used to, in AppVeyor Environment configuration:

https://www.appveyor.com/docs/environment-variables/

I'm now using provided docker image [`electronuserland/builder`](https://hub.docker.com/r/electronuserland/builder/)  + `jenkins` to build my app 

```sh
docker run --rm -e GH_TOKEN=xxxxx  electronuserland/builder:wine blahblahblah
```

**Comment by Xiongzhenyu** [comment]
Thank you. I think I've solved this problem.
