### ISSUE TITLE
Using generator functions in build mode doesnt work

### ISSUE THREAD

**Issue by samatt** [SimulatedGREG/electron-vue#386]
#### Found an isuisue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
I've got a bit of a complicated setup where I'm trying to run nightmarejs through electron. In order to get it to do what I need I am using a generator function and vo for the control flow. The app works fine with `run dev` but when I `run build` the generator function doesnt seem to get invoked. This seems to only be the case on osx when I run `run build`. I can add you to the repo if that helps.

##### How can I reproduce this problem?
\#
Try running a generator function using vo for the control flow on osx. It runs in `dev` but not `build` 
##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:8.1.3
  * NPM version: 5
  * vue-cli version: (if necessary)
  * Operating System: osx

**Comment by SimulatedGREG** [comment]
> This seems to only be the case on osx when I run run build

Since you imply that this is working on other platforms, this is most likely not a direct issue with electron-vue itself, and more of just handling the differences in OSs. The problem you are running into is probably better suited for the communities of `nightmare` or `vo`. I can't really say much more without seeing actual code.

**Comment by samatt** [comment]
yup, sorry my question was so vague. After a lot of messing around I found I found that [automatonic](https://www.npmjs.com/package/automatonic) solved my issue. Putting it here for posterity.Thanks!

**Comment by SimulatedGREG** [comment]
No worries 😄
