### ISSUE TITLE
dist/fonts empty if "ignore: /icons/" present in build options - Bootstrap custom fonts crashing

### ISSUE THREAD

**Issue by vedtam** [SimulatedGREG/electron-vue#39]
For about a day now, I am trying to figure out why bootstrap glyphicons aren't showing up in my production builds.

While looking at dev-tools (in production app) I found:

> x64_error/test.app/Contents/Resources/app/dist/fonts/glyphicons-halflings-regular.fa27723.woff net::ERR_FILE_NOT_FOUND
> x64_error/test.app/Contents/Resources/app/dist/fonts/glyphicons-halflings-regular.e18bbf6.ttf net::ERR_FILE_NOT_FOUND

Than I have checked ./config.js to see what gets ignored. As I have removed the ignore statement, all the bootstrap fonts were exported correctly.

I have tried to remove the ignored paths one by one, in the end I have realized that if I remove: **|icons** the fonts get exported.

What has the **icons** folder doo with the fonts folder and bootstrap fonts export??

This is how the build statement works for now:

```
...
building: {
    //  arch: 'ia32',
    arch: 'x64',
    asar: false,
    dir: path.join(__dirname, 'app'),
    icon: path.join(__dirname, 'app/icons/icon'),
    //  ignore: /node_modules|src|index.ejs|icons/,
    ignore: /node_modules|src|index.ejs/, // <--- fonts are exported if ' \icons ' is ommited
    out: path.join(__dirname, 'builds'),
    overwrite: true,
    platform: process.env.PLATFORM_TARGET || 'all'
  }
}
```

the way I import bootstrap:

```
main.js:

import Vue from 'vue'
import Electron from 'vue-electron'
import Resource from 'vue-resource'
import Router from 'vue-router'

import App from './App'
import routes from './routes'

import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.min.js'

Vue.use(Electron)
Vue.use(Resource)
Vue.use(Router)
Vue.config.debug = true

const router = new Router({
  scrollBehavior: () => ({ y: 0 }),
  routes
})

/* eslint-disable no-new */
new Vue({
  router,
  ...App
}).$mount('#app')

```
export results:

![screen shot 2016-10-15 at 11 31 03](https://cloud.githubusercontent.com/assets/4981592/19408626/e4acc374-92ca-11e6-8b6b-925cb18ae818.png)

**Comment by SimulatedGREG** [comment]
@vedtam 

> What has the icons folder doo with the fonts folder and bootstrap fonts export??

The `ignore` line in `config.js` tells `electron-packager` what files to not include when making a build. In your case, it turns out that the RegExp doesn't test against file/folder names in their full form but will actually test within the filename as well. Was totally unaware of this and a fix is on the way to enforce word boundaries.

In short, since...
```js
/icons/.test('glyphicons.halflings-regular.[hash].[ext]') // returns true
```
...bootstrap's glyphicons were being ignored during the build process.

**Comment by vedtam** [comment]
Cool, this makes sense now. Can't wait to see how you will handle the RegExp.
