### ISSUE TITLE
vue组件中使用node模块报错/vue component use node moudle bug

### ISSUE THREAD

**Issue by xu455255849** [SimulatedGREG/electron-vue#390]
//home.vue 
```
   const ipc = require('electron').ipcRenderer;
    const fs = require('fs')
    const sizeOf = require('image-size');
```

在vue组件中使用fs，node第三发包 开发模式正常  打包的时候提示以下错误 

//  bug messgae
｀｀｀
ERROR in ./node_modules/_electron@1.7.6@electron/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xushaoping/Documents/my-project/node_modules/_electron@1.7.6@electron'
 @ ./node_modules/_electron@1.7.6@electron/index.js 1:9-22
 @ ./src/renderer/db.js
 @ ./src/renderer/main.js

ERROR in ./node_modules/_image-size@0.6.1@image-size/lib/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/xushaoping/Documents/my-project/node_modules/_image-size@0.6.1@image-size/lib'
 @ ./node_modules/_image-size@0.6.1@image-size/lib/index.js 3:9-22
 @ ./node_modules/_babel-loader@7.1.2@babel-loader/lib!./node_modules/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script&index=0!./src/renderer/page/home/home.vue
 @ ./src/renderer/page/home/home.vue
 @ ./src/renderer/router/index.js
 @ ./src/renderer/main.js

ERROR in ./node_modules/_image-size@0.6.1@image-size/lib/types/tiff.js
Module not found: Error: Can't resolve 'fs' in '/Users/xushaoping/Documents/my-project/node_modules/_image-size@0.6.1@image-size/lib/types'
 @ ./node_modules/_image-size@0.6.1@image-size/lib/types/tiff.js 6:9-22
 @ ./node_modules/_image-size@0.6.1@image-size/lib/types ^\.\/.*$
 @ ./node_modules/_image-size@0.6.1@image-size/lib/index.js
 @ ./node_modules/_babel-loader@7.1.2@babel-loader/lib!./node_modules/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script&index=0!./src/renderer/page/home/home.vue
 @ ./src/renderer/page/home/home.vue
 @ ./src/renderer/router/index.js
 @ ./src/renderer/main.js

ERROR in ./node_modules/_babel-loader@7.1.2@babel-loader/lib!./node_modules/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script&index=0!./src/renderer/page/home/home.vue
Module not found: Error: Can't resolve 'fs' in '/Users/xushaoping/Documents/my-project/src/renderer/page/home'
 @ ./node_modules/_babel-loader@7.1.2@babel-loader/lib!./node_modules/_vue-loader@12.2.2@vue-loader/lib/selector.js?type=script&index=0!./src/renderer/page/home/home.vue 4:9-22
 @ ./src/renderer/page/home/home.vue
 @ ./src/renderer/router/index.js
 @ ./src/renderer/main.js

｀｀｀

##### Tell me about your development environment.
  * Node version: v8.4.0
  * NPM version: 5.4.0
  * vue-cli version: (if necessary)
  * Operating System: osx 10.11.5 (15F34)

**Comment by xu455255849** [comment]
this is a bug  when i  build my project  ,  run dev  is no problem

**Comment by SimulatedGREG** [comment]
@xu455255849 

Are you trying to build for `web`, `npm run build:web`? Building for `web` won't be possible because you are using modules specific to the node environment. `fs` does not exist in a traditional browser, only works in `electron`.

**Comment by xu455255849** [comment]
OK... A bell is just rang by ya in my mind ， thanks

**Comment by georgezouq** [comment]
@SimulatedGREG  Hi i got some issues when I run both `build` and `build:web`.

<img width="677" alt="screen shot 2017-09-26 at 11 17 05 am" src="https://user-images.githubusercontent.com/5990860/30846853-c4d72c58-a2cb-11e7-9ac7-3d8375b4800e.png">

While I need require 'electron' in renderer to communication with main process, and how can I do that?

**Comment by georgezouq** [comment]
@SimulatedGREG  Hi I got same issues when i run both `build` and `build:web`

While
<img width="1110" alt="screen shot 2017-09-26 at 3 02 22 pm" src="https://user-images.githubusercontent.com/5990860/30847126-efa2cf54-a2cc-11e7-8323-5c937b0cba4a.png">

 While I need require `electron` to communication with main process. How can I do that?

**Comment by xu455255849** [comment]
you should separate your project , if you build web  , you can not use node modules ，you can use `process.env.IS_WEB`   to do like this 
![image](https://user-images.githubusercontent.com/15166243/30848122-aa30114e-a2d0-11e7-9e40-388d110a46a0.png)
