### ISSUE TITLE
Yarn install electron beta

### ISSUE THREAD

**Issue by marceloavf** [SimulatedGREG/electron-vue#391]
#### Found an issue or bug with electron-vue? Tell me all about it!
When I use `yarn` command, it get the beta version from electron, not the latest stable. Is this a bug with this package, or electron? How to solve this?

##### Tell me about your development environment.
  * Node version: 8.4.0
  * NPM version: 5.4.0
  * Operating System: Windows 10

**Comment by SimulatedGREG** [comment]
@marceloavf 

Looks like `yarn` made a change to how dependency ranges are installed. This isn't really a bug, but just a slightly unexpected behavior or *opinion*. Will be pushing a fix, but you can get back to a stable install with `yarn add electron@latest --dev`.

When using the carrot range, `yarn` will install the highest version within the range, ignoring any `dist` tags related to betas, RCs, etc.

**Comment by SimulatedGREG** [comment]
Seems that this issue has solved itself. Might have been related to the removed beta versions that shipped with the Chrome security vulnerability. 

Make sure to update `yarn`, version `^1.0.0` is now out.
