### ISSUE TITLE
__static not found after packing application

### ISSUE THREAD

**Issue by imtiyazs** [SimulatedGREG/electron-vue#392]
Hello everyone, Firstly, thank you Greg for such a beautiful boilerplate of electron-vue. 
I have been really struggling with static folder to put my application in production. __static path works perfect in "development" ENV but after building the application , it gives an error of __static undefined. Well, I am not sure whether it is a bug or lack of my knowledge over the template. I checked webpack configurations, recent fixes related to static, pulled up latest version of everything but really cannot get rid of the error. 
Regarding usage purpose: I am using static folder for images, js files and few html pages that I dont want in vue. so basically if I am using an html in New browserWindow, the path is: 

  SPLASH_PAGE: path.join(__static, '/pages/splash.html'),

Similarly, I have 2 more pages and they all work awesome in Dev ENV but gives error after building an EXE.

##### If visual, provide a screenshot.
![error](https://user-images.githubusercontent.com/31210898/30412549-e997edf6-9935-11e7-895b-a9c9fc494c05.png)

\#

##### Tell me about your development environment.
  * Node version: 8.4.0
  * NPM version: 5.4.x
  * vue-cli version: (if necessary)
  * Operating System: Windows 10 64bit

**Comment by SimulatedGREG** [comment]
@imtiyazs 

Did you happen to remove [this code](https://github.com/SimulatedGREG/electron-vue/blob/master/template/src/main/index.js#L7-L13) when working in `src/main/index.js`?

**Comment by imtiyazs** [comment]
No. The code is present in index.js.

**Comment by SimulatedGREG** [comment]
@imtiyazs 

Do you have a project repo I could take a look at?

**Comment by imtiyazs** [comment]
@SimulatedGREG 

Thanks a lot !!
The above snippet actually fixed the __static issue. The file that I imported in index.js had __static used in them. I just pulled up the above snippet to the top of index.js before importing other files and that fixed the issue.

**Comment by SimulatedGREG** [comment]
Ahh, I was wondering if that may be the case. Glad you got this sorted out.

**Comment by imtiyazs** [comment]
Thanks for the help. Do you have any idea how can I access Vue component in production mode? For development mode, the components are loaded using "http://localhost:9080/#/record"  (Record component)  but the same doesnt work in production mode.

**Comment by SimulatedGREG** [comment]
@imtiyazs 

If you are asking about opening a specific route in production, then you can simply append `#route-name` to the end of the URL.

#### Example
**src/renderer/router/index.js**
```js
/* ... */

{
  path: '/some-other-route',
  name: 'some-other-route',
  component: require('@/components/SomeOtherRoute')
}

/* ... */
```

**src/main/index.js**
```js
const winURL: string = process.env.NODE_ENV === 'development'
  ? `http://localhost:9080`
  /* append route path with # */
  : `file://${__dirname}/index.html#some-other-route`
```

**Comment by imtiyazs** [comment]
Thank you again!
