### ISSUE TITLE
SCSS imports in .vue components break tests

### ISSUE THREAD

**Issue by joshua-owens** [SimulatedGREG/electron-vue#397]
I'm using scss in my .vue files and importing a global variables.scss file that is sitting in `src/renderer/assets/scss`. Everything is working fine in dev and prod builds. However, running tests has been quiet problematic. `npm run test` chokes up on the variables.scss file and spits out ` You may need an appropriate loader to handle this file type.`. I'm wondering if there is a solution to getting around this?

This can be reproduced by importing a .scss file into a .vue component and attempting to run `npm run test` 

  * Node version: v6.11.2
  * NPM version: 3.10.10
  * Operating System: Mac OSX

**Comment by SimulatedGREG** [comment]
See https://github.com/SimulatedGREG/electron-vue/issues/352 for more info.
