### ISSUE TITLE
cannot use decorator even babel-plugin-transform-decorators-legacy installed

### ISSUE THREAD

**Issue by XGHeaven** [SimulatedGREG/electron-vue#399]
##### Describe the issue / bug.
I need to use decorator, so I install `babel-plugin-transform-decorators-legacy` and add `"transform-decorators-legacy"` in `.babelrc` plugins property.
But no works, It still alerts me install `babel-plugin-transform-decorators-legacy`.

I try doing it in the vue-cli offered webpack template. It works.

##### How can I reproduce this problem?
Install `babel-plugin-transform-decorators-legacy` and edit `.babelrc`.
Then write some code with decorators, pack it.
An error should occur.

##### Tell me about your development environment.
  * Node version: v8.5.0
  * NPM version: v5.3.0
  * vue-cli version: (if necessary) v2.8.2
  * Operating System: osx10.11

**Comment by SimulatedGREG** [comment]
Please see https://github.com/SimulatedGREG/electron-vue/issues/339 for more information. This is probably related to the babel issue mentioned there.

**Comment by XGHeaven** [comment]
Sound sadly. I have to solve this problem by add plugins to every environment.

**Comment by XanderLuciano** [comment]
Closed due to age - many dependencies have been updated and this may not still be an issue. Please create a new issue if you are encountering this problem.
