### ISSUE TITLE
Uncaught Error: Received packet in the wrong sequence - if config.devtool = '' with mysql driver

### ISSUE THREAD

**Issue by vedtam** [SimulatedGREG/electron-vue#40]
Hi ,

I am using for quite some time the [mysql](https://www.npmjs.com/package/mysql) node driver in my Electron projects which works fine. But now while using this boilerplate, my production builds throw:

`Uncaught Error: Received packet in the wrong sequence.`

After some testing I have realised that the error goes away if I keep/set config.devtool = 'eval' in the webpack.conf.js file:

```
if (process.env.NODE_ENV === 'production') {
  config.devtool = '' // <----- this will throw Uncaught Error if I omit 'eval'

  config.plugins.push(
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    })
  )
}
```

HomeView.vue

```
<script>
  var mysql = require('mysql')
  var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: 'password',
    database: 'EONIC'
  })

  connection.connect()
  connection.query('SELECT * from products', function (err, rows, fields) {
    if (err) throw err <---- here will the error happen
    console.log(rows)
  })

  connection.end()

</script>
```

error happening in mysql/lib/protocol/Protocol.js at line 272:

```
 if (!sequence[packetName]) {
    var err   = new Error('Received packet in the wrong sequence.');
    err.code  = 'PROTOCOL_INCORRECT_PACKET_SEQUENCE';
    err.fatal = true;

    this._delegateError(err);
    return;
  }

```

Keeping **config.devtool = 'eval'** solves the problem but this way my project slows down. Tested using a bare electron install, no error in production builds.

The error is really easy to reproduce: fresh electron-vue install +  [mysql](https://www.npmjs.com/package/mysql) node driver, write a simple query and as you make a production build the error shows up.

** Latest version of the boilerplate
** OS:
OSX 10.11 / Windows 7 / Ubuntu 16.04

**Comment by SimulatedGREG** [comment]
@vedtam 

I haven't seen instances where the `devtool` configuration actually "breaks" usages of modules, but I can see how it can hinder performance. electron-vue specifically uses [`#eval-source-map`](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.dev.conf.js#L17) as it provides the best performance in development for Vue. This issue isn't directly related with electron-vue so I'm going to close this, but could I ask why you are using the `mysql` driver and not communicating with an API? I've never seen usage of official database drivers (or ORMs like [sequelize](http://docs.sequelizejs.com/en/v3/)) outside of back-end node process.

**Comment by vedtam** [comment]
First I have tried to put the database connection and query inside the main process (electron.js) while passing the query request from the renderer process (LandingPageVue.vue) via **ipcRenderer**:

electron.js:

```
'use strict'

const electron = require('electron')
const path = require('path')
const mysql = require('mysql')
const app = electron.app
const ipc = electron.ipcMain
const BrowserWindow = electron.BrowserWindow

...

/*
*
* DB CONNECTION - listen for DB calls from render process
*
*/ 
ipc.on('db-query', (event, arg) => {
    var connection = mysql.createConnection({
      multipleStatements: true,
      host: 'localhost',
      user: 'root',
      password: 'password',
      database: 'prb'
    })

    connection.connect()

    connection.query(arg, function (err, rows, fields) {
      if (err) alert(err)
      event.returnValue = rows
    })

    connection.end()

})
```

LandingPageView.vue:

```
<style scoped>
</style>


<template>
  <div class="">
    Hello
  </div>
</template>


<script>
  export default {
    data: function () {
      return {
      }
    },
    created: function () {

      // *** sending query request to Main Process here: ***

      var ipc = require('electron').ipcRenderer
      console.log(ipc.sendSync('db-query', 'SELECT * FROM clients'))
    }
  }
</script>

```

Now if I in development everything works as expected. But when I make a production build I get an alert box stating that the mysql module cannot be found:

> Uncaught Exception:
> Error: Cannot find module 'mysql'
>     at Module._resolveFilename (module.js:455:15)
>     at Function.Module._resolveFilename (/App Projects/Electron/test-vue/builds/test-vue-darwin-x64/test-vue.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:403:25)
>     at Module.require (module.js:483:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/App Projects/Electron/test-vue/builds/test-vue-darwin-x64/test-vue.app/Contents/Resources/app/electron.js:5:15)
>     at Module._compile (module.js:556:32)
>     at Object.Module._extensions..js (module.js:565:10)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)


For a workaround I have placed the mysql statement inside the LandingPageView.vue which was a temporary solution, but in the end both suck....:((

**Comment by vedtam** [comment]
Dear @SimulatedGREG ,

I have read your docs twice already and now understand that dependencies from the './package.json' are not exported in the production build. Is this the reason for the missing mysql module mentioned above?

But you have said:

>  I've never seen usage of official database drivers (or ORMs like sequelize) outside of back-end node process.

But if things required in the back-end process will not be exported in the final build made by Webpack, how on earth could I set up an ORM and require mysql in the back-end hoping that it will be available in the final build?

I am toatlly confused and start to become desperate. I have spent 2 weeks building an app using your boilerplate.
The app creates and stores invoices for a client on a local computer. Data is stored in a local mysql database as well so I have no external API to query the DB other than the one I build in electron.

Do you have any recommendation on how could I connect to the local database in the electron back-end still using your boilerplate?

Best Regards,
vedtam

**Comment by SimulatedGREG** [comment]
Hey @vedtam,

> Is this the reason for the missing mysql module mentioned above?

Yes, just like it is stated in the docs.

> But if things required in the back-end process will not be exported in the final build made by Webpack, how on earth could I set up an ORM and require mysql in the back-end hoping that it will be available in the final build?

When I said "back-end node process", I meant an actual **back-end server** and **not** electron's main process.

> The app creates and stores invoices for a client on a local computer. Data is stored in a local mysql database as well so I have no external API to query the DB other than the one I build in electron.

If the db is on the network, does your environment not allow you to make a simple API with something like [Loopback](http://loopback.io/)? This could be a great solution for you as Loopback can easily auto generate API end-points for you with support for user roles, authentication, rules, etc.

If you really have to use the `mysql` driver and don't want to deal with slow performance (with webpack) in the renderer process, then I'd suggest using `mysql` in the main process and refer to #22 for manually including the module after making a production build.

---

PS: This can be shortened with [`vue-electron`](https://www.npmjs.com/package/vue-electron)...
```js
var ipc = require('electron').ipcRenderer
console.log(ipc.sendSync('db-query', 'SELECT * FROM clients'))
```
...to...
```js
console.log(this.$electron.ipcRenderer.sendSync('db-query', 'SELECT * FROM clients'))
```

**Comment by vedtam** [comment]
Thanks @SimulatedGREG for your detailed suggestions! Now I have two really promising ways to finish my project!

Best Regards,
vedtam
