### ISSUE TITLE
Notifications icon and title

### ISSUE THREAD

**Issue by randyou** [SimulatedGREG/electron-vue#400]
I have replaced the icons at  '[appPath]/build/icons'

I use HTML5 Notification API  to send a notification. It shows like this:
![image](https://user-images.githubusercontent.com/8247661/30581940-84ea6d1a-9ce7-11e7-8d30-c386869687c9.png)
The icon is not my app icon, also the titile is not. It always show 'MY-ELECTRON-VUE'，I can't repalce it to my app' name.
 
  * Node version: v8.5.0
  * NPM version: 5.3.0
  * vue-cli version: (if necessary) 2.8.2
  * Operating System:MacOS 10.12.6

**Comment by jamtycle** [comment]
Hi! Did you solve your problem? I have a similiar issue when using the Notification object from electron.

It shows as follow:
![image](https://user-images.githubusercontent.com/38017959/119281102-f7963800-bbf9-11eb-9580-d0736c4fcafe.png)

I dont know how to avoid the **electron.app**

vue-cli version: 4.5.11
OS: Windows
