### ISSUE TITLE
how to open new window 

### ISSUE THREAD

**Issue by xu455255849** [SimulatedGREG/electron-vue#401]
I want to show my chart on the new window , but below code is not work  . I need to send data to the new window .  how can i do  ,  thanks.

vue is a SAP APP,  so  i create a new page to do this ,    whether has another better way？

ipc.on('showChart', function (e, data) {
    const modalPath = process.env.NODE_ENV === 'development'
        ? `http://localhost:9080/showChart.html`
        : `file://${__dirname}/showChart.html`
    let win = new BrowserWindow({ width: 400, height: 320, webPreferences: {webSecurity: false} })
    win.on('close', function () { win = null })
    win.loadURL(modalPath)
})

**Comment by randyou** [comment]
Your webpack should have multiple entries. 
[multiple entries](https://github.com/randyou/snail/blob/5036edbded0685f655905a4221ab539601d8af6e/.electron-vue/webpack.renderer.config.js#L25)
[set plugins](https://github.com/randyou/snail/blob/5036edbded0685f655905a4221ab539601d8af6e/.electron-vue/webpack.renderer.config.js#L132)

**Comment by marceloavf** [comment]
First of all, you need to disable `mode: 'history'` in your vue-router, check in [vue-router docs](https://router.vuejs.org/en/essentials/history-mode.html)

Then do the following: 

**src/main/index.js** example
```js
ipc.on('showChart', function (e, data) {
  const modalPath = process.env.NODE_ENV === 'development'
    ? 'http://localhost:9080/#/showChart'
    : `file://${__dirname}/index.html#showChart`
  let win = new BrowserWindow({ width: 400, height: 320, webPreferences: {webSecurity: false} })
  win.on('close', function () { win = null })
  win.loadURL(modalPath)
})
```

In your router, use the exactly path to your url
**src/renderer/router.js** example

```js
{
   path: '/showChart',
   name: 'showChart',
   component: require('your-router'),
 },
```

---

If your need another approach, take a look at this repo:

* [- The creating of another window](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/windows/about.js#L14)
* [- Calling it from a menu or via ipc](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/menu.js#L435)

**Comment by xu455255849** [comment]
it is work,  thank you

**Comment by marceloavf** [comment]
Refs #207

**Comment by SimulatedGREG** [comment]
Thanks for the help @marceloavf !

**Comment by PasserbyFluid** [comment]
> First of all, you need to disable `mode: 'history'` in your vue-router, check in [vue-router docs](https://router.vuejs.org/en/essentials/history-mode.html)
> 
> Then do the following:
> 
> **src/main/index.js** example
> 
> ```js
> ipc.on('showChart', function (e, data) {
>   const modalPath = process.env.NODE_ENV === 'development'
>     ? 'http://localhost:9080/#/showChart'
>     : `file://${__dirname}/index.html#showChart`
>   let win = new BrowserWindow({ width: 400, height: 320, webPreferences: {webSecurity: false} })
>   win.on('close', function () { win = null })
>   win.loadURL(modalPath)
> })
> ```
> 
> In your router, use the exactly path to your url
> **src/renderer/router.js** example
> 
> ```js
> {
>    path: '/showChart',
>    name: 'showChart',
>    component: require('your-router'),
>  },
> ```
> 
> If your need another approach, take a look at this repo:
> 
> * [- The creating of another window](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/windows/about.js#L14)
> * [- Calling it from a menu or via ipc](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/menu.js#L435)

it not works  for me,could help me  ~

**Comment by PasserbyFluid** [comment]
import { app, BrowserWindow, dialog } from 'electron'
import { ipcMain } from 'electron'

ipcMain.on('close-event', function (e) {
  // e.sender.getOwnerBrowserWindow().close()
  app.quit()
})
/**
 * Set `__static` path to static files in production
 * https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-static-assets.html
 */
if (process.env.NODE_ENV !== 'development') {
  global.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
}

let loginWindow,mainWindow
const winURL = process.env.NODE_ENV === 'development'
  ? `http://localhost:9080`
  : `file://${__dirname}/index.html`
  // const winURL = process.env.NODE_ENV === 'development'
  // ? `http://localhost:9080/dashboard?usr_udn=7005&usr_password=xc1&cadname=xc1&cadtype=2&note=%E8%A1%8C%E8%BD%A6%E8%B0%83%E5%BA%A61`
  // : `file://${__dirname}/index.html#/dashboard`

  const mainURL =  process.env.NODE_ENV === 'development'
  ? `http://localhost:9080/#/dashboard?usr_udn=7005&usr_password=xc1&cadname=xc1&cadtype=2&note=%E8%A1%8C%E8%BD%A6%E8%B0%83%E5%BA%A61`
  : `file://${__dirname}/index.html#dashboard?usr_udn=7005&usr_password=xc1&cadname=xc1&cadtype=2&note=%E8%A1%8C%E8%BD%A6%E8%B0%83%E5%BA%A61`
  var webContents;
function createWindow() {
  /**
   * Initial window options
   */
  loginWindow = new BrowserWindow({
    height: 200,
    useContentSize: true,
    width: 360,
    minimizable:false,
    fullscreenable:false,
    resizable:false,
  })

  loginWindow.loadURL(winURL)
  
  loginWindow.on('closed', () => {
    loginWindow = null
  })
}
function createMainWindow() {
  mainWindow = new BrowserWindow({
  })
  mainWindow.loadURL(mainURL)
  mainWindow.on('closed', () => {
    mainWindow = null
  })
}
app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (loginWindow === null) {
    createWindow()
  }
})
ipcMain.on('login-to-mainWindow', () => {
  loginWindow.close();
  createMainWindow();
})
ipcMain.on('loginoff--to-loginWindow', () => {
  mainWindow.close();
  createWindow();
  
})
ipcMain.on('loginoff', () => {
  app.quit()
})
/**
 * Auto Updater
 *
 * Uncomment the following code below and install `electron-updater` to
 * support auto updating. Code Signing with a valid certificate is required.
 * https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-electron-builder.html#auto-updating
 */

/*
import { autoUpdater } from 'electron-updater'

autoUpdater.on('update-downloaded', () => {
  autoUpdater.quitAndInstall()
})

app.on('ready', () => {
  if (process.env.NODE_ENV === 'production') autoUpdater.checkForUpdates()
})
 */

**this is my index.js  code**

**Comment by 3zbumban** [comment]
```js
new BrowserWindow({
    width: 400,
    height: 320,
    webPreferences: { webSecurity: false, nodeIntegration: true },
    show: false,
  });
```

In my case [it](https://github.com/SimulatedGREG/electron-vue/issues/401#issuecomment-330656658) worked after adding [`nodeIntegration: true`](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions) to the `BrowserWindow` options. 

>[It turns out, `nodeIntegration` was true by default in previous electron versions, but false by default in 5.0.0.](https://github.com/electron/electron/pull/16235#issue-241835034)

> First of all, you need to disable `mode: 'history'` in your vue-router, check in [vue-router docs](https://router.vuejs.org/en/essentials/history-mode.html)
> 
> Then do the following:
> 
> **src/main/index.js** example
> 
> ```js
> ipc.on('showChart', function (e, data) {
>   const modalPath = process.env.NODE_ENV === 'development'
>     ? 'http://localhost:9080/#/showChart'
>     : `file://${__dirname}/index.html#showChart`
>   let win = new BrowserWindow({ width: 400, height: 320, webPreferences: {webSecurity: false} })
>   win.on('close', function () { win = null })
>   win.loadURL(modalPath)
> })
> ```
> 
> In your router, use the exactly path to your url
> **src/renderer/router.js** example
> 
> ```js
> {
>    path: '/showChart',
>    name: 'showChart',
>    component: require('your-router'),
>  },
> ```
> 
> If your need another approach, take a look at this repo:
> 
> * [- The creating of another window](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/windows/about.js#L14)
> * [- Calling it from a menu or via ipc](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/menu.js#L435)

_versions:_
`
chrome: "73.0.3683.121"
electron: "5.0.8"
node: "12.0.0"
v8: "7.3.492.27-electron.0"
`

**Comment by hanjt** [comment]
@3zbumban My code like this 
```
ipc.on('showChart', function (e, data) {
  const modalPath = process.env.NODE_ENV === 'development'
    ? 'http://localhost:9080/#/showChart'
    : `file://${__dirname}/index.html#showChart`
  let win = new BrowserWindow({ width: 400, height: 320, webPreferences: {webSecurity: false} })
  win.on('close', function () { win = null })
  win.loadURL(modalPath)
})
```
After build it, new window is blank when open it in the main window

**Comment by 3zbumban** [comment]
@hanjt 
make sure that:
* [ ] it works with your main BrowserWindow
* [ ] do you have set the vue-router to `mode: 'history'` (`src/renderer/router/index.js`)
* [ ] you are serving on the right port `9080`
* [ ] you are passing in a `process.env.NODE_ENV` (try to log it to the console). you might be using the `vue-cli-service` to serve or build your app which [desides based on the command wich NODE_ENV to use](https://cli.vuejs.org/guide/mode-and-env.html#modes).

you also might want to check out [vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder) in my opinion the simplest way to use vue inside electron.

**Comment by kingangelAOA** [comment]
![image](https://user-images.githubusercontent.com/15135537/84383023-1cc6ac00-ac1e-11ea-827e-5104afba0f63.png)
create new window error

**Comment by WoutGeeurickx** [comment]
Hey guys,

I'm porting my existing 'pure' electron app over to include vue and I (successfully) implemented opening multiple windows using above approach. However I encountered some unexpected (at least for me) behavior. On the pure electron app I used to do something like this

```
const secondWin = new BrowserWindow({width: 400, height: 320, show: false)

secondWin.loadUrl('url/to/load')

secondWin.once('ready-to-show', () => {
    secondWin.show()
    firstWin.hide()
})

secondWin.on('close', () => {
    firstWin.show()
})
```
The idea was to have some kind of landing page that you dismiss when opening the second window, but that pops back up when you close that window.

When using above approach with this same setup, I noticed that I got the second window, but the first window wasn't hidden. By inserting some logs I noticed that the 'ready-to-show' is actually never fired.
Does any of you have any idea why 'ready-to-show' isn't fired? And does any of you have any idea why the second window is actually showing if I initially set 'show' to false and the line where I call show() is never reached since it's in the 'ready-to-show' callback?

I can get everything working as expected when I move the two lines outside the 'ready-to-show' handler, but I'm just curious to know why this is behaving differently than what I would expect.

Best,
Wout

**Comment by maxoyed** [comment]
@marceloavf That works for me, thanks

**Comment by dragos-boisteanu** [comment]
> ```js
> showChart
> ```

I have just tried this and it opens the entire app again instead of just the component I want. This is like opening a new instance of the app and setting it's router to a specified path. Is there any way to open component in a new browser window while keeping the main app settings, package, etc without reloading the entire app ?

**Comment by dragos-boisteanu** [comment]
> First of all, you need to disable `mode: 'history'` in your vue-router, check in [vue-router docs](https://router.vuejs.org/en/essentials/history-mode.html)
> 
> Then do the following:
> 
> **src/main/index.js** example
> 
> ```js
> ipc.on('showChart', function (e, data) {
>   const modalPath = process.env.NODE_ENV === 'development'
>     ? 'http://localhost:9080/#/showChart'
>     : `file://${__dirname}/index.html#showChart`
>   let win = new BrowserWindow({ width: 400, height: 320, webPreferences: {webSecurity: false} })
>   win.on('close', function () { win = null })
>   win.loadURL(modalPath)
> })
> ```
> 
> In your router, use the exactly path to your url **src/renderer/router.js** example
> 
> ```js
> {
>    path: '/showChart',
>    name: 'showChart',
>    component: require('your-router'),
>  },
> ```
> 
> If your need another approach, take a look at this repo:
> 
>     * [- The creating of another window](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/windows/about.js#L14)
> 
>     * [- Calling it from a menu or via ipc](https://github.com/webtorrent/webtorrent-desktop/blob/master/src/main/menu.js#L435)

I have just tried this and it opens the entire app again instead of just the component I want. This is like opening a new instance of the app and setting it's router to a specified path. Is there any way to open component in a new browser window while keeping the main app settings, package, etc without reloading the entire app ?
