### ISSUE TITLE
Error about static file after npm run build

### ISSUE THREAD

**Issue by tindecken** [SimulatedGREG/electron-vue#403]
I'm new with electron-vue

After use `npm run build` , then start app, it show error about static resource
[https://i.imgur.com/QSXYfxU.png](https://i.imgur.com/QSXYfxU.png)

Please help me to fix this problem.
Thank you.

**Comment by randyou** [comment]
try `icon: __static + '/imgs/exit.png'`

**Comment by tindecken** [comment]
hi, still meet the same issue,
https://i.imgur.com/oKI5r2b.png

`npm run dev` works well (with `{label: 'Exit', type: 'normal', role: 'quit', icon: 'static/imgs/exit.png'},`)

**Comment by randyou** [comment]
Hi try below 
`npm run dev works well (with {label: 'Exit', type: 'normal', role: 'quit', icon: 'imgs/exit.png'},)`
or
`npm run dev works well (with {label: 'Exit', type: 'normal', role: 'quit', icon: __static +'imgs/exit.png'},)`

**Comment by tindecken** [comment]
it works, thank you so much
