### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by iamwelk** [SimulatedGREG/electron-vue#406]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
npm run build error, can't download `tmp-15952-0-electron-v1.7.6-win32-x64.zip`

##### If visual, provide a screenshot.
![image](https://user-images.githubusercontent.com/6983075/30634954-6a8f8c06-9e23-11e7-9f99-a48001edc6ee.png)

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by marceloavf** [comment]
It's a problem with your connection dropping in the middle of the download, try to use `Yarn` instead, it handle better these connection issues.

**Comment by iamwelk** [comment]
thank you~
