### ISSUE TITLE
How could I get IS_WEB in vue component?

### ISSUE THREAD

**Issue by yangjianhua** [SimulatedGREG/electron-vue#408]
##### Describe the issue / bug.
\#
in src/renderer/main.js, use the following code can know IS_WEB 

if (!process.env.IS_WEB) Vue.use(require('vue-electron'))

I want to show/hide a button in the vue component, depends on the client mode or WEB, how could I archive this?

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:8.5.0
  * NPM version:5.4.2
  * vue-cli version: (if necessary)
  * Operating System:Mac OS

**Comment by xu455255849** [comment]
you can use    `process.env.IS_WEB`   to  judge  web or electron   , you can give process.env.IS_WEB  a value , it will render a web mode

**Comment by yangjianhua** [comment]
Thank you xu, but it's not what I mean and what I want.

I develop an app using electron-vue and I deploy it using client (windows/linux/mac client) and also deploy it on a web page (using the "yarn run build:web" create all web pages).

I don't know the user access from web page or client, so I want to determine it.

How could I do this?


And I found now the "process.env.IS_WEB" is undefined, so it's not a method to determine the client access mode... ...

**Comment by SimulatedGREG** [comment]
`process.env.IS_WEB` is `undefined` within the `electron` environment and defined as `true` when building for `web`. This is expected behavior, and `process.env.IS_WEB` can be accessed from any JavaScript.

Based on that knowledge, you can use a simple `v-if` to hide/show a button based on the target platform.
