### ISSUE TITLE
Issues installing dependencies

### ISSUE THREAD

**Issue by paulbdavis** [SimulatedGREG/electron-vue#409]
##### Describe the issue / bug.

Cannot install dependencies with `yarn`.

Error is `Error: Failed to find Electron v1.8.0 for linux-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-linux-x64.zip` 

Seems that electron has a tag for that, but not a proper release?

##### How can I reproduce this problem?

```
vue-cli vue init simulatedgreg/electron-vue proj
cd proj
yarn
```

##### Tell me about your development environment.
  * Node version: 8.4.0 (via nvm)
  * NPM version: 5.3.0 (via nvm) 
  * yarn version: 1.0.2
  * vue-cli version: 2.8.2 
  * Operating System: Arch Linux

##### EDIT:

I was able to install by running `yarn add electron@1.7.6`

**Comment by SimulatedGREG** [comment]
@paulbdavis 

This is related to #391. Currently you can install the proper version as you mentioned in your edit.
