### ISSUE TITLE
error MSB4019:

### ISSUE THREAD

**Issue by miecio1212** [SimulatedGREG/electron-vue#41]
durring npm install:
Can't find solution.
error MSB4019: The imported project "G:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by SimulatedGREG** [comment]
Based on the little information provided, I am able to know that you are on the Windows platform. I don't know if this the the problem, but make sure you have [`windows-build-tools`](https://github.com/felixrieseberg/windows-build-tools) installed as electron and other dependencies require specific `node-gyp` functions that may fail without them.

**Comment by miecio1212** [comment]
npm ERR! node v6.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.

I have windows-build-tools and .NET framework 4.5 sdk

**Comment by SimulatedGREG** [comment]
Yeah, I thought this would be a `node-gyp` issue. As this isn't a direct problem with electron-vue, I'm going to close this. Although `windows-build-tools` covers most cases there's probably a chance you might need a full installation of Visual Studio.

**Comment by XeonPowder** [comment]
@miecio1212 check out this link: 
`http://www.flavienbeninca.fr/2016/10/13/electron-vuejs-electron-vue.html `
(just auto translate with chrome to English if you can't read french like me!)

I was also having the same error, but i had Visual Studio 💯% installed. 
Now i'm able to '**npm run dev**' 

my versions:
```
npm v4.0.0
node v6.9.1
```

**Comment by SimulatedGREG** [comment]
@XeonPowder Thanks for the info. I've been meaning to add some documentation for Windows Users. I've seen many different scenarios where users are unable to scaffold electron-vue, but haven't had much of a chance to look into the problems as I am on macOS. Going to definitely add `windows-build-tools`, python, etc to the docs.
