### ISSUE TITLE
"npm run pack" doesn't pack any dependency in my package.json

### ISSUE THREAD

**Issue by rookiebulls** [SimulatedGREG/electron-vue#410]
It works perfect in 'dev' mode,  then I run "npm run pack" and copy the 'electron' directory under 'dist' to a new directory, but when I try to launch my app by using command "electron electron\main.js", it fails. However,  it works fine in the 'original electron'  folder when I use the same command. It seems my app still rely on the 'node_modules', I copy the whole 'node_modules' too, then it works. I guess the webpack doesn't pack my dependencies.

**Comment by SimulatedGREG** [comment]
@rookiebulls 

If you are needing to move your `electron` directory, then you would need to update the `main` field inside your `package.json` to the new location. This is not a direct issue with electron-vue since you modified the document structure; closing. Feel free to ask any other questions.

**Comment by rookiebulls** [comment]
@SimulatedGREG
 I figure out why, it's the webpack config, I thought it would pack all the dependencies by default.
Thanks for reply so fast.
