### ISSUE TITLE
Problems with the document object and unit testing

### ISSUE THREAD

**Issue by lx4r** [SimulatedGREG/electron-vue#412]
##### Describe the issue / bug.
I'm trying to setup unit tests for my project that I started with electron-vue. Two of my Vue components queries the DOM to register callbacks for a `dialog` element:

```html
<script>
  export default {
    name: 'licenses',
    mounted: function () {
      // register licenses dialog
      const dialog = document.querySelector('#oss-licenses')
      dialog.querySelector('.close').addEventListener('click', function () {
        dialog.close()
      })
    }
  }
</script>
```

When I run `npm run unit` I get this error message:

```
ERROR LOG: '[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'querySelector' of null"

found in

---> <Licenses> at D:\Documents\Code\MarkDawn\src\renderer\components\LandingPage\Licenses.vue
       <LandingPage> at D:\Documents\Code\MarkDawn\src\renderer\components\LandingPage.vue
         <Root>'
ERROR LOG: TypeError{}
```

My understanding is that there is something wrong with the `document` node. What confuses me is that the code works perfectly fine when run with `npm run dev`.  
Logging the document object to the console outputs a huge HTML string (as it should be?).  
I apologize in advance if this is not the right place to ask this question. 😇 

##### How can I reproduce this problem?
Clone https://github.com/lx4r/markdawn, `npm install` and run `npm run unit`.

##### Tell me about your development environment.
  * Node version: 6.10.2
  * NPM version: 3.10.10
  * vue-cli version: (if necessary)
  * Operating System: Windows 10

**Comment by SimulatedGREG** [comment]
This isn't a direct issue with electron-vue, so I'll be closing. But looking at your issue, I would recommend trying to use a [`ref`](https://vuejs.org/v2/api/#ref) instead of using `document.querySelector` to access your element.

**Comment by lx4r** [comment]
@SimulatedGREG Thanks for the help and sorry, I didn't mean to pollute your repo.

**Comment by SimulatedGREG** [comment]
No worries. Also testing features will be upgraded soon to use
`vue-test-utils`.

**Comment by lx4r** [comment]
@SimulatedGREG A follow-up question:
I got the refs working properly (thanks again) and can now unit test e.g. the text in my components. As the dialog opening is triggered by an IPC message my next goal is now to test IPC messages. In order to do that I think I need a reference to the browser window the Electron instance that Karma starts uses (to be able to use Electrons `webContents.send`).
How can I get a reference to the browser window Karma's Electron uses?

Thanks in advance for the help 🙂
