### ISSUE TITLE
Keeping up-to-date

### ISSUE THREAD

**Issue by pmccarren** [SimulatedGREG/electron-vue#413]
I have two questions about how to stay up to date:

- Are there any best-practices for keeping up-to-date with the latest changes in a/this vue template? Is the best answer to init a new project and take a copy-the-world approach?
- Is there a concept of 'upgrading' or should one simply go through the commits and manually make changes to keep up-to-date?

For example, I scaffolded a project in late June of this year, and recently electron-vue switched to vue-loader v13. I'd like to follow suit but am hesitant with the copy-world approach am looking for a better way.

Any tips / ideas would be great! Also, apologies if this is not the best place to discuss this!

**Comment by SimulatedGREG** [comment]
@pmccarren 

At the current moment, the [**Migration Guide**](https://simulatedgreg.gitbooks.io/electron-vue/content/en/migration-guide.html) is currently the best steps for upgrading. This method avoids the need to manually go through commits and apply changes.

In the future, electron-vue will be migrating to use `electron-webpack`, which was heavily inspired by this boilerplate. The benefits of switching will include being able to have a **updatable** module that handles all development needs. 

https://github.com/electron-userland/electron-webpack/

**Comment by pmccarren** [comment]
Thank you for the info!
