### ISSUE TITLE
Build fail with error from electron-packager

### ISSUE THREAD

**Issue by iGarym** [SimulatedGREG/electron-vue#417]
> May be a `electron-packager` bug

### Env
  * Node version: v8.6.0
  * NPM version: v5.3.0
  * YARN version: v1.1.0
  * vue-cli version: v2.8.2
  * Operating System: win10

Init the project by vue-cli, it but build fail by `yarn run build` or `npm run build`

I just added the `download.mirror` config to `build.config.js`

```
download: {
  mirror: 'https://npm.taobao.org/mirrors/electron/'
},
```

### Part of the CLI information

```shell
Packaging app for platform darwin x64 using electron v1.7.8

 ERROR  `electron-packager` says...

Error: Command failed: npm prune --production
npm WARN electron-vue-demo@0.0.1 No repository field.

npm ERR! May not delete: C:\Users\gaoym\AppData\Local\Temp\electron-packager\dar
win-x64\electron-vue-demo-darwin-x64\Electron.app\Contents\Resources\app\node_mo
dules\.bin

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gaoym\AppData\Roaming\npm-cache\_logs\2017-09-27T10_33_42_
957Z-debug.log
```

**Comment by Tailzip** [comment]
Same error here, but on MacOS:

- Node version: v8.4.0
- NPM version: v5.3.0
- YARN version: v1.1.0
- vue-cli version: v2.8.2
- Operating System: MacOS 10.12.6

**Comment by SimulatedGREG** [comment]
This is a `npm@5.3.0` bug. Update `npm` to fix.

Related #348
