### ISSUE TITLE
Use main process modules from the Vue component.

### ISSUE THREAD

**Issue by Alex-fun** [SimulatedGREG/electron-vue#42]
Hi!

I have some questions using main process modules from some components. For example, I want to click a button and trigger the main process event. just like that:

In one component.

```js
//  ../../electron => main process javascript file
openFile() {
    this.$electron.remote.require('../../electron').openFile();
}
```
I think, you should know, after webpack bundling, when i click the button, it would throw an error:

```js
Uncaught Error: Cannot find module '../../electron'
``` 

And then, do you have any good solutions?

**Comment by SimulatedGREG** [comment]
@Alex-fun 

I would suggest using electron's IPC APIs ([ipcRenderer](http://electron.atom.io/docs/api/ipc-renderer/) & [ipcMain](http://electron.atom.io/docs/api/ipc-main/)) to trigger the click event. It's basically an event bus / pubsub.

**Comment by Alex-fun** [comment]
@SimulatedGREG 

Yelp, *ipcRenderer* can solve my problem. But, `electron.remote.require('module')` still not supported if we use webpack. In fact, I just wonder if there is a solution, maybe we should avoid it.😂

All right, thank u for ur reply! If you find a solution, please let me know.😄

**Comment by SimulatedGREG** [comment]
Yeah it is best to typically avoid this, but if absolutely needed you could change `../../electron` to `../electron` as that is the position inside [production builds](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/project_structure.html#production-builds). You could then use the NODE_ENV to determine the proper path for development vs production.

**Comment by Alex-fun** [comment]
I tried, but not work. The main reason is the web sources do not have 'electron.js' file.
