### ISSUE TITLE
How To: Build extensible app ?

### ISSUE THREAD

**Issue by p418** [SimulatedGREG/electron-vue#425]
Hi, 

I'm trying to figure it out how to make my app extensible.

I understand that export  sub components  from a single-file component is not possible.
(named exports are not supported in *.vue files says vue-loader)

So, what is the best way to expose my app's internal components to be extended by others ?
Could it be done from  `/src/renderer/main.js` ?

Thank you for your help.

**Comment by SimulatedGREG** [comment]
I'm not entirely sure what your asking, but if `vue-loader` doesn't support it, then I'm not sure how much further this boilerplate could take you.

**Comment by p418** [comment]
I would like to provide a way for one to develop his own extension/plugin for my application.
This extension/plugin needs to be loaded at runtime

If you have any suggestion how to do this in a electron/vue way

**Comment by develar** [comment]
https://github.com/zeit/hyper has such plugin system.

**Comment by SimulatedGREG** [comment]
There isn't really a specific way to accomplish this with Vue. Remember everything is always JS in the end. Closing this as it isn't a direct issue with electron-vue. Feel free to continue discussing, but like @develar mentioned, I would also take a look at what they are doing.
