### ISSUE TITLE
How to: Maintain Application Specific configurations by environment

### ISSUE THREAD

**Issue by abishekrsrikaanth** [SimulatedGREG/electron-vue#427]
Is there a built-in way to maintain application-specific configurations by different environments? -
For example:
- Maintaining server credentials/token 
- Maintaining server url's by environment

**Comment by marceloavf** [comment]
If I understand your question, there is two environments under `process.env.NODE_ENV`, they are `production` and `development`. There is also `process.env.BABEL_ENV`, that receives `test` environment.

You can use them to have different server url's this way:
```js
const HOST = process.env.NODE_ENV === 'production' ? 'http://192.168.0.254' : 'http://localhost:8088';
```

**Comment by SimulatedGREG** [comment]
If I mean something like [Environment Variables](https://webpack.electron.build/environment-variables), then there currently isn't a way to do so. But since electron-vue will be migrating to user `electron-webpack`, this will be possible soon enough. Closing as this isn't a direct issue.
