### ISSUE TITLE
axios tick error " is_buffer can not find" where build

### ISSUE THREAD

**Issue by nodephp** [SimulatedGREG/electron-vue#428]
##### How can I reproduce this problem?
- run dev no errror
- run build axios tick error **is_buffer can not find**

1. so I remove axios in package.json
1. then npm install axios
1. build no error

**Comment by SimulatedGREG** [comment]
Sounds like a dependency issue. Are you running `npm` or `yarn`? If `npm`, make sure it's fully updated.

**Comment by nodephp** [comment]
thanks i will try
