### ISSUE TITLE
webpack 2

### ISSUE THREAD

**Issue by wormen** [SimulatedGREG/electron-vue#43]
tell whether the config appears to webpack 2?

**Comment by SimulatedGREG** [comment]
If you are asking if the current `webpack.config.js` works with webpack 2, then I'm not entirely sure. I do know that some beta versions require an extra webpack plugin for Vue to function, but official support within electron-vue won't come around until more stable versions of webpack are available.

**Comment by SimulatedGREG** [comment]
Closing for now. Feel free to comment back if needed.
