### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by exgonline** [SimulatedGREG/electron-vue#431]
Help Please !

I have downloaded the boilerplate and am trying to add a new component, but am getting the error below when i npm run dev

Here is my template code , any help would be appreciated.

Thanks

<template>
  <div id="wrapper">
    <main>
      <div>  
        <span class="title">
          Welcome to your new project! {{ msg }}
        </span> 
     </div>
  </main>
 </div>
</template>

<script>
export default {
  name: 'calendar-page',
  data () {
    return {
      msg: 'neil'
    }
  }
}
</script>

Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <MyProject> at src\renderer\App.vue
         <Root>

**Comment by marceloavf** [comment]
Could you please provide more details and part of the component that you are trying to create?

**Comment by exgonline** [comment]
The template is very simple. Just starting out with electron!

`<template>
  <div id="wrapper">
    <main>
      <div>  
        <span class="title">
          Welcome to your new project! {{ msg }}
        </span> 
     </div>
  </main>
 </div>
</template>

<script>
export default {
  name: 'calendar-page',
  data () {
    return {
      msg: 'neil'
    }
  }
}
</script>
`

**Comment by marceloavf** [comment]
As I can see, you need to provide a basic Vue.js structure **template-script-style** - [Check this link](https://vuejs.org/v2/guide/single-file-components.html)

Your code should be like that:

```vue
<template>
  <div>
    Welcome to your new project! {{ msg }}
  </div>
</template>

<script> 
 export default {
    name: 'calendar-page',
    data () { 
       return { msg: 'neil' } 
     } 
  } 
</script>
```

**Comment by exgonline** [comment]
I have tried the above code and still the same.

**Comment by marceloavf** [comment]
Strange, seems that your webpack is not compiling templates or some configuration are wrong.

**Comment by exgonline** [comment]
I have tried the subtitle boilerplate and the same happens there. I will try and set up on another PC and see if that helps. Thanks for the replies, just wanted to be sure I wasn't missing something obvious!

**Comment by exgonline** [comment]
Just tried on another machine and all works perfect. Many thanks for the replies, much appreciated.
