### ISSUE TITLE
electron-builder build app throw err:Cannot find module "is-buffer"

### ISSUE THREAD

**Issue by taodong0710** [SimulatedGREG/electron-vue#432]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\# 'npm run dev' work is fine , but 'npm run build' work it throw err:Cannot find module "is-buffer"

##### How can I reproduce this problem?
\#  Followed by initial setup.

##### If visual, provide a screenshot.
\# 
dev versions:
![image](https://user-images.githubusercontent.com/24261582/31815610-c60e845c-b5bf-11e7-82d7-4b5b0c70ddb7.png)

build versions:
![image](https://user-images.githubusercontent.com/24261582/31815632-d27cb95c-b5bf-11e7-85bc-2c2c3567b21f.png)

##### Tell me about your development environment.
  * Node version: v6.9.5
  * NPM version: 3.10.10
  * vue-cli version: (if necessary)
  * Operating System: window10 10.0

**Comment by SimulatedGREG** [comment]
Sounds like a dependency management issue. I would definitely try updating your `node` and `npm` versions, then try once more.

**Comment by taodong0710** [comment]
I try once more,update my` node` and `npm` versions,and install `Python`. but it `npm run build` wrok throw err:`Cannot find module 'is-buffer'`

* my `node` and `npm` version is newest
![image](https://user-images.githubusercontent.com/24261582/31869803-f2fa3dca-b7dc-11e7-9521-b9fca445678c.png)

* packaging process is fine
![image](https://user-images.githubusercontent.com/24261582/31869828-2311d338-b7dd-11e7-8eea-a4b9c37296f3.png)

* dev version is fine
![image](https://user-images.githubusercontent.com/24261582/31869997-0ef8ede0-b7de-11e7-9c94-97c8c224773f.png)

* build version throw err:`Connot find module 'is0-buffer`
![image](https://user-images.githubusercontent.com/24261582/31869969-ef8a417a-b7dd-11e7-9ff4-fc82675641d9.png)

@SimulatedGREG  what could I do next , please tell me about it.

**Comment by Naraku777** [comment]
Has same problem before.
Can't build app on window system, it show blank window.
Same error log on devtools' console, and then I updated the npm to version 5.3, didn't solve.
Many problem on window building with npm, I think you could use yarn, emmmm, in fact, that is no problem 😂 
Now I use yarn on window os, macOS too.
@taodong0710

**Comment by taodong0710** [comment]
@Naraku777
thank you for your suggest.
The problem has been solved.
