### ISSUE TITLE
yarn run dev return breaking header page

### ISSUE THREAD

**Issue by patriciussanctus** [SimulatedGREG/electron-vue#433]
i try install clear version on my pc - **no work**.
try install on other pc - work.
yarn run build - work.
what happened?

```
�H����.�M����.�HTTP/1.1 200
OKX-Powered-By: ExpressAccept-Ranges: bytesContent-Type: application/font-woff2; 
charset=UTF-8Content-Length: 77160ETag: W/"12d68-1vSMun0Hb7by/Wupk6dbncHsvww"
Date: Fri, 20 Oct 2017 13:13:27 GMT::1x#
```

![electron-vue](https://user-images.githubusercontent.com/16253399/31824874-12895728-b5b9-11e7-8b90-720b5fcd1267.png)

  * electron-builder
  * Node version: 8.2.1
  * NPM version: 5.3.0
  * vue-cli version: 2.9.1
  * Operating System: macOS Sierra

**Comment by SimulatedGREG** [comment]
Not sure what exaclty is happening since you didn't really provide too many details. But one thing to try is updating your `npm` version. `v5.3.0` had a serious bug when it came to dependency management.

**Comment by patriciussanctus** [comment]
reinstalling node, nvm and brew solved my problem.
