### ISSUE TITLE
Application is built but can't be debugged in build mode

### ISSUE THREAD

**Issue by boulabiar** [SimulatedGREG/electron-vue#436]
##### issue / bug.
I have an application that works perfectly in dev mode. It access file system and the debugger works either from WebStorm console or from Chrome through chrome://inspect.
Once built for Mac or windows, it just shows the front side I have no access to server side debugging 
app.commandLine.appendSwitch('inspect', '5858'); only works in dev mode

I don't know how to show or debug the built application to understand why it doesn't work there.

/[...]/Contents/Resources/app.asa…:7409 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
/[...]/build/mac/agent.app/Contents/Resources/app.asa…:7419
/[...]/build/mac/agent.app/Contents/Resources/app.asa…:7420

You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

**Comment by SimulatedGREG** [comment]
This really isn't an issue and more of a question. If you are looking for production application debugging, then you are probably going to have to change a few things like adding in source maps. I would look into general `electron` debugging in production, as the way to accomplish this is not tied to `vue` in anyway. Closing as this isn't a direct issue with electron-vue.
