### ISSUE TITLE
Bundle a large file for Mac/Win and consume it on Mac/Win

### ISSUE THREAD

**Issue by wdmtech** [SimulatedGREG/electron-vue#440]
Hey again @SimulatedGREG :)

My main questions for this issue are:

1. What is the optimal way to bundle a large neDB database file with my application (to put it in the macOS application data/Windows user data for later consumption?)

2. How can I consume the database file (using NEDb) in a consistent way - in both `production` and `development`

I feel like the way I'm approaching this is wrong, and is very difficult to debug.

My current attempt is as follows:

Cheers :)

Will

--- 

I have a (very large) neDB database file (`items.db`) that I would like to use in my application purely as a read-only datasource.

It currently exists as `./static/items.db`

This is created before the app is built, so I only need to move it into the user's files when the build step is run (both macOS and Windows) - as below:

```js
// ./src/main/index.js

if (process.env.NODE_ENV !== 'development') {
  Fs.createReadStream(
    Path.join(global.__static, '/items.db')
  ).pipe(
    Fs.createWriteStream(app.getPath('userData') + '/items.db')
  )
}
```

(This does not always work)

Later, I attempt to consume the file in the render process like so:

```js
import Datastore from 'nedb'
import Path from 'path'
import { remote } from 'electron'

let filename = Path.join(remote.app.getPath('userData'), '/items.db')

if (process.env.NODE_ENV !== 'production') {
  filename = Path.join(__static, '/items.db')
}

export default new Datastore({ filename })
```

This works fine in `development`, but errors in `production` - and I'm not sure why as devtools doesn't show anything.

**Comment by wdmtech** [comment]
Also I have to build this on a VM each time so it takes ages each time I want to test my build 🙈

**Comment by SimulatedGREG** [comment]
Sorry for such a late reply. The way you have approached this is actually the way I would have suggested. Looking at what you've posted I would take it a step further and put in some checks with `fs.exists` to ensure your DB exists before trying to load it in. This method unfortunately is deprecated, so you might want to look into using [`fs-extra`](https://www.npmjs.com/package/fs-extra).

Going to close as this isn't a direct issue with electron-vue.
