### ISSUE TITLE
Uncaught Error: Cannot find module 'raven-js'

### ISSUE THREAD

**Issue by amorist** [SimulatedGREG/electron-vue#444]
npm run dev no err but build app show err
```
Uncaught Error: Cannot find module 'raven-js'
```
![image](https://user-images.githubusercontent.com/14037268/32261097-4c196292-bf07-11e7-8f55-18048f046b54.png)

![image](https://user-images.githubusercontent.com/14037268/32261156-ab1a833e-bf07-11e7-88ed-e4b0b43bd2b4.png)

![image](https://user-images.githubusercontent.com/14037268/32261139-8c7b92a6-bf07-11e7-85bb-bdc9c58fdf2d.png)

**Comment by georgezouq** [comment]
同问

**Comment by SimulatedGREG** [comment]
##### Tell me about your development environment.
  * Node version:
  * NPM/yarn version:
  * Operating System:

**Comment by georgezouq** [comment]
@SimulatedGREG Build my project on window run:
```
npm run build
```
Build is success. But open it will case an error cannot find module js-base64:

![323d50087bfccd2beca0aa1bf1a3d82f](https://user-images.githubusercontent.com/5990860/32650966-59a83888-c5c5-11e7-9d9a-64e38255ebeb.png)

 I use js-base64 in project like blow: 

![screen shot 2017-11-10 at 5 10 02 pm](https://user-images.githubusercontent.com/5990860/32650813-c4fa6328-c5c4-11e7-8f35-866f820a96ea.png)

I think it may not pack into build file, how can i include this module??
It will work when i build a mac version, only got this problem build a win32 version.

- Node version: v8.7.0
- NPM version: 5.4.2
- Operating System: win10

**Comment by amor520** [comment]
node:v8.4.0
npm:5.5.1
Operating System: Mac OS 10.13

**Comment by XanderLuciano** [comment]
Closed due to age. If this is still an issue please let me know or create a new issue.
