### ISSUE TITLE
appveyor can not find module

### ISSUE THREAD

**Issue by mbykov** [SimulatedGREG/electron-vue#447]
##### Describe the issue / bug.
\#

I have appveyor.yml from electron-vue cli,

but appveyor gives:
yarn build
yarn run v1.2.1
$ node .electron-vue/build.js && electron-builder
module.js:538
    throw err;
    ^
Error: Cannot find module 'cfonts'

##### How can I reproduce this problem?
\#

Look appveyor:
https://ci.appveyor.com/project/mbykov/morpheus-vue
project on github:
https://github.com/mbykov/morpheus-vue

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: 8.6.0
  * NPM version: 5.4.0 (but I use yarn)
  * yarn version: 1.2.1
  * vue-cli version: (if necessary)
  * Operating System: appveyor

**Comment by SimulatedGREG** [comment]
Are you still having this issue? Looks like your builds are going through fine now, and may have just been a rare edge case you ran into. Going to close.

**Comment by mbykov** [comment]
yes, thank you. I had odd environment variable NODE_ENV=production. When I have removed this line an issue disappeared. Some time ago this line did not interferes, and I thought that it was necessary, or not affects, and did not pay attention to it. Thank you once more!

**Comment by Laura-O** [comment]
I have the same problem with [Travis](https://travis-ci.org/Laura-O/todo-tron/builds/346564829) (repo is [here](https://github.com/Laura-O/todo-tron)).

The builds are going through fine locally (Mac and Linux environment) but Travis complains that it can't find cfonts:

> node .electron-vue/build.js && electron-builder
module.js:540
    throw err;
    ^
Error: Cannot find module 'cfonts'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/Laura-O/todo-tron/.electron-vue/build.js:5:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! todotron-3000@0.0.0 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the todotron-3000@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Any help with this is appreciated!
