### ISSUE TITLE
webpack-dev-server 

### ISSUE THREAD

**Issue by miecio1212** [SimulatedGREG/electron-vue#45]
webpack  'webpack-dev-server' is not recognized as an internal or external command,
         operable program or batch file.

OS windows 8.1 x64
node v6.9.1
npm 3.10.9

**Comment by Luminess** [comment]
Do `npm i -g webpack` in cmd and try again.

**Comment by miecio1212** [comment]
tried and also tried npm i -g webpack-dev-server

**Comment by Luminess** [comment]
Just `webpack` in cmd gives that error too?

**Comment by SimulatedGREG** [comment]
> @miecio1212 Could you give this try on an earlier node version? There are some cases where some packages loose functionality if node releases some breaking changes.

**Comment by SimulatedGREG** [comment]
Closing for now. Feel free to comment back.
