### ISSUE TITLE
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify

### ISSUE THREAD

**Issue by ykl124** [SimulatedGREG/electron-vue#450]
I input npm install and entered it , then it suggested
```
 npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify.
``` 
 I did as tips
``` 
npm install babel-preset-minify --save-dev
```
but it still didn't work. 
Can you update the dependency? How can I fix the problem?

**Comment by MiYogurt** [comment]
假如一切正常的话，其实不用管它，只是一个 warning 而已。

if everything it's work，never mind， it's just a warning tip。

if you want update the dependency
```
npm i babel-minify -D 
```

and read the project reamdme。

**Comment by SimulatedGREG** [comment]
This is only a warning and not an immediate issue. This also is specific to `babili-webpack-plugin`.

**Comment by ykl124** [comment]
但问题是一切不正常。。。 @MiYogurt  报错之后安装就停止了
