### ISSUE TITLE
How to debug main process in webstorm or vs code?

### ISSUE THREAD

**Issue by Taffyw** [SimulatedGREG/electron-vue#453]
![image](https://user-images.githubusercontent.com/25218775/32637986-9932209c-c582-11e7-9d2a-bea1e8ba4295.png)

**Comment by yockii** [comment]
可以再vscode中用attach的方式附加到进程中

**Comment by Taffyw** [comment]
@yockii 大神 有没有例子~

**Comment by yockii** [comment]
启动electron的时候加上参数 –debug-brk=5858  5858这个端口号作为后面附加到该进程用的端口
然后用attach启动就可以了
{
            "name": "Attach", 
            "type": "node", 
            "request": "attach", 
            "port": 5858, 
            "address": "localhost", 
            "restart": false, 
            "sourceMaps": false, 
            "outDir": null, 
            "localRoot": "${workspaceRoot}", 
            "remoteRoot": null
        }

**Comment by Taffyw** [comment]
@yockii 好的我试试

**Comment by Molunerfinn** [comment]
@Taffyw 请问你的操作可以成功么？我通过attach的方式进入的debug模式并不能捕捉到断点

**Comment by FAKER-A** [comment]
@Molunerfinn 您好！ 我也无法捕捉到断点，不知道您后来是如何解决这个问题的？
