### ISSUE TITLE
The problem of port being occupied

### ISSUE THREAD

**Issue by Lizhooh** [SimulatedGREG/electron-vue#454]
If the 9080 port is occupied, `electron-vue` will not run.
It means that it's wrong to start two `electron-vue` at the same time (unless you manually change the port)

```js
// .electron-vue/dev-runner.js
server.listen(9080)

// src/main/index.js
let mainWindow
const winURL = process.env.NODE_ENV === 'development'
  ? `http://localhost:9080`
  : `file://${__dirname}/index.html`
```

I hope that when the port is occupied, automatically use other ports?

**Comment by SimulatedGREG** [comment]
Might be worth adding documentation about this scenario, but this is not a direct focus for electron-vue as a _boilerplate_. Although vue-cli@3 might have a solution for this.
