### ISSUE TITLE
Use vue-test-utils package to clean up tests

### ISSUE THREAD

**Issue by bdsoha** [SimulatedGREG/electron-vue#455]
The current testing framework is good, but there is a lot of overhead to get things running as well as a lot of boilerplate in the tests.

I don't see why this project doesn't include [`vue-test-utils`](https://github.com/vuejs/vue-test-utils) out of the box.

**Comment by SimulatedGREG** [comment]
Will be revisiting testing when work begins for supporting the new `vue-cli@3`

**Comment by DiegoFleitas** [comment]
Any news on this matter? Thanks
