### ISSUE TITLE
right click is not work

### ISSUE THREAD

**Issue by lichnow** [SimulatedGREG/electron-vue#456]
use `@click.right` or `@click.ctrl` event is not work,but `@click` event work fine,what's wrong?

**Comment by wendzhue** [comment]
Maybe you mean `@contextmenu`?

**Comment by lichnow** [comment]
@wendzhue `@contextmenu` is work fine,why `@click.ctrl` not work? in vue's document it exists!

**Comment by wendzhue** [comment]
@lichnow With `@contextmenu` set you won't need to set `@click.ctrl` manually. At least that works in my project. Maybe you should provide detailed information?

**Comment by SimulatedGREG** [comment]
This is not a direct issue with electron-vue, and I will be closing. Please know that the presensce of `electron` doesn't change how Vue.js is used. This is a question better suited for official documentation or respective communities.

**`electron`**
* https://electron.atom.io/docs/

**`vue`**
* https://vuejs.org/v2/guide/
* https://forum.vuejs.org/
* https://chat.vuejs.org/
