### ISSUE TITLE
URGENT!! Hownto access the currently active BrowserWindow from vue

### ISSUE THREAD

**Issue by Dsaint109** [SimulatedGREG/electron-vue#459]
I want to create custom _close, minimize and maximize_ icons but dont know how to get access the the currently active Browser window 
I tried `this.$electron.remote` but iit didn't work

Any idea on how to go about this

**Comment by AndreColli** [comment]
`<a @click="$electron.remote.getCurrentWindow().close()">X</a>`

**Comment by Dsaint109** [comment]
I did this:
> methods: {
    Close() { this.$electron.remote.BrowserWindow.getCurrentWindow().close()
}
}
