### ISSUE TITLE
electron-packager error

### ISSUE THREAD

**Issue by lijun090823** [SimulatedGREG/electron-vue#461]
##### Tell me about your development environment.
  * Node version:v8.4.0
  * NPM version: 5.3.0
  * vue-cli version:2.8.1
  * Operating System:
electron-packager  
 
![image](https://user-images.githubusercontent.com/33612117/33053233-7d1b39aa-cead-11e7-8081-54762c6c7492.png)

this is why？

**Comment by SimulatedGREG** [comment]
This is an error related to `electron-packager`. Please reach out to their respective communities for further guidance as this is not a direct issue with electron-vue.
