### ISSUE TITLE
How to open new browser window frim vue

### ISSUE THREAD

**Issue by Dsaint109** [SimulatedGREG/electron-vue#465]
Hi,
Thanks for this project, it's a life saver 

I am working with electron-vue and I want to open a new browser window on click of a button but I'm not sure how to go about it

**Comment by mdobeck** [comment]
Electron API. Open a shell. https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl

**Comment by SimulatedGREG** [comment]
This is not a direct issue with electron-vue, and I will be closing. Please know that the presensce of `electron` doesn't change how Vue.js is used. This is a question better suited for official documentation or respective communities.

**`electron`**
* https://electron.atom.io/docs/

**`vue`**
* https://vuejs.org/v2/guide/
* https://forum.vuejs.org/
* https://chat.vuejs.org/
