### ISSUE TITLE
How to enable cross-domain access under dev environment?

### ISSUE THREAD

**Issue by zuoxinyu** [SimulatedGREG/electron-vue#468]
I need access resources on remote server through ajax, but under development environment I can't obtain things cause of Same-Origin-Policy and the remote server doesn't set a Access-Control-Allow-Origin header.
So how to configure with ajax ?

**Comment by zhangwen9229** [comment]
[https://github.com/SimulatedGREG/electron-vue/issues/387](https://github.com/SimulatedGREG/electron-vue/issues/387)
