### ISSUE TITLE
How to Close from Renderer

### ISSUE THREAD

**Issue by philippefutureboy** [SimulatedGREG/electron-vue#469]
Hi!

I have a very simple question: How can I close the application from the renderer? Is there a communication bus between the renderer and the main bundles?

I tried to import electron.app directly in the renderer, to no avail. Is there any built-in way to do so? If not I would suggest the implementation of an event bus between the two entry points with predefined events (like app.quit).

Setup:
  * Node version: 8.9.1
  * Yarn version: 1.3.2
  * NPM version: 5.5.1
  * Operating System: macOS 10.13.1 High Sierra

Let me know what you think!

Cheers ✨

**Comment by pixeldesu** [comment]
@philippefutureboy You have `$electron` available in your Vue instance, so no need to import anything else from anywhere.

The best way to close the application from the renderer is using IPC channels electron provides.

Electron Documentation for IPC channels:

* [ipcMain](https://electronjs.org/docs/api/ipc-main)
* [ipcRenderer](https://electronjs.org/docs/api/ipc-renderer)

Small example:

```js
// Your component
<template>
  <div>
    <button @click="close">Close</button>
  </div>
</template>

<script>
export default {
  methods: {
    close: function () {
      this.$electron.ipcRenderer.send('close-event')
    }
  }
}
</script>

// app main index.js

import { ipcMain } from 'electron'

ipcMain.on('close-event', function (e) {
  e.sender.getOwnerBrowserWindow().close()
}
```

**Comment by philippefutureboy** [comment]
Many thanks 🌈  🕉  ✨

**Comment by rajjagani021** [comment]
@philippefutureboy  @pixeldesu 

Is this still working like this? I am trying to use the same way mentioned above but events are not getting triggered. When I trigger `ipcMain.send` it throws the below error. 

Event If I trigger this from one component to another then also it's not working. 

![ipc_error](https://user-images.githubusercontent.com/4434991/168459923-c67fff03-91dc-4175-ab39-fdebb9b85b62.png)

**Comment by p-hebert** [comment]
Hey @rajjagani021,

No, we've moved on from electron a while ago. If we did solve this I do not remember the solution, unfortunately.

I wish you luck in your endeavour!
