### ISSUE TITLE
Cannot Get Route

### ISSUE THREAD

**Issue by mazedulislamkhan** [SimulatedGREG/electron-vue#47]
### Found an issue or bug? Tell me all about!
I'm just playing with the `electron-vue` and unfortunately, I am having an issue with creating a new route. I am creating a route using the following in `src/routes.js:
```javascript
{
    path: '/application',
    name: 'application',
    component: require('components/ApplicationPageView')
}
```
And added a simple component that only display a message. I added the route link in the default `Links.vue` file like the following:

`<li><a href="/application">Application</a></li>`

Unfortunately, it doesn't work for me and shows cannot get route `/application`. Not sure what I am missing here. Any thoughts on this?

**Comment by SimulatedGREG** [comment]
Are you using Vue 2.x?

**Comment by mazedulislamkhan** [comment]
I am using Vue v2.0.3. In addition, I already tried with the new `<router-link/>`, no luck :/ Have you tested this on your end?

**Comment by SimulatedGREG** [comment]
@mazedulislamkhan 

Just tried with a fresh scaffold of electron-vue using defaults and was able to create another route and use `<router-link/>` to navigate to it.

**App.vue**
```html
<!-- ... -->
<template>
  <div>
    <router-view></router-view>
    <router-link to="langing-page">go-home</router-link>
    <router-link to="another-route">go-another-route</router-link>
  </div>
</template>
<!-- ... -->
```

**routes.js**
```js
//...
{
  path: '/another-route',
  name: 'another-route',
  component: require('components/AnotherRouteView')
}
//...
```

**components/AnotherRouteView.vue**
```html
<template>
  <div>this is another route</div>
</template>
```

If you have your project up on a repo and you'd like me to take a look, feel free to post a link.

**Comment by mazedulislamkhan** [comment]
@SimulatedGREG if I remove the following redirect routes or place the following redirect routes below all the new routes, then new routes works:
```JavaScript
{
    path: '*',
    redirect: '/'
}
```
Didn't understand why this _redirect routes_ in the `routes.js` file exists then if it redirects all the URLs to the `/`.

In the past, I was adding the `<router-link/>` to the `src/components/Links.vue` file. Adding the `<router-link/>` now adding to the `App.vue` fixed it.

**Comment by SimulatedGREG** [comment]
I believe this may be related to nesting routes as your first attempt put the `<router-link/>` inside `Links.vue` which is also nested within the `langing-page` view. Then modifying the *redirect route* made it work in this case. Glad you got this sorted out. ☺️

**Comment by wahengchang** [comment]
same error, @iamazik , do u have a sample repo that I can refer ?

**Comment by iamazik** [comment]
Unfortunately, I don't @wahengchang
