### ISSUE TITLE
File system is not available the first time the app is built

### ISSUE THREAD

**Issue by FrancisBou** [SimulatedGREG/electron-vue#470]
Whenever I build my all for the first time "npm run dev", filesystem operations are not successful.
In the example below, the callback is never called. However, when I refresh the window the file is read successfully. The reason for this test is because I did not have much success with Nedb either (from the docs). It seems to only work after I hit refresh as well. Setting a timeout did not help either, so I don't know if it's not ready or I'm doing something wrong here.

From my main.js file:

```
// I know this file exists
const myFile = path.join(remote.app.getPath('userData'), '/lastConnection.db');
const fs = require("fs");

fs.readFile(myFile , function (err, data) {
  if (err) {
    return console.error(err);
  }
  // This is never logged until I hit F5
  console.log("Asynchronous read: " + data.toString());
});
```

  * Node version: 8.8.1
  * Operating System: Windows

**Comment by PeachT** [comment]
- npm install --save-dev read-file-utf8

```
import Read from 'read-file-utf8';
import path from 'path';

try {
  const file = Read(path.join(remote.app.getPath('userData'), '/data.json'))
} catch (error) {}
```
I hope it helps you.

**Comment by FrancisBou** [comment]
@PeachT Unfortunately I still can't read the file the first time the app is loaded. The strange thing is that this only happens in developpement, I did not have this problem in production. This is an almost clean project and I had this problem on two machines hence the bug repport here. I'll keep investigating the issue.
