### ISSUE TITLE
Verification that Vuex works

### ISSUE THREAD

**Issue by davidAlittle** [SimulatedGREG/electron-vue#473]
Can anyone provide sample code of Vuex working with this project? 

Given that all the boilerplate is there (I included Vuex when setting up the project), I _should_ be able to just throw in a {{this.$store.state.count}} and at least show a value in my vue. 

I've tried all the "standard" vuex things, I'm not finding any way to get it to work. No errors, just nothing in the generated html.

**Comment by pixeldesu** [comment]
Almost, it looks like the state containing the number is not `counter` directly but `counter.main` (if that doesn't work try `Counter.main` instead)

https://github.com/SimulatedGREG/electron-vue/blob/master/template/src/renderer/store/modules/Counter.js#L2

**Comment by davidAlittle** [comment]
Gah! THANK YOU. It was your second suggestion: {{this.$store.state.Counter.main}}

It's confusing because it seems like .state should be a child of .Counter, if anything.

**Comment by pixeldesu** [comment]
@davidAlittle well each module has it's own state, and a module is part of the big overall state

technically, if you just wanted `this.$store.state.counter` to work, you could try changing the Counter-module state from

```js
const state = {
  main: 0
}
```

to something like

```js
const state = 0
```

but as you usually want to manage multiple things with one state, this is probably a pattern that goes against the general design of Vuex, who knows
