### ISSUE TITLE
Add stylelint support

### ISSUE THREAD

**Issue by pixeldesu** [SimulatedGREG/electron-vue#474]
To not just lint our lovely JS with ESLint, it also would be great to have support for [stylelint](https://stylelint.io/) in electron-vue.

It looks like the vue-cli webpack template is close to getting this included as well: https://github.com/vuejs-templates/webpack/pull/842

I already tried getting this to work myself, but except the npm tasks to run the linter for the Vue files I didn't get stuff working with webpack, maybe someone else has more luck and can get it into this boilerplate then!

**Comment by SimulatedGREG** [comment]
Intending to evaluate this and `eslint-plugin-vue` once electron-vue is converted for new vue-cli changes.
