### ISSUE TITLE
Error publishing to github

### ISSUE THREAD

**Issue by mbeatrizmagalhaes** [SimulatedGREG/electron-vue#475]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
Both in travis and appveyor I am getting an error when publishing to the release, since it doesn't exist. From what I understood from the documentation, the release should be automatically created by the CI.
Is it something wrong with the electron-builder configuration or am I doing something wrong? 
Thank you!

##### How can I reproduce this problem?
I have found this bug with generated code that uses electron-builder, with no changes in package.json nor in the appveyor.yaml and travis.yaml. I believe that following the documentation on CI integration should reproduce the problem

##### If visual, provide a screenshot.
<img width="975" alt="screen shot 2017-12-03 at 16 55 25" src="https://user-images.githubusercontent.com/7109748/33527570-f05b503e-d84a-11e7-9ddc-a68ad36e0af3.png">

##### Tell me about your development environment.
  * Node version: v8.7.0
  * NPM version: 5.4.2
  * vue-cli version: (if necessary)
  * Operating System: macOS High Sierra

**Comment by mbeatrizmagalhaes** [comment]
I triggered a new build, without changing nothing and the artifacts were already published successfully. 
However, the appveyor build failed with `The system cannot find the path specified.` (although it has published to github). Can you help me with this error or should I open a different issue? 
Thank you!

**Comment by mbeatrizmagalhaes** [comment]
Hi! I have some news on this.
I have some builds that are able to publish, but when changing the version to a new one the error returns.

**Comment by pixeldesu** [comment]
As the error suggests, it can't find a tag for `v0.0.1` or any subsequent release. 

Everytime you want to publish a new release you need to create a tag or a draft release on Github, otherwise the CI won't upload the created artifacts.

**Comment by develar** [comment]
1. Ensure that you are using latest version of electron-builder.
2. Pass CLI option `--publish=always` to automatically create draft releases. Or name yarn/npm task as `release`.

**Comment by mbeatrizmagalhaes** [comment]
Thanks for the answers. From the documentation, I understood that the release would be automatically created, hence my question. 
I've found that with the CLI option @develar suggested it works as I intended, thank you for the responses.
