### ISSUE TITLE
Static assets in CSS

### ISSUE THREAD

**Issue by synic** [SimulatedGREG/electron-vue#479]
##### Describe the issue / bug.

Static assets are accessible via `<img src="static/some_file.jpg">`, however, the following does not work:

```html
<div style="background: url('static/some_file.jpg');">
```

It works when you are developing, but not in the final packaged product, because it looks for `file:///static/some_file.jpg`, which does not exist.

If I change it to:

```html
<div style="background: url('/static/some_file.jpg');">
```
I get the error `Module not found: Error: an't resolve './static/some_file.jpg'`.

My question is, what am I doing wrong here?  Should be using `static` like this, or should be using `~@/assets/` instead?

##### Tell me about your development environment.
  * Node version: 7.10.0
  * NPM version: 5.5.1
  * vue-cli version: 2.9.2
  * Operating System: Ubuntu 17.10

**Comment by yuval1982** [comment]
Hi, did you manage to solve this issue? I'm having the same problem.

**Comment by kvinlambert** [comment]
Would also be interested in resolving this issue. Can't find a way to import font files in build.

**Comment by onekiloparsec** [comment]
I left a [comment](https://github.com/SimulatedGREG/electron-vue/issues/463#issuecomment-360444181) with my complete setup about static and css assets in #463 that can be of some interest here as well.

**Comment by SimulatedGREG** [comment]
The way you are consuming the image would make this considered an asset, as webpack will be handling the import. `static` assets are purely meant for items that are consumed outside of webpack. So yes, the comment that @kvinlambert left would be the proper recommendation.
