### ISSUE TITLE
"Can't resolve 'fs'" Error in "yarn run build:web" command (no error on yarn run build)

### ISSUE THREAD

**Issue by yangjianhua** [SimulatedGREG/electron-vue#480]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\# 
    Using the fs in electron-vue, and it works fine when running at client.
    And also build OK when "yarn run build" and "yarn run build:win"
    All fs works fine.

    But when run "yarn run build:web" it get error.

    Can't resolve 'fs' in '../'

    As the article: https://stackoverflow.com/questions/40959835/webpack-express-cannot-resolve-module-fs-request-dependency-is-expression

    1. Open webpack.web.config.js, add

node: {
    fs: "empty"
}
    compile OK, but there's nothings when open index.html, got nothing. (means no page component showed).

##### How can I reproduce this problem?
\#
1. import fs from 'fs'
2. yarn run build:web
3. got error

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:8.5.0
  * NPM version:5.4.2
  * vue-cli version: (if necessary)
  * Operating System:MacOS High Serria

**Comment by SimulatedGREG** [comment]
This is 100% expected behavior as browsers like Google Chrome or Firefox **do not** have access to node modules like `fs` or `path`.

Related: https://github.com/SimulatedGREG/electron-vue/issues/355
