### ISSUE TITLE
The local HTML file cannot be rendered blank

### ISSUE THREAD

**Issue by 617450941** [SimulatedGREG/electron-vue#481]
![image](https://user-images.githubusercontent.com/7607957/33823350-d4e6fc80-de95-11e7-8455-c76566b0ad65.png)
![image](https://user-images.githubusercontent.com/7607957/33823386-f0a4fea4-de95-11e7-87af-5aae2354b589.png)
![image](https://user-images.githubusercontent.com/7607957/33823406-fdf1b7b4-de95-11e7-8bcb-38f872794a46.png)
 The local HTML file cannot be rendered blank

**Comment by SimulatedGREG** [comment]
The current `webpack` setup **does not** support multiple html entries. You will need to modify the existing webpack configuration if you want multiple html entries.
