### ISSUE TITLE
Use Poi over Webpack

### ISSUE THREAD

**Issue by ryzokuken** [SimulatedGREG/electron-vue#484]
https://poi.js.org/
https://github.com/egoist/poi

Poi is a simpler, cleaner and more convenient alternative to using Webpack directly (it uses basically manages the heavy lifting for you). What's better is that is has been built by a member of the Vue team, and has built in support for making Vue projects with little to no assembly required. I suggest shifting to Poi over using Webpack directly for a more hands-off approach.

**Comment by SimulatedGREG** [comment]
electron-vue will not be switching away from `webpack `anytime soon as the Vue community favors `webpack` at the moment and for the foreseeable future. Thank you for the suggestion though.
