### ISSUE TITLE
[Question] Error when build with Firebase. 

### ISSUE THREAD

**Issue by Neewd** [SimulatedGREG/electron-vue#491]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.

I started my project with the electron-vue boilerplate, I communicate with a firebase database. 
When I run the "yarn run dev" that works just fine .. but when I try to build ... I got a a problem when I rebuild the native production dependencies. 

##### If visual, provide a screenshot.

http://www.hostingpics.net/viewer.php?id=295479Capturedecran20171230a160124.png

##### Tell me about your development environment.
  * Node version: v8.0.4
  * NPM version: 5.4.2
  * Operating System: OS X

If anyone can help me to integrate a firebase connection into the boilerplate I would be more than happy. 

Cheers.

**Comment by emjimadhu** [comment]
i had similar kind of error but when i build for web. and it has been answered here #365
