### ISSUE TITLE
How to call a vue method from a menu item?

### ISSUE THREAD

**Issue by karimhossenbux** [SimulatedGREG/electron-vue#492]
I have a menu which is define from the src/main/index.js inside createWindow(), I not sure if it's the correct way of doing it? But the Learn more button is working...

However I'm trying to console.log something from a menu item but not success.
My goal is to call a method which is available in a vue component... but I can't make a simple console.log works :(

Thank you in advance.
Happy new year!

````
function createWindow () {
  // OTHER CODE HERE FOR THE WINDOWS CREATION
  /* MENU */
  const template = [
    {
      label: 'Appname',
      submenu: [
        { role: 'about' },
        { type: 'separator' },
        {
          label: 'Test',
          click: () => { console.log('plop') }
        },
        {
          label: 'Learn more',
          click: () => { shell.openExternal('https://url') }
        },
        { type: 'separator' },
        { role: 'quit' }
      ]
    },
    {
      label: 'View',
      submenu: [
        { role: 'reload' }
      ]
    },
    {
      role: 'window',
      submenu: [
        { role: 'close' },
        { role: 'minimize' },
        { type: 'separator' },
        { role: 'front' }
      ]
    }
  ]
  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
}

app.on('ready', createWindow)
````

**Comment by SimulatedGREG** [comment]
You would need to use the `ipc` electron modules to communicate between the `main` and `renderer` processes.

https://electronjs.org/docs/api/ipc-renderer
https://electronjs.org/docs/api/ipc-main

See https://github.com/SimulatedGREG/electron-vue/issues/260 for an example.
