### ISSUE TITLE
Webpack loads static assets when running development but can't locate modules when packaged

### ISSUE THREAD

**Issue by LiamDotPro** [SimulatedGREG/electron-vue#495]
#### Found an issue or bug with electron-vue? Tell me all about it!

As per my reading of the documentation I have been using the development build just fine to load and get everything working, But when it comes to actually packaging up my build I get this error about loading modules

 `Uncaught Exception Error: Cannot find module "."` What I have noticed it that when I run the application in development all of my assets within the `static` folder are being parsed and transformed using webpack whereas I'm not able to find if there being added into the production build at all.

Within my index.js inside of main I am doing the following:

```
const Server = require(__static + "\\app\\server").default;

let server = new Server();
```

This loads up my server which inside has the following:

```
import express from 'express';
import {ipcMain, remote, BrowserWindow} from "electron";

const MailClients = require(__static + "\\app\\lib\\MailClients");
const MailWrapper = require(__static + "\\app\\lib\\MailWrapper");

export default class Server {
    constructor() {

        const app = express();

        // Highly unlikely that we will be port sharing.
        app.listen(4938);
    }


}
```

In development mode this runs absolutely fine but on packaging I'm getting what looks like some kind of default webpack error.

##### How can I reproduce this problem?
\# 

Create a new project using default settings and using the electron-builder, add a javascript file to static and then try to import and use it on the main process using require(__static + "path"). Once that's done you just want to package it up and then attempt to run the program.

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: 9.2.0
  * NPM version: 5.5.1
  * vue-cli version: (if necessary)
  * Operating System: Windows x64

**Comment by parion** [comment]
Did you ever figure this out?

**Comment by LiamDotPro** [comment]
@parion Yes, it depends heavily on how you interact with the file system strings as to where the static folder is detected from `__static` you should avoid using this in conjunction with relative strings. https://github.com/SimulatedGREG/electron-vue/blob/master/docs/en/using-static-assets.md
