### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by rodneyrehm** [SimulatedGREG/electron-vue#496]
Hey there,

thank your for this package. It got me up and running in no time. <3
After I got playing a bit I noticed:

* [package.json](https://github.com/SimulatedGREG/electron-vue/blob/master/template/package.json) is missing `sass-loader` (and `node-sass`, because it's a peer dependency) referenced in [.electron-vue/webpack.web.config.js](https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/webpack.web.config.js#L56-L59)
* eslint is still configured to use `eslint-plugin-html` instead of [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue)

would you like a PR for this?

**Comment by SimulatedGREG** [comment]
No PR will be necessary. I'll be having to do a pretty heavy overhauling now that `@vue/cli` is approaching final release. And that mention of `sass-loader` is needed because of the backwards nature that `sass-loader` has for handling Sass vs. SCSS.
