### ISSUE TITLE
How can I use fontawesome 5?

### ISSUE THREAD

**Issue by ODelibalta** [SimulatedGREG/electron-vue#497]
I am sorry that this is not technically an issue but I've asked two other questions on SO and did not get an answer for any of them. 

I have the font awesome 5 downloaded and I've put them under ```assets/fonts``` and I am trying to use it inside a components directory. 

![screen shot 2018-01-09 at 10 17 59 am](https://user-images.githubusercontent.com/4956550/34730953-7bbf999e-f526-11e7-8eb5-1e52df86a262.png)

**Comment by SimulatedGREG** [comment]
You can also import the font-awesome style sheets directly in your `App.vue`'s `<style>` tag using an `@import`.
