### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by K-Wen** [SimulatedGREG/electron-vue#498]
##### Describe the issue / bug.
Hello SimulatedGREG,
Today I use this package to start a electron-vue project and my steps just as the document said. After 'yarn run dev', I got a warning of "Critical dependency: the request of a dependency is an expression" and here is the full warning:
```
WARNING in ./node_modules/electron-debug/index.js
  81:45-58 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/electron-debug/index.js
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js
  
  WARNING in ./node_modules/electron-debug/index.js
  84:85-106 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/electron-debug/index.js
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js
```
What does this mean and if I need take care of something?

##### How can I reproduce this problem?
Here is my project configurations:
```
? Application Name test-project
? Project description this is a test project
? Select which Vue plugins to install axios, vue-electron, vue-router, vuex
? Use linting with ESLint? No
? Setup unit testing with Karma + Mocha? No
? Setup end-to-end testing with Spectron + Mocha? No
? What build tool would you like to use? builder
```
And then 
1.yarn 
2.yarn run dev
everything just as the guide

##### Tell me about your development environment.
  * Node version: v8.5.0
  * NPM version: v5.4.2
  * vue-cli version: (if necessary) v2.8.2
  * Operating System: macOS Sierra 10.12.5

**Comment by bdsoha** [comment]
Same issue here...

**Comment by JerryCjr** [comment]
Same issue here...

**Comment by dakshinasd** [comment]
Can confirm this exists

**Comment by wendzhue** [comment]
Same issue here...
I have to say I run into a lot of troubles with electron-vue...

**Comment by ifrias-fuze** [comment]
That's caused by electron-debug trying to require a module using a dynamic path, which webpack doesn't support.

**Comment by akaone** [comment]
How do we solve this tho ?

**Comment by ifrias-fuze** [comment]
ask electron-debug maintainer to fix that ? either him or webpack's team, other approach : fix that yourself, not difficult, 

there's a package on npm with that fixed @soleng-fuze/electron-debug,

**Comment by peteringram0** [comment]
Also getting this. If someone has a fix please share. Thanks

**Comment by qazbnm456** [comment]
Just pin the version of `electron-debug` to 1.4.0 like [this](https://github.com/LulumiProject/lulumi-browser/blob/master/package.json#L76).

The cause of the  problem is exactly what @ifrias-fuze mentioned, and the author doesn't want to fix this because he thinks it's webpack's fault. See https://github.com/sindresorhus/electron-debug/pull/59 for further details.

**Comment by bdsoha** [comment]
I am running _v1.5.0_ and still getting this issue

**Comment by qazbnm456** [comment]
The solution is to simply pin the version to 1.4.0, not the latest 1.5.0 one. Then, the error message will just vanish away.

If you still want to use the latest version, you will need to modify the code directly.

**Comment by gustavoSoriano** [comment]
Hi Guys ! i had same issue. I installed version 1.4.0 and resolved

**Comment by MeirionHughes** [comment]
You can just configure webpack to treat it as an external and not include `electron-debug` in the compilation.

**Comment by acapro** [comment]
I find @MeirionHughes solution nice since I can keep my dependencies up to date.  Here's a quick n dirty snippet to get rid of the warning:

add
```
externals: [{
  'electron-debug': 'electron-debug'
}],

```
to `webpack.main.config.js`

**Comment by junxion-io** [comment]
@acapro and if you already have this in there, what would you suggest?
```
externals: [
    ...Object.keys(dependencies || {})
  ]
```

**Comment by acapro** [comment]
@junxion-io this seems to work
```
externals: [
  ...Object.keys(dependencies || {}),
  {'electron-debug': 'electron-debug'}
],
```

**Comment by vlad909** [comment]
@JerryCjr shift-shift and press file-name :dagger:

**Comment by hyjiacan** [comment]
> Where is `webpack.main.config.js` within electron-vue? I'm not seeing it :/

`.electron-vue/webpack.main.config.js`
