### ISSUE TITLE
hot-reload weird issue

### ISSUE THREAD

**Issue by mshahbazi** [SimulatedGREG/electron-vue#499]
Thanks for the great work.

I have an issue with hot-reload. Actually I need to edit my code twice to see the changes. 
I tested it with a clean installation of Node, vue-cli, electron-vue. No success!
  * Node version: 8.9.4
  * NPM version:  5.6.0
  * Vue version: 2.9.2
  * Operating System: Windows 10

Really appreciate any help

**Comment by AlexVFornazieri** [comment]
@mshahbazi Have you tried deleting the 'node_modules' folder and run '$ npm install' again?
I had problems with hot-reload recently and this solved the problem.

**Comment by mshahbazi** [comment]
Thanks for your reply,
I found out that the hot-reload does not work on UNC paths.
Hope this save some time for those who may have the same issue.

Thanks again for the great work.
