### ISSUE TITLE
Can't use npm modules inside electron.js

### ISSUE THREAD

**Issue by simonwjackson** [SimulatedGREG/electron-vue#50]
##### Describe the issue / bug.

Can't use npm modules inside electron.js. _(socket.io for example)_

I know the `node_modules` are removed in the final build, but they seem to work only when included inside the Vue instance.

Is there some way i can still `require` these in `electron.js`?
##### How can I reproduce this problem?

``` bash
npm install --save socket.io
cd app 
npm install --save socket.io
npm run build:win32
# then execute exe
```

**/app/electron.js**

``` javascript
const io = require('socket.io')
```
##### If visual, provide a screenshot.

![image](https://cloud.githubusercontent.com/assets/189379/19838799/b034fed2-9ea4-11e6-963e-ebecee15b924.png)
##### Tell me about your development environment.
- Node version: 6.5.0
- NPM version: 3.10.8
- Operating System: Win 10

**Comment by SimulatedGREG** [comment]
@simonwjackson 

Any modules required within the scope of `app/src/main.js` will be bundled with webpack for the renderer process only. Modules required in `app/electron.js` will not work in production, after making a build. There's currently no plans to support bundling the main process at the moment ([more info](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/project_structure.html#on-the-subject-of-webpack-bundling)).

Related:
#22

**Comment by SimulatedGREG** [comment]
Looking to bring `electron-builder` support soon, which should make external modules for main process a lot easier to manage. Not many boilerplates handle this well so there is some pioneering to do since webpack is involved. Thanks for understanding.
