### ISSUE TITLE
Why does electron-vue installs Electron v1.7.5. which is half a year old?

### ISSUE THREAD

**Issue by AlexSHoffman** [SimulatedGREG/electron-vue#500]
I've just installed electron-vue with npm and noticed that it specifies `"electron": "^1.7.5" ` in **/package.json**, although in **/node_modules/electron/package.json** it says `"version": "1.7.10",` the newest one.

I'm not sure, is it the way it supposed to be?

---

- Node version: 9.4.0 (latest)
- NPM version: 5.6.0 (latest)
- vue-cli version: 2.9.2 (latest)
- Operating System: Windows 10

**Comment by jtidwe11** [comment]
@AlexSHoffman when you install, the caret (^) means that it will take the most recent minor version of the package.  By doing it this way, you should be able to safely use any newer minor version of the same major version without worrying about breaking changes.  It also keeps package owner from having to test the every time a new version comes out.  Google around for semver to learn more about it.

**Comment by SimulatedGREG** [comment]
https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by AlexSHoffman** [comment]
@SimulatedGREG thanks for the link. 
By the way, Greg if you have a few seconds could you take a look at [this stackoverflow issue](https://stackoverflow.com/questions/48481154/how-to-specify-another-disk-for-fs-readdirpath-in-electron-vue-app) (it's regarding your Wander project). No one posted any solution yet. I would really appreciate it.
