### ISSUE TITLE
The web contents size is not the same as the browser window size

### ISSUE THREAD

**Issue by JackieLs** [SimulatedGREG/electron-vue#502]
![image](https://user-images.githubusercontent.com/14228179/34935706-ba7ab4c8-fa19-11e7-8ba1-05b5d6b51d34.png)
The project is Generated by the latest version. 
I run `npm run dev`
Platform: Mac OS-10.13.2

**Comment by AlexVFornazieri** [comment]
@JackieLs 
This is the div#wrap, is centralized, see body and html elements size for confirm that as a issue.

**Comment by JackieLs** [comment]
![image](https://user-images.githubusercontent.com/14228179/34967611-14721dec-fa9f-11e7-8efd-eef208a1b08a.png)
@AlexVFornazieri I removed the div#app only remain html && body, and the size like the picture above.Element HTML width is 622, but the window width is 568.

**Comment by AlexVFornazieri** [comment]
@JackieLs Keep in mind that the desired size in the main/index.js file is the size of the window that will be opened, consequently the size of the web content according to standard code.

What happens is that the dev tools (the right) of the browser is open and occupying part of the width of the window, which ends up decreasing the available space for the web content (body, html), you can simply configure it for appear in a separate window in options menu (upper right corner) and choose the first option in "dock side".

Please, going to close that issue.

**Comment by JackieLs** [comment]
Just have a try, then you'll know that is not because of the dev-tools.Whatever, maybe This is shouldn’t your issue.This should be the electron's
