### ISSUE TITLE
Help: how to autoupdate 

### ISSUE THREAD

**Issue by tomy8910** [SimulatedGREG/electron-vue#504]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\# how do I do auto updates with github releases? ![My Electronic Voting System](https://github.com/tomy8910/evs). Do I have to edit the dist script in the package.json? Should I add a 
—publish=always. Also my target environment is windows and the appveyor script works perfectly as it creates a draft release every time I push a tag. Also, if it helps, I install my app through the releases. So it only installs .exe files to my windows computer. My only problem is that my developed app can not detect an update every time a new release is made? How do I do this with just the GitHub releases? You can view my repo( linked above).

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: 9.4.0
  * NPM version: 5.6.0
  * vue-cli version: (if necessary)
  * Operating System: macOS High Sierra

**Comment by SimulatedGREG** [comment]
This more pertains to `electron-builder` and how auto updates are handled. One important thing to know is that **you will need** a valid/paid code signing certificate if you want auto updates. If you don't want to get a certificate, you can set up an internal script in your application to check latest releases and point the user to a download link where they can manually get the new version.

Docs: https://www.electron.build/auto-update
