### ISSUE TITLE
[feat require]Support Webstorm electron main process debug

### ISSUE THREAD

**Issue by daviyang35** [SimulatedGREG/electron-vue#507]
Jetbrains Webstorm 2017.3.3 support debug electron main process directly.
this is the description blog [Getting started with Electron in WebStorm](https://blog.jetbrains.com/webstorm/2016/05/getting-started-with-electron-in-webstorm/?utm_source=weibo&utm_medium=post&utm_campaign=regular_task)

##### How can I reproduce this problem?
change the electron-vue template support debug electron main process directly.

##### Tell me about your development environment.

```
         Vue : 2.9.2
        Node : v9.4.0
        Host : Mac OS X 10.13.2 (17C205)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
```

**Comment by SimulatedGREG** [comment]
There won't be any official support for debugging in this manner. If you want debugging, you need to remotely attach to the existing process that `npm run dev` yields.

Docs: https://simulatedgreg.gitbooks.io/electron-vue/content/en/debugging-production.html
