### ISSUE TITLE
minimized prod version instead of build exe

### ISSUE THREAD

**Issue by bluelemonade** [SimulatedGREG/electron-vue#508]
hello,

is it possible to run a biuld process for an minimized version without the dll/exe stuff. something I could run with electron .  That would be great for permanent changing apps in showrooms. to update the whole dll stuff is a big package.

regards

**Comment by bluelemonade** [comment]
ok, I can use the dist folder and put an package.json with the path to electron/main.js and the used dependencies. it works for me.

thanks

**Comment by erguotou520** [comment]
close the issue please
