### ISSUE TITLE
Throw eslint error when importing css file

### ISSUE THREAD

**Issue by sheguloves** [SimulatedGREG/electron-vue#511]
I followed document and imported bootstrap, but eslint throw an error.

The [spectre.css](https://github.com/picturepan2/spectre) is a Lightweight, Responsive and Modern CSS Framework, no dependency.

```
> eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src


  ✘  https://google.com/#q=import%2Ffirst  Absolute imports should come before relative imports
  src/renderer/main.js:8:8
  import 'spectre.css/dist/spectre.css';
               ^


✘ 1 problem (1 error, 0 warnings)
```

Then I use `import 'bulma/css/bulma.css';`, error is still there

**Comment by SimulatedGREG** [comment]
Please read the error fully, as it explains exactly what the issue is.
