### ISSUE TITLE
How to show vue-devtools in electron?

### ISSUE THREAD

**Issue by 18621132966** [SimulatedGREG/electron-vue#512]
#### 
Just follow these commands:

vue init simulatedgreg/electron-vue my-project
cd my-project
yarn
yarn run dev

By default, It should appear the vue-devtools, but it doesn't.

##### Screenshot
![_20180124202234](https://user-images.githubusercontent.com/17920881/35331971-598f8c74-0144-11e8-9251-d584845a3dea.png)

After electron startup for a while, console show this message:

┏ Electron -------------------

  Failed to fetch extension, trying 4 more times

┗ ----------------------------

##### Development environment
  * vue-electro: 1.0.6
  * Node version: 7.9.0
  * NPM version: 5.6.0
  * vue-cli version: (if necessary) 2.9.2
  * Operating System: win7-sp1 x64-based

**Comment by 18621132966** [comment]
I finally solved the problem. 
The reason is: Chrome extention server cannot access by normally in China .
So use some proxy and run dev, then the extention is cached into folder "%USERPROFILE%\AppData\Roaming\Electron\extensions". Now, you can use the devtools without proxy.
If you want use it offline, just download the zip file (version 4.1.1) and unzip it to the cache folder. Restart you dev, then it works.
[nhdogjmejiglipccpnnnanhbledajbpd.zip](https://github.com/SimulatedGREG/electron-vue/files/1667205/nhdogjmejiglipccpnnnanhbledajbpd.zip)

**Comment by jeeftor** [comment]
Any idea where this folder would be on linux or mac?

**Comment by JoeShi** [comment]
@jeeftor 

It is under `/Users/<usrname>/Library/Application Support/Electron/extensions` on mac
