### ISSUE TITLE
Firestore is not a function

### ISSUE THREAD

**Issue by mlapeyre3** [SimulatedGREG/electron-vue#513]
##### Describe the issue / bug.
Hi there,
I am using this vue-cli template to create a new VueJs+Electron project powered by [Firestore](https://firebase.google.com/docs/firestore/).
However, when I define the configuration of my VueJs client to connect with my Firestore database, I receive a `firebaseApp.firestore is not a function`.
I first asked the question at  https://github.com/firebase/firebase-js-sdk/issues/464

##### How can I reproduce this problem?
You may clone https://github.com/mlapeyre3/firestore-issue-464 to reproduce the issue. Just run `yarn` then `yarn run dev`.
My configuration is
```
import firebase from 'firebase';
import 'firebase/firestore';

const firebaseApp = firebase.initializeApp({
  apiKey: '...',
  authDomain: '...',
  databaseURL: '...',
  projectId: '...',
  storageBucket: '...',
  messagingSenderId: '...',
});


const auth = firebaseApp.auth();
const db = firebaseApp.firestore();

export { db, auth };
```
However this should not be the source of my issue as, when using an other vue-cli template (`webpack` instead of `simulatedgreg/electron-vue` as described in [this tutorial)](https://scotch.io/tutorials/getting-started-with-firebase-cloud-firestore-build-a-vue-contact-app) it works perfectly.

##### If visual, provide a screenshot.
![2018-01-24_15h51_31](https://user-images.githubusercontent.com/19735493/35338727-f984e718-011e-11e8-9265-a813c87cb3b7.png)
![2018-01-24_15h55_10](https://user-images.githubusercontent.com/19735493/35338741-01fcdb76-011f-11e8-9a13-4c54fe575eac.png)
![2018-01-24_15h54_20](https://user-images.githubusercontent.com/19735493/35338737-fe58b5b2-011e-11e8-8d8b-3b33794c2dd2.png)

##### Tell me about your development environment.
  * Node version: 8.9.0
  * Yarn version: 1.3.2
  * vue-cli version: 2.8.2
  * Operating System: Windows Version	10.0.16299 Build 16299

**Comment by mlapeyre3** [comment]
Hi there,

In a very ugly way, I manage to initialise the firestore SDK directly in *index.ejs* file.
```
<script src="https://www.gstatic.com/firebasejs/4.9.0/firebase.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.9.0/firebase-firestore.js"></script>
var config = {
  apiKey: "..."
  ...
  };
  firebase.initializeApp(config);
  var db = firebase.firestore();
```

This will do the job for the moment but it is not production ready :)

If you have any idea on how to manage this SDK properly ... please tell me!
Thanks!

**Comment by SimulatedGREG** [comment]
I've honestly see so many issues with the `firebase` sdk with webpack. Firebase just really _insists_ you import via a `<script>` tag. There are a few other issues that may both checking. I'm going to close this as it isn't a direct issue with the boilerplate.

**Comment by rohan2388** [comment]
I am also facing similar problem.
![developer tools - http___localhost_9080_ 2018-02-27 01 35 22](https://user-images.githubusercontent.com/20577654/36692592-8ba827e6-1b5e-11e8-8e39-68b71afb726f.png)

Thanks @mlapeyre3 for your 'ugly' solution though, atleast its working!

**Comment by padarom** [comment]
```js
import firebase from 'firebase'
require('firebase/firestore')

console.log(typeof firebase.firestore)
// "function"
```

This solved it for me. `firebase/firestore` has side effects, so I had to require, rather than import it.

**Comment by bdiz** [comment]
@mlapeyre3 I think I've got it. Was from a post related to importing codemirror with electron-webpack. [https://github.com/electron-userland/electron-webpack/issues/81](https://github.com/electron-userland/electron-webpack/issues/81)

This worked for me.

```
// package.json
{
  ...
  "electronWebpack": {
    "whiteListedModules": [
      "firebase"
    ]   
  },
  ...
}
```

**Comment by RJSeven** [comment]
Btw, this worked for me:

I used this:
```
import firebase from '@firebase/app';
import '@firebase/firestore'
```

Rather than this:
```
import firebase from 'firebase';
import 'firebase/firestore';
```

**Comment by muhyidin3222** [comment]
I fixed it by importing multiple libraries: firebase and firebase/firestore. That's because the firebase core library does not include the firestore library innately. So the full code to fix it is:
```

import * as firebase from 'firebase';
import 'firebase/firestore';
```
