### ISSUE TITLE
index.ejs have an error

### ISSUE THREAD

**Issue by StormKid** [SimulatedGREG/electron-vue#514]
Please Look at this picture:

![5g_j 83oqsx 8ix phv5ste](https://user-images.githubusercontent.com/13798727/35367044-4ea34dd2-01b7-11e8-84c7-ea321e81c7cc.png)

And I has done in this picture to solve the problem of this mistake:
![9 3hphe 9kl sdu9 gt ub4](https://user-images.githubusercontent.com/13798727/35367191-0564e77e-01b8-11e8-82e2-a4e03cb07019.png)

Would you please solve this problem while version update?

**Comment by erguotou520** [comment]
+1

**Comment by SimulatedGREG** [comment]
This is a non-issue, as it only pertains to how a text editor will read this. On a full build this doesn't happen as the end result yields `.push('<node_modules path>')`, which in the end follows the `standard` js linting rule of using single quotes.

Related: https://github.com/SimulatedGREG/electron-vue/pull/283
