### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by LWH2017** [SimulatedGREG/electron-vue#516]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
ReferenceError: process is not defined
##### How can I reproduce this problem?
\#
ReferenceError: process is not defined
##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by SimulatedGREG** [comment]
This ticket does not provide enough information on how to reproduce the issue you are running into. Please provide steps to reproduce.

**Comment by ShavidzeT** [comment]
When we build project with `yarn build:web` it throws runtime exception
Because `process` is undefined variable https://github.com/SimulatedGREG/electron-vue/blob/master/template/src/index.ejs#L17
