### ISSUE TITLE
Is it possible to integrate a nodeJS in an electron?

### ISSUE THREAD

**Issue by voroncv** [SimulatedGREG/electron-vue#523]
I need it after the project is build, when I start it, raise the server on the nodeJS and send requests. This can be done? Help please.

**Comment by SimulatedGREG** [comment]
This is not a direct issue with electron-vue, and I will be closing. Please know that the presensce of `electron` doesn't change how Vue.js is used. This is a question better suited for official documentation or respective communities.

**`electron`**
* https://electron.atom.io/docs/

**`vue`**
* https://vuejs.org/v2/guide/
* https://forum.vuejs.org/
* https://chat.vuejs.org/
