### ISSUE TITLE
Startup bug on WSL.

### ISSUE THREAD

**Issue by itsacorn** [SimulatedGREG/electron-vue#535]
##### Describe the issue / bug.
When doing `npm run dev`, i get this error: https://hastebin.com/ukelugitax.tex
Electron by itself works.

##### How can I reproduce this problem?
I installed all dev dependences. I ran `npm run dev`. I get a crash. I am sad.

##### Tell me about your development environment.
  * Node version: 9.5.0
  * NPM version: 5.6.0
  * vue-cli version: 2.9.2. I know theres 2.9.3 but who cares...
  * Operating System: Ubuntu on Windows (basically 16.04)

**Comment by DanMossa** [comment]
```
sudo apt-get install libxss1
sudo apt install libgconf2-4
```

**Comment by SimulatedGREG** [comment]
This is definitely outside the scope of electron-vue (as a boilerplate).
