### ISSUE TITLE
ERROR in unknown: Octal literal in strict mode (5457:23)

### ISSUE THREAD

**Issue by CrzKev** [SimulatedGREG/electron-vue#537]
Have exactly the same problem as(https://github.com/SimulatedGREG/electron-vue/issues/314).
I can't find the problem have an issue with a plugin (vue2-ace-editor) I use and he said they don't use octal values in his code (https://github.com/chairuosen/vue2-ace-editor/issues/17).
Is there an easy way to debug this.
The error is easily reproducible.
1) vue init simulatedgreg/electron-vue electron-vue-project-test
2) cd electron-vue-project-test
3) npm install
4) npm install --save-dev vue2-ace-editor
5) Add to the main.js 
  import Vue2AceEditor from 'vue2-ace-editor'
  Vue.use(Vue2AceEditor)
6) npm run build ## (**side note npm run dev WORKS**)
![image](https://user-images.githubusercontent.com/33102056/36273724-bc1ee2fc-1285-11e8-805b-61de260fc6c4.png)

**Comment by lcherone** [comment]
@CrzKev Had the same issue with that package its not a vue-electron issue, rather its to do with emmet if you look into the actual code thats used its a cloud9 build for the ace demo page https://github.com/cloud9ide/emmet-core/blob/master/emmet.js wade though the code you will see many instances of `\211PNG\r\n\032\n` for string matching etc, I couldn't find the particular line which is causing the problem but i'm sure there is many. I dont think its suited for use with electron-builder. You could try finding another version of emmet getting it to work and the doing a PR.. Though what I did as Im not interested in emmet, is to just include the following 60 line module somewhere and add `"brace": "^0.11.0"` to package.json.

```
var ace = require('brace')

module.exports = {
  template: `<div style="position: relative" :style="{ height: height ? px(height) : '100%', width: width ? px(width) : '100%'}"></div>`,
  props: {
    value: {
      type: String,
      required: true
    },
    lang: String,
    theme: String,
    height: true,
    width: true
  },
  data: function () {
    return {
      editor: null,
      contentBackup: ''
    }
  },
  methods: {
    px (n) {
      if (/^\d*$/.test(n)) {
        return n + 'px'
      }
      return n
    }
  },
  watch: {
    value: function (val) {
      if (this.contentBackup !== val) {
        this.editor.setValue(val, 1)
      }
    },
    theme: function (newTheme) {
      this.editor.setTheme('ace/theme/' + newTheme)
    },
    lang: function (newLang) {
      this.editor.getSession().setMode('ace/mode/' + newLang)
    }
  },
  mounted: function () {
    var lang = this.lang || 'text'
    var theme = this.theme || 'chrome'

    this.editor = ace.edit(this.$el)

    this.$emit('init', this.editor)

    this.editor.$blockScrolling = Infinity
    this.editor.getSession().setMode('ace/mode/' + lang)
    this.editor.setTheme('ace/theme/' + theme)
    this.editor.setValue(this.value, 1)

    this.editor.on('change', () => {
      var content = this.editor.getValue()
      this.$emit('input', content)
      this.contentBackup = content
    })
  }
}
```

I submitted a pull request to the package, which also fixes some original linting issues, but not the emmet one.

Sometimes its just easier to copy the needed lines of code from these kind of packages.

Anyways hope it helps.
