### ISSUE TITLE
Console shows "Electron Security Warning" after the last update

### ISSUE THREAD

**Issue by AlexSHoffman** [SimulatedGREG/electron-vue#540]
Is anyone else seeing this? 

##### How to reproduce this problem:
- Create a new electron-vue project
- Run it (`yarn run dev`)
- You should see the "Electron Security Warning" in the console right away

##### Tell me about your development environment.
  * Node version: 9.4.0
  * NPM version: 5.6.0
  * vue-cli version: 2.5.13
  * Operating System: Win10

**Comment by qazbnm456** [comment]
Electron has added these security warnings in recent version. They'll show up only the binary name is **electron**.

Further investigation is at https://github.com/electron/electron/issues/11970.

**Comment by AlexSHoffman** [comment]
@qazbnm456 thanks for the info! 
So all I have to do to get rid of this message is to change the name of the process? 

This message might be the most useless warning ever. It makes it sound like your app has some backdoors or some serious security holes allowing anybody to execute any code remotely.

**Comment by qazbnm456** [comment]
Yes, or if you're using Electron 2.0, you can also disable them by setting environment variables.

Ref: https://github.com/electron/electron/blob/master/docs/tutorial/security.md#electron-security-warnings

**Comment by robin7331** [comment]
Not sure if disabling the warning resolves the actual issue. Why is this closed?

**Comment by AlexSHoffman** [comment]
@robin7331 you are right, it just hides all those scary warnings, but there's still no explanation on how to fix those problems and why Chrome considers Node.js such a great threat

**Comment by AlexSHoffman** [comment]
@robin7331 you are right, it just hides all those scary warnings, but there's still no explanation on how to fix those problems and why Chrome considers Node.js such a great threat

Here's a follow up thread: https://github.com/electron/electron/issues/12049
