### ISSUE TITLE
how to use vue plugin ( vuex , router ) other html file

### ISSUE THREAD

**Issue by m-alinasab** [SimulatedGREG/electron-vue#541]
hi .
 
after create html file and Load to other window , how to use vue plugin ( vuex , router ) ?

i want create a factor page for print factor .

**Comment by SimulatedGREG** [comment]
This is not a direct issue with electron-vue, and I will be closing. Please know that the presensce of `electron` doesn't change how Vue.js is used. This is a question better suited for official documentation or respective communities.

**`electron`**
* https://electron.atom.io/docs/

**`vue`**
* https://vuejs.org/v2/guide/
* https://forum.vuejs.org/
* https://chat.vuejs.org/
