### ISSUE TITLE
On `vue init` error: `warning Failed to append commit SHA on README.md`

### ISSUE THREAD

**Issue by Hyjaz** [SimulatedGREG/electron-vue#543]
##### issue / bug.
I have downloaded the cli, when I do the following command:
`vue init simulatedgreg/electron-vue my-project`, I get the following error:
`warning Failed to append commit SHA on README.md`.

I saw this same error on another issue, but there was no apparent solution.

  * Node version: v8.9.4
  * NPM version:5.6.0
  * vue-cli version: (if necessary) 2.9.3
  * Operating System: mac os sierra 10.12.6

**Comment by DanMossa** [comment]
I am also having this issue.

Node version: v9.6.1
NPM version:5.7.1
Operating System: mac os High Sierra 10.13.3

**Comment by betteryourweb** [comment]
I'm having the exact same problem. I thought the issue may have been vue-cli, however, I'm able to init webpack and webpack-simple projects...

- Distributor ID:	Debian
- Description:	Debian GNU/Linux 9.3 (stretch)
- Release:	9.3
- Codename:	stretch
- NPM version 5.7.1
- Node version v9.7.1

**Comment by SimulatedGREG** [comment]
You can safely ignore this `warning`. This is a step in the scaffolding that attempts to add on the commit SHA on your readme.

![image](https://user-images.githubusercontent.com/8327811/40634764-54b3d97e-62bc-11e8-8ad4-6135d543e88d.png)
