### ISSUE TITLE
background window as worker

### ISSUE THREAD

**Issue by Blaapje** [SimulatedGREG/electron-vue#544]
I'm using the [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3) module in my application, which has been great so far together with electron-vue. However, my queries can be quite extensive, blocking the main thread for as much as 6 seconds at times. There's not really much to win there, so I tried offloading the database operations to a separate thread/process.

My first try was creating a webworker for sqlite3 with worker-loader. While the worker is easy to set up, requireing the better-sqlite3 module results in bindings not being found [(similar issue)](https://github.com/JoshuaWise/better-sqlite3/issues/44). My best guess is that this is either an issue with webpack or else some permission issue with web workers in general. In any case, I was not able to figure this out nor get a solid lead on the cause.

So my second approach was to use a background window and run my sqlite3 database there. Communication would need to happen via either IPC or [electron-remote](https://github.com/electron-userland/electron-remote). I liked the remote approach, but could not see how to apply this in electron-vue. The IPC approach kind of worked, but I ended up with a window that lived in the same "url space" (e.g. I had it pointing to a component called Background which handled all the messages and database calls). Electron started throwing errors after some time, apparently the backgroundWindow was suddenly undefined in index.js

My question is, given the added complexity of webpack/router/vue etc. how can I implement this example: [electron-background-task-app](https://github.com/johnhaley81/electron-background-task-app)? I really just want the backgroundWindow to load a script that I can communicate with through IPC. Adding components and routes doesn't feel like the right way to go for me.

**Comment by Blaapje** [comment]
Think I found my solution:
http://electron.rocks/different-ways-to-communicate-between-main-and-renderer-process/

Will update this post later with my findings for future readers.

**Comment by emjimadhu** [comment]
@Blaapje have you found the solution? i am facing the same issue.
