### ISSUE TITLE
Is there a Bootstrap 4 implementation of this?

### ISSUE THREAD

**Issue by kinoli** [SimulatedGREG/electron-vue#545]
Just wondering if anyone has added Bootstrap 4 to the library or if there's any instructions anyone could give on this, before I try it.

**Comment by lcherone** [comment]
Adding bootstrap is no different to adding any other CSS lib, though it feels wrong to bring in jQuery ;p

`npm install bootstrap-4 popper.js jquery --save`

Then add the following to `src/renderer/main.js`

```
/* eslint-disable no-unused-vars */
import $ from 'jquery'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap/dist/js/bootstrap.bundle.min.js'
```

Then add something to `LandingPage.vue`, for example, source from: https://getbootstrap.com/docs/4.0/examples/jumbotron/

![enter image description here](https://i.imgur.com/xoaO9iX.png)

Maybe that helps.

**Comment by kinoli** [comment]
Thanks for the reply. I ended up using ElementUI.

**Comment by jasonbronson** [comment]
bootstrap-vue npm package exists
https://www.npmjs.com/package/bootstrap-vue
