### ISSUE TITLE
Blank page after build

### ISSUE THREAD

**Issue by Almoullim** [SimulatedGREG/electron-vue#546]
##### Describe the issue / bug.
After issuing `yarn build` or `npm run build` the resulting app is just a blank page.

##### How can I reproduce this problem?
just build the application using either npm or yarn. A repo with the all the source files can be found here => https://github.com/Almoullim/air-date

##### Tell me about your development environment.
  * Node version: v8.9.4
  * NPM version: 5.6.0
  * vue-cli version: 2.9.3
  * Operating System: Ubuntu 17.10

**Comment by lcherone** [comment]
Don't remove the frame whilst developing, you need to access devtools!

Then run: `npm run dev`

Console shows `Uncaught TypeError: Cannot read property 'split' of null`

Which points to this line in your `mainView.vue` component:

`var jsonlist = localStorage.getItem('tvname').split(',');`

Solution check `localStorage.getItem('tvname')` before trying to split it.

**Basic debugging, not really a vue-electron bug.**

**Comment by Almoullim** [comment]
@lcherone 
I access the devtools using <kbd>Ctrl+Shift+I</kbd>, I don't need them to popup automaticaly.
In regard to the error you mentioned, I do not get it when I run `npm run dev` on my machine. You're probably getting that error because localStorage is empty on your end. Which explains why I wasn't getting the error and couldn't figure out what the issue what. 

If only there was an option to enable devtools in production mode! I've looked everywhere but couldn't find any.

Thanks for the help!

**Comment by SimulatedGREG** [comment]
https://simulatedgreg.gitbooks.io/electron-vue/content/en/debugging-production.html
