### ISSUE TITLE
node module not working

### ISSUE THREAD

**Issue by kunaldodiya** [SimulatedGREG/electron-vue#547]
youtube-dl is installed globally, and also as node_module

```
npm install youtube-dl
```

```
var { spawnSync } = require("child_process")

const ls = spawnSync('youtube-dl', [
          "https://oload.tv/embed/1q10JGbGLAs",
          "--skip-download",
          "--dump-json"
        ]);
````

code works and get video information only when I run command,
```
npm run dev
```

but when app is build running
```
npm run build:darwin
```

nothing happens, any help would be great.

**Comment by SimulatedGREG** [comment]
You need to ensure that the `youtube-dl` binary exists within your production build. You should be able to place the binary within the `/static` directory and then reconfigure your `spawnSync` command to point towards that binary in production.
