### ISSUE TITLE
All of a sudden my app is a mere directory listing.

### ISSUE THREAD

**Issue by sustained** [SimulatedGREG/electron-vue#549]
##### Describe the issue / bug.
My app is now a directory listing.

##### How can I reproduce this problem?
Go to bed, wake up, then start the project to suddenly have a directory listing instead of an app.

No, sorry, I have no idea.

This has happened before, for seemingly no reason. I don't know why. It just stopped doing it the last time. 

##### If visual, provide a screenshot.
![screenshot from 2018-03-01 14-31-23](https://user-images.githubusercontent.com/5995080/36849953-4d44193c-1d5d-11e8-8983-ddc8e673faff.png)

##### Tell me about your development environment.
  * Node version: 7.10.0
  * NPM version: 4.2.0
  * Operating System: Fedora

**Comment by sustained** [comment]
And it fixed itself again. Interesting. Don't ask, I don't know.

**Comment by kwen8** [comment]
if u have some eslint error then it will show this page

**Comment by KrustyC** [comment]
I got the same but without electron, any insights?

**Comment by clementvp** [comment]
I have this on a fresh install of the boiler plate.

**Comment by theodark** [comment]
@KrustyC  @clementvp check thoroughly the console messages. There should be something logged.

 @clementvp maybe you have an outdated version of npm / node / library ?

**Comment by sarjanwebdev** [comment]
In my case I had removed axios, re-installed that dependency and I am fine now.

**Comment by vimalmistry** [comment]
I have same problem today. It was working last day. I changed nothing. nothing updated. Today suddenly it shows directory list. Please any solution. I have deadline. and cant figured out it by myself.
I removed axios still not works.

**Comment by jessecrofutt** [comment]
This just happened to me. I walked my project changes back to yesterday when everything worked but I still have the same directory listing. I just pushed the code to a Github Page and it runs there.

**Comment by leandrowylde** [comment]
I have this same problem here. After installing the library moment.js the problem occurs and returning to what it was before did not resolve the problem. Any idea?

**Comment by e1016** [comment]
in my case I broke the file `.eslintrc.js` meanwhile I update node.js from 8 to 10 (in this process node-sass was broken too), to create, check for `.eslintrc.js` file, use node 8, and reinstall node-sass: `npm i -g node-sass`, It's weird situation...

**Comment by sugoidesune** [comment]
I had the port 3000 blocked by another server.

**Comment by davidwang1988** [comment]
for me, it is caused by a wrong src
