### ISSUE TITLE
Blank app after yarn run build, and it's a new template totally

### ISSUE THREAD

**Issue by shuiRong** [SimulatedGREG/electron-vue#551]
##### Describe the issue / bug.
\#

I tried to init template and build it immediatly:

```
$ vue init simulatedgreg/electron-vue test
$ cd test
& yarn && yarn run build:darwin
```
and I have result is blank app window

I got this when i use `electron path/test.app/Contents/MacOS/test`

![image](https://user-images.githubusercontent.com/16076993/36885795-11fe058c-1e24-11e8-8ba8-0d5da13dd8d0.png)

##### How can I reproduce this problem?
\#

see above

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:  9.5.0
  * NPM version:   5.6.0
  * vue-cli version: (if necessary)  2.9.2
  * Operating System: OSX 10.13.1

**I watched some other issued and that does not worked, thanks a lot for any help**

**Comment by shuiRong** [comment]
Here is a [solution](https://github.com/SimulatedGREG/electron-vue/issues/515),
But i don't think it's a perfect answer.

**Comment by XanderLuciano** [comment]
Closed due to age. Many dependencies have been updated and it is likely this has been fixed. Please let me know or create a new issue if this is still a problem.
