### ISSUE TITLE
Singleton and multiple windows

### ISSUE THREAD

**Issue by simdax** [SimulatedGREG/electron-vue#553]
Hello all,

As I saw, the classic way of doing multiple windows is to instantiate a new Browser Window calling the main process URL + the name of your component view.

The problem is that these technique rebuild a new complete Instance of Vue, store included.

How can I prevent electron to rebuild an entire Vue app ? How can I pass a global object through these multiple Vue? Do I have to edit directly the build.js in .electron-vue, or can I pass object through BrowserWindow to instances ??

Thank you

**Comment by zxc23** [comment]
This has been discussed in #256
