### ISSUE TITLE
Can not @import .less files

### ISSUE THREAD

**Issue by AthusVieira** [SimulatedGREG/electron-vue#555]
Electron-Vue seems to no compile very well when I import less files inside a component using the style tags (and the log shows nothing... ). I've installed the less-loader and less as well, added it into webpack.rendererer.config.js as follow:

```
{
   test: /\.less$/,
   use: ExtractTextPlugin.extract({
       fallback: 'style-loader',
       use: 'css-loader!less-loader'
   })
},
```

and I've done some modification in this part:

```
{
    test: /\.vue$/,
    use: {
        loader: 'vue-loader',
        options: {
            extractCSS: process.env.NODE_ENV === 'production',
            loaders: {
                sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1',
                scss: 'vue-style-loader!css-loader!sass-loader',
                less: 'vue-style-loader!css-loader!less-loader'
            }
        }
    }
},
```

I've created another file called "theme.less" with these values:

```
@import '~iview/src/styles/index.less';

@primary-color: #8c0776;
@btn-border-radius: 0px;
@btn-border-radius-small: 0px;
```

and then I imported it into the style tag of my component, like this:

```
<style lang="less">
    @import '../assets/theme/theme.less';
</style>
```

When I run the command `npm run dev`, I just got a blank window with the message: 'Cannot GET /login.html'

If I remove the @import statement from the style tags, then everything works fine.

Note: I also tried to import the `theme.less` file into the .js script, but I got the same error.

  * Node version: 8.9.4
  * NPM version: 5.6.0
  * vue-cli version: 2.9.3
  * Operating System: Windows 10 Pro

Am I doing something wrong or is it an issue?

**Comment by vdcrea** [comment]
@AthusVieira it worked for me, with the same config described, and with iviewui, the same ui framework. Everything compile well.

For iviewui, you also have to `npm i iview-loader --save-dev` and change the vue loader like that:
```
{
  test: /\.vue$/,
  use: [
    {
      loader: 'vue-loader',
      options: {
        extractCSS: true,
        loaders: {
          sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1',
          scss: 'vue-style-loader!css-loader!sass-loader'
        }
      }
    },
    {
      loader: 'iview-loader',
      options: {
        prefix: false
      }
    }
  ]
}
```

**Comment by AthusVieira** [comment]
@vdcrea it worked with the config above. Thank you!
