### ISSUE TITLE
__stacit is not defined

### ISSUE THREAD

**Issue by silentpride** [SimulatedGREG/electron-vue#560]
Hello there !
My project is based on yours.
In [main.js], my code is like this:

/**
 * Set `__static` path to static files in production
 * https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-static-assets.html
 */
if (process.env.NODE_ENV !== 'development') {
    global.__static = require('path')
        .join(__dirname, '/static')
        .replace(/\\/g, '\\\\')
}
let iconPath = path.join(__static, 'icon.png')
let transparentIconPath = path.join(__static, 'transparent_icon.png')

when I run dev, everything is OK.
But, when I run build and run the project, err occurred : 
【A JavaScript error occurred in the main process】
【Uncaught Exception: ReferenceError: __stacic is not defined】

Any suggestion ? 
THX

**Comment by rodrigopavezi** [comment]
@silentpride did you find how to solve this issue? cheers

**Comment by pfreema1** [comment]
If anyone else comes across this issue, this is what solved it for me.  Inside `webpack.main.config.js` and `webpack.renderer.config.js` I had to comment out the if statements that were checking if the `process.env.NODE_ENV` was not equal to 'production'.

**Comment by silentpride** [comment]
@rodrigopavezi 
yeah. check your process.env.NODE_ENV.

**Comment by JsonMa** [comment]
this works for me, thanks!!!
