### ISSUE TITLE
Router Issue, Cannot Get when CTRL/CMD + R or Reload is Clicked

### ISSUE THREAD

**Issue by Quadriphobs1** [SimulatedGREG/electron-vue#561]
#### Found an issue or bug with electron-vue? Tell me all about it!
I have just tried the boilerplate out the first time, and I am moving from route to another route, at default it moves to the route, but if CTRL + R is clicked it shows cannot get error with the route link.

The following error is been shown in the console 

> Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-vdjZcosZlrT8RbIl66uL4P8KawZHjNSV+bVC3gpYylg='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

![sketch](https://user-images.githubusercontent.com/20229808/37510973-4f58f5a2-28fd-11e8-9cfa-b3c8a87751d3.png)

##### Tell me about your development environment.
  * Node version: 9.4.0
  * NPM version: 5.7.1
  * Operating System: Windows

**Comment by mtuchi** [comment]
How did you fix this issue, Am having the same issue

**Comment by Quadriphobs1** [comment]
I noticed i was using history mode in my routing instead of using hash bang mode so i changed it back to using hash mode

**Comment by AllanPinheiroDeLima** [comment]
3 hours stucked in this issue, now I have some closure. 
It isn't specified in the documentation? It is really simple, but messed up error
