### ISSUE TITLE
Error when importing vue-worker

### ISSUE THREAD

**Issue by devszr** [SimulatedGREG/electron-vue#562]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
 Getting an error when importing vue-worker within an electron-vue app. Not sure if this is caused by electron-vue or vue-worker. I've already posted an issue at vue-worker, thought I'll refer it here as well.
israelss/vue-worker/issues/11

##### How can I reproduce this problem?
refer israelss/vue-worker/issues/11

##### Tell me about your development environment.
  * Node version: v8.9.4
  * NPM version: 5.7.1
  * vue-cli version: (if necessary) 2.9.2

**Comment by SimulatedGREG** [comment]
Hey @devszr,

This looks to be an issue related to https://github.com/israelss/vue-worker/pull/5. In short, this module distributes a full ES6 syntax. The current webpack/babel setup ignores transpiling any dependency; this is a common standard used across all projects.
