### ISSUE TITLE
 The defined window global variable cannot be obtained.

### ISSUE THREAD

**Issue by zhouyuexie** [SimulatedGREG/electron-vue#564]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.

in `main.js` defined `window._et = {/****/}`, and then throw error "Uncaught ReferenceError: _et is not defined"

##### How can I reproduce this problem?

just defined some variable in you `main.js` and then use it.

##### If visual, provide a screenshot.

`main.js`:

```js
window._et = {
  config,
  utils
}
```

and you can in console input `_et`

##### Tell me about your development environment.
  * Node version:8.9.0
  * NPM version:5.5.1
  * vue-cli version: (if necessary)
  * Operating System: window 10

**Comment by mubaidr** [comment]
In electron script there is no `window` object. Instead there is `global` object available.

**Comment by zhouyuexie** [comment]
@mubaidr Thank you!

This really works.
