### ISSUE TITLE
Double roaming folder in Windows AppData folder

### ISSUE THREAD

**Issue by killua99** [SimulatedGREG/electron-vue#565]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
Hi, I'm having an issue with the instalation of my electron app on windows. When the app launch at first it generate two roaming data folders, one with the name of package.json and the second one with the meta title that the app has. Why?

##### How can I reproduce this problem?
Quite simple, write a name inside package.json and in index.ejs change the title meta to a different one.

##### Tell me about your development environment.
  * Node version: v9.7.1
  * YARN version: 1.5.1
  * vue-cli version: 2.9.3
  * Operating System: Windows 10

**Comment by SimulatedGREG** [comment]
That issue should be fixed now. https://github.com/SimulatedGREG/electron-vue/pull/530

**Comment by QuentinJanuel** [comment]
I still have the same issue today

**Comment by dam62500** [comment]
still same too
