### ISSUE TITLE
How to add support for muon?

### ISSUE THREAD

**Issue by thamaraiselvam** [SimulatedGREG/electron-vue#570]
How to add the support for muon?

I have tried below things.

changed electron-prebuilt in devDependencies and removed the `electron`

`"electron-prebuilt": "github:brave/electron-prebuilt",`
 
and added `.npmrc` file and changed the spawn at `dev-runner.js`

`electronProcess = spawn('electron', [__dirname, ...process.argv.slice(2)], options)`

but `npm run dev` throws following error 

**Error launching app
Unable to find Electron app at /var/www/html/manageyum/.electron-vue

Cannot find module '/var/www/html/manageyum/.electron-vue'**

Any idea how to make it work and what is the meaning of above error?

**Comment by SimulatedGREG** [comment]
This is definitely outside the scope of this boilerplate. At first glance, it would seem you need to change 
```js
electronProcess = spawn('electron', [__dirname, ...process.argv.slice(2)], options)
```
to...
```js
electronProcess = spawn('electron', [require('path').join(__dirname, '../'), ...process.argv.slice(2)], options)
```
