### ISSUE TITLE
can't drag file to the app window

### ISSUE THREAD

**Issue by jaweii** [SimulatedGREG/electron-vue#572]
* Electron version: 1.8.3
* Operating system: windows 10

### Expected behavior

I want to drag a file to the window of an electron app , But I can't do this, when I drag the file to the application window, the mouse cursor becomes disabled.

### Actual behavior

the mouse cursor changes to disabled: 🛇
can't capture drag & drop event

### How to reproduce

> 
> //Install vue-cli and scaffold boilerplate
> npm install -g vue-cli
> vue init simulatedgreg/electron-vue my-project
> 
> //Install dependencies and run your app
> cd my-project
> yarn # or npm install
> yarn run dev # or npm run dev
> 
> 
![2](https://user-images.githubusercontent.com/22613580/38015025-16f8328c-329d-11e8-83d9-0720733d362f.gif)

**Comment by erikkallen** [comment]
You are writing an application, it is not a browser if you want to build a picture viewer you should implement drag and drop support in your application have a look at this link it explains it in detail https://ourcodeworld.com/articles/read/288/how-to-handle-drag-and-drop-file-feature-in-electron-framework

**Comment by SimulatedGREG** [comment]
@jaweii 

Sorry for the late response! I actually ran into this very same issue from a past project. In short, this is a _dumb_ Windows thing. Please see https://github.com/electron/electron/issues/5243 for more info.
