### ISSUE TITLE
Process for debugging main

### ISSUE THREAD

**Issue by jeeftor** [SimulatedGREG/electron-vue#573]
##### Describe the issue / bug.
The FAQ only mentions debugging the render process - but my issues appear to be in the main process

Is there guidance on a best practice (or any practice) how to debug main?

**Comment by jeeftor** [comment]
I'm dumb:
Main Process

When running your application in development you may have noticed a message from the main process mentioning a remote debugger. Ever since the release of electron@^1.7.2, remote debugging over the Inspect API was introduced and can be easily accessed by opening the provided link with Google Chrome or through another debugger that can remotely attach to the process using the default port of 5858, such as Visual Studio Code.

┏ Electron -------------------

  Debugger listening on port 5858.
  Warning: This is an experimental feature and could change at any time.
  To start debugging, open the following URL in Chrome:
      chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5858/22271e96-df65-4bab-9207-da8c71117641

┗ ----------------------------

**Comment by wbern** [comment]
https://stackoverflow.com/questions/48091899/electron-main-and-renderer-process-debug-configuration/50787937#50787937
