### ISSUE TITLE
yarn run build only builds for mac?

### ISSUE THREAD

**Issue by junxion-io** [SimulatedGREG/electron-vue#578]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\# Not sure if this is a bug or my incompetence. I can't figure out how to build for all 3 platforms. I'm on a mac.

##### How can I reproduce this problem?
\# yarn run build is the command I'm using on a mac

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: the latest
  * NPM version: the latest
  * vue-cli version: (if necessary)
  * Operating System: OSX

**Comment by junxion-io** [comment]
It turns out updating the scripts portion of package.json like this allows for it to build an exe as well.

```
"build": "node .electron-vue/build.js && electron-builder -mwl --x64 --ia32"
```

**Comment by SimulatedGREG** [comment]
The build setup provided defaults to `electron-builder`'s defaults. So yes, you will need to manually configure other platforms if needed.
