### ISSUE TITLE
What can cause blank screen after build?

### ISSUE THREAD

**Issue by AlexVFornazieri** [SimulatedGREG/electron-vue#580]
Hi everyone, I'm developing a project to some time, it's already in a big point and I hear the need to migrate from Electron-packager to Electron-builder but I'm facing some problems, I hope you guys can help me.

Using an electron-vue project with the electron-builder created after Vue-CLI as a reference, I did:

- The substitution of ".electron-vue/build.js" together with the configurations of the particular processes of my project (besides main and renderer standart procceses).

- I changed the dependencies and scripts in "package.json" to respond to the project with "electron-builder".
 
- I deleted the "node-modules" folder completely and reinstalled all dependencies through npm.

Result, running normally with "npm run dev" but when running "npm run build" it required that "electron@1.7.5" be used to run the script.

Script build rotated to my surprise when running the application .exe the window is white and its processing locked.

As an attempt to work around the bug according to electron-userland/electron-builder#1615 I reinstalled all dependencies with Yarn, so I was able to run the build script with electron@1.8. 4, but so does the executable, white window.

Running the .exe through PowerShell as a form of debug logging does not return any error, just the normal project execution logs.

What could be causing this?

OS: Window 10 SL x64
Node: v8.10.0
Electron: v1.8.4
---------

**Comment by AlexVFornazieri** [comment]
Looking at more information I find out that it seems to be related to a temporary failure in electron reported at https://github.com/electron/electron/issues/11326 and https://github.com/SimulatedGREG/electron-vue/issues/515.

The last ref above presents a provisional solution, only that is in Chinese, in my translation and interpretation I understood that it would comment the line below in webpack.renderer.config.js:

`... Object.keys (dependencies || {}) .filter (d =>! WhiteListedModules.includes (d))`

But I still have not been able to solve it, maybe I misunderstood.

An interesting observation is that if you create a new electron-vue project with Electron-builder everything works perfectly.

**Comment by AlexVFornazieri** [comment]
Discussion transferred to #583

**Comment by amolngt** [comment]
Hello sir,

I am facing same issue.. when electron runs for long time(2-3 days) .... my electron(v1.7.10) app going to run 365 days 24 hours...previously i was using ia32 package on 64bit... now m using x64 on 64 bit
node version v8.11.3
npm version 5.6.0
see following cmd....

electron-packager . --overwrite --asar=true --platform=win32 --arch=x64 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName="CompanyName" --version-string.FileDescription=CE --win32metadata.requested-execution-level=requireAdministrator --version-string.ProductName="project_name"

will it be useful ?
should i update my electron

**Comment by amolngt** [comment]
> Looking at more information I find out that it seems to be related to a temporary failure in electron reported at [electron/electron#11326](https://github.com/electron/electron/issues/11326) and #515.
> 
> The last ref above presents a provisional solution, only that is in Chinese, in my translation and interpretation I understood that it would comment the line below in webpack.renderer.config.js:
> 
> `... Object.keys (dependencies || {}) .filter (d =>! WhiteListedModules.includes (d))`
> 
> But it not been able to solve for me, maybe I misunderstood.
> 
> An interesting observation is that if you create a new electron-vue project with Electron-builder everything works perfectly.

Hello sir,

I am facing same issue.. when electron runs for long time(2-3 days) .... my electron(v1.7.10) app going to run 365 days 24 hours...previously i was using ia32 package on 64bit... now m using x64 on 64 bit
node version v8.11.3
npm version 5.6.0
see following cmd....

electron-packager . --overwrite --asar=true --platform=win32 --arch=x64 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName="CompanyName" --version-string.FileDescription=CE --win32metadata.requested-execution-level=requireAdministrator --version-string.ProductName="project_name"

will it be useful ?
should i update my electron
