### ISSUE TITLE
Ask for suggestion on how to disable webpack and only run on dev mode

### ISSUE THREAD

**Issue by chrno1209** [SimulatedGREG/electron-vue#589]
Hi,
First thing, this is not a bug or issue, I just want to have some suggestion on how to use your boilerplate without webpack.

I am developing an internal tool in nodejs, which will use Electron and Vuejs to build an UI so we don't have to write command on Nodejs console to run a function, in other word, the app always runs under development environment, no release or build as the code will be changed frequenly.

The difficulty I am facing now is, when use your boilerplate, webpack does much things in background before running the app, so it's hard for me to develop, as I am not familiar with webpack and all of it's plugins.

My question is:
1. is there anyway to run your boilerplate without webpack?
2. even if I run app with webpack, is there anyway to config to disable hot-reload and run the app under port 9080?

Thank so much.

**Comment by chrno1209** [comment]
closed as I have found a solution for this

**Comment by FINDarkside** [comment]
For real? How about posting the solution then, so next one doesn't have to raise the same issue?

**Comment by chrno1209** [comment]
@FINDarkside the simplest solution to disable hot reload is modifying dev-client.js and set autoConnect=false.

`const hotClient = require('./hmr-client?noInfo=true&reload=true&autoConnect=false')`

However, the real solution that I really want to have is, to determine whenever HMR needs to update the page, so I can control it and only let HMR auto apply changes when I want since my app is a tool only running under development and the code can be changed frequently.

By modifying a little bit of webpack-hot-middleware client, then the result is:
![image](https://user-images.githubusercontent.com/4859745/39302720-ca501682-497d-11e8-9c85-f4307cb430c9.png)

So, whenever HMR has update for the page, the button on the top right corner will appear telling user there is code changes and if user click on the button, it will apply changes to the page, that's exactly what I want.
