### ISSUE TITLE
Electron build does not work without nodeIntegration

### ISSUE THREAD

**Issue by FINDarkside** [SimulatedGREG/electron-vue#590]
##### Describe the issue / bug.
Electron build stops working when nodeIntegration is set to false for the mainWindow (white screen)

##### How can I reproduce this problem?
vue init simulatedgreg/electron-vue my-project
Disable everything optional and pick either builder.
Delete LandingPage/SystemInformation, remove from LandingPage.vue too
Remove require('electron') line from LandingPage.vue
Test that web build works (npm run build:web)
Change mainWindow creation to this:

```
  mainWindow = new BrowserWindow({
    height: 563,
    useContentSize: true,
    width: 1000,
    webPreferences: {
      nodeIntegration: false
    }
  })
```
> npm run build

Run the program, and you'll get white screen

##### Tell me about your development environment.
  * Operating System: Windows 10

Is this possible thing to fix? Web build works just fine, so I'd assume there is.

**Comment by thezachcannon** [comment]
Do you have an URL for the mainWindow to load. If you open DevTools and do window.location in console what do you see?

**Comment by FINDarkside** [comment]
Sorry, should have posted the error too. This is the error from renderer.js:
    Uncaught ReferenceError: module is not defined at renderer.js:1

On a sidenote, it seems like renderer.js contains hot reloading code even in production.

window.location is:

    file:///E:/Backup/my-project2/build/my-project2-win32-x64/resources/app.asar/dist/electron/index.html

**Comment by virteman** [comment]
@FINDarkside 's method resolve my problem.

**Comment by FINDarkside** [comment]
@virteman You sure you don't run into issues when trying to use dependencies? See https://github.com/SimulatedGREG/electron-vue/issues/644
