### ISSUE TITLE
How to connect static js files to the project?

### ISSUE THREAD

**Issue by k1ll1n** [SimulatedGREG/electron-vue#592]
I installed the npm package uikit
Connected stylesheet - `@import '~uikit/dist/css/uikit.min.css'` - and it works !

But I can not connect js files from this package in any way.
I tried to do so
`import uikit from 'uikit/dist/js/uikit.min'` - does not work
`import uikit from '~uikit/dist/js/uikit.min'` - does not work
tried to put the files in the `static` directory
`import uikit from 'static/js/uikit.min'` - does not work

Please, tell me how can I do this?

In the settings of the webpack, I did not change anything.

**Comment by FINDarkside** [comment]
I don't think this has anything to do with electron-vue. How does it not work? Did you read the [Webpack installation guide](https://getuikit.com/docs/webpack)?
