### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by valsaven** [SimulatedGREG/electron-vue#593]
Is it possible to update the Webpack version?

**Comment by bdsoha** [comment]
Unfortunately, the current setup will not work with **webpack 4I**. I am also looking forward to the update!

**Comment by mubaidr** [comment]
Webpack 4 has updated options & plugin system this makes current configs and scripts incompatible with it. Though it does require less config out of the box.

**Comment by mubaidr** [comment]
I have upgraded my pet project configs/script for webpack-4, working fine so far. Will post the update.

**Comment by mubaidr** [comment]
You can try: [vue-electron-template](https://github.com/mubaidr/vue-electron-template)

All features from this boilerplate, all packages updated and simplified scripts.

**Comment by develar** [comment]
@mubaidr http://github.com/electron-userland/electron-webpack support webpack 4 (https://github.com/SimulatedGREG/electron-vue/issues/310)

**Comment by Haixing-Hu** [comment]
I have resolved this issue via my pull request #620

**Comment by XanderLuciano** [comment]
https://github.com/SimulatedGREG/electron-vue/pull/625 is a slightly more complete version at this point.

**Comment by XanderLuciano** [comment]
#625 has been merged and this template is now using webpack 4
