### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by xcsweb** [SimulatedGREG/electron-vue#594]
##### Tell me about your development environment.
  * Node version: 8.10.0
  * NPM version: 5.6.0
  * CNPM version: 5.2.0
  * vue-cli version: 2.9.3
    wepack version: 2.5.1
  * Operating System:

npm run dev
![qq 20180425161800](https://user-images.githubusercontent.com/20693737/39233892-40703aac-48a4-11e8-81ef-df37e43c135a.png)

![qq 20180425162033](https://user-images.githubusercontent.com/20693737/39234079-d4bcfcfe-48a4-11e8-907b-9dc5dae71fc7.png)

**Comment by FINDarkside** [comment]
First of all, you could add the error in plain text. But at least post the whole error, not just 60% of it. Assuming you changed any code from the template you should also post your code.

**Comment by xcsweb** [comment]
https://github.com/sairion/buble-loader/issues/39
