### ISSUE TITLE
Lifecycle hooks are not executed

### ISSUE THREAD

**Issue by devondahon** [SimulatedGREG/electron-vue#595]
##### How can I reproduce this problem?

Insert these lifecycle hooks in a component:
```
     ready () {
        console.log('Ready done')
      },
      beforeMounted () {
        console.log('Before mounted')
      },

      beforeCreated () {
        console.log('Before created')
      },
      mounted () {
        console.log('Updated')
      },

      activated () {
        console.log('Activated')
      },

      updated () {
        console.log('Updated')
      },

      created () {
        console.log('Created')
      }
```

##### Tell me about your development environment.
  * Node version: v8.1.3
  * NPM version: 6.0.0
  * vue-cli version: (if necessary)
  * Operating System: macOS High Sierra 10.13.4

**Comment by MoNaiZi** [comment]
> ##### 我怎样才能重现这个问题？
> 在组件中插入这些生命周期钩子：
> 
> ```
>      ready () {
>         console.log('Ready done')
>       },
>       beforeMounted () {
>         console.log('Before mounted')
>       },
> 
>       beforeCreated () {
>         console.log('Before created')
>       },
>       mounted () {
>         console.log('Updated')
>       },
> 
>       activated () {
>         console.log('Activated')
>       },
> 
>       updated () {
>         console.log('Updated')
>       },
> 
>       created () {
>         console.log('Created')
>       }
> ```
> 
> ##### 说说你的开发环境。
> * 节点版本：v8.1.3
> * NPM 版本：6.0.0
> * vue-cli 版本：（如有必要）
> * 操作系统：macOS High Sierra 10.13.4

What is the reason？
