### ISSUE TITLE
Apply Babel to main process

### ISSUE THREAD

**Issue by citycide** [SimulatedGREG/electron-vue#6]
I'm really liking this boilerplate but I'd like to suggest applying the transpilation to the main process files as well, including the Electron entry point. This would keep things consistent by allowing not only `import` / `export` syntax just like in renderer files but also any other presets or plugins.

Along with this, it seems like it would benefit from a slightly more clear structure in terms of renderer & main processes. Say, within `app/src` you'd have `/renderer` as well as `/main`. For this I might suggest adding a second main process file to call from `electron.js`.. It doesn't have to really be very functional - just a simple starting point for this structure.

So my proposal is basically - transpile main process along with the renderer, and consider structuring the `src` directory something like this.

```
/app
|  /src
|  |  /main
|  |  |- electron.js
|  |  |- util.js
|  |  /renderer
|  |  |  /components
|  |  |  /vuex
|  |  |- App.vue
|  |  |- main.js
|  |  |- routes.js
```

**Comment by SimulatedGREG** [comment]
I've actually had this into consideration lately and I love your proposal for the file structure. As of now I can't devote my time on this but will probably happen in the near future.

**Comment by citycide** [comment]
Glad you like it, although admittedly bummed you won't have the time because I fought for hours last night trying to get this in place myself. Webpack defated me hard. I couldn't figure out how to restructure things without them breaking pretty much irreparably heh... I've been using gulp for a while and have only used Vue as a basic, more modern jquery ( as in, script tags :open_mouth: ) so this is a very cool setup. 

Totally get the lack of time though. If you have any advice on how I could go about this I'd be willing to give it a shot myself.

**Comment by SimulatedGREG** [comment]
One big difference is that the webpack target would need to be `electron` for the main process. Since you can't have multiple targets you'd have to create another webpack configuration. I believe you can export an array of configs from the `webpack.config.js` and the `npm run dev` should run both. Nobody has really supported this in the past so it would take a little pioneering to perfect this setup. 

Thinking about all this makes me want to get started 😁. So maybe I can get something ready tonight or by this weekend.

**Comment by citycide** [comment]
It is exciting isn't it :wink: ES2019 all the things.

I've actually come across a few that do something similar, but again I don't know a lot about webpack so they might differ in ways I'm not seeing. I'll throw them here as references since they should be helpful:

[React / Electron / Webpack boilerplate by jogleasonjr](https://github.com/jogleasonjr/electron-react-webpack-quick-start) - this one is the most accurate in terms of what I'd want for directory structure
[Tc by mccxiv](https://www.github.com/mccxiv/tc) - this one has what seems like a more desirable webpack configuration.

**Comment by citycide** [comment]
Amazing what sleeping on an issue will do... I came back for round 2 against Webpack and was able to get it. @SimulatedGREG let me know your thoughts.
