### ISSUE TITLE
 webSecurity: false  works... and then it does not

### ISSUE THREAD

**Issue by borja-rojano** [SimulatedGREG/electron-vue#604]
##### Describe the issue / bug.

I am trying to build an app for use inside our corporate structure. I need to access an API that manages authentication with Kerberos. My mainWindow var looks like this.

`  mainWindow = new BrowserWindow({
    height: 1000,
    useContentSize: true,
    width: 1600,
    webPreferences: { webSecurity: false },
  })`

When I launch the first query to the API, I get the message below

```
<!--
* This page is displayed to a user in case a browser does not support SPNEGO 
* protocol or is not configured properly to support SPNEGO.
* The behaviour behind SPNEGO is as follows.
* If a user requests secured resource, a server sends an authentication challenge
* with the header "WWW-Authenticate" and value "Negotiate".
* Normally, if a browser supports SPNEGO it responds with a new HTTP request that 
* contains SPNEGO token as HTTP header and everything works fine.
* But if a browser does not support SPNEGO (or misconfigured) it does not respond on 
* authentication challenge and a user sees an empty page.
* To avoid that empty page and provide some inteligible information to a user,
* this simple page is introduced.
* It is inculded into HTTP response within server's authentication challenge.
* Now, if a browser does not support SPNEGO, a user sees this page.   
-->
<html>
  <body>
    A browser did not respond to authentication challenge sent by a server.<br/> 
    Most probably your browser is not configured properly to handle SPNEGO authentication challenge or does not support SPNEGO.<br/>
    Please, contact your System Administrator to deal with the problem.
  </body>
</html>
```

If I then refresh the app and make a second GET request, it starts working, but the first request always fails. 

I tried to make two automatic API call on `mounted` hook, but the result is unstable. Sometimes the first actual request the user makes works, sometimes not. 

Is there a way to make electron and/or this boilerplate ready for kerberos?

#### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version: 8.11.1
  * NPM version: 5.6.0
  * vue-cli version: 2.9.3
  * Operating System: Windows 7

**Comment by SimulatedGREG** [comment]
This would definitely be outside the scope of this boilerplate. Please see advise from the respective `electron` or `webpack-dev-server` communities.
