### ISSUE TITLE
Enable VueJS devtools plugin in production

### ISSUE THREAD

**Issue by jeeftor** [SimulatedGREG/electron-vue#609]
##### Describe the issue / bug.

I'm running an app in a production format, however, I still need access to the devtools to debug some of the incoming data.  I've been able to enable the standard devtools in production mode but I'm having trouble loading the vuejs specific dev tools extension.

##### How can I reproduce this problem?
\#

I added
`require('electron-debug')({
  enabled: true
})`

to `index.js` which enabled the devtools

I've tried adding:

```

  let installExtension = require('electron-devtools-installer')
  if (process.env.NODE_ENV === 'development') {
    installExtension.default(installExtension.VUEJS_DEVTOOLS)
      .then(() => {})
      .catch(err => {
        console.log('Unable to install `vue-devtools`: \n', err)
      })
  }
```

to the `createWindow` function - but this doesn't seem to work correctly.  

Am I missing something?

**Comment by FINDarkside** [comment]
https://github.com/vuejs/vue-devtools/issues/190

**Comment by SimulatedGREG** [comment]
Trying to use the `vue-devtools` with the production build from webpack is not possible. Vue strips out all devtool APIs needed for the devtools to function.

**Comment by mittalyashu** [comment]
I have moved this line of code to `main/index.js` file _(main process)_

```js
require("electron-debug")({ showDevTools: true })
```

but still when I press `ctrl+shift+i`, it doesn't open `dev-tools` in production.

**Comment by pranayb703** [comment]
I am using minified version of Vue js , any way to make this work ? @mittalyashu @jeeftor
