### ISSUE TITLE
electron-builder and node modules is included.

### ISSUE THREAD

**Issue by Davidzhu001** [SimulatedGREG/electron-vue#610]
##### Tell me about your development environment.
  * Node version:  9.7.1
  * NPM version: yarn  v1.5.1
  * vue-cli version: (if necessary)
  * Operating System: Mac OS

#### *If you are looking to suggest an enhancement or feature, then feel free to remove everything above.*

Why when i try to build with electron-builder my node modules is included.

Do i necessary need node modules? Or i can i ignore it in a right way?

Thanks

**Comment by SimulatedGREG** [comment]
These are necessary for your application to function. Please know `devDependencies` are not bundled.
