### ISSUE TITLE
vue-cli 3 support

### ISSUE THREAD

**Issue by BotellaA** [SimulatedGREG/electron-vue#613]
Do you plan to support the new vue-cli 3.0? I do not know how much work is needed to move to this version.

**Comment by mubaidr** [comment]
I think this depends on: https://github.com/SimulatedGREG/electron-vue/issues/593

**Comment by SimulatedGREG** [comment]
Migration to `@vue/cli` will be done in a complete rewrite, more news to come. :slightly_smiling_face:

**Comment by nklayman** [comment]
Not to steal SimulatedGREG's thunder, but I made [vue-cli-plugin-electron-builder](https://nklayman.github.io/vue-cli-plugin-electron-builder). @SimulatedGREG I think we should work together to make one plugin instead of competing with each other. What do you think?

**Comment by DivinerSQQ** [comment]
When can I create a project directly using vue-cli 3?
