### ISSUE TITLE
why can't use module "puppeteer" in electron-vue

### ISSUE THREAD

**Issue by purestart** [SimulatedGREG/electron-vue#615]
i had  npm install puppeteer , but when i require this module show err,(Error: Cannot find module "." )

in main process,   index.js

import { app, BrowserWindow } from 'electron'
const {ipcMain} = require('electron');
**const Puppeteer = require('puppeteer'); // can't find this module**

**Comment by vieruu** [comment]
why use puppeteer when you can preload a script in a hidden browserwindow

**Comment by githoniel** [comment]
puppeteer run well in my apps

**Comment by SimulatedGREG** [comment]
This is for sure specific to running `puppeteer` within the `electron` environment, which would be an outside issue to this boilerplate.
