### ISSUE TITLE
Cannot find module 'chalk'

### ISSUE THREAD

**Issue by mbykov** [SimulatedGREG/electron-vue#616]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
$ yarn
......
success Saved lockfile.
$ yarn run dev
yarn run v1.6.0
warning package.json: No license field
$ node .electron-vue/dev-runner.js
....
Error: Cannot find module 'chalk'

##### How can I reproduce this problem?
\#

Just install  electron-vue from the very scratch :

$ vue init simulatedgreg/electron-vue morpheus-greek

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
$ node --version                                    
v8.6.0

  * NPM version:
$ npm --version
5.3.0

$ yarn --version
1.6.0

  * vue-cli version: (if necessary)
$ vue --version 
2.9.3

(but 3.0 has the same error)

  * Operating System:

Linux

**Comment by XanderLuciano** [comment]
Did you try installing chalk?

> npm install chalk

or 

> yarn add chalk

**Comment by SimulatedGREG** [comment]
Sounds like you had a issue installing dependencies when running `yarn`, which is definitely and outside issue to electron-vue.

**Comment by mbykov** [comment]
yes, thank you!
