### ISSUE TITLE
v-bind:src not working as should be expected

### ISSUE THREAD

**Issue by lim-enhui** [SimulatedGREG/electron-vue#618]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
I am using dynamic binding for the image src but somehow it did not work..

![image](https://user-images.githubusercontent.com/13527348/40375668-cf869472-5e1e-11e8-823f-0ead6ccfa588.png)

https://forum.vuejs.org/t/mounted-hooks-with-computed-property-questions-and-doubts-that-may-due-to-life-cyclehooks/34744

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

![](https://forum.vuejs.org/uploads/default/original/2X/a/aa56c7fc7a1c919686f947a08a8207c3ae295549.png)

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by SimulatedGREG** [comment]
`vue-loader` cannot interpret the module resolution in this manner. You would be best to treat your image(s) as [static assets](https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-static-assets.html).
