### ISSUE TITLE
stylus Support

### ISSUE THREAD

**Issue by JarlRyan** [SimulatedGREG/electron-vue#622]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#

##### How can I reproduce this problem?
\#

i need use stylus in vue, but i can't config it, i hope like vue init webpack, init suport stylus.

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by JarlRyan** [comment]
or show some samples what i can study.

**Comment by SimulatedGREG** [comment]
@JarlRyan 

All should need to do is install the proper dependencies with...
```bash
npm install stylus-loader stylus --save-dev
```
From there, you should be able to add the `lang="stylus"` attribute to your `<style>` tags.
