### ISSUE TITLE
how to load local js file in index.ejs ?

### ISSUE THREAD

**Issue by ejkgmea** [SimulatedGREG/electron-vue#623]
I'm trying to get the local js file at the header in the index.ejs, like this:

<script src="static/sdk/vendor/decimal.js"></script>

when I use npm run dev everything ok,

but I use npm run build:mas or npm run build:win32 then the package building will done, when I open the application it was not work...

  * Node version: v8.11.1
  * NPM version: 5.6.0
  * vue-cli version: (if necessary) 2.9.3
  * Operating System: mac os x 10.13.4

**Comment by XanderLuciano** [comment]
Did you try: `<script src="/static/sdk/vendor/decimal.js"></script>`?

**Comment by ejkgmea** [comment]
@XanderLuciano  thinks

**Comment by sansil** [comment]
Hi,

I'm experimenting the same problem as @ejkgmea  says. In particulary I'm importing a [blockly](https://github.com/google/blockly) script in the index.ejs (<script src="../static/js/blockly_compressed.js"> </script>) that works fine in development mode, but it's not working at npm run build . How can I import the script files correcty? 

Thank you in advance

**Comment by weiki-li** [comment]
hi Have you solved your problem？ I had the same problem

**Comment by weiki-li** [comment]
@sansil Have you solved your problem？ I had the same problem

**Comment by sansil** [comment]
Hi @weiki-li typing the script import like this, works for me:

<script type="text/javascript" src="./static/js/blockly_compressed.js"> </script>

I hope this help you.

**Comment by C0deZLee** [comment]
I'm facing the same issue and the above solution doesn't work for me. 
I'm trying to use the Xel framework in my project and trying to load it into my project like this 
```
   <link rel="stylesheet" href="./node_modules/xel/themes/vanilla.css" />
    <script src="./node_modules/xel/xel.min.js"></script>
```
it works fine in dev mode, but in build it just says

`Failed to load resource: net::ERR_FILE_NOT_FOUND`

I searched online for days and no one seems to solve this issue, I have literally no idea what should I do now
