### ISSUE TITLE
Incorrect window size in dev mode

### ISSUE THREAD

**Issue by jsnjack** [SimulatedGREG/electron-vue#627]
## Description
If I run an application in dev mode (with yarn run dev), the browser reports (in fullscreen)  window.innerWidth = 2103 (my screen size is 1920) which causes incorrect size of the webpage in webview (the page is cropped).

If I build the application and run it, the page is displayed correctly. So I guess it is caused by some setting or plugin which is enabled in dev mode only.

## How to reproduce
Create an app with a webview that occupies the whole page. For example, I open Google Inbox in webview and the right part with Compose button is not visible:

### In dev mode
![screenshot from 2018-06-02 18-46-38](https://user-images.githubusercontent.com/5493713/40878731-72d788ba-6695-11e8-9aa9-dee7c8ed860e.png)

### In production mode
![screenshot from 2018-06-02 18-47-08](https://user-images.githubusercontent.com/5493713/40878734-7a02c384-6695-11e8-8b9e-a2f9edacf022.png)

  * Node version: v8.11.2
  * NPM version: 5.6.0
  * Operating System: fedora 28

**Comment by XanderLuciano** [comment]
What are the settings on your `BrowserWindow` object?

**Comment by jsnjack** [comment]
Nothing special, I hope!
```javascript
    mainWindow = new BrowserWindow({
        width: 1200,
        height: 800,
        autoHideMenuBar: true,
});
```

**Comment by XanderLuciano** [comment]
Hmmm, how are you shrinking down the web page? Seems to me like you're getting some scaling in Chrome, which is why it's reporting the window width as wider than your monitor. e.g. if you zoom out by ~10% you'll get a number around 2100pixels. 

Try adding this on the renderer thread:

```javascript
var webFrame = require('electron').webFrame;
webFrame.setVisualZoomLevelLimits(1, 1);
webFrame.setLayoutZoomLevelLimits(0, 0);
```

(in `src/renderer/main.js` for example)

**Comment by jsnjack** [comment]
Hmm.. I have just cleared my profile directory and the issue is gone :/
