### ISSUE TITLE
A lot of outdated dependencies

### ISSUE THREAD

**Issue by Luminess** [SimulatedGREG/electron-vue#63]
Using 100% default settings in vue-cli.

Checked with a completely untouched fresh package.json

### Dev environment

**[Major]** Dependencies that are out of declared version range in package.json:

> cross-env                     ^1.0.7  →        ^3.1.3
> css-loader                   ^0.23.1  →       ^0.25.0
> electron-devtools-installer   ^1.1.4  →        ^2.0.1
> eslint                       ^2.10.2  →        ^3.9.1
> eslint-config-standard        ^5.1.0  →        ^6.2.1
> eslint-plugin-promise         ^1.0.8  →        ^3.3.1
> eslint-plugin-standard        ^1.3.2  →        ^2.0.1
> file-loader                   ^0.8.5  →        ^0.9.0
> inject-loader                 ^2.0.1  →  ^3.0.0-beta2
> karma-electron                ^4.1.1  →        ^5.1.1
> webpack-merge                ^0.14.1  →       ^0.15.0
> vue-hot-reload-api            ^1.3.2  →        ^2.0.6

**[Minor]** Dependencies that are within the declared version range in package.json but are still behind:

> babel-core                       ^6.8.0  →  ^6.18.2
> babel-loader                     ^6.2.4  →   ^6.2.7
> babel-plugin-transform-runtime   ^6.8.0  →  ^6.15.0
> babel-preset-es2015              ^6.6.0  →  ^6.18.0
> babel-preset-stage-0             ^6.5.0  →  ^6.16.0
> babel-runtime                    ^6.6.1  →  ^6.18.0
> del                              ^2.2.1  →   ^2.2.2
> devtron                          ^1.1.0  →   ^1.4.0
> electron                         ^1.3.1  →   ^1.4.6
> electron-packager                ^8.0.0  →   ^8.2.0
> electron-rebuild                 ^1.1.3  →   ^1.3.0
> babel-eslint                     ^7.0.0  →   ^7.1.0
> eslint-friendly-formatter        ^2.0.5  →   ^2.0.6
> eslint-loader                    ^1.3.0  →   ^1.6.1
> eslint-plugin-html               ^1.3.0  →   ^1.6.0
> html-webpack-plugin             ^2.16.1  →  ^2.24.1
> karma-mocha                      ^1.2.0  →   ^1.3.0
> babel-register                  ^6.14.0  →  ^6.18.0
> require-dir                      ^0.3.0  →   ^0.3.1
> mocha                            ^3.0.2  →   ^3.1.2
> vue-html-loader                  ^1.2.2  →   ^1.2.3
> vue-loader                       ^9.5.1  →   ^9.8.1
> webpack                         ^1.13.0  →  ^1.13.3
> webpack-dev-server              ^1.14.1  →  ^1.16.2

### App Framework

**[Major]** Dependencies that are out of declared version range in package.json: **none**.

**[Minor]** Dependencies that are within the declared version range in package.json but are still behind:

> vue           ^2.0.1  →  ^2.0.5
> vue-electron  ^1.0.0  →  ^1.0.4
> vue-router    ^2.0.0  →  ^2.0.1

You can use [Gemnasium](https://gemnasium.com/) or a similiar service to automatically track dependencies for you.

**Comment by SimulatedGREG** [comment]
@Luminess 

Thanks for the info! Was going to do this myself rather soon, but didn't know something like Gemnasium existed. Waiting for webpack 2 to be released and will use this to update everything.

**Comment by Luminess** [comment]
I have no idea. I looked at the log and it definitely checked vuex's and vue-resource's version. I manually checked and vuex is up-to-date. vue-resource is behind one patch version (semver).

I use [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) to locally check outdated dependencies.

**Comment by mikhaildelport** [comment]
Maybe when you do this, can this project/generator get some version as well? I just finished a work project using it, and I know you're working on the new webpack version for it (and other awesome stuff) but I don't want people coming to the project in 6 months and you've made it way better but the version I made is different and causes confusion. Just some way to either reference a version or something?

**Comment by SimulatedGREG** [comment]
@mikhaildelport 

Sorry for the late reply, but I probably won't be giving the boilerplate much of an official *version* but more of just adding more features. I plan to not break any previous functionality, but if necessary those items will be noted within the documentation. If if there is a need to manually update for newer features, most work is done is a few specific files unlike the offical `webpack`templates with many different scripts and webpack configurations.

**Comment by cschweda** [comment]
Any update on this?

**Comment by SimulatedGREG** [comment]
I'm pretty much done waiting for webpack 2 to be released, so expect some updates rather soon.

**Comment by cschweda** [comment]
Awesome! Thank you!

**Comment by SimulatedGREG** [comment]
All dependencies have been updated within the `dev` branch. Expect a `master` release soon.
