### ISSUE TITLE
__static not working when building and "linking" a sqlite database

### ISSUE THREAD

**Issue by fjrial** [SimulatedGREG/electron-vue#630]
##### Describe the issue / bug.
Using your template (thanks for doing it)

Included a sqlite database in static/db/database.sqlite

Only included this three lines in main.js to connect to it
`const SQL = require('sqlite3').verbose();
var path = require('path');
const db = new SQL.Database(path.join(__static, '/db/database.sqlite'));`

Works fine when dev release, but not when building for production (enabled  devTools for production and this message appears : SQLITE_CANTOPEN: unable to open database file)

  * Node version: v8.11.2
  * NPM version: 5.6.0
  * vue-cli version: (if necessary)
  * Operating System: Ubuntu 17.04

**Comment by fjrial** [comment]
Ok, after some tries, I figured it out in how to make this work. I thought that __static should be the method, but maybe I was wrong.

This is what I do:

-Included the db folder in the ExtraResources section in package.json
-Changed the db connection code to something like this:

> const SQL = require('sqlite3').verbose();
> var connectDB = function(){
>    if (process.env.NODE_ENV === 'development')
>      var db=new SQL.Database('db/db.sqlite');
>   else
>      var db=new SQL.Database(process.resourcesPath+'/db/db.sqlite');
>   return db;
> }
> export default connectDB

**Comment by fjrial** [comment]
Edited: working fine, with the exception that in "build" releases, the file is read-only, must use app.getPath('userData').. Nothing related to your wonderful template.. 

Thanks again.

Closing issue

**Comment by 617450941** [comment]
Why data cannot be read after it is created

**Comment by 617450941** [comment]
Is there a demo code?

**Comment by fjrial** [comment]
basically, you can not write to static folder when build is production.. is a read-only dir..

if you need to do some write ops.. you must use app.getPath('userData') to store your data, so you can read/write to it.

in your js code you must use as a path to store data. 
`app.getPath('userData');`
it's recommended to user another folder inside this one, to store your app relative data into it

`var fs = require ('fs');
var myApp='myapp';`

`const storagePath=fs.join(app.getPath('userData'),myApp);
`

Check the docs here
[https://electronjs.org/docs/api/app](https://electronjs.org/docs/api/app)
