### ISSUE TITLE
Is there a way sharing a global var through vue and electron?

### ISSUE THREAD

**Issue by pipilupipixia** [SimulatedGREG/electron-vue#631]
sorry for my poor english :)
Is there a way sharing a global var through vue and electron? I've tried electron-settings but i realized that it cant trigger vue to update the value on the page.

**Comment by propotatomaster** [comment]
use ipc to send values and receive them in vue

**Comment by pipilupipixia** [comment]
@propotatomaster I have tried this but it seems that it cant trigger vue to regenerate the page when i edit the value in render progress.

**Comment by propotatomaster** [comment]
uh that's weird
