### ISSUE TITLE
Multi-window support

### ISSUE THREAD

**Issue by book12085** [SimulatedGREG/electron-vue#634]
Hello, could you support multiple Windows? Not one to the other, but several Windows exist simultaneously.

**Comment by julyL** [comment]
I have same problem, how to resolve?

**Comment by dannyrb** [comment]
This is possible using the existing Electron API. If you want an abstraction that makes window management easier, you could check out `electron-window-manager`

Electron API:
- https://electronjs.org/docs/api/browser-window

Electron Window Manager:
- https://github.com/TamkeenLMS/electron-window-manager

**Comment by book12085** [comment]
Thank you
