### ISSUE TITLE
[Feature Request]: Update to Electron 2.0.2

### ISSUE THREAD

**Issue by aaronmallen** [SimulatedGREG/electron-vue#637]
Update the template to the newly released [Electron 2.0.2](https://electronjs.org/releases#2.0.2)

**Comment by carlblock** [comment]
Worth mentioning if someone has problems with vue-devtools not being installed anymore, try upgrading "electron-devtools-installer" to "^2.2.4".

**Comment by thedevbob005** [comment]
@aaronmallen I already did a PR  #625 with all updates and changes I could think of. The repo owner has not been online to check the PRs in a few days we just have to wait on him. Meanwhile if you want to use it, use the following command to initiate your project.
`$ vue-init thedevbob005/electron-vue#wbp4 myproject`

**Comment by Akumzy** [comment]
@thedevbob005 
entrypoint is returning undefined
```js
Child html-webpack-plugin for "index.html":
                                     Asset      Size  Chunks  Chunk Names
                                index.html  1.38 MiB       1
      c70b2ea90865039addd3.hot-update.json  44 bytes
      Entrypoint undefined = index.html
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 1.07 KiB {1}
      [./node_modules/lodash/lodash.js] 527 KiB {1}
      [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {1}

┗ ----------------------------
```

**Comment by thedevbob005** [comment]
@Akumzy Can you provide more information reguarding the problem including your platform, what commands did u use, yarn or npm, versions etc

**Comment by sixpetrov** [comment]
@thedevbob005 this worked for me perfectly, thank you so much

**Comment by Maus3rSR** [comment]
Electron currently planned 3.0 beta, there is some roadmap planned for Electron-vue to follow changes?

I'm a new user of Electron-vue and the version of my Electron installed with the boilerplate is     "electron": "^1.7.5",
"electron-devtools-installer": "^2.2.0",

What is the best way to maintain code up to date?

**Comment by thedevbob005** [comment]
@Maus3rSR Use my PR #625 for the latest versions.
`$ vue-init thedevbob005/electron-vue#wbp4 myproject`

**Comment by Maus3rSR** [comment]
Ok sorry should saw it above ! Thanks !

**Comment by xinhongChen** [comment]
@thedevbob005  Hi~ Bakshi, I had just use the command of 
`$ vue-init thedevbob005/electron-vue#wbp4 myproject`
but when I execute `npm run dev` there were some errors,  here is the detail info 
[2018-08-06T02_32_51_534Z-debug.log](https://github.com/SimulatedGREG/electron-vue/files/2261038/2018-08-06T02_32_51_534Z-debug.log)
thanks !

**Comment by XanderLuciano** [comment]
PR #625 has been merged and template has been updated with updates to electron and webpack.
