### ISSUE TITLE
[Question] How to keep Vuex state after closing/opening app

### ISSUE THREAD

**Issue by harveylewis** [SimulatedGREG/electron-vue#638]
I have created an app, im looking at how to keep states between pages. This is obviously easy to do using Vuex. However the state is reset if I close the app and reopen. Is there a way I can keep the state between restarts? thanks in advance

**Comment by lbenie** [comment]
my guess would probably be to use some plugin to persist the state to disk and reload the state when the app opens

**Comment by book12085** [comment]
Local Storage ? Session Storage ? indexdDB ? Cookies ?

**Comment by Mo0546** [comment]
Use 'vuex-electron' with 'vuex-shared-mutations' plugin.
`import { createPersistedState, createSharedMutations } from 'vuex-electron'`
and then
`export default new Vuex.Store({
  modules,
  plugins: [
    createPersistedState(),
    createSharedMutations(),
  ],
})`
