### ISSUE TITLE
[feature] support main process bundling

### ISSUE THREAD

**Issue by zxc23** [SimulatedGREG/electron-vue#64]
Hi. I was looking to load and save the window state (width, height, maximised etc) and most of the time I see that it's recommended to use one of many storage packages on NPM. However, given that we can't use NPM packages within electron.js, how would you suggest going about this? Thanks.

Edit: Also, I imagine this would be a common thing that people would want in their Electron apps. Maybe it would be a good idea to add this to the boilerplate?

**Comment by SimulatedGREG** [comment]
@zxc23 

You bring a very valid point here. There are plans to bring support for main process bundling, but they are taking a more time than expected as I'm waiting for webpack 2 to be come of beta. For now, you could look into [`window.js`](https://github.com/szwacz/electron-boilerplate/blob/master/src/helpers/window.js) from `electron-boilerplate` and copy this script over manually. It does require `fs-jetpack` but should be too difficult to migrate to just using standard `fs`.

**Comment by zxc23** [comment]
Thanks for the response. I didn't mean 'LocalStorage' specifically, but I can see how it might come across that way. I'll edit it to whatever is more suitable, but I don't know how to phrase it better. :)

I'll give that script a go, and if it doesn't work out, I'll sit tight and hope for the best in the future. Today I started using vuex-persistedstate, which is working out nicely for persisting some settings across sessions, but of course it's limited to the Vue side of the app.

**Comment by SimulatedGREG** [comment]
Gotcha. Sorry for the inconvenience. I tried supporting this awhile back, but webpack was pretty finicky, so hoping for better results this time around.

**Comment by SimulatedGREG** [comment]
Webpack 2 has finally been released and the structure has changed a little. All dependencies will now be treated as `externals` and `node_modules` will no longer be ignored. This will enable the use of external node modules within both the `renderer` and `main` processes.  You can take a look now in the `dev` branch. Expect an update to `master` soon.
