### ISSUE TITLE
use "yarn build" works incorrectly

### ISSUE THREAD

**Issue by jxiangji** [SimulatedGREG/electron-vue#640]
* Node version: 8.9.1
  * NPM version: 5.5.1
  * Yarn version:1.3.2

The dependency package is as follows
![image](https://user-images.githubusercontent.com/17931143/41452589-2e87e2bc-70a5-11e8-8d39-f8d7c311940f.png)
![image](https://user-images.githubusercontent.com/17931143/41452600-3a619128-70a5-11e8-9814-566df7a06cd1.png)

When I execute the "yarn build" command, the console throw some errors as follows
![image](https://user-images.githubusercontent.com/17931143/41452754-dc2751aa-70a5-11e8-9566-aa3adc4a3a3b.png)

**Comment by XanderLuciano** [comment]
Did you run `yarn install` to install your dependencies?

**Comment by XanderLuciano** [comment]
Closing due to lack of response.
