### ISSUE TITLE
How to generate a perfect sized icon?

### ISSUE THREAD

**Issue by pipilupipixia** [SimulatedGREG/electron-vue#641]
Sorry for my poor English :)
I have checked that another app based on electron-vue use 32*32 png file as a tray icon, and i generated mine but it seemed strange.
My icon:
<img width="16" alt="light" src="https://user-images.githubusercontent.com/24778583/41496539-a00d0c9e-7174-11e8-873a-17c3df6efea7.png">
![image](https://user-images.githubusercontent.com/24778583/41496536-9731c420-7174-11e8-9081-d6ed32ba81cd.png)
Other's icon:
<img width="16" alt="enabled 2x" src="https://user-images.githubusercontent.com/24778583/41496540-a6963d2e-7174-11e8-90d9-3ae1aa6d8f5f.png">
![image](https://user-images.githubusercontent.com/24778583/41496550-cf64169a-7174-11e8-8d13-6eaa6a20fa55.png)

I use photoshop to generate my icon. I opened other's icon and edit it into mine to keep its size, but it still seems strange. How can i generate my icon?

**Comment by frankgraave** [comment]
Hi @pipilupipixia 

Just came across this myself recently. Here's a helpful article on this: http://electron.rocks/proper-tray-icon/

It shows how to do this, by also keeping in mind that the user might have the dark menubar on macOS. Hope it helps :)

**Comment by XanderLuciano** [comment]
Closing as this issue is not directly related to the template / boilerplate and appears to have a valid solution.
