### ISSUE TITLE
Q: Integrate MetroUI (meta tag)

### ISSUE THREAD

**Issue by KingKnecht** [SimulatedGREG/electron-vue#645]
Hi,

from the MetroUi docs ([https://metroui.org.ua/vuejs.html](https://metroui.org.ua/vuejs.html)): 

> 1. Add meta tag of late initialization Metro 4 <meta name="metro4:init" content="false">
> 2. Initialize Metro 4 in the hook mounted

I have added it to the index.ejs:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="metro4:init" content="false">
    ...
```

and used the mount-hook to init Metro:

```
new Vue({
  components: { App },
  router,
  store,
  template: '<App/>',
  mounted: function () {
    Metro.init();
  }
}).$mount('#app');
```

But this gives me:

`[Vue warn]: Error in mounted hook: "ReferenceError: Metro is not defined"`

Q: Is it possible to use the meta-tag stuff together with electron/vue?

Thx

**Comment by thedevbob005** [comment]
@KingKnecht did you import metro? you need to import metro before referencing it.

**Comment by KingKnecht** [comment]
I think I don't know how to import Metro. I thought the `<meta name="metro4:init" content="false">` stuff would import it somehow.
I tried to import Metro directly (something like `import Metro from './foo/bar/Metro' `), but I wasn't able to get it work. 
I checked the sources of Metro for a file I could import, but without success.

**Comment by thedevbob005** [comment]
@KingKnecht Try including the metro css and script in index.html in head section before any webpack imports.

**Comment by KingKnecht** [comment]
Okay, one step done. 
I'm able to run the electron-vue-metro combination:
![image](https://user-images.githubusercontent.com/4339172/42125253-7ebdd942-7c73-11e8-9efc-521f1b3e6d4d.png)

Next problem is, that when I build a setup (exe) it looks like CSS is not included:
![image](https://user-images.githubusercontent.com/4339172/42125262-c169501e-7c73-11e8-8c86-3a0293baeae2.png)

How do I include all the stuff needed into my build/setup?
Thx,
Sven

**Comment by KingKnecht** [comment]
Solved!
Instead of `<link rel="stylesheet" href="../node_modules/metro4/build/css/metro-all.min.css">`
I imported it like:
`@import '../../../node_modules/metro4/build/css/metro-all.min.css';`
in the vue component (landing page)

tataa! :-)

**Comment by thedevbob005** [comment]
@KingKnecht Yep and you can just import them in main.js with
`
import '@/metro4/build/css/metro-all.min.css'
`
