### ISSUE TITLE
blank screen on build

### ISSUE THREAD

**Issue by simdax** [SimulatedGREG/electron-vue#647]
Something related to https://github.com/SimulatedGREG/electron-vue/issues/457

I'm building my app with electron-builder.
`yarn dev` works fine, but the build give me the following error.

![screen shot 2018-06-24 at 5 14 57 pm](https://user-images.githubusercontent.com/2458806/41820435-2652937e-77d2-11e8-91d5-5a71f1ddc44b.png)
![screen shot 2018-06-24 at 5 09 42 pm](https://user-images.githubusercontent.com/2458806/41820409-c4b9fdb4-77d1-11e8-9e62-47da40dcdfc6.png)

Here the error is obvious. It searchs for electron/index.html/style.css instead of electron/style.css
Where this bug could come from ?

  * Node version: v10.4.0
  * NPM version: YARN 1.7.0
  * Operating System: macOS sierra 10.12.6

**Comment by XanderLuciano** [comment]
How are you bringing in the CSS file? Are you using SASS? 

If you're using sass, you should just import the SCSS code like so in the `App.vue` file:

```vue
<style lang='scss'>
    @import './scss/app';
</style>
```

Then your CSS should be automatically injected into the `head` of the DOM.

**Comment by FINDarkside** [comment]
This isn't really even nearly enough to reproduce the issue, so I'm exactly not sure how anyone would solve this for you.

**Comment by simdax** [comment]
For those with the same error, it was something else a little tricky.
I had a mistyping in the URL I was loading. I added by mistake a trailing /. 
When you yarn dev, your url is localhost:some_port, so adding a '/' does not matter. But when building, you use the index.htlm endpoint, and you should not add any '/' behind, or electron builder think it is a dir, and search from 'index.html' and not from root '/'

So, just mistyping js bug business as usual, just use Typescript :)
