### ISSUE TITLE
Error running electron-builder via TravisCI: Cannot check wine version

### ISSUE THREAD

**Issue by klamping** [SimulatedGREG/electron-vue#651]
##### Describe the issue / bug.
When running my build through TravisCI, the OSX version runs fine, but the Linux build fails with the following message:
```sh
Error: Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
    at /home/travis/build/klamping/chester-desktop/node_modules/builder-util/src/wine.ts:100:13
    at Generator.throw (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

Full log output here:
https://travis-ci.org/klamping/chester-desktop/jobs/400527733#L793

##### How can I reproduce this problem?
Set up a basic project via the CLI, then add the project to Github/TravisCI. On the first build, you should see the issues.

[My travisci.yml file](https://github.com/klamping/chester-desktop/blob/master/.travis.yml) is a straight copy of what's provided by default.

##### Tell me about your development environment.
  * Node version: 8
  * NPM version: 
  * vue-cli version: 2.9.6
  * Operating System: trusty

**Comment by klamping** [comment]
Looks like this was caused by me changing something that I didn't realize i changed.  Disregard.

**Comment by liuzeyafzy** [comment]
> Looks like this was caused by me changing something that I didn't realize i changed. Disregard.

I have the same problem, but I have no idea to fix it...
