### ISSUE TITLE
Q: Access router from vuex

### ISSUE THREAD

**Issue by KingKnecht** [SimulatedGREG/electron-vue#652]
Hi,
I know it's probably not a bug, but this question seems to be to specific for Stackoverflow.

How can I access the router ( for push) in a vuex module?

I have tried all variations I can think of.

I think this would help others too when they search the issues....

EDIT: After having a fresh beer, I'm thinking about that this could be an anti-pattern? Should I listen to the state change somewhere else? Can I listen to the vuex in the router?

Thanks a lot,
Sven

**Comment by lbenie** [comment]
you can import the router in a vuex action and do a redirect if needed.

i.e

```es6
import router from '../router'
...


async [someAction]({commit, dispatch}) => {
  const { data } = await someApiCall()
  commit(someAction, data)
  router.push({ name: 'routerNamedRoute' })
}
```

**Comment by ubirajaramneto** [comment]
This solution did not work for me.

I was importing the router file into one of my vuex module files and it failed to compile telling me that it could not find the components that were defined in the router file, here is the error:

`ERROR in ./src/renderer/router/index.js
  Module not found: Error: Can't resolve '@/components/Dashboard' in 'src/renderer/router'
   @ ./src/renderer/router/index.js 17:15-48
   @ ./src/renderer/store/modules/Login.js
   @ ./src/renderer/store/modules sync nonrecursive \.js$
   @ ./src/renderer/store/modules/index.js
   @ ./src/renderer/store/index.js
   @ ./src/main/index.js
   @ multi ./src/main/index.dev.js ./src/main/index.js`

**Comment by dnovacik** [comment]
a bit late but @ubirajaramneto this happens when you import your store to the index.js in the electron start file, because you import router it then needs to impor the views (.vue files) and this will fail, as webpack for main isn't configured for .vue files

have you resolved the issue?
