### ISSUE TITLE
Cannot use import components

### ISSUE THREAD

**Issue by IniZio** [SimulatedGREG/electron-vue#66]
##### Describe the issue / bug.
Gives error `Unknown custom element: <mu-menu-item> - did you register the component correctly?` when I install Muse-UI and use the components in the library after `Vue.use(MuseUI)` . Gives same error with other custom components of other libraries e.g. Vue-mdl.

It works though when I import custom components separately instead of using `Vue.use(MuseUI)`

##### How can I reproduce this problem?
1. `npm i -S muse-ui`, 
2. add `import MuseUI from 'muse-ui'` and `Vue.use(MuseUI)` to main.js
3. Use the components of muse ui.

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:4.2.6
  * NPM version:3.5.2
  * vue-cli version: (if necessary)2.5.0
  * Operating System:

**Comment by SimulatedGREG** [comment]
@IniZio 

I wasn't able to reproduce this issue you are running into. Were you sure to install `muse-ui` within the `app/package.json`? After installing, and including the css file with `import 'muse-ui/dist/muse-ui.css'`, I was able to succesfully use the `<mu-menu>` components with no errors.

**App.vue**
```html
<template>
  <div>
    <mu-paper class="demo-menu">
      <mu-menu>
        <mu-menu-item title="Preview" leftIcon="remove_red_eye"/>
        <mu-menu-item title="Share" leftIcon="person_add"/>
        <mu-menu-item title="Get Links" leftIcon="link"/>
        <mu-divider />
        <mu-menu-item title="Make a copy" leftIcon="content_copy"/>
        <mu-menu-item title="Download" leftIcon="file_download"/>
        <mu-menu-item title="Remove" leftIcon="delete"/>
      </mu-menu>
    </mu-paper>
    <mu-paper class="demo-menu">
      <mu-menu>
        <mu-menu-item title="Clear Config"/>
        <mu-menu-item title="New Config" rightIcon="person_add"/>
        <mu-menu-item title="Project" rightIcon="settings"/>
        <mu-menu-item title="Workspace" rightIcon="settings" rightIconColor="#559"/>
        <mu-menu-item title="Paragraph" rightIcon="¶"/>
        <mu-menu-item title="Section" rightIcon="§"/>
      </mu-menu>
    </mu-paper>
  </div>
</template>

<script>
  import store from 'src/vuex/store'

  export default {
    store
  }
</script>
```

**Comment by IniZio** [comment]
Sorry for mistaking as I did not enter app directory to use the package.json inside instead of the one at root. It is my fault for not reading through the instructions in Documentation that already stated the difference. Issue can be closed.
