### ISSUE TITLE
Gitbooks documentation - Broken link to vuex

### ISSUE THREAD

**Issue by RustyPedrosa** [SimulatedGREG/electron-vue#663]
##### Describe the issue / bug.
\# gitbooks documentation -> Project Structure -> Renderer Process -> Link to vuex intro page doesn't work

The link points to http://vuex.vuejs.org/en/intro.html which redirects to
https://vuex.vuejs.org/guide/guide/ which leads to a 404 page.

The link should probably just be changed to the vuex homepage https://vuex.vuejs.org/

##### How can I reproduce this problem?
\# See https://simulatedgreg.gitbooks.io/electron-vue/content/en/renderer-process.html
Last link, under "vuex modules" at bottom of page

(Sorry if this is the wrong place for documentation issues.  I thought I should mention the broken link when I found it)

**Comment by XanderLuciano** [comment]
I believe this has been fixed by a PR.
