### ISSUE TITLE
Builded App is blank!

### ISSUE THREAD

**Issue by paulvl** [SimulatedGREG/electron-vue#67]
Hi there I was just play around with this electron-vue repo to test some other simple vuejs app that I was testing. Everything is fine with `npm run dev` but when I compile the apps using `npm run build` the app just display a blank page, I had no errors during building, I'm on linux, ubuntu 14.04.

 Hope you can help me, I'm new in the webpack world.

**Comment by SimulatedGREG** [comment]
@paulvl 

Were you able to solve the issue you were having?

**Comment by paulvl** [comment]
@SimulatedGREG yes, I was viewing a blank page because vue-router mode was set to 'history', removed that and everything worked like a charm.

**Comment by SimulatedGREG** [comment]
Ahh. I think this is worth nothing in the Docs.

**Comment by c446984928** [comment]
try  add 
```javascript
function createWindow () {
  mainWindow = new BrowserWindow({
    //...
  })
// use this to open dev tools manualy to debug
 mainWindow.webContents.openDevTools()
//...
}
```

**Comment by abbrechen** [comment]
Strange, but the history mode was the reason for this issue for me, too.
