### ISSUE TITLE
Electron Builder Support

### ISSUE THREAD

**Issue by lokenx** [SimulatedGREG/electron-vue#68]
Firstly, thanks for the great project! Just got out an internal application in two days using this and it was near perfect 👍 

The only "downside" that I had was the building side of things. I typically use Jakub's [boilerplate](https://github.com/szwacz/electron-boilerplate) when I don't want or need Vue, and it uses [electron-builder](https://github.com/electron-userland/electron-builder) for its build step. The main benefit from that is I get an installable executable for Windows that copies it to the users AppData I believe and add's a Start Menu icon (as well as auto updating which I don't care about). This gives it a more native feel for the users with no work on my side--I may be lazy!

Is there any reason you went with electron-packager instead? I know you're not using a Gulp build pipeline and using Webpack (for Vue I'm assuming) so there may be a reason but just curious! I looked into making my own build step for this but I haven't had time to properly figure out how you guys are bundling things for production in a way that I can pass to electron-builder yet.

**Comment by SimulatedGREG** [comment]
@lokenx 

Thanks for the feedback, and I'm glad electron-vue helped you out.

And you'll be happy to know that `electron-builder` is already in the works (and is shown in the [GitHub Project](https://github.com/SimulatedGREG/electron-vue/projects/2)). It will soon be a `vue-cli` configuration during project scaffolding. It's been put on hold for the moment until webpack 2 releases, so I can update many things at one time including main process support, so stayed tuned. 👀

**Comment by lokenx** [comment]
Ah OK great, thanks for prompt update and project! I keep forgetting about the new GitHub projects thing.
