### ISSUE TITLE
muse-ui message相关插件在electron-vue都不能使用，是怎么回事

### ISSUE THREAD

**Issue by phpjishu** [SimulatedGREG/electron-vue#685]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
https://muse-ui.org/#/zh-CN/message
插件在该项目下无法使用

##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
Route Name:
landing-page
Vue.js:
2.5.17
Electron:
2.0.8
Node:
8.9.3
Platform:
win32

**Comment by IvanLi-CN** [comment]
同样的问题，我调试了下，发现在 electron 中引入了两个 vue 的文件，似乎这是造成找不到组件的问题。
![2018-10-07_10-41](https://user-images.githubusercontent.com/30215105/46577622-8a6c0f00-ca1d-11e8-821b-bac4cd499f05.png)
一个是 webpack://，另一个是 file://
