### ISSUE TITLE
Black page screen on production.

### ISSUE THREAD

**Issue by Peelz** [SimulatedGREG/electron-vue#687]
The problem is when I change url by using

**window.location.href = "/#/some-url"**

My app will show a blank page on production (build to .exe or AppImage), but working fine on **npm run dev**

environment.
  * Node version: 8.9
  * NPM version: 5.6
  * Operating System: ubuntu18.04, window10

Sorry, for my English.

**Comment by Akumzy** [comment]
There is something called vue-router it was made for that purpose

**Comment by bulolo** [comment]
the same

**Comment by Peelz** [comment]
> the same

This issue getting when you try to locate new link directly by using **window.location.href**.
To avoid this issue just using **vue-router** libary instead
