### ISSUE TITLE
[Docs] Expired doc certificate (legacy gitbooks.io)

### ISSUE THREAD

**Issue by brospars** [SimulatedGREG/electron-vue#688]
Gitbooks.io seems to have moved to a new domain, you may need to update the link to the documentation.

SSL expired for :
https://simulatedgreg.gitbooks.io/electron-vue/content/
https://gitbooks.io

New link : https://www.gitbook.com/

**Comment by XanderLuciano** [comment]
Thanks for the report, this looks to be an issue on Gitbook's side though as we don't have the option to use  their .com domain. We will have to wait for gitbooks to update their SSL certificate.

Hopefully they resolve this soon.

**Comment by XanderLuciano** [comment]
They have fixed their SSL certificate :)
