### ISSUE TITLE
Add .node native modules support

### ISSUE THREAD

**Issue by Dummyc0m** [SimulatedGREG/electron-vue#69]
As of right now, .node files do not get packaged into the build. I have spent several days researching ways to package .node files into the electron app but have had no luck. The node-loader for webpack would give off absolute pathes although file-loader loads the file correctly into dist. As I attempt to give .node files relative paths, then it would not load.

**Comment by SimulatedGREG** [comment]
I've had trouble myself using `node-loader` in the past. I was able to get something working with this [fork](https://github.com/nkocic/node-loader). This treats `node-loader` more like `file-loader`. I don't have major plans to provide official support for native modules at the moment, but will be implementing `electron-builder` rather soon, which helps out this situation.

**Comment by Dummyc0m** [comment]
Wow, that was quick. So, by the look of things, electron-builder will package the natives? I am not awfully familiar with builder, but wouldn't it just package the same webpack dist directory?

**Comment by SimulatedGREG** [comment]
It's taking a little time to pioneer so I'm really considering all options to get the best results. And yes electron-builder would do the same thing, but I'm planning to extend the build process to make adjustments for these types of situations.

**Comment by Dummyc0m** [comment]
Error: The specified module could not be found.
Whelp, seems like I have hit a stone wall.  The thing refuses to load for some reason, even in development.

**Comment by SimulatedGREG** [comment]
Using Native Node modules within the `renderer` process is still pretty difficult when dealing with webpack. But support for main process modules will be coming in the Mutliplex milestone which makes running native modules in the `main` process way easier.

**Comment by rdpascua** [comment]
Sorry for replying to closed issue @SimulatedGREG , but do you have any idea to package native application to the current boilerplate? do we have hacks? or workaround to integrate some of it?

**Comment by SimulatedGREG** [comment]
@rdpascua 

Sorry for late reply, been away fro the holidays.

You could try adding your module as an external dependency within the `webpack.config.js` and then updating the ignore filter in `config.js` in INCLUDE node_modules within production builds.
