### ISSUE TITLE
Problem when trying to use global Sass files.

### ISSUE THREAD

**Issue by atasanchez** [SimulatedGREG/electron-vue#699]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\# I am trying to use a global Sass file and access color variables from it in my components, but I always get the result of "variable not found".

##### How can I reproduce this problem?
\# In a new project from scratch, configure a global Sass file following the official guide in this [link](https://simulatedgreg.gitbooks.io/electron-vue/en/using_pre-processors.html).

##### If visual, provide a screenshot.
\#
![image](https://user-images.githubusercontent.com/9469502/45912085-70fa7e80-bdf2-11e8-9dc3-5b5e776acf52.png)

##### Tell me about your development environment.
  * Node version: v8.11.3
  * NPM version: 5.6.0
  * **Yarn version**: 1.6.0
  * vue-cli version: 2.9.6
  * Operating System: Windows 10 BUILD 1803

**Comment by atasanchez** [comment]
This is my current webpack configuration.

![image](https://user-images.githubusercontent.com/9469502/45912130-16155700-bdf3-11e8-9116-5b5c1df39636.png)

`'use strict'

process.env.BABEL_ENV = 'renderer'

const path = require('path')
const { dependencies } = require('../package.json')
const webpack = require('webpack')

const BabiliWebpackPlugin = require('babili-webpack-plugin')
const CopyWebpackPlugin = require('copy-webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const { VueLoaderPlugin } = require('vue-loader')

/**
 * List of node_modules to include in webpack bundle
 *
 * Required for specific packages like Vue UI libraries
 * that provide pure *.vue files that need compiling
 * https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals
 */
let whiteListedModules = ['vue']

let rendererConfig = {
  devtool: '#cheap-module-eval-source-map',
  entry: {
    renderer: path.join(__dirname, '../src/renderer/main.js')
  },
  externals: [
    ...Object.keys(dependencies || {}).filter(d => !whiteListedModules.includes(d))
  ],
  module: {
    rules: [
      {
        test: /\.(js|vue)$/,
        enforce: 'pre',
        exclude: /node_modules/,
        use: {
          loader: 'eslint-loader',
          options: {
            formatter: require('eslint-friendly-formatter')
          }
        }
      },
      {
        test: /\.scss$/,
        use: ['vue-style-loader', 'css-loader', 'sass-loader']
      },
      {
        test: /\.sass$/,
        use: ['vue-style-loader', 'css-loader', 'sass-loader?indentedSyntax']
      },
      {
        test: /\.less$/,
        use: ['vue-style-loader', 'css-loader', 'less-loader']
      },
      {
        test: /\.css$/,
        use: ['vue-style-loader', 'css-loader']
      },
      {
        test: /\.html$/,
        use: 'vue-html-loader'
      },
      {
        test: /\.js$/,
        use: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.node$/,
        use: 'node-loader'
      },
      {
        test: /\.vue$/,
        use: {
          loader: 'vue-loader',
          options: {
            extractCSS: process.env.NODE_ENV === 'production',
            loaders: {
              sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1&data=@import "./src/renderer/globals"',
              scss: 'vue-style-loader!css-loader!sass-loader?data=@import "./src/renderer/globals";'
            }
          }
        }
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: 'imgs/[name]--[folder].[ext]'
          }
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: 'media/[name]--[folder].[ext]'
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: 'fonts/[name]--[folder].[ext]'
          }
        }
      }
    ]
  },
  node: {
    __dirname: process.env.NODE_ENV !== 'production',
    __filename: process.env.NODE_ENV !== 'production'
  },
  plugins: [
    new VueLoaderPlugin(),
    new MiniCssExtractPlugin({filename: 'styles.css'}),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: path.resolve(__dirname, '../src/index.ejs'),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true
      },
      nodeModules: process.env.NODE_ENV !== 'production'
        ? path.resolve(__dirname, '../node_modules')
        : false
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin()
  ],
  output: {
    filename: '[name].js',
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '../dist/electron')
  },
  resolve: {
    alias: {
      '@': path.join(__dirname, '../src/renderer'),
      'vue$': 'vue/dist/vue.esm.js'
    },
    extensions: ['.js', '.vue', '.json', '.css', '.node']
  },
  target: 'electron-renderer'
}

/**
 * Adjust rendererConfig for development settings
 */
if (process.env.NODE_ENV !== 'production') {
  rendererConfig.plugins.push(
    new webpack.DefinePlugin({
      '__static': `"${path.join(__dirname, '../static').replace(/\\/g, '\\\\')}"`
    })
  )
}

/**
 * Adjust rendererConfig for production settings
 */
if (process.env.NODE_ENV === 'production') {
  rendererConfig.devtool = ''

  rendererConfig.plugins.push(
    new BabiliWebpackPlugin(),
    new CopyWebpackPlugin([
      {
        from: path.join(__dirname, '../static'),
        to: path.join(__dirname, '../dist/electron/static'),
        ignore: ['.*']
      }
    ]),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  )
}

module.exports = rendererConfig
`

**Comment by Abramwow** [comment]
Change this

![_20181010133133](https://user-images.githubusercontent.com/2335683/46715116-30737f80-cc91-11e8-845c-2ff8820f6997.png)

to

![_20181010133405](https://user-images.githubusercontent.com/2335683/46715145-54cf5c00-cc91-11e8-87c4-a944c1635b75.png)

This worked for me.

**Comment by atasanchez** [comment]
Ah ok, this problem is solved with answer of @Abramwow. Please, close this issue.

Thanks!

**Comment by asakiasako** [comment]
This saved my day. Thanks.

**Comment by mochi-co** [comment]
@abramdev 's [answer](https://github.com/SimulatedGREG/electron-vue/issues/699#issuecomment-428444374) worked for me. 

This should probably be updated in https://simulatedgreg.gitbooks.io/electron-vue/content/en/using_pre-processors.html because the example given doesn't work.

**Comment by cuzzins** [comment]
Wanted to follow up on this as I am also having issues following:
https://simulatedgreg.gitbooks.io/electron-vue/content/en/using_pre-processors.html 

I did also try using @abramdev 's approach and that worked, however I could never get it to allow me to use standard scss formatting. It kept wanting me to use indentedSyntax no matter how hard I tried to turn it off.

If anyone has any thoughts where I might be going wrong, please let me know. New to vue-electron.

**Comment by karlpablo** [comment]
> Wanted to follow up on this as I am also having issues following:
> https://simulatedgreg.gitbooks.io/electron-vue/content/en/using_pre-processors.html
> 
> I did also try using @abramdev 's approach and that worked, however I could never get it to allow me to use standard scss formatting. It kept wanting me to use indentedSyntax no matter how hard I tried to turn it off.
> 
> If anyone has any thoughts where I might be going wrong, please let me know. New to vue-electron.

Did you update the scss not the sass loader?

**Comment by DiegoFleitas** [comment]
Thank you @abramdev

**Comment by bbrandt** [comment]
> Change this
> 
> ![_20181010133133](https://user-images.githubusercontent.com/2335683/46715116-30737f80-cc91-11e8-845c-2ff8820f6997.png)
> 
> to
> 
> ![_20181010133405](https://user-images.githubusercontent.com/2335683/46715145-54cf5c00-cc91-11e8-87c4-a944c1635b75.png)
> 
> This worked for me.

`data` has been renamed to `prependData` [in v8](https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#800-2019-08-29).

**Comment by ngr900** [comment]
I've just spent the better part of the day resolving this, and in my case the fault lied in missing the semicolon at the end of the import.
