### ISSUE TITLE
Add appveyor.yml config setup

### ISSUE THREAD

**Issue by obonyojimmy** [SimulatedGREG/electron-vue#70]
#### *If you are looking to suggest an enhancement or feature, then feel free to remove everything above.*

Id like to propose appveyor.yml setup config to help in cl support when  using appveyor for building 

Nice , template by the way !

**Comment by AkiraLaine** [comment]
Hi @obonyojimmy 

According to @SimulatedGREG, Electron-builder support will be coming soon and he has plans to include the proper configs for both `appveyor` and `circeci` for remote building.

**Comment by SimulatedGREG** [comment]
@obonyojimmy 

Sorry for the late reply, was out on vacation. But yes, what @AkiraLaine stated is correct. I've created a Milestone you can reference to watch as things come together.
