### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by zcshan** [SimulatedGREG/electron-vue#700]
The callback-based version of packager() is deprecated and will be removed in a future major version, please convert to the Promise version or use the nodeify module.

 app for platform mas x64 using electron v2.0.10

 signing is required for mas builds. Provide the osx-sign option, or manually sign the app later.

**Comment by XanderLuciano** [comment]
https://github.com/SimulatedGREG/electron-vue/issues/348

Could you try using electron-builder instead of package?

**Comment by chunshan-pro** [comment]
electron-builder No problem

but ， I want to use it Win pack Mac application
