### ISSUE TITLE
Add pug as preprocessor

### ISSUE THREAD

**Issue by tato469** [SimulatedGREG/electron-vue#702]
##### Describe the issue / bug.
I am trying pug as template processor, I did it before in vuejs 2 projects. It is compatible?

##### How can I reproduce this problem?
I installed with yarn:
`yarn add pug pug-loader`

Edited App.vue:
```
<template lang="pug">
  #app
    router-view
</template>

<script>
  export default {
    name: 'veedar'
  }
</script>

<style>
  /* CSS */
</style>
```

and run:
`yarn run dev`
But I got this error:
```
    Error compiling template:

    #app
    	router-view

    - Component template requires a root element, rather than just text.
```

##### Tell me about your development environment.
  * Node version: 8.9.4
  * YARN version: 1.3.2

**Comment by lbenie** [comment]
i think you must add `pug-plain-loader` instead

**Comment by tato469** [comment]
Seems that it works!
I added [pug-plain loader](https://github.com/yyx990803/pug-plain-loader)
I edited `webpack.renderer.config.js` and add the rule: 
```
{
  module: {
    rules: [
      {
        test: /\.pug$/,
        loader: 'pug-plain-loader'
      }
    ]
  }
} 
```

Thanks a lot!
