### ISSUE TITLE
problem with importing codemirror

### ISSUE THREAD

**Issue by bwiercinski** [SimulatedGREG/electron-vue#704]
##### Tell me about your development environment.
  * Node version: v8.9.3
  * NPM version: 6.4.1
  * Operating System: Windows 10

##### Describe the issue / bug.

hello
I'm struggling with problem. I want to use this template with [codemirror](https://github.com/codemirror/CodeMirror) library. I have created clean project and everything I've done is replacing LandingPage.vue file with following content:
```
<template>
    <div id="wrapper">
        <textarea ref="ed" id="editor">
import someResource from 'codemirror/some-resource'
export default {
  data () {
    return {
      exampleCode: 'const a = 10'
  }
}
        </textarea>
    </div>
</template>

<script>
    /* eslint-disable */
    import CodeMirror from 'codemirror'
    import 'codemirror/mode/javascript/javascript.js'
    import 'codemirror/lib/codemirror.css'
    import 'codemirror/theme/monokai.css'

    export default {
        name: 'landing-page',
        mounted: function () {
            CodeMirror.fromTextArea(document.getElementById('editor'), {
                lineNumbers: true,
                mode: 'text/javascript',
                theme: 'monokai'
            });
        }
    }
</script>
```
but javascript coloring scheme seems to not import

when i remove 2 first lines of imports and add to index.ejs this:
```
<script src="node_modules/codemirror/lib/codemirror.js"></script>
<script src="node_modules/codemirror/mode/javascript/javascript.js"></script>
```
it starts to working but of course it's not my solution.

I thing its some problem in webpack confing.

Maybe sourcecode of [codemirror/mode/javascript/javascript.js](https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js) will help

bw

**Comment by XanderLuciano** [comment]
Are you getting any errors?

**Comment by bwiercinski** [comment]
@XanderLuciano nope :(

**Comment by XanderLuciano** [comment]
Do you *need* codemirror? Or would [Ace](https://ace.c9.io) work? I'm not too familiar with codemirror, but I have used Ace inside electron and vue before without issue. 

Also, maybe try: https://github.com/surmon-china/vue-codemirror

**Comment by bwiercinski** [comment]
@XanderLuciano

eventually I'm going to use component made by @surmon-china (witch has same problem with importing code coloring with this boilerplate webpack config), but I'm using pure Codemirror to be sure where the problem occurs. unfortunately i'm going to use features of codemirror, but i take some time to find similar in Ace.
for now i spended sleepless nigths to know why this line of import doesn't works

thanks

**Comment by bwiercinski** [comment]
ok i had to add this to webpack renderer config

`let whiteListedModules = ["vue", "codemirror", "vue-codemirror"];`

issue can be closed
