### ISSUE TITLE
修改关于主进程的代码，程序重启时遇到的问题

### ISSUE THREAD

**Issue by FAKER-A** [SimulatedGREG/electron-vue#718]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\# 修改关于主进程的代码，程序重启时遇到的问题，程序重启的过程中报一下错误
Starting inspector on 127.0.0.1:5858 failed: address already in use
##### How can I reproduce this problem?
\#
![image](https://user-images.githubusercontent.com/25676164/46859181-a1f13080-ce3f-11e8-952f-1c338a4de3d6.png)
![image](https://user-images.githubusercontent.com/25676164/46859191-a9183e80-ce3f-11e8-9e9e-a3e09c3dd4b5.png)

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:10.8.0
  * NPM version:6.2.0
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by kevinelliott** [comment]
I have this exact problem. How to remedy?

**Comment by FAKER-A** [comment]
> I have this exact problem. How to remedy?

I wrote the following in the lower 111 lines of the dev-runner.js file.
![image](https://user-images.githubusercontent.com/25676164/53726708-7ed82380-3ea9-11e9-9c68-acb94439947a.png)
