### ISSUE TITLE
setTimeout is not reliable

### ISSUE THREAD

**Issue by cristiangiagante** [SimulatedGREG/electron-vue#719]
I'm trying to clean a input text after press a button for 2000ms when I test it the clear is triggered in 3000ms Im using mouwdown event and I found a issue related to electron old versions https://github.com/electron/electron/issues/7079 I try to up the dependency version of electron to the lastest 3.0.4 and the issue persist, I ask to reopen this bug in electron but I don't know if maybe this is a issue introduced in vue-electron. I need help here, thanks

##### Describe the issue / bug.
setTimeout have a delay in order of 1000ms to the selected timeout time

##### How can I reproduce this problem?
set a timeout in a mousedown event and check the time to take be triggered

##### Tell me about your development environment.
  * Node version: 8.11.4
  * NPM version: 5.6.0
  * vue-cli version: (if necessary) N/A
  * Operating System: Windows 10

**Comment by XanderLuciano** [comment]
`setTimeout` only guarantees a _minimum_ amount of time has passed, but can take longer. If you need better timing, use `requestAnimationFrame` in a loop, checking how much time has passed with `performance.now()`.
