### ISSUE TITLE
Migrate to Webpack 2

### ISSUE THREAD

**Issue by SimulatedGREG** [SimulatedGREG/electron-vue#72]
Update setup to use Webpack 2. Initial plan to support `webpack@^2.1.0-beta.25` and release to master once official release is made.

**Comment by citycide** [comment]
FYI, be on the lookout for a stable Webpack 2.x very soon.

https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.4

> This is probably the last RC. We released it as final test.
If no critial bugs are discovered, we release 2.2.0 in < 10 days.

**Comment by SimulatedGREG** [comment]
Just what I want to hear! Thanks.

**Comment by SimulatedGREG** [comment]
Migrating webpack structure to treat all dependencies as `externals`. Much better for building and will enable use of main process modules.

**Comment by SimulatedGREG** [comment]
Webpack 2 is fully supported within the current project structure and is currently available within the `dev` branch. Since all dependencies will now be treated as `externals` I will changing the project structure a little to give more support for the `main` process. Once that is complete, expect a release to `master` soon.
