### ISSUE TITLE
No such file or directory after start a builded app

### ISSUE THREAD

**Issue by marctwen** [SimulatedGREG/electron-vue#721]
##### Describe the issue / bug.
If I try to run the application built by the command
`yarn run build`
a project with the 'steam' npm package that is imported into src/renderer/main.js, then I see a blank screen.

If i use
`yarn run dev`
everything works

I tried to add the 'steam' package to the whiteListedModules array in the webpack.renderer.config file, but that didn't work either.

In devtools I see this error (check the screenshot)

##### How can I reproduce this problem?
1)install steam npm package
`yarn add steam`
2)import this package in src/renderer/main.js file
`import steam from 'steam'`
3)run the build command
`yarn run build`
4)Start app from build/win-unpacked/(AppName).exe

##### If visual, provide a screenshot.
![image](https://user-images.githubusercontent.com/44109515/46902556-c690eb00-cec7-11e8-89e9-fb32f85b0193.png)

##### Tell me about your development environment.
  * Node version: 10.9.0
  * NPM version: 6.2.0
  * vue-cli version: (if necessary)
  * Windows 10 x64

**Comment by god-eater** [comment]
This out since this is a limitation of `asar`. This dependency calling `process.chdir` inside. Use a forked version of this package that doesn't `chdir` or you may be able just patch `fs.readFileSync`

**Comment by marctwen** [comment]
okay, thx for answer
