### ISSUE TITLE
Feature Request : Can we have out of the box support for sqllite?

### ISSUE THREAD

**Issue by zeeshanyshaikh** [SimulatedGREG/electron-vue#722]
Hi, Can we have out of the box support for sqllite or mysql (based on installation choice may be) as part of the boilerplate? or atleast some documentation with examples to implement sqllite with electron-vue ?
As i have seen people struggling to get sqlite work and so am i :) 

Let me know if any example is already been documented, please guide me through.

**Comment by 417606028** [comment]
if you want to use localDB you can try indexDB or webSQL  localForrage maybe can resolve you problem

**Comment by zeeshanyshaikh** [comment]
Any db would work, but the main thing i want is how to implement? where to do the connection (in main or renderer) and where to call the queries from. I just want the ideal implementation.

**Comment by zeeshanyshaikh** [comment]
English doesn't matter, what matters is the knowledge. :) :+1:
