### ISSUE TITLE
e-charts did not display after "npm build"

### ISSUE THREAD

**Issue by yankunsam** [SimulatedGREG/electron-vue#724]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
Here is my code: https://github.com/oasis-eos/saas/blob/master/src/renderer/components/OverviewComponent/IntegralOverview.vue

In "yarn run dev" mode, all is ok.
But after build on macbook and run the .dmg file, the charts did not show.
Thanks!
##### How can I reproduce this problem?
\#

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:
  * NPM version:
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by aKaigege** [comment]
you need add some UI dependencies to your whiteListedModules
[https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals](url)

**Comment by yankunsam** [comment]
@aKaigege  Sorry. "https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals" is wrong url.
