### ISSUE TITLE
use element-ui:$listeners is readonly. and $attrs is readonly.

### ISSUE THREAD

**Issue by zerooverture** [SimulatedGREG/electron-vue#725]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#
It's not compatible with element-ui

##### How can I reproduce this problem?
\#
use element-ui:This error occurs when both el-input and el-select are used before using el-message

##### Tell me about your development environment.
  * Node version:v8.9.0
  * NPM version:6.1.0
  * vue-cli version: (if necessary)
  * Operating System:windows 10

**Comment by bendebebe** [comment]
I've not actually used element-ui but I had a similar issue happen with vuetify and I resolved it by adding it to the whitelistedModules in the webpack config: `let whiteListedModules = ['vue', 'vuetify']`.
