### ISSUE TITLE
npm run build:web erroneous

### ISSUE THREAD

**Issue by aBlackCatAndDog** [SimulatedGREG/electron-vue#735]
#### How can I reproduce this problem?
\# first, use electron-vue build a project;
     second, implement 'npm install' to install rely on;
     third, implement 'npm run build:web' to build a web package and this step will erroneous.

#### If visual, provide a screenshot.
\#
![image](https://user-images.githubusercontent.com/22109830/47694208-9e2f1d80-dc37-11e8-8225-b4eeb61aeb4a.png)

##### Tell me about your development environment.
  * Node version: 8.11.3
  * NPM version: 5.6.0
  * vue-cli version: (if necessary) 2.9.6
  * Operating System: windows 10

**Comment by EvanWaL** [comment]
Same for me

**Comment by Imfdj** [comment]
Same for me

**Comment by miyanokomiya** [comment]
Do you use vuex-electron?
If you use it, let's try this.
https://github.com/SimulatedGREG/electron-vue/pull/751/files

**Comment by SmilinSamurai** [comment]
Try adding:

```
 node: {
    fs: 'empty',
  },
```
to the webConfig variable, inside of the webpack.web.config.js file.

**Comment by aBlackCatAndDog** [comment]
@SmilinSamurai Thank you. I tried the advice you gave and solved the problem.
