### ISSUE TITLE
right place for images

### ISSUE THREAD

**Issue by ChangJoo-Park** [SimulatedGREG/electron-vue#74]
##### Describe the issue / bug.
\#
Where is the **right** place for images?
`when I using in development build, everything is working well.
images are placed in `src/assets/images`

but after build, It has problem. App can't find images.

##### How can I reproduce this problem?
\#
```js
let trayMenu;
const iconPath = path.join(__dirname, './src/assets/images/light-tray-icon.png')
const highlightIconPath = path.join(__dirname, './src/assets/images/dark-tray-icon.png')
trayMenu = new Tray(iconPath)
trayMenu.setPressedImage(highlightIconPath)
```

##### If visual, provide a screenshot.
\#
![error!](http://i.imgur.com/OfPw3HD.png)
##### Tell me about your development environment.
  * Node version: 6.5.0
  * NPM version: 3.10.3
  * vue-cli version: (if necessary) 2.1.3
  * Operating System: macOS Sierra

**Comment by SimulatedGREG** [comment]
@ChangJoo-Park 

As per the documentation, the `app/src` folder does not exist in [final production builds](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/project_structure.html#production-builds). [**Static Assets**](https://simulatedgreg.gitbooks.io/electron-vue/content/docs/using_the_file_structure.html#using-static-assets) like the tray icons you are wanting to use should be placed within the `app/dist`folder and referenced accordingly.

**Comment by ChangJoo-Park** [comment]
@SimulatedGREG Thank you 👍  may need to add build with copy src to dist all assets
