### ISSUE TITLE
how can i update the electron version to the new version

### ISSUE THREAD

**Issue by 417606028** [SimulatedGREG/electron-vue#746]
if i want to update the electron version to newer version, waht should i do ,  or ,,,,the electron-vue can update the base devdependencies ?

**Comment by dev3k** [comment]
i tried updating electron on my app by running below command , updated from 2.0.4 to 3.0.8, seems working fine so far :)
 
`npm i -D electron@latest`

**Comment by XanderLuciano** [comment]
See #871
