### ISSUE TITLE
[Question] Error After Migration: Global SCSS vue-loader

### ISSUE THREAD

**Issue by JojoMig** [SimulatedGREG/electron-vue#752]
Just migrated from a old electron-vue into the latest and I'm having the Error Bellow...
Does any one get the Error bellow regarding the scss globals configuration for Pre-Processors?

On the old version I've successfully configured the VueLoader for Scss following these:
-  **_Docs_**: [https://github.com/SimulatedGREG/electron-vue/blob/master/docs/en/using_pre-processors.md](url)
- **_Issue_:** [https://github.com/SimulatedGREG/electron-vue/issues/125](url)

After Migrating to the Latest Electron-Vue i got this Error when running the npm run dev:

**_ERROR:_**

> ERROR in ./src/renderer/App.vue?vue&type=style&index=0&lang=scss& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/renderer/App.vue?vue&type=style&index=0&lang=scss&)
>   Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> 
>   undefined
>                      ^
>         Undefined variable: "$BrandPrimary".

##### Development Environment:
  * Node version: 10.12.0
  * NPM version: 6.4.1
  * vue-cli version: (if necessary)
  * Operating System: Windows 10 v1819

**Comment by umer4ik** [comment]
Hope this helps https://github.com/SimulatedGREG/electron-vue/issues/699#issuecomment-428444374

**Comment by JojoMig** [comment]
Hi @umer4ik yes it definitely helped! Thank you very much man! Issue Solved ;)
