### ISSUE TITLE
Travis CI Error: The command "yarn" failed and exited with 1 during .

### ISSUE THREAD

**Issue by Wenish** [SimulatedGREG/electron-vue#753]
##### Describe the issue / bug.
The Travis CI dosnt work anymore

##### How can I reproduce this problem?
Init the basic template with
```
npm install -g vue-cli
vue init simulatedgreg/electron-vue
```
Add Repo on Travis and set the env variable GH_TOKEN

##### Error Log:
```
error fs-extra-p@7.0.0: The engine "node" is incompatible with this module. Expected version ">=6 <7 || >=8". Got "7.10.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command "yarn" failed and exited with 1 during .
````

**Comment by lefuturiste** [comment]
I also encounter the same issue, I just change the yarn command to `npm i`

**Comment by xiaowang1314** [comment]
How to resolve?

**Comment by Wenish** [comment]
@xiaowang1314 https://github.com/SimulatedGREG/electron-vue/pull/754/files

**Comment by xiaowang1314** [comment]
> @xiaowang1314 https://github.com/SimulatedGREG/electron-vue/pull/754/files

thanks

**Comment by XanderLuciano** [comment]
Related PR merged.
