### ISSUE TITLE
Using Tailwind-css

### ISSUE THREAD

**Issue by AdamKeen** [SimulatedGREG/electron-vue#764]
Hi is there a way to use tailwind-css within the electron-vue, I've followed the docs but i doesn't seem to work

**Comment by tom-milner** [comment]
Did You find a solution for this? I'm struggling myself.

**Comment by AdamKeen** [comment]
Yes i did
first open `.electron-vue/webpack.renderer.config.js` and add `postcss-loader` like this
```php
{
module: {
  rules: [
    //...
    test: /\.css$/,
    use: ['vue-style-loader', 'css-loader', 'postcss-loader']
 },
```
then install it `yarn add -D postcss-loader`

Now create `postcss.config.js` in the root of the project
write inside it
````php
module.exports = {
  plugins: [
    require("tailwindcss")("./tailwind.js"),
    require("autoprefixer")(),
  ]
};
```

this should solve the problem

**Comment by ciarans** [comment]
Guys did you ever get @apply functions to work? I managed to get the inline styles working but not @apply to build my own styles

**Comment by u12206050** [comment]
@ciarans Have you been able to solve the @apply functions? I can't get them to work.

**Comment by shealan** [comment]
For anyone reading this in the future the info above helped me to get Tailwind working on Electron Vue, but you also need to do the following:

Create a tailwind.css file in your project assets folder.

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Import that into your main.js Vue script (not the App.vue)

```javascript
import './assets/css/tailwind.css'
```

**Comment by cwilby** [comment]
@MiloudiMohamed thanks, that worked!

I didn't need to run `yarn add -D postcss-loader` as it is a dependency of `vue-loader`.

**Comment by dyaskur** [comment]
in my case `postcss.config.js` didnt work , but I can set config in webpack like below: 


```
      {
        test: /\.css$/,
        use: ['vue-style-loader', 'css-loader',
        {
            loader: 'postcss-loader',
            options: {
                postcssOptions: {
                    plugins: [
                        require('tailwindcss'),
                        require('autoprefixer'),
                    ]
                }

            },
        }]
      },
```

**Comment by Ilnvokerr** [comment]
`postcss-loader@4.3.0` worked ,but the newest version  not
