### ISSUE TITLE
Unintentional SCSS?

### ISSUE THREAD

**Issue by nelsonjchen** [SimulatedGREG/electron-vue#77]
### Found an issue or bug? Tell me all about!
https://github.com/SimulatedGREG/electron-vue/blob/3ca90c627010dc7fd958145ed330c315aeaa4092/template/app/src/components/LandingPageView/Links.vue#L6

##### Describe the issue / bug.
The default Out-Of-Box link hover state does not work. The CSS here appears to be in SCSS. You can't nest stuff with plain CSS. 

##### How can I reproduce this problem?
The compile will work, but the hover state of the links at the bottom will not work. They will not go to a darker color.

##### If visual, provide a screenshot.
current (bad):

![bad](https://cloud.githubusercontent.com/assets/5363/20899290/b2dfee66-bade-11e6-8bce-2445b21d8782.gif)

what was probably meant (good):

![good](https://cloud.githubusercontent.com/assets/5363/20899308/c0209fda-bade-11e6-8a95-eafc47a21086.gif)

##### Tell me about your development environment.
  * Node version: v7.1.0
  * NPM version: i just use yarn
  * vue-cli version: (if necessary) not necessary
  * Operating System: macOS

**Comment by nelsonjchen** [comment]
I'm not sure if:

* Add SCSS

or

* Assume Plain CSS

is the solution here.

**Comment by SimulatedGREG** [comment]
Oh yeah, another nice catch!

It originally was SCSS, but was reverted to CSS since `node-sass` requires proper build tools for Windows users. Feel free to make a PR to fix, or I'll patch it up in the next update since it is not a major issue.

Thanks again @nelsonjchen

**Comment by nelsonjchen** [comment]
Cool, I'll just make a PR to make it plain.
