### ISSUE TITLE
When I run it on Ubuntu, I get an error because I can not load the svg file.

### ISSUE THREAD

**Issue by kimyearho** [SimulatedGREG/electron-vue#774]
##### Describe the issue / bug.
\#  

When running on Ubuntu, an error occurs because the svg file can not be loaded.
However, it will function normally in Windows environment. what's the problem?
In the screenshot below, all components with svg will fail. Removing svg will start it normally. Do I need additional configuration on linux?

##### If visual, provide a screenshot.
\#

![image](https://user-images.githubusercontent.com/17153380/50556316-e5f72180-0d1a-11e9-96bc-fb54ea6764bf.png)

##### Tell me about your development environment.
  * Node version: v10.15.0
  * NPM version: 6.5.0
  * vue-cli version: (if necessary) 3.2.1
  * Operating System: Ubuntu 18.04.1 LTS

**Comment by myazarc** [comment]
You use static value for src attr.
try with require.
`<img :src="require('@/assets/image.png')" />`
