### ISSUE TITLE
Unable to get constructor of async function (AsyncFunction)

### ISSUE THREAD

**Issue by wstam88** [SimulatedGREG/electron-vue#777]
I'm wondering how to change the target for babel/webpack so that it doesn't transpile the async functions. The reason for this is that there is no direct way to construct a new AsyncFunction other then by getting the prototype/constructor of an async function like this:

```js
const AsyncFunction = Object.getPrototypeOf(async function(){}).constructor;
```

When I run this code in the Chrome console from my vue electron app it will log:

`AsyncFunction() { [native code] } `

Which is what I want! However when I put the same code in one of my vue components I will get:

`Function() { [native code] }`

And thus I cannot create new async functions with the AsyncFunction constructor.

[developer.mozilla.org: AsyncFunction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction)

**Comment by frudman** [comment]
I came across a similar issue: I did not solve it "correctly" (still looking for a way to "prevent" webpack/babel from converting it out of the code (anyone?)...

...but I did find a **temporary workaround** to get the AsyncFunction, as follows:
```
const AsyncFunction = new Function(`return Object.getPrototypeOf(async function(){}).constructor`)();
log('is this correct?', AsyncFunction); // answer: yes!
```

You can then use AsyncFunction as per the example:
```
var a = new AsyncFunction('a', 'b', 'return await resolveAfter2Seconds(a) + await resolveAfter2Seconds(b);');
console.log(a, typeof a);
window.resolveAfter2Seconds = function(x) {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve(x);
      }, 2000);
    });
}
a(10, 20).then(v => console.log('Hello!', v)) // prints 30 after 4 seconds
```

**Comment by wstam88** [comment]
I resolved it by changing the babel target to the current node/browser version.
