### ISSUE TITLE
Another electron-vue project's Vuex Store has does't go away though cookies/cache clear

### ISSUE THREAD

**Issue by yokane** [SimulatedGREG/electron-vue#790]
### Describe the issue / bug.
When I develop multi project together, encountered this problem.
For example, In `/src/renderer/store/modules`,` Project A` has `Counter.js`, `Deposit.js`, `Product.js`. `Project B` has `Todo.js`, `Message.js`

First of all we have developed ProjectA, and the items of Vuex in ChromeDevTool at this time are
`store Counter, Deposit, Product `
After development of Project A was completed, when development of Project B was started, 
only `store Todo, Message` should be displayed in DevTool, but `store Counter, Deposit, Product,Todo, Message` was displayed.

### How could I resolve this problem?
I tried Electron's cache clear, but there was no effect.
```main.js
app.on("window-all-closed", () => {
  session.defaultSession.clearCache(() => {});
  mainWindow.webContents.session.clearStorageData();
  mainWindow.webContents.clearHistory();

  mainWindow = null;
});
```

When I continued exploring a little more, I found `vuex.json` in the following folder:
`/Users/<user>/Library/Application Support/Electron` (not `~/Library/Application Support/<electron-project-name/Cache`!)

Then, deleting this `vuex.json` now correctly displays `store Todo, Message` in `Project B`.

##### Tell me about your development environment.
  * Node version: 11.5.0
  * NPM version:  6.5.0
  * vue-cli version: (if necessary): 2.9.6
  * Operating System: OSX 10.14.2

#### *If you are looking to suggest an enhancement or feature, then feel free to remove everything above.*

Perhaps this problem may be caused by Electron, not electron-vue. but if you are in trouble with the same problem, please refer to this remedy.

**Comment by gabrielstuff** [comment]
Hello, the issue is with `vuex-electron` which does not expose `clear()` function. 
https://github.com/vue-electron/vuex-electron/issues/10

As this package use `electron-store` your data are saved to an other folder than the default cache from Electron. Thus you need to clear a _special_ cache folder. This is a *trap* that comes from the `vuex-electron` integration.

G

**Comment by yokane** [comment]
Oh! The cause was in `vuex-store` instead of` electron-vue`.
Thank you very much for your kindness.
