### ISSUE TITLE
Bulma sass customization

### ISSUE THREAD

**Issue by avvRobertoAlma** [SimulatedGREG/electron-vue#799]
Hello!, 

I am an attorney, but I am using this wonderful boilerplate to develop a desktop application which shall be used by Italian attorneys.
Everything is going well, but I have a maybe simple question.
I have read the docs and I have installed and imported bulma css-framework. I would like to add some customization, following the official [Bulma docs] (https://bulma.io/documentation/customize/with-node-sass/). 
I imagine i should create a `/sass/` folder and creating a `myStyle.sass` file within which import bulma and override variables (I already did so in pure vue web projects).

The question is, should I modify something in `webpack.renderer.config.js`, but exactly where?

Sorry if it is a stupid question, but I am not a developer :-(

**Comment by michalzaq12** [comment]
If you confirmed "use sass" during project scaffolding, you don't have to modify anything in `webpack.renderer.config.js`
