### ISSUE TITLE
Navigate between components with vue-router

### ISSUE THREAD

**Issue by sebastian-raubach** [SimulatedGREG/electron-vue#803]
##### Describe the issue / bug.
I'm trying to navigate between components by using the electron menu. To do so, I create events and send them via something like `mainWindow.webContents.send('navigate', 'about')`. I currently receive those events on my landing page (main component) and the call `this.$router.push(page)`.
All this works fine, if I always return back to the landing page before trying to navigate to one of the other pages.
When I try to go from non-landing page A to B via the menu, nothing happens, because the event listeners are on the non-landing page.

How can I manage page navigation in a centralized way? Can I manipulate the router from the electron menu directly? I'm trying to achieve this without every component having the same event listeners that handle navigation

##### How can I reproduce this problem?
Add `A.vue` and `B.vue` to the router and a menu to electron. From the menu call `mainWindow.webContents.send('navigate', 'a')` and in the landing page `ipc.on('navigate', this.navigate, (event, page) => { this.$router.push(page) })`.
While on A call `mainWindow.webContents.send('navigate', 'b')` from the menu. It won't redirect, as A doesn't have an event listener for page navigation.

##### Tell me about your development environment.
  * Node version: 10.15.1
  * NPM version: 6.5.0
  * vue-cli version: 3.3.0
  * Operating System: Windows 10

**Comment by MaverickMartyn** [comment]
Why not have the code handling the routing in the same file as your `<router-view></router-view>` element?
Use that as your main layout, and then change out the contents in the middle using the router view.
I hope this made sense, and if not, feel free to ask questions. :)

**Comment by sebastian-raubach** [comment]
Thanks, that indeed works just fine. Should have thought of that 🤦‍♂️
