### ISSUE TITLE
use ffi module，npm run build Error

### ISSUE THREAD

**Issue by 594904020** [SimulatedGREG/electron-vue#805]
Hello:
Using the FFI module, NPM run dev runs normally, but NPM run build package fails

你好：
使用ffi模块，npm run dev运行正常，可是npm run build打包失败

![image](https://user-images.githubusercontent.com/32348909/52911715-8bbe1a00-32e2-11e9-9900-981f136b7b68.png)

**Comment by webees** [comment]
`set npm_config_node_gyp=D:\Program Files (x86)\nodejs\npm_global\node_modules\node-gyp\bin\node-gyp.js`

环境变量未设置

**Comment by 594904020** [comment]
ok,thanks
