### ISSUE TITLE
SFC style order

### ISSUE THREAD

**Issue by 50l3r** [SimulatedGREG/electron-vue#815]
Hi guys,

How can i load SFC styles after all CSS files? My component's style override by other CSS files.

webpack.renderer.config.js

    {
        test: /\.scss$/,
        use: ['vue-style-loader', 'css-loader', 'sass-loader']
    },
    {
        test: /\.sass$/,
        use: ['vue-style-loader', 'css-loader', 'sass-loader?indentedSyntax']
    },
    {
        test: /\.less$/,
        use: ['vue-style-loader', 'css-loader', 'less-loader']
    },
    {
        test: /\.css$/,
        use: [
            'vue-style-loader',
            { loader: 'css-loader', options: { importLoaders: 1 } },
            'postcss-loader'
        ]
    },
    {
        test: /\.vue$/,
        use: {
            loader: 'vue-loader',
            options: {
                extractCSS: process.env.NODE_ENV === 'production',
                loaders: {
                    sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1',
                    scss: 'vue-style-loader!css-loader!sass-loader',
                    less: 'vue-style-loader!css-loader!less-loader'
                }
            }
        }
	},

postcss.config.js:

	var tailwindcss = require('tailwindcss');

	module.exports = {
		plugins: [
			tailwindcss('tailwind.js'),
			require('autoprefixer'),
		]
	}

**Comment by FluidCui** [comment]
I‘m not a programmer,I'm just passing by···

**Comment by 50l3r** [comment]
I dont understand your answer 😅

**Comment by michalzaq12** [comment]
You can't force the loading order through webpack configuration. 
Simply import all css files before you create vue instance in main.js

**Comment by 50l3r** [comment]
Thanks, i'l change the order :)
