### ISSUE TITLE
Upgrade electron to 5.0.0 beta fails

### ISSUE THREAD

**Issue by betterRunner** [SimulatedGREG/electron-vue#835]
#### Found an issue or bug with electron-vue? Tell me all about it!
\#
I was trying to upgrade the electron from 4.0.0 to 5.0.0 beta with `yarn upgrade electron@beta`, but the project raises errors when running `npm run dev` and the screen is blank.

##### Describe the issue / bug.
\#
`Uncaught ReferenceError: require is not defined
    at (index):1`
`Uncaught ReferenceError: module is not defined
    at renderer.js:1`

##### How can I reproduce this problem?
\#
`npm run dev`

##### If visual, provide a screenshot.
\#

##### Tell me about your development environment.
  * Node version:v11.11.0
  * NPM version:6.9.0
  * vue-cli version: (if necessary)
  * Operating System:

**Comment by angelbeatsying** [comment]
Solved excuse me

**Comment by davidAlittle** [comment]
Please explain your solution for others (like myself) looking for the same.

**Comment by BorysTyminski** [comment]
I am also looking for this answer. I also need to upgrade NodeJS to latest version.

**Comment by BorysTyminski** [comment]
Answer is now in #855

**Comment by linuxjuggler** [comment]
You should specify the following option in `src/main/index.js` file

```
    webPreferences: {
      nodeIntegration: true,
    }, 
```

You can check my full answer here https://github.com/SimulatedGREG/electron-vue/issues/855#issuecomment-503002257

**Comment by heronggen** [comment]
hey @betterRunner check the answer here #855 and especially the last comment #855 (comment)
