### ISSUE TITLE
How to use electron protocol in Vue? | 怎么在Vue中使用 electron protocol

### ISSUE THREAD

**Issue by StringKe** [SimulatedGREG/electron-vue#836]
How to use [protocol](https://electronjs.org/docs/api/protocol) in Vue？
RegisterFileProtocol and registerHttpProtocol cannot be used in Vue Route, outputting the contents of index.html

不知道怎么配合vue router来实现这个效果，很多情况下只输出了index.html的内容，要么就是js的内容找不到位置

**Comment by fushilu06** [comment]
解决了吗
