### ISSUE TITLE
failed to fetch extension error

### ISSUE THREAD

**Issue by yushunwei** [SimulatedGREG/electron-vue#84]
![image](https://cloud.githubusercontent.com/assets/4023816/21256185/d50d0fc0-c3ab-11e6-98af-c3b6d6c57123.png)

**Comment by SimulatedGREG** [comment]
@yushunwei 

This is an issue with [`electron-devtools-installer`](https://github.com/MarshallOfSound/electron-devtools-installer/issues/25). If you are behind a proxy then it will fail to download the extensions from the Google Chrome Store.
