### ISSUE TITLE
Update devtools to v5.0.0

### ISSUE THREAD

**Issue by mittalyashu** [SimulatedGREG/electron-vue#844]
How to update vue devtools to version `5.0.0`?

**Comment by michalzaq12** [comment]
Try to delete folder 
C:/Users/< user >/AppData/Roaming/Electron/extensions/nhdogjmejiglipccpnnnanhbledajbpd (vue devtools ID)

`electron-devtools-installer` should automatically download the latest version

**Comment by mittalyashu** [comment]
Awesome, it worked. Thanks.
