### ISSUE TITLE
Bug Electron 5.0.0

### ISSUE THREAD

**Issue by Kaa10** [SimulatedGREG/electron-vue#865]
updating to electron 5.0.0 occurs errors as shown below.
Note:
To install the final electro 5.0.0 it is necessary to install the packages before:
 - ajv-keywords
 - ajv

I've tried uninstalling and installing again, but to no avail!
So far I have returned to version 4.1.4 which is running smoothly.
![npm i electron@latest](https://user-images.githubusercontent.com/49574544/56699960-2b769a80-66ce-11e9-8634-f5dda3fc5910.PNG)
![electron debug app](https://user-images.githubusercontent.com/49574544/56699968-35989900-66ce-11e9-913d-634236600b5a.PNG)

**Comment by Fndroid** [comment]
default value of ``webPreferences.nodeIntegration`` is ``false`` in Electron 5.0.0

so what you can do is set it to true in src/main/index.js

**Comment by yaoleia** [comment]
mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      webSecurity: false
    }
  })

**Comment by serhii-cherednyk** [comment]
I have the same issue. Did you find a solution?

**Comment by Kaa10** [comment]
Hello. 

I did it in my code as yaoleia commented.

It's work

mainWindow = new BrowserWindow({
webPreferences: {
nodeIntegration: true,
nodeIntegrationInWorker: true,
webSecurity: false
}
})

Thanks

**Comment by serhii-cherednyk** [comment]
> Hello.
> 
> I did it in my code as yaoleia commented.
> 
> It's work
> 
> mainWindow = new BrowserWindow({
> webPreferences: {
> nodeIntegration: true,
> nodeIntegrationInWorker: true,
> webSecurity: false
> }
> })
> 
> Thanks

could u send me your package.json?

**Comment by Vmadmax** [comment]
@serhii-cherednyk 
in `index.js`
replace:
```javascript
mainWindow = new BrowserWindow({
    height: 563,
    useContentSize: true,
    width: 1000
  })
```

with:
```javascript
mainWindow = new BrowserWindow({
    height: 563,
    useContentSize: true,
    width: 1000,
    webPreferences: {
      nodeIntegration: true,
      nodeIntegrationInWorker: true,
      webSecurity: false
    }
  })
```
