### ISSUE TITLE
Could not locate the bindings file

### ISSUE THREAD

**Issue by 1198681139** [SimulatedGREG/electron-vue#866]
Uncaught Error: Could not locate the bindings file. Tried:
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/build/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/build/Debug/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/build/Release/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/out/Debug/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/Debug/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/out/Release/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/Release/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/build/default/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/compiled/10.11.0/darwin/x64/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/addon-build/release/install-root/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/addon-build/debug/install-root/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/addon-build/default/install-root/bindings.node
 → /Users/shijian/electron/lock-upper-monitor/build/mac/molcok.app/Contents/Resources/app.asar/lib/binding/node-v69-darwin-x64/bindings.node

**Comment by xihadandan** [comment]
I have the same question
