### ISSUE TITLE
ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by penghzhang** [SimulatedGREG/electron-vue#867]
Hi,
Recently, I used this project to package my application. I locate my JS code in src/renderer/*, and in the index.ejs, I add "  <script type="text/javascript" src="src/renderer//util/Utils.js"></script>". But after I package the App using 'npm run build:win32', I found 'ERR_FILE_NOT_FOUND' in the console. Anyone can help me?

**Comment by linuxjuggler** [comment]
you can't add the file manually to `index.ejs` file, you should modify `webpack.renderer.config.js` file and add that file to `rendererConfig`

something like:

```javascript
  entry: {
    renderer: [
        path.join(__dirname, '../src/renderer/main.js'),
        path.join(__dirname, '../src/renderer/util/Utils.js')
    ]
  },
```
