### ISSUE TITLE
Vuex Electron Storage is not valid, Cause the page blank;

### ISSUE THREAD

**Issue by mxj7000** [SimulatedGREG/electron-vue#870]
When I use the electron builder to build the package , then successfully installed in the pc, but when I run it ,run into this issue, error message:

C:\Users\Administrator\AppData\Local\Programs\kaka\resources\app.asar\node_modules\vuex-electron\dist\persisted-state.js:1 Uncaught Error: [Vuex Electron] Storage is not valid. Please, read the docs.
    at a (C:\Users\Administrator\AppData\Local\Programs\kaka\resources\app.asar\node_modules\vuex-electron\dist\persisted-state.js:1)
    at C:\Users\Administrator\AppData\Local\Programs\kaka\resources\app.asar\node_modules\vuex-electron\dist\persisted-state.js:1
    at renderer.js:12
    at Array.forEach (<anonymous>)
    at new y (renderer.js:12)
    at Object.<anonymous> (renderer.js:7)
    at d (renderer.js:1)
    at n (renderer.js:1)
    at Object.<anonymous> (renderer.js:7)
    at d (renderer.js:1)
a @ C:\Users\Administrator\AppData\Local\Programs\kaka\resources\app.asar\node_modules\vuex-electron\dist\persisted-state.js:1
(anonymous) @ C:\Users\Administrator\AppData\Local\Programs\kaka\resources\app.asar\node_modules\vuex-electron\dist\persisted-state.js:1
(anonymous) @ renderer.js:12
y @ renderer.js:12
(anonymous) @ renderer.js:7
d @ renderer.js:1
n @ renderer.js:1
(anonymous) @ renderer.js:7
d @ renderer.js:1
n @ renderer.js:1
(anonymous) @ renderer.js:7
d @ renderer.js:1
n @ renderer.js:1
(anonymous) @ renderer.js:7
d @ renderer.js:1
(anonymous) @ renderer.js:1
(anonymous) @ renderer.js:1
C:\Users\Administrator\AppData\Local\Programs\kaka\resources\app.asar\node_modules\vue\dist\vue.runtime.common.js:8087 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
C:\Users\Administrator\AppData\Local\Programs\kaka\resources\app.asar\node_modules\vue\dist\vue.runtime.common.js:8098 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

**Comment by notbucai** [comment]
Have you solved the problem? I have encountered it, too

**Comment by Gkiokan** [comment]
I've found a valide fix for this error.  
You can find it here in my comment: [fix for Storage is not valid](https://github.com/vue-electron/vuex-electron/issues/38#issuecomment-1008051401)
