### ISSUE TITLE
electron  Error: ETIMEDOUT  at Timeout._onTimeout (E:\lpsp-lclient11\lpsp-lclient\node_modules \request\request.js:813:19)

### ISSUE THREAD

**Issue by yushunwei** [SimulatedGREG/electron-vue#89]
![image](https://cloud.githubusercontent.com/assets/4023816/21344527/2736284e-c6d7-11e6-8747-2b90f761ab92.png)

**Comment by SimulatedGREG** [comment]
Please don't post duplicate issues. I've already expressed this is not an issue with the boilerplate. If you want to opt-out of using `vue-devtools`, then modify your [`app/electron.js`](https://github.com/SimulatedGREG/electron-vue/blob/master/template/app/electron.js#L35).
