### ISSUE TITLE
how to update electron version to the new version

### ISSUE THREAD

**Issue by heronggen** [SimulatedGREG/electron-vue#890]
who can help me? update electron version to the Latest release v5.0.4

**Comment by linuxjuggler** [comment]
hey @heronggen check the answer here https://github.com/SimulatedGREG/electron-vue/issues/855 and especially the last comment https://github.com/SimulatedGREG/electron-vue/issues/855#issuecomment-503002257

and be sure to close this ticket if you got the answer you need

**Comment by heronggen** [comment]
@linuxjuggler  Thanks very much
