### ISSUE TITLE
devtool里面的network不显示网络请求

### ISSUE THREAD

**Issue by Cmelon9** [SimulatedGREG/electron-vue#891]
不知道为什么devtool里面的network为什么无缘无故就开始不显示网络请求了，本来还以为自己配置错了什么项，然后回滚到很久之前的版本测试，还是不会显示网络请求，只会显示一些静态资源的加载。不知道有没有人有同样情况，这样子开发真的很难受，完全看不到网络请求，都不知道有没有发出请求。。

**Comment by Cmelon9** [comment]
我试用了ajax，能看到网络请求，但是axios在network里面就看不到，真的奇怪

**Comment by panjiang** [comment]
我也遇到过这个问题，axios新版本的问题，降回老版本就好了

**Comment by Cmelon9** [comment]
> 我也遇到过这个问题，axios新版本的问题，降回老版本就好了

请问你用什么版本的axios呢？

**Comment by c690554125** [comment]
因为axios0.19版本，内部源码在判断使用adapters改了逻辑，优先判断了是否存在node环境的process全局变量，如果是的话，用的是node环境的。导致接口请求浏览器抓不到了。

全部配置下adapters就行
axios.defaults.adapter = require('axios/lib/adapters/http');

**Comment by chenendian** [comment]
我把axios 版本修改成0.18.0  发现还是不行   用原生的xhr是能看到请求的   我也尝试了下面这个方案发现也不行

> 因为axios0.19版本，内部源码在判断使用adapters改了逻辑，优先判断了是否存在node环境的process全局变量，如果是的话，用的是node环境的。导致接口请求浏览器抓不到了。
> 
> 全部配置下adapters就行
> axios.defaults.adapter = require('axios/lib/adapters/http');

**Comment by chenendian** [comment]
看了一下 axios 的源码这个问题解决了   应该配置这个    配置替换后就行了 axios.defaults.adapter = require('axios/lib/adapters/xhr');
