### ISSUE TITLE
Init command not working

### ISSUE THREAD

**Issue by lucasctd** [SimulatedGREG/electron-vue#894]
##### Describe the issue / bug.
When I type `vue init simulatedgreg/electron-vue my-project` it first asks me for the App Name, then for App ID, but it stucks on App ID, it neither let me type the App ID nor it let me press enter to use the default.

##### How can I reproduce this problem?
Run:
```
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project
```
Type the App Name (or use the default) then try to type the App ID.

##### If visual, provide a screenshot.
![Video_1561045468](https://user-images.githubusercontent.com/5876679/59940851-25810980-9432-11e9-9162-6b831e4d96dc.gif)

##### Tell me about your development environment.
  * Node version: 10.15.3
  * NPM version: 6.4.1
  * vue-cli version: 2.9.6
  * Operating System: Windows 10

**Comment by ZzqiZQute** [comment]
I have the same problem. 😥

As it's the first time I use `electron-vue`, I have no idea whether if my operating system (Windows 10) make it stop working. I recently updated the version of Windows to `10.0.18917.1000` and moved it to the `Hyper-V` architecture. 

I also try it on the Linux system and the Termux  on the Android system(just for try), and it works.

**Comment by thomasraydeniscool** [comment]
I am having the same problem. I am using Ubuntu.

I have tried waiting & changing my network, but all I can do is kill the node process.

**Comment by 3lVv0w** [comment]
sam issue here

**Comment by HashPloXR** [comment]
This happens on Mac as well. After entering the Application Name, it prompts you for the Application Id and essentially hangs (i.e. you cannot do anything, not even CTRL+C)

**Comment by rm170** [comment]
I have the same problem on my Mac.

**Comment by michalzaq12** [comment]
After some research, I found the reason for hanging. [#807](https://github.com/SBoudrias/Inquirer.js/issues/807) [#88](https://github.com/strongloop/loopback-cli/issues/88)
It was bug  in vue-cli dependency 'Inquirer.js' and it was fixed 10 hours ago. 

To download latest 'Inquirer.js' you need to find a global node_modules directory
(for windows: C:\Users\<user>\AppData\Roaming\npm\node_modules) and delete the entire vue-cli dir.
Then download the vue-cli package again:
`npm install -g vue-cli`

**Comment by ZzqiZQute** [comment]
@michalzaq12 Problem solved, thank you so much.

**Comment by lucasctd** [comment]
It's working now.
