### ISSUE TITLE
Landing page showing as Anonymous Component

### ISSUE THREAD

**Issue by artokun** [SimulatedGREG/electron-vue#9]
Quick fix for this:

In _app/src/routes.js_

```
import Vue from 'vue'

export default {
  '/': {
    component: Vue.component('landing-page', require('./components/LandingPageView'))
  }
}
```

Then just add `name` to your component like so:

In _app/src/components/LandingPageView.vue_

```
...
export default {
    components: {
      CurrentPage,
      Links,
      Versions
    },
    name: 'landing-page'
  }
...
```

**Comment by thisisforeagle** [comment]
Found this page from a google search.
This has been bugging me for longer than I'd care to admit!!

Thanks @artokun
