### ISSUE TITLE
Help! How to make an installer of my application using your boilerplate? Thanks

### ISSUE THREAD

**Issue by rob1121** [SimulatedGREG/electron-vue#90]
Help! How to make an installer of my application using your electron-vue boilerplate? Thanks

**Comment by SimulatedGREG** [comment]
If you need an installer, then look no further than using [`electron-builder`](https://github.com/electron-userland/electron-builder). It takes a little extra configuration but is easy to place inside the electron-vue project structure with ease. I am actually going to bring support for this once webpack 2 is officially released so stay tuned.
