### ISSUE TITLE
AG-GRID: Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by i3lackout223** [SimulatedGREG/electron-vue#901]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
I can't use Ag-Grid. I get the Error `Uncaught SyntaxError: Unexpected token import`
\#

##### How can I reproduce this problem?
Just try to setup ag-grid:
- https://www.ag-grid.com/vue-getting-started/#add-ag-grid-to-your-project
\#

##### If visual, provide a screenshot.
![Bildschirmfoto 2019-07-10 um 01 02 36](https://user-images.githubusercontent.com/52723212/60928693-abb0a300-a2ae-11e9-8c9b-2029e25aa0ac.png)
\#

##### Tell me about your development environment.
  * Node version: v8.9.1
  * NPM version: 6.9.0
  * vue-cli version: (if necessary)
  * Operating System: Mac OS Mojave 10.14.5

#### *If you are looking to suggest an enhancement or feature, then feel free to remove everything above.*

**Comment by AllenLiuNZ** [comment]
Yeah, I met the same issue.

<img width="730" alt="Screen Shot 2019-08-15 at 4 46 07 PM" src="https://user-images.githubusercontent.com/31225357/63073313-61d96d80-bf7c-11e9-9e2a-f450fc8fa013.png">

- Node version: v8.4.0
- NPM version: 6.10.3
- Operating System: Mac OS Mojave 10.14.6

**Comment by lunaeidolon** [comment]
Same issue

**Comment by lunaeidolon** [comment]
Uncaught SyntaxError: Unexpected token import
Need Help PLEASE!
