### ISSUE TITLE
npm run dev error 

### ISSUE THREAD

**Issue by LittleChai** [SimulatedGREG/electron-vue#902]
Html Webpack Plugin:
  ReferenceError: process is not defined
  
  - index.ejs:11 eval
    [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2
  
  - index.ejs:16 module.exports
    [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3
  
  - index.js:284 
    [electron_demo]/[html-webpack-plugin]/index.js:284:18
  
  - task_queues.js:89 processTicksAndRejections
    internal/process/task_queues.js:89:5

**Comment by LG17** [comment]
same question...

**Comment by LittleChai** [comment]
I solved this problem
change node version to 10.16.0

**Comment by LG17** [comment]
> I solved this problem
> change node version to 10.16.0

i solved this problem as Issues #871

**Comment by MarkMinerov** [comment]
> I solved this problem
> change node version to 10.16.0

It helped me also, thank you. I think node has some bugs in new versions, just install version 10.16.0 and everything will work again
