### ISSUE TITLE
babili-webpack-plugin case some wrong code

### ISSUE THREAD

**Issue by zhangshichun** [SimulatedGREG/electron-vue#903]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
just see https://github.com/zhangshichun/electron-vue-build-bug

##### How can I reproduce this problem?
just run build  https://github.com/zhangshichun/electron-vue-build-bug

##### Tell me about your development environment.
  * Node version: 10.16.0
  * NPM version: 6.9.0
  * vue-cli version: (if necessary) 3.7.0
  * Operating System: windows

#### WHY?
It cased by the babili-webpack-plugin, this webpack-plugin may minify you JS code,and make it wrong
from
```
    computed: {
        isCountEq2 () {
            return this.count + '' === '2'
        }
    }
```
to

```
computed:{isCountEq2:function(){return this.count+"2"}}
```
and this plugin's last commit, is 3 years ago……

#### HOW TO DO?
just use babel-minify-webpack-plugin!

**Comment by XanderLuciano** [comment]
PR merged
