### ISSUE TITLE
How to use electron protocol in Vue? | 怎么在Vue中使用 electron protocol

### ISSUE THREAD

**Issue by fushilu06** [SimulatedGREG/electron-vue#905]
How to use protocol in Vue？
RegisterFileProtocol and registerHttpProtocol cannot be used in Vue Route, outputting the contents of index.html

不知道怎么配合vue router来实现这个效果，很多情况下只输出了index.html的内容，二级路由无法正确进入

**Comment by fushilu06** [comment]
@StringKe

**Comment by StringKe** [comment]
protocol 无法配合 vue router ，我也没有找到解决方法
只有 修改地址 /index.html#aaa 这种方法

具体原因为  protocol 发送html后 js和css文件的不正确，可以理解成 html结构正常，但是js和css的文件位置不正确，无法加载，这个问题我想用文件代理的方式实现或者把静态文件都改成url方式但是没有实现

**Comment by fushilu06** [comment]
registerHttpProtocol + [server](https://www.npmjs.com/package/server)
![自定义协议](https://user-images.githubusercontent.com/52439659/61590277-0a4c1a00-abe9-11e9-9c1f-f9119d1f6d66.gif)

**Comment by StringKe** [comment]
看看你的代码。。server是怎么做的

**Comment by fushilu06** [comment]
![image](https://user-images.githubusercontent.com/52439659/61612710-de38a380-ac91-11e9-9747-9bd963d1f357.png)
![image](https://user-images.githubusercontent.com/52439659/61612732-ed1f5600-ac91-11e9-9ec8-54a0809dde7f.png)
