### ISSUE TITLE
Hwo to disable auto open devTools in development environment

### ISSUE THREAD

**Issue by legolaserea** [SimulatedGREG/electron-vue#911]
I set a window as transparent window in the BrowserWindow options by
`frame: false, transparent: true,`
this window will not work when the devTools is open.

Unfortunately, when i start electron-vue project by `npm run dev`, it will auto open the devTools. How can i disable auto opening  devTools by some configs or options?

**OS: Windows 10,
     vue-electron: 1.0.6
     Electron: v6.0.0**

**Comment by zeybek** [comment]
https://github.com/SimulatedGREG/electron-vue/blob/master/template/src/main/index.dev.js#L11

Change `showDevTools: true` to `showDevTools: false`
