### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by ChangJoo-Park** [SimulatedGREG/electron-vue#915]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#

Add https://github.com/jinjiang/vue-mark-display in electron-vue project.

##### How can I reproduce this problem?
\#
```
npm run dev
```
##### If visual, provide a screenshot.
\#
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1451365/63083167-0363bd80-bf83-11e9-975c-7a2262530dcd.png">

##### Tell me about your development environment.
  * Node version: 10
  * NPM version: 6
  * vue-cli version: (if necessary)
  * Operating System: macOS

**Comment by tahaferhani** [comment]
You should add **vue-mark-display** to whitelist in `.electron-vue/webpack.renderer.config.js`

```
/**
 * List of node_modules to include in webpack bundle
 *
 * Required for specific packages like Vue UI libraries
 * that provide pure *.vue files that need compiling
 * https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals
 */
let whiteListedModules = ['vue', 'vue-mark-display']
```
