### ISSUE TITLE
Can't debugging renderer process with VSCode

### ISSUE THREAD

**Issue by leonkong** [SimulatedGREG/electron-vue#918]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
\#  
I can debugging main process, set breakpoint and track it. But when I am setting a breakpoint in renderer process, the breakpoint will be disabled and can't be track.

##### How can I reproduce this problem?
\# 
VSCode launch.json file
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "launch",
        "name": "Electron: Main",
        "cwd": "${workspaceRoot}",
        "runtimeExecutable": "node",
        "windows": {
            "runtimeExecutable": "node"
        },
        "runtimeArgs" : [
          ".electron-vue/dev-runner.js",
          "--remote-debugging-port=9223",
        ],
        "sourceMaps": true,
        "env": {
          "npm_execpath": "npm-cli.js"
        },
        "protocol": "inspector",
      },
      {
        "name": "Electron: Render",
        "type": "chrome",
        "request": "attach",
        "port": 9223,
        "timeout": 30000,
        "sourceMaps": true,
        "webRoot": "${workspaceFolder}/src",
      },
  ],
  "compounds": [
    {
      "name": "Electron: All",
      "configurations": [
          "Electron: Main",
          "Electron: Render"
      ]
    },
  ]
}

In webpack.main.config.js, I add mainConfig.devtool = 'source-map' in "Adjust mainConfig for development settings" section.
In webpack.renderer.config.js, I add rendererConfig.devtool = 'source-map' in "Adjust rendererConfig for development settings" section.

In VSCode debug view, run "Electron: All", I can set breakpoint in main process, such as ./src/main/index.js. But I can't set breapoint in renderer process, such as script section in LandingPage.vue.

##### If visual, provide a screenshot.
\#
![image](https://user-images.githubusercontent.com/26429579/63578627-785a7700-c5c3-11e9-8769-304769a105db.png)

##### Tell me about your development environment.
  * Node version: 10.11.0
  * NPM version: 6.9.0
  * vue-cli version: 2.6.1
  * Electron version: 4.0.3
  * Operating System: macOSX 10.14.6

**Comment by panghaijiao** [comment]
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Electron: Main",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "node",
            "windows": {
                "runtimeExecutable": "node"
            },
            "runtimeArgs" : [
                ".electron-vue/dev-runner.js",
                "--remote-debugging-port=9223",
            ],
            "sourceMaps": true,
            "env": {
                "npm_execpath": "npm-cli.js"
            },
            "protocol": "inspector",
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Electron: Render",
            "port": 9223,
            "timeout": 30000,
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}/src",
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*",
            }
        },
    ],
    "compounds": [
        {
            "name": "Electron: All",
            "configurations": [
                "Electron: Main",
                "Electron: Render"
            ]
        }
    ]
}

**Comment by panghaijiao** [comment]
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Electron: Main",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "node",
            "windows": {
                "runtimeExecutable": "node"
            },
            "runtimeArgs" : [
                ".electron-vue/dev-runner.js",
                "--remote-debugging-port=9223",
            ],
            "sourceMaps": true,
            "env": {
                "npm_execpath": "npm-cli.js"
            },
            "protocol": "inspector",
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Electron: Render",
            "port": 9223,
            "timeout": 30000,
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}/src",
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*",
            }
        },
    ],
    "compounds": [
        {
            "name": "Electron: All",
            "configurations": [
                "Electron: Main",
                "Electron: Render"
            ]
        }
    ]
}`

**Comment by panghaijiao** [comment]
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Electron: Main",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "node",
            "windows": {
                "runtimeExecutable": "node"
            },
            "runtimeArgs" : [
                ".electron-vue/dev-runner.js",
                "--remote-debugging-port=9223",
            ],
            "sourceMaps": true,
            "env": {
                "npm_execpath": "npm-cli.js"
            },
            "protocol": "inspector",
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Electron: Render",
            "port": 9223,
            "timeout": 30000,
            "sourceMaps": true,
            "webRoot": "${workspaceFolder}/src",
            "sourceMapPathOverrides": {
                "webpack:///src/*": "${webRoot}/*",
            }
        },
    ],
    "compounds": [
        {
            "name": "Electron: All",
            "configurations": [
                "Electron: Main",
                "Electron: Render"
            ]
        }
    ]
}

**Comment by leonkong** [comment]
I have solved this problem,thanks all.
Vscode how to debug renderer process
1、modify .electron-vue/dev-runner.js 
function startElectron () {
  var args = [
    '--inspect=5858',
    '--remote-debugging-port=9223', // add this line
    path.join(__dirname, '../dist/electron/main.js')
  ]

2、.electron-vue/webpack.renderer.config.js
modify devtool: '#cheap-module-eval-source-map',
to devtool: '#eval-source-map',

3、launch.json文件
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Renderer",
      "type": "chrome",
      "request": "attach",
      "port": 9223,
      "webRoot": "${workspaceFolder}/src",
      "timeout": 5000,
      "sourceMapPathOverrides": {
        "webpack:///./*": "${webRoot}/*",
        "webpack:///src/*": "${webRoot}/*",
        "webpack:///*": "*"
      }
    },
  ]
}

4、npm run dev
5、debug， and select item with 9080（according to the port in .electron-vue/server.listen()）
6、set breakpoint and enjoy
