### ISSUE TITLE
eslint Parsing error: Unexpected token

### ISSUE THREAD

**Issue by Jodathan** [SimulatedGREG/electron-vue#928]
#### Found an issue or bug with electron-vue? Tell me all about it!
Questions regarding how to use `electron` or `vue` are likely to be closed as they are not direct issues with this boilerplate. Please seek solutions from official documentation or their respective communities. 

##### Describe the issue / bug.
After I added an electron ipcMain listener to my src/main/index.js file, I got the eslint error "Parsing error: Unexpected token". I already tried to create a clean project and paste the file into it but it did'nt work.

##### How can I reproduce this problem?
Add a ipcMain listener to the index.js file. I wrote the callback function arrow-style.

##### If visual, provide a screenshot.
<img width="480" alt="unexpected token" src="https://user-images.githubusercontent.com/17207671/65691266-da9a1200-e070-11e9-824b-14bfe50663e3.PNG">

##### Tell me about your development environment.
  * Node version: 10.16.3
  * NPM version: 6.11.3
  * vue-cli version: (if necessary)
  * Operating System: Windows 10

**Comment by symant233** [comment]
eslint on `index.ejs`: Parsing error: Unexpected token

![image](https://user-images.githubusercontent.com/25316350/72605743-4eca2f80-3958-11ea-92d7-cbcebb300738.png)
