### ISSUE TITLE
How to create multiple windows?

### ISSUE THREAD

**Issue by gicaivo** [SimulatedGREG/electron-vue#944]
```
let previewWindow = null;
const  previewURL = process.env.NODE_ENV === 'development'
  ? `http://localhost:9080/#/preview` // this is OK in developoment
  : `file://${__dirname}/index.html#preview`; // this is NOT OK in production, how to set production URL??
```

This works well in development, but how can I use it in production. How should I write ` file://${__dirname}/index.html#preview`

```
export default new Router({
  routes: [{
      path: '/',
      name: 'Home',
      component: require('@/components/Home').default
    }, {
      path: '/preview',
      name: 'Preview',
      component: require('@/components/Preview').default
    }]
})
```

**Comment by zandercodes** [comment]
You can define several urls for the different pages and then create a second window in Electron with the other url.

**Comment by gicaivo** [comment]
@zandercodes thanks,  where is the `index.html` and where should I create second.html?

I'm using SPA:

BTW, I have following route:

```
export default new Router({
  routes: [{
      path: '/',
      name: 'Home',
      component: require('@/components/Home').default
    }, {
      path: '/preview',
      name: 'Preview',
      component: require('@/components/Preview').default
    }]
})
```

**Comment by gicaivo** [comment]
Solved: https://github.com/SimulatedGREG/electron-vue/issues/736

**Comment by d0peCode** [comment]
@gicaivo So for every new window we create new Vue instance? With own router which contains one route `/`? It kinda sucks. Electron should be used with Nuxt. If I would be starting new project I would chose this https://github.com/michalzaq12/electron-nuxt
