### ISSUE TITLE
npm/yarn run dev fails with SyntaxError

### ISSUE THREAD

**Issue by Secr3ts** [SimulatedGREG/electron-vue#949]
##### Describe the issue / bug.
\#
`npm run dev` / `yarn run dev` fails with SyntaxError: Unexpected token {
##### How can I reproduce this problem?
\#
Install node 10.13.0, init a project then run dev server
##### If visual, provide a screenshot.
\#
http://prntscr.com/pumc9k
http://prntscr.com/pumcca
##### Tell me about your development environment.
  * Node version:
10.13.0 (v12 doesn't work)
  * NPM version:
6.4.1
  * vue-cli version: (if necessary)
4.0.5
  * Operating System:
Windows 10 Pro (also fails on Fedora 30)

**Comment by yangjiakun326** [comment]
you can try to:  yarn add electron-localshortcut@3.1.0

**Comment by Secr3ts** [comment]
@yangjiakun326 I'll try this

**Comment by Crossfire972** [comment]
I can confirm that @yangjiakun326 solution works

**Comment by ROTGP** [comment]
@yangjiakun326 it's a temporary solution, @SimulatedGREG this needs a permanent fix

**Comment by derekzhan** [comment]
windows cmd run：npm install electron-localshortcut@3.1.0

**Comment by Secr3ts** [comment]
yo thanks all for your replies

**Comment by Secr3ts** [comment]
should i close this issue ?
