### ISSUE TITLE
Can't create a route using vue accessory

### ISSUE THREAD

**Issue by gjuchault** [SimulatedGREG/electron-vue#95]
##### Describe the issue / bug.
Running `npm run vue:route Test` on a fresh electron-vue package is not working

##### How can I reproduce this problem?
Using latest CLI, run basic steps (vue init, npm install) and try adding a route

Stack trace:
```
/.../project/tasks/vue/route.js:26
    .replace(/\n$/, '')
    ^
SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

##### Tell me about your development environment.
  * Node version: 7.1
  * NPM version: 4.0.3 (yarn 0.17.8)
  * vue-cli version: 2.7.0
  * Operating System: macos Sierra

Additional notes:
This might be related to the vue-cli templating system where we can see that [this line](https://github.com/SimulatedGREG/electron-vue/blob/master/template/tasks/vue/route.js#L25) gets replaced to this once inited:
```
routes.splice(
  routes.length - 2,
  0,
  routesTemplate
    .replace(//g, routeName)
    .replace(/\n$/, '')
)
```

Which is pretty much:
```
routes.splice(
  routes.length - 2,
  0,
  routesTemplate
    .replace(
    .replace(/\n$/, '')
)
```

**Comment by SimulatedGREG** [comment]
@gjuchault 

I've actually been meaning to remove this feature as I haven't found an efficient way to add new routes through parsing a string of text. This is also why this feature has been labeled *experimental* on the documentation. If you are wanting to make a PR feel free to do so. But for the moment, this will be put on hold.

**Comment by liril-net** [comment]
#115

**Comment by gjuchault** [comment]
@SimulatedGREG I think removing the feature wouldn't be that bad.

**Comment by SimulatedGREG** [comment]
Referring to #115, this feature will be removed. Thanks for all contributions and feedback on this issue.
