### ISSUE TITLE
It does't have the vue devtool tab

### ISSUE THREAD

**Issue by SidKwok** [SimulatedGREG/electron-vue#97]
##### Describe the issue / bug.
I just start the project and try to find tab vue in devtools, but it only has devtron.

##### Tell me about your development environment.
  * Node version: v6.5.0
  * NPM version: 3.8.9
  * vue-cli version: 2.7.0
  * Operating System: maxOS

If it helps, the terminal keeps on telling me that `Failed to fetch extension`, I don't really know if it means `vue-devtool`;

**Comment by SimulatedGREG** [comment]
@SidKwok 

That error is indeed for `vue-devtools`. This would be an issue with [`electron-devtools-installer`](https://github.com/MarshallOfSound/electron-devtools-installer). Would you happen to be behind a proxy?

**Comment by SidKwok** [comment]
Thanks for your feedback, proxy indeed.
