### ISSUE TITLE
Static files not present in the built .dmg file

### ISSUE THREAD

**Issue by georgeben** [SimulatedGREG/electron-vue#978]
Hello @SimulatedGREG , thank you for this awesome package. I have an app that displays a pdf. I put the pdf in a static/pdfs folder. During development, it works as expected, the pdf is displayed. However, after packaging the app by running `npm run build`, the app builds successful, but the pdf doesn't display. Please what am I doing wrong?

This is my build configuration:
```
"build": {
    "productName": "geography-e-library",
    "appId": "com.ndugeography.e-libraray",
    "directories": {
      "output": "build"
    },
    "files": [
      "dist/electron/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 410,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 130,
          "y": 150,
          "type": "file"
        }
      ]
    },
    "mac": {
      "icon": "build/icons/icon.icns"
    },
    "win": {
      "icon": "build/icons/app_icon.ico",
      "target": "nsis"
    },
    "linux": {
      "icon": "build/icons"
    }
  },
```

##### Tell me about your development environment.
  * Node version: 10.16.3
  * NPM version: 6.9.0
  * vue-cli version: (if necessary)
  * Operating System: MacOS
 * vue-electron version: ^1.0.6

I would appreciate any help I can get. Thank you!

**Comment by lord-zeus** [comment]
Hello Please How did you resolve this static files issue ?

**Comment by gigouni** [comment]
Hi. @lord-zeus  @georgeben how did you fix it ? I cannot get the dev and prod mode both working, quite a loosing time. Thks
