### ISSUE TITLE
[Question] How to build a web version

### ISSUE THREAD

**Issue by gazpachu** [SimulatedGREG/electron-vue#98]
First of all, thank you very much for this boilerplate. It's truly awesome! Amazing work. It does indeed make people happy 👍 

I was wondering if it is possible to build a version for the web (aside from the versions for the different SOs). I've looked into the `dist` folder and run a quick live server on the `index.html` file, but the browser console throws this error `Uncaught ReferenceError: require is not defined`.

In case this boilerplate is not ready to build a version for the web, what would be the correct approach to maintain a project for Mac, Windows and Web using the same codebase?

Thanks in advance.

PS. I've managed to build the initial demo app in all SOs from a Mac OS Sierra. Woohoo!

**Comment by SimulatedGREG** [comment]
@gazpachu 

Take a look at this [issue](https://github.com/SimulatedGREG/electron-vue/issues/85). @nicklaw5 was able to get this working with a little direction from me. I might considering adding this as an official feature.

**Comment by nicklaw5** [comment]
+1 for adding it as an official feature. It's really quite easy to do and adds a load of benefits for those looking to build for both the web and native desktop.

**Comment by gazpachu** [comment]
Agree. That will match the features other similar frameworks already offer.

**Comment by SimulatedGREG** [comment]
Going to close this for now. Feel free to comment any questions.
